### ISSUE TITLE
Write and submit a JOSS article

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#1080]
http://joss.theoj.org/papers/new

**Comment by stefan-mueller** [comment]
We have the necessary files in [this branch](https://github.com/quanteda/quanteda/tree/write-joss). I think the text is quite advanced and we should aim to submit soon. Things we need to discuss:

1. Structure: Currently, we have a _Summary_ and then four subsections on the **quanteda** principles. I think this makes sense.

2. References: We need to add references to other packages (e.g., if we expand a bit more on the `convert()` function) or if we go into detail about the packages underlying **quanteda** (which we don't do at the moment). Do you think it's necessary to mention other packages?

3. I think we could also mention the `textmodel_` functions in the _Summary_ paragraph and cite the respective literature (Laver et al. 2003; Slapin and Proksch 2008; Perry and Benoit 2017). Or is this too specific? 

4. Update and check author's affiliations and ORCID if available.

**Comment by kbenoit** [comment]
I'll get to this soon.

**Comment by kbenoit** [comment]
After extensive editing, I put a version of this the `master` branch in the `papers/` subdirectory. @adamobeng is the Facebook affiliation OK? Can everyone have a look, edit with PRs?
