### ISSUE TITLE
Make a centralized data repo

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda#1108]
We have datasets everywhere:

* **quantedaData**
* http://docs.quanteda.io/articles/pkgdown/examples/data/
* https://github.com/kbenoit/ITAUR/tree/master/data
* https://github.com/kbenoit/QTAUR-halfday/tree/master/data
* Ken's ~/Dropbox/QUANTESS/*

We need to keep all of them in one place. It can be a website where all the datasets are listed, but we can also make an downloader package/function in R that fetches only files you need, so large (100MB <) corpus could be distributed easily (it should have caching functionality). This will look like:

```r
data_download('wiki', cache = TRUE)
```

**Comment by kbenoit** [comment]
**data_corpus** ?

**Comment by koheiw** [comment]
I think we should make clear that the function downloads from the web, not just loads files on the disk.

**Comment by kbenoit** [comment]
`repository` could be local or a URL, and by default, would be a URL where we store the files.

**Comment by kbenoit** [comment]
Can also load .rda files directly from GitHub: See https://github.com/opetchey/RREEBES/wiki/Reading-data-and-code-from-an-online-github-repository#reading-a-rdata-file-from-github.
