### ISSUE TITLE
Move repo to quanteda/quanteda

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#1186]
Should be a simple move, and adjusting the issues URL in `DESCRIPTION`.

But will also need a placeholder `README.md` to indicate the relocation, in https://github.com/kbenoit/quanteda/.

**Comment by kbenoit** [comment]
@koheiw You will need to adjust the website links (http://quanteda.io) once the move is complete.

**Comment by kbenoit** [comment]
Actually GitHub seems smart enough to redirect automatically! And it even lists quanteda/quanteda as a pinned repository in my account: https://github.com/kbenoit.  Brilliant.

@koheiw Check that everything works, and if not, please fix, if it does, then close this issue.

**Comment by koheiw** [comment]
I also updated DNS entities for the documentation site and Netlify setting for the landing site. It will take some time for the settings to propagate, but should be ok.
