### ISSUE TITLE
AsMethod(object) error with TidyText 

### ISSUE THREAD

**Issue by pbradl42** [quanteda/quanteda#1199]
I was getting this error on tidy(DFM):

 Error in asMethod(object) : invalid class of object to as_cholmod_sparse 

using with Quanteda 0.99.22 and tidytext 0.1.6

I went back to Tidytext 0.1.4, and nothing changed. So I went back to quanteda 0.99.12, and everything is working again. I'm not sure where the bug lies.

**Comment by kbenoit** [comment]
Happy to look into this, but can you please supply a reproducible example?
