### ISSUE TITLE
Find a workaround for the UBSAN warnings

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#1200]
Each time we (re)submit to CRAN, we get flagged on the UBSAN warnings ([clang-UBSAN](https://www.stats.ox.ac.uk/pub/bdr/memtests/clang-UBSAN/quanteda/) and [gcc-UBSAN](https://www.stats.ox.ac.uk/pub/bdr/memtests/gcc-UBSAN/quanteda/)) arising from the TBB calls through **RcppParallel**.  These are happening when the examples and tests are calling functions using multi-threading, when the threads options is > 1, e.g.
```r
> quanteda_options("threads")
[1] 7
```

This is a [known issue in **RcppParallel**](https://github.com/RcppCore/RcppParallel/issues/36#issuecomment-358445542), but no immediate fix seems to be in sight.

To test this setup, we need to create a branch with some custom Makevars flags. The general method is described [here](https://cran.r-project.org/web/checks/check_issue_kinds.html) and in a [helpful blog post here](https://francoismichonneau.net/2014/03/how-to-do-ubsan-tests-r-package/).

Possible solutions:
1. Solve the underlying problem.  (if only)
2. Switch to 1 thread by default, for the package (if this in fact makes the warnings disappear - we would need to test this first of course). Not preferred, however, since most users will not reset the threads and hence will unknowingly deny themselves the benefits of multi-threading.
3. Switch to single-threaded examples in the examples sections for all multi-threaded functions, and for the tests. We could put the former in the examples sections, and the latter in `testthat.R`.
4. Adjust for CRAN, meaning we would need to detect CRAN, and then: 
    a. Skip the multi-threaded tests on CRAN; or change to a single thread on CRAN;
    b. Figure out a similar solution for the examples, for CRAN only.

**Comment by HervePerdry** [comment]
I admit solution 4 comes to mind -- but it sounds a little VW-ish, doesn't it? :)

**Comment by amatsuo** [comment]
Regarding 4. The detection of CRAN seems to be very simple:
https://github.com/r-lib/testthat/blob/master/R/skip.R#L103-L109

**Comment by kbenoit** [comment]
@amatsuo as far as I understand, that only applies to tests, not examples.

**Comment by HervePerdry** [comment]
Regarding this comment (to which I agree): _most users will not reset the threads and hence will unknowingly deny themselves the benefits of multi-threading,_ note that now the CRAN enforces the following rule: _Please ensure that your package does not use more than 2 cores by default or in your examples._

So we'll have to add ugly code to set #threads = 2 in examples, and then switch back to previous value...

**Comment by kbenoit** [comment]
Umm... Had not seen that. @HervePerdry can you send the link to this reference? This means we will need to change the default. This is currently set on loading to (#cores - 1). It can be set by:

```r
quanteda_options(threads = 2)
```

**Comment by HervePerdry** [comment]
My reference is a mail I received yesterday night from CRAN regarding a new submission of my package `gaston`. I quote: _Please ensure that your package does not use more than 2 cores by default or in your examples._

Note that I have the feeling that these rules are not systematically enforced. But in my experience, once you've been asked to comply, there’s no bargaining.

**Comment by kbenoit** [comment]
BTW when submitting v1.1.0 I was told in no uncertain terms by Ripley that this was “a serious policy violation”. The policy is here: 

> Checking the package should take as little CPU time as possible, as the CRAN check farm is a very limited resource and there are thousands of packages. Long-running tests and vignette code can be made optional for checking, but do ensure that the checks that are left do exercise all the features of the package.
> 
> If running a package uses multiple threads/cores it must never use more than two simultaneously: the check farm is a shared resource and will typically be running many checks simultaneously.

In an email, Uwe also stated:
> Also note that users should not always make use of all resources in some shared environments, hence pls really do not use more than 2 as the default and allow for more to be specified by the user.

So we changed the default to two threads (or 1 if the user has just one) and resubmitted.

**Comment by koheiw** [comment]
Thank you @HenrikBengtsson for sharing your thoughts. Your package also looks very useful.

**Comment by kbenoit** [comment]
Very good points and hard to disagree with. Really interesting package (**futures**)!

**Comment by HervePerdry** [comment]
Thank you @HenrikBengtsson that’s a great answer to the problem of limiting cores during R check. 

I do agree about the default number of cores, Gaston sets the number of cores to a maximum of 8 on machines having more that 16 cores, and half the number of cores on smaller machines.
