### ISSUE TITLE
Smarter n-gram pulling

### ISSUE THREAD

**Issue by brousseauj** [quanteda/quanteda#1207]
I'm making some dfm() on a data.frame with options to remove stopwords and when I include the option for ngrams(1:4), I get n-grams like 'of_the' , ' and then' which are clear stop words. It's not a huge pain to just remove them after the fact, but would be nice as a feature to just include "smart" n-grams.

**Comment by stefan-mueller** [comment]
You could first tokenize the text, remove stop words through `tokens_remove()`, and then create a `dfm` which includes the `ngrams` option.

```r
test_corpus <- corpus("A text with a lot of stopwords like and then and of the.")

tokens(test_corpus) %>% 
    tokens_remove(stopwords("english")) %>% 
    dfm(ngrams = 3) %>% 
    head()

# Document-feature matrix of: 1 document, 3 features (0% sparse).
# 1 x 3 sparse Matrix of class "dfm"
# features
# docs    text_lot_stopwords lot_stopwords_like stopwords_like_.
# text1                  1                  1                1
```

**Comment by brousseauj** [comment]
Awesome! This is good to know. Thanks for writing back.

**Comment by brousseauj** [comment]
Sorry to bring this back up so much later, is there a way to keep docvars in this approach? When I do it my way, I first make a corpus which has the docvars, but here the tokens() function doesn't contain docvars right?

**Comment by stefan-mueller** [comment]
I am not sure whether I understand your question, but `docvars` associated with a `corpus` object are preserved in `dfm` and `tokens` objects. Also see `?docvars`. 
```r
mytoks <- tokens(data_corpus_inaugural) %>% 
  tokens_remove(stopwords("english"), padding = TRUE) 

docvars(mytoks) %>% 
  head()

# Year  President FirstName
# 1789-Washington 1789 Washington    George
# 1793-Washington 1793 Washington    George
# 1797-Adams      1797      Adams      John
# 1801-Jefferson  1801  Jefferson    Thomas
# 1805-Jefferson  1805  Jefferson    Thomas
# 1809-Madison    1809    Madison     James

mydfm <- dfm(mytoks, ngrams = 3) 

docvars(mydfm) %>% 
  head()

# Year  President FirstName
# 1789-Washington 1789 Washington    George
# 1793-Washington 1793 Washington    George
# 1797-Adams      1797      Adams      John
# 1801-Jefferson  1801  Jefferson    Thomas
# 1805-Jefferson  1805  Jefferson    Thomas
# 1809-Madison    1809    Madison     James
```

Note that if you use `dfm_group()` only the document-level variables that have no variation within groups are saved.

**Comment by brousseauj** [comment]
hmm okay. I guess I should back up a bit and reframe. I'm trying to remove ngrams that are i_was, and_then, etc. 

`    x = dfm(x = xCorp,
            remove_numbers = TRUE, remove_punct = TRUE,
            ngrams = 1:3,remove_symbols=T,concatenator= ' ')
    x = dfm_replace(x,pattern = lemmaFile$V2,lemmaFile$V1)
    x = dfm_remove(x,pattern = c(paste0("^", stopwords("english"), "_"), 
                                 paste0("_", stopwords("english"), "$")), 
                   valuetype = "regex")
    x = dfm_remove(x,stopwords('english'))`

**Comment by stefan-mueller** [comment]
It is slightly confusing what you want to achieve exactly and your example is not reproducible. Do you want to get grouped feature frequencies using `textstat_frequency()`? If this is the case, the question is not related to ngrams, but rather the use of `groups` in `textstat_frequency()`. 

Below is a possible solution that shows how to get grouped frequencies using one of the `docvars` (in this case "party" in `data_corpus_irishbudget2010`).

```r
iedfm <- tokens(data_corpus_irishbudget2010) %>% 
  tokens_remove(stopwords("english"), padding = TRUE) %>% 
  dfm(remove_punct = TRUE, ngrams = 3) 

# get three most frequent terms (ngrams) for each party
textstat_frequency(iedfm, groups = docvars(iedfm, "party"), n = 3)

# feature frequency rank docfreq group
# 1         public_service_pay         6    1       2    FF
# 2    social_welfare_spending         4    2       1    FF
# 3   mortgage_interest_relief         4    3       2    FF
# 4            fine_gael_party         8    1       1    FG
# 5           anglo_irish_bank         6    2       2    FG
# 6      local_government_fund         3    3       2    FG
# 7              past_30_years         2    1       1 Green
# 8          schools_stay_open         2    2       1 Green
# 9      tackle_climate_change         2    3       1 Green
# 10          anglo_irish_bank         6    1       1   LAB
# 11      deputy_brian_lenihan         5    2       2   LAB
# 12     minister_deputy_brian         4    3       2   LAB
# 13   social_welfare_payments         5    1       1    SF
# 14 social_welfare_recipients         4    2       2    SF
# 15       social_welfare_bill         3    3       1    SF
```

Does this solve your problem? Please try to provide reproducible examples, and ask questions on SO if they are not related to a bug or feature request.
