### ISSUE TITLE
case_insensitive for tokens_compound not working as intended

### ISSUE THREAD

**Issue by methodds** [quanteda/quanteda#1209]
Hi,

it seems that the argument `case_insensitive` in `tokens_compound()` is not working as intended. The output below shows that when tokens are not converted to lowercase, collocations will not be combined correctly:

```r
library(quanteda)
library(tidyverse)
library(stringr)

ref <- read_csv('refugees_mwp_2015.zip') 

ref_tok <- ref %>%
  corpus() %>%
  tokens(remove_punct = TRUE) %>%
  tokens_tolower() %>% 
  tokens_remove(stopwords('english'), padding = TRUE)

ref_coll <- textstat_collocations(ref_tok,   min_count = 100)

# all of these were detected
c('last year', 'united states', 'human rights', 'mr obama') %in% 
  ref_coll$collocation

[1] TRUE TRUE TRUE TRUE

ref_clean <- tokens_compound(ref_tok, ref_coll, join = FALSE,
                             case_insensitive = TRUE) 

# all of these were combined
c('last_year', 'united_states', 'human_rights', 'mr_obama') %in%
  str_subset(ref_clean, '_')

[1] TRUE TRUE TRUE TRUE

ref_tok2 <- ref %>%
  corpus() %>%
  tokens(remove_punct = TRUE) %>%
  tokens_remove(stopwords('english'), padding = TRUE)

ref_coll2 <- textstat_collocations(ref_tok2, min_count = 100)

# all of these were detected
c('last year', 'united states', 'human rights', 'mr obama') %in% 
  ref_coll2$collocation

[1] TRUE TRUE TRUE TRUE

ref_clean2 <- tokens_compound(ref_tok2, ref_coll2, join = FALSE,
                             case_insensitive = TRUE) 

# not all of these were combined
c('last_year', 'united_states', 'human_rights', 'mr_obama') %in%
  str_subset(ref_clean2, '_')

[1]  TRUE FALSE  TRUE FALSE
```
Maybe this problem occurs within `quanteda:::regex2id` ? In case you need the data for reproduction  please find it [here](https://www.dropbox.com/s/5rwcoe3uzls6g3m/refugees_mwp_2015.zip?dl=1).

Edit: I used `quanteda_1.0.0` for this example.

**Comment by koheiw** [comment]
This is a mistake that I do too. When `pettern` is a collocation object, it is fixed cases-sensitive match. 
If you want to use `case_insensitive`, it should be `phrase(ref_coll2$collocation)`. In your case, `textstat_collocations(ref_tok2, min_count = 100, tolower = FALSE)` should work as well.

Please see the end of this page: http://docs.quanteda.io/articles/pkgdown/examples/phrase.html

**Comment by methodds** [comment]
Oh I see, thanks for the explanation! I'm not sure very user will understand this, so maybe a reference to phrases in the documentation of `tokens_compound()` would be useful?

**Comment by koheiw** [comment]
True. Why don't you issue a PR?

**Comment by kbenoit** [comment]
@koheiw what if we changed the behaviour so that collocation matching follows the standard behaviour with `case_insensitive`, even without `phrase()`? The `phrase()` is not meant to fix case, but rather to treat sequences as special. We are not supposed to have to use it with `collocations` objects, and the reference to the `ref_coll2$collocation` (the example here) is not supposed to be necessary.

**Comment by methodds** [comment]
Sorry for the only slightly-related question, but what do you recommend as best practice for removing the empty strings created by `padding = TRUE` in `tokens_remove()`? I noticed several times that people forgot to remove these empty strings later in the analysis and, at least from my experience, these are mostly used such that finding collocations works properly.

Would you just use `tokens_select(tokens, min_nchar = 1L)` after compouding tokens and collocations?

**Comment by koheiw** [comment]
Currently behavior is mean to avoid slow down by `regex2fixed`, `phrase()` takes more than 10 sec only to translate to token IDs for 6,400 collocations. 
```
Unit: seconds
   expr       min        lq      mean    median        uq       max neval
 phrase 12.596059 14.324397 15.809849 15.362182 17.851825 19.072070    10
    col  1.063913  1.105862  1.285949  1.242545  1.329644  1.918028    10
```
The easiest way solution is to set `tolower = FALSE` or remove the argument entirely (I don't know who added this). Users should use `tokens_tolower()` if they want collations to be all lower case. If collocations are in the same case as tokens, fixed case-sensitive match woks perfectly.

**Comment by koheiw** [comment]
@methodds I usually remove pads in `dfm(toks, remove = '')`, but you can do it using `tokens _remove(toks, '')` as well.

**Comment by methodds** [comment]
alright, thank you. I still find it a little bit weird that the min_nchar and max_nchar parameters are only available for `tokens_select` / `dfm_select` functions and not for `tokens_remove` and `dfm_trim`, but I guess you have your reasons for that and its reallty not a big deal.

**Comment by kbenoit** [comment]
They are available for `tokens_remove()` and `dfm_remove()`, through `...`.

`dfm_trim()` is for feature counts (cell values) only, not feature attributes.
