### ISSUE TITLE
Quanteda does not work on the base installation of the latest versions of R and the package.

### ISSUE THREAD

**Issue by dkholo** [quanteda/quanteda#1215]
I am getting an error in R Studio after installing latest version of R  and R studio.
CRAN version doe snot work. Git hub installation brings a different version, but it is also does not work.

> txt<-"ipad freeze Header"
> 
> library(quanteda)
quanteda version 1.0.1
Using 3 of 4 threads for parallel computing

Attaching package: ‘quanteda’

The following object is masked from ‘package:utils’:

    View

> fomcCorpus <- corpus(txt)
> token <- tokenize(fomcCorpus,  remove_numbers = TRUE, 
+                   remove_punct = TRUE, 
+                   remove_hyphens = TRUE,
+                   ngrams = 1)
Error in tokenize(fomcCorpus, remove_numbers = TRUE, remove_punct = TRUE,  : 
  could not find function "tokenize"

> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] quanteda_1.0.1

loaded via a namespace (and not attached):
 [1] ggrepel_0.7.0       Rcpp_0.12.15        lubridate_1.7.1     lattice_0.20-35     grid_3.4.3          plyr_1.8.4         
 [7] gtable_0.2.0        magrittr_1.5        scales_0.5.0        RcppParallel_4.3.20 pillar_1.1.0        ggplot2_2.2.1      
[13] stringi_1.1.6       rlang_0.1.6         lazyeval_0.2.1      data.table_1.10.4-3 rpart_4.1-11        Matrix_1.2-12      
[19] stopwords_0.9.0     fastmatch_1.1-0     tools_3.4.3         stringr_1.2.0       munsell_0.4.3       network_1.13.0     
[25] spacyr_0.9.3        compiler_3.4.3      colorspace_1.3-2    tibble_1.4.2       
> packageVersion("quanteda")
[1] ‘1.0.1’
> 

Older version of the package works fine, but attempt to enable the package on a new development machine is failing.
I would greatly appreciate support especially on the CRAN side.
Power BI team is actively enabling the package so we need to ensure that CRAN Version is stable.

**Comment by kbenoit** [comment]
That's because there is no (longer) a function in **quanteda** named `tokenize()`. Use `tokens()` instead.

For the future, you can enclose code blocks in GitHub using the <> or just typing the triple backticks before and after the code.

**Comment by dkholo** [comment]
Thank you Ken. Makes sense. I have sent you a separate email with some additional questions.

**Comment by Alexandershemetev** [comment]
The bad thing is that the new versions of quanteda eliminate working of many old codes :( 
somefunction = function(x, ngramSize = 1, simplify = T) {
        
    # Do some regex magic with quanteda
    toLower(
        quanteda::tokenize(x,
            removeNumbers = T,
            removePunct = T,
            removeSeparators = T,
            removeTwitter = T,
            ngrams = ngramSize,
            concatenator = " ",
            simplify = simplify
        ) 
    )
}
Not working anymore;

# Transfer to quanteda corpus format and segment into sentences
anotherfunction = function(x) {
    corpus(unlist(segment(x, 'sentences')))
}
Not working 

And many more.... 
It's very sad. You need to rewrite your codes with every "improvement"
