### ISSUE TITLE
Wordfish results change from run to run

### ISSUE THREAD

**Issue by chriswratil** [quanteda/quanteda#1216]
Hi,

the textmodel_wordfish() function does not give the exact same results in two runs in case the DFM is sparse. Is this due to the use of an approximation to the SVD if the DFM is sparse? In any case, it would be great to add a possibility of deterministic results in case the DFM is sparse. This would be important for replication purposes.

To see the problem, just run the following a few times and compare the last digits of the theta estimates.
```r
library(quanteda)
summary(textmodel_wordfish(dfm(data_corpus_inaugural)))
```
Thanks so much for your support and best wishes,

Chris

**Comment by koheiw** [comment]
Thank you for the post. It is related to random initial values for sparse implimentation:
https://github.com/quanteda/quanteda/blob/76e2cbff386fb8ef4dcf079b4f6e9971137dda8a/src/wordfish_mt.cpp#L331
We will try to fix.

**Comment by kbenoit** [comment]
I've changed the default to `sparse = FALSE`. Doesn't solve the fundamental issue, but will stop the difference in results from repeating the function call.
