### ISSUE TITLE
Move textplot_wordcloud() to wordcloud2

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda#1218]
Mainly for #1208, but related to #1213. Advantages of **wordcloud2** are 

  * no need of **slam** 
  * similar behavior to **ggplot2** (render via print method). 

Its disadvantages are 

  * does not render the most frequent words sometimes 
  * cannot save outputs as vector images (e.g. PDF or SVG)

Try
```r
require(quanteda)
require(wordcloud2)
require(RColorBrewer)

irish_dfm <- dfm(data_corpus_irishbudget2010, remove_punct = TRUE, remove = stopwords('en'))

f <- colSums(dfm_trim(irish_dfm, min_count = 5))
col <- rev(tail(brewer.pal(6, "Blues"), 5))

p <- wordcloud2(data.frame(names(f), f), minRotation = 0, maxRotation = 0, 
                color = col[as.integer(cut(f, length(col)))])
p
```

**Comment by kbenoit** [comment]
OK I'm in total agreement. Let's make this switch. Best would be to have it resemble the existing circular word cloud inasmuch as possible. For instance:
```r
require(quanteda)
require(wordcloud2)
require(RColorBrewer)

irish_dfm <- dfm(data_corpus_irishbudget2010[1:2], remove_punct = TRUE, 
                 remove = stopwords("english")) %>%
    dfm_trim(min_count = 5)
f <- colSums(irish_dfm)

wordcloud2(data.frame(names(f), f), 
           size = .5, ellipticity = 1, shuffle = FALSE, shape = "circle") + 
    WCtheme(1)
```
![rplot](https://user-images.githubusercontent.com/2182246/35984001-5184175e-0ceb-11e8-86ac-e6ef99491138.png)

However, there are **two things** I'd prefer to resolve before abandoning the existing method:
1. Despite `shuffle = FALSE` above, the plotted cloud is different each time it is called. Is there a way to fix this?  
2. How do we preserve the functionality from `textplot_wordcloud(x, comparison = TRUE)`? Using the shapes available in **wordcloud2** there should be a way to program this, but it's not built-in as with **wordcloud**.

**Comment by methodds** [comment]
Is it possible to reproduce parameters from the old package ? The option for placing the most frequent words in the middle with `random.order = FALSE` as well as the parameters for maximum word size and scaling were really useful.

**Comment by kbenoit** [comment]
@koheiw and I discussed this Friday and decided to keep the older word cloud format, but too reimplement it from the code (it's actually very simple) to use **quanteda** objects instead of **tm**'s format.

We could then implement a `textplot_wordcloud2()` as a purely convenience wrapper.

So don't worry, the old functionality will remain!

**Comment by koheiw** [comment]
See #1224
