### ISSUE TITLE
(Possibly) Change default threads to two

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#1219]
[This](https://github.com/quanteda/quanteda/issues/1200#issuecomment-361626447) from HervePerdry (30 Jan):

> My reference is a mail I received yesterday night from CRAN regarding a new submission of my package gaston. I quote: Please ensure that your package does not use more than 2 cores by default or in your examples.

**Comment by koheiw** [comment]
**quanteda** must be enjoying 24 cores when running on CRAN, but we can restrict the number to two in zzz.R
```r
if (!identical(Sys.getenv("NOT_CRAN"), "true")) {
    quanteda_option(threads = 2)
}
```

**Comment by kbenoit** [comment]
Exactly what I was thinking. Perhaps we can leave it as is, until/unless we get told off by CRAN the next time we submit.

**Comment by kbenoit** [comment]
Can we live with that? I had originally moved it to be half of the available threads, but a certain speed demon changed that threads - 1...
