### ISSUE TITLE
Request `as.dfm.DocumentTermMatrix` & `as.dfm.TermDocumentMatrix`

### ISSUE THREAD

**Issue by trinker** [quanteda/quanteda#1222]
It is nice to be able to convert between data structures that are common in the text world. 
 As the `dfm` becomes one of the preferred structures it'd be nice to convert from another structure that is common the `DocumentTermMatrix` & `TermDocumentMatrix` .  Granted, I'm sure you'd prefer people just go from Corpus to `dfm` in quanteda but sometimes you have one of thes **tm** structures already because of preference or some pakage output or just to give the user flexibility.  

**quanteda** already provides the `as.dfm` conversion for matrices and data.frames.  I'd like to request extensions of `as.dfm.DocumentTermMatrix` & `as.dfm.TermDocumentMatrix` that allow for easy conversion from these data forms.  Below I provide the current code I use for such conversion though I realize you're using more sophisticated methods  with `as_dfm_constructor` under the hood.  I also get that this flexibility may be in antithesis of the **quanteda** in which case I'll accept "This is out of scope" as a response.  But I figure I might ask and see.

Also, I may have overlooked the fact that **quanteda** already does this.  If this is the case kindly tell me I'm a bone head and the next time we meet up your first beer is on me :-)

## Crude code for converting to `dfm`
```
as.dfm.DocumentTermMatrix <- function(x, ...){

    as.dfm(
        Matrix::sparseMatrix(
            i = x$i, 
            j = dtm$j, 
            x = x$v, 
            dimnames = list(seq_len(nrow(x)), colnames(x))
        )
    )

}
```

**Comment by kbenoit** [comment]
There's already an app for that: `convert(x, format = "tm")`. We don't do TermDocumentMatrix formats since these are an affront to nature. 😉

**Comment by trinker** [comment]
`convert` will make the `DocumentTermMatrix` I'm asking about converting from a `DocumentTermMatrix` to a `dfm` .  I don't think `convert` will make a `dfm`  as I believe it specifies that `x` must be a `dfm`.  

This is what I want to try to accomplish...let's say I have been given the following `DocumentTermMatrix`  called `x` by a street text analysis dealer:.  How could I make it into a `dfm`?  The `as.dfm.DocumentTermMatrix(x)` above will do this?  You seem (https://github.com/quanteda/quanteda/blob/6e3469c98faca4bb03192854a36dd319f8034546/R/dfm-methods.R) to take pitty on people with data.frame, matrix, Matrix, and sparseMatrix data formats of counts of documents and terms... providing these souls with the `as.dfm` generic method.  

```
library(tm); library(quanteda)
data("crude")

x <- DocumentTermMatrix(crude,
    control = list(
        weighting = function(x) weightTfIdf(x, normalize = FALSE),
        stopwords = TRUE
    )
)

convert(x, format = "tm")
```

Result of the `as.dfm` generic method on a `DocumentTermMatrix`:

```
as.dfm(x)
Error in as.dfm.default(x) : 
  as.dfm() only works on data.frame, dfm, dfmSparse, matrix, Matrix, textmodel_lsa objects.
```

## Result of `as.dfm` after inclusing the poorly written method I demoed above:

```
as.dfm.DocumentTermMatrix <- function(x, ...){

    as.dfm(
        Matrix::sparseMatrix(
            i = x$i, 
            j = dtm$j, 
            x = x$v, 
            dimnames = list(seq_len(nrow(x)), colnames(x))
        )
    )

}

as.dfm(x)

## Document-feature matrix of: 20 documents, 1,200 features (92.1% sparse).
```

I feel I didn't do a good job of explaining my request to convert to `dfm` not the other way around.  Mostly I don't want to owe you a beer  but if there is already a way to convert a `documentTermMatrix` to ` dfm` I'm not that cheap and will buy promised beer.  If there is not a way to make a `dfm` from a `DocumentTermMatrix` and you don't want to provide the `as.dfm` because you are trying to enforce an adherence to a specific standard I get that too.

**Comment by kbenoit** [comment]
OK now I understand! Happy to add `as.dfm.DocumentTermMatrix()` and `as.dfm.TermDocumentMatrix()` methods. Will do so asap.

You can still owe me a :beer:.

**Comment by trinker** [comment]
A 🍺 for a feature seems cheap.  Done.  Thanks :-)
