### ISSUE TITLE
Incorporate wordcloud code directly into quanteda

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#1224]
The [source code](https://github.com/ifellows/wordcloud) for the **wordcloud** package is pretty lightweight and could easily be modified for **quanteda** objects (`tokens`, `dfm`) and put into its own `textplot_wordcloud.R` file. This would remove the dependency on **tm** and **slam** (and on **wordcloud** itself).

We should:

- make the input `x` a `tokens` or `dfm` object
- change the arguments to underscores, but trap the old `wordcloud::wordcloud()` arguments with deprecation warnings, in case old code uses these.
- remove the min.freq argument since this should be the task of `dfm_trim()` not part of the plotting command. (We can keep the equivalent of `max.words` since this is a plotting interaction argument.)
- make `random.order = FALSE` be the default.

**Comment by koheiw** [comment]
I incorporated the **wordcloud** into our package. See https://github.com/quanteda/quanteda/blob/dev-wordcloud/R/textplot_wordcloud2.R. Note that it is nothing do with the **wordcloud2** package.

The functions needs reorganization, but they are working as they should. We can also drop `use_r_layout` and use C++ code always.

**Comment by kbenoit** [comment]
Superb. I suggest temporarily renaming the old function to something like `textplot_wordcloudold()` and calling the new one by `textplot_wordcloud()`, since the behaviour should be identical. Once we confirm that they are in fact identical, we can kill the old one in the PR before merging.

**Comment by kbenoit** [comment]
And eliminate the Import of the **wordcloud** package.

**Comment by kbenoit** [comment]
Is this something we can fix?

https://stackoverflow.com/questions/48811619/lots-of-empty-whitespace-in-textplot-wordcloud-comparison-cloud

**Comment by koheiw** [comment]
I think I can. I am making labels more customizable in terms of color, position, size.

**Comment by methodds** [comment]
Hi just a quick question: there is no way to make the quanteda wordcloud version compatible with ggplot2, as base plots work differently right? It would be awesome because many other quanteda plots are already using ggplot2.

**Comment by koheiw** [comment]
I am tying to use base the function on **ggplot2**. My tentative implementation is already in the code. Please give it a try.

**Comment by methodds** [comment]
cool! how can I try it out? I just installed quanteda via `devtools::install_github("quanteda/quanteda", rev = "dev-wordcloud") `, but I think the result is not a ggplot2 cloud yet:

```
library(quanteda)
mydfm <- dfm(corpus_subset(data_corpus_inaugural, President == "Obama"), 
             remove = stopwords("english"), remove_punct = TRUE)

# plot in colors with some additional options passed to wordcloud
test <- textplot_wordcloud(mydfm, random.color = TRUE, rot.per = .25, 
                   colors = sample(colors()[2:128], 5))

![rplot01](https://user-images.githubusercontent.com/7460499/36304849-77c3b5b0-1311-11e8-9a85-a59484238658.png)


class(test)
NULL
```

**Comment by koheiw** [comment]
@methodds, you seems to be using the old function. The **ggplot** version looks like
```r
textplot_wordcloud(x, min_size = 0.5, max_size = 4, max_words = 1000,
  color = "skyblue", font = NULL, adjust = 0, rotation = 0.1,
  random_order = TRUE, random_color = FALSE, ordered_color = FALSE,
  labelcolor = "black", labelsize = 1, labeloffset = 0.1,
  fixed_aspect = TRUE, ..., comparison = FALSE)
```
The classic function is available as `textplot_wordcloudold()` for comparison. Please let me know how you like it.

**Comment by koheiw** [comment]
Great to hear. It is not a full **ggplot2** extension yet, but the output looks like so. The trick here is that the layout is generated in a graphics device (not on grid), and place words using `geom_text`. Next step is full **ggplot2** extension.

**Comment by gabrielparriaux** [comment]
Hello, 

Do I understand correctly that if I use `textplot_wordcloud` now in latest version of **Quanteda**, it’s this new version that you rebuilt from the wordcloud package?

I’m using it and it works well for me, but is there a way to save the plot to disk using code, as it is now a kind of **ggplot2** extension? I tried `ggsave`, but it doesn’t seem to save anything…

Thanks a lot for helping,

Gabriel
