### ISSUE TITLE
Possible limit due  to 10,000 document batch tokenizing

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#1225]
I ran some tests following [this discussion on SO](https://stackoverflow.com/questions/48725927/i-am-trying-to-create-a-documenttermmatrix-while-keeping-all-special-characters/48726809). For me, it seems to be fine.

```r
generate_docs <- function(n, len = 100) {
    vec <- sample(letters, n * len, replace = TRUE)
    vec <- split(vec, rep(seq_len(n), each = len))
    vec <- vapply(vec, paste, collapse = " ", "character")
    names(vec) <- paste0("doc", seq_len(n))
    vec
}

set.seed(1)
tokens(generate_docs(3, 10))
# tokens from 3 documents.
# doc1 :
# [1] "g" "j" "o" "x" "f" "x" "y" "r" "q" "b"
# 
# doc2 :
# [1] "f" "e" "r" "j" "u" "m" "s" "z" "j" "u"
# 
# doc3 :
# [1] "y" "f" "q" "d" "g" "k" "a" "j" "w" "i"

library("testthat")

toks <- tokens(generate_docs(20001))
expect_equal(ndoc(toks), 20001)

toks <- tokens(generate_docs(20001), what = "fasterword")
expect_equal(ndoc(toks), 20001)
```

Unless we find a problem, we will close this issue soon.

**Comment by jz8** [comment]
I do not get the error on your test, but I have over 72,000 tokens and it fails when I go over 10000  documents.  Fails at exactly 10,001.

**Comment by kbenoit** [comment]
I've replicated this error now:
```r
library("quanteda")

labTests <- read.csv("~/Downloads/JeffZeanah-All.csv",  sep = ';', stringsAsFactors = FALSE)

# create a corpus
qdfm <- dfm(labTests[1:10000, "BagOfWords"], what = "fasterword", verbose = TRUE)
qdfm
head(featnames(qdfm), 100)

qdfm2 <- dfm(labTests[1:10001, "BagOfWords"], what = "fasterword", verbose = TRUE)
# Creating a dfm from a character input...
# ... lowercasing
# ... found 10,001 documents, 72,190 features
# 
# Error: all(dims >= dims.min) is not TRUE 
```

@koheiw I will send you the file separately (since it's not for posting).

**Comment by koheiw** [comment]
@jz8 please try the Github version. I should be fine now.

**Comment by hamzameer** [comment]
@koheiw I got the same error: 'Error: all(dims >= dims.min) is not TRUE' in sparseMatrix in my work using CVXR. Unfortunately this is the only reference I found to this error - so I'm looking for leads on how to fix it. This is a long shot but could you explain how you got rid of this error? (even if it is on a high level)

**Comment by koheiw** [comment]
@hamzameer I haven't see the error in recent versions. Which version are you using? I have no knowledge of **CVXR**, but you can just coerce a DFM to regular matrix `as(mt, "dgCMatrix")` to avoid **quanteda**-related errors.

**Comment by hamzameer** [comment]
@koheiw I am not using **quanteda**- apologies for the confusion. I came across the same error in `sparseMatrix.R` in my work with **CVXR** and this is the only place where there is a reference to such an error. So I was trying to pin point the solution. But thanks for your help :)
