### ISSUE TITLE
allow sparsity reduction of tf-idf weighted dfm

### ISSUE THREAD

**Issue by hadgi** [quanteda/quanteda#1237]
Currently, it is possible to perform dfm_trim() on dfm object and then add tf-idf weights, however, when I want to add tf-idf weights first by using all terms for tf-idf calculations and only then reduce the sparsity of the matrix, I get `Error in docfreq.dfm(x) : this dfm has already been term weighted as:inverse10`.

**Comment by kbenoit** [comment]
Please provide a reproducible example.

**Comment by hadgi** [comment]
Sorry. Here is one: 

`dfm.object1 <- dfm(c("the quick brown fox jumps over the lazy dog", "the quick brown foxy ox jumps over the lazy god"))
dfm.object1
dfm.trimmed1 <- dfm_trim(dfm.object, min_docfreq = 0.9)
dfm.trimmed1
dfm.tfidf1 <- dfm_tfidf(dfm.trimmed)
dfm.tfidf1

dfm.object2 <- dfm(c("the quick brown fox jumps over the lazy dog", "the quick brown foxy ox jumps over the lazy god"))
dfm.object2
dfm.tfidf2 <- dfm_tfidf(dfm.object)
dfm.tfidf2
dfm.trimmed2 <- dfm_trim(dfm.tfidf, min_docfreq = 0.9)
dfm.trimmed2`

**Comment by kbenoit** [comment]
The short answer is: It's partly a bug (which I will address soon) and partly a feature, designed to prevent users from applying an inappropriate definition of the trim thresholds in `dfm_trim()` to a weighted dfm.

The simple reproducible error is:
```r
data_dfm_lbgexample %>%
    dfm_tfidf() %>%
    dfm_trim()
## Error in docfreq.dfm(x) : 
##     this dfm has already been term weighted as:inverse10 
```
More soon.

**Comment by hadgi** [comment]
Thanks in advance for the fixing the bug part... and even bigger thanks in retrospect for quanteda :)

**Comment by kbenoit** [comment]
Should be working now as of 4a5d606. The `min_docfreq = 0.9` will eliminate features that occur in fewer than 90% of your documents. In your example, with ndoc = 2, this means it will eliminate any feature that does not occur in both documents.
