### ISSUE TITLE
fcm size requested too large

### ISSUE THREAD

**Issue by Monduiz** [quanteda/quanteda#1240]
I am getting this error and I am a bit stomped by it. 

Here is an example:
Data: [Kaggle toxicity challenge data](https://www.kaggle.com/c/jigsaw-toxic-comment-classification-challenge/data)

Using the train.csv.zip dataset and a simple workflow:

```
library(tidyverse)
library(quanteda)

train <- read_csv("train.csv.zip")
train_corpus <- corpus(train$comment_text)

train_tokens <- tokens(train_corpus)
train_dfm <- dfm(train_tokens, remove = stopwords("english"), remove_punct = TRUE, verbose = TRUE)

features_selected <- featnames(dfm_trim(train_dfm, min_count = 5, verbose = TRUE))
train_toks <- tokens(train_corpus) %>% tokens_select(features_selected, padding = TRUE)

train_fcm <- fcm(train_toks, context = "window", count = "weighted", 
                weights = 1 / (1:5), tri = TRUE)
```

No matter what I try, I get this:

> error: SpMat::init(): requested size is too large
Error in qatd_cpp_fcm(x, length(types), count, window, weights, ordered,  : 
  SpMat::init(): requested size is too large

**Comment by kbenoit** [comment]
What's the output of 
```r
summary(ntoken(train_toks)); ndoc(train_toks)
```

**Comment by Monduiz** [comment]
I have 16GB of RAM and the output is:

```
 Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 1.00   21.00   43.00   80.49   89.00 4948.00 
[1] 159571
```

**Comment by Monduiz** [comment]
I am now thinking that this is probably not an issue but the need to apply some form of feature reduction. Chi square test or PCA maybe. I didn't think this would be too large.

**Comment by kbenoit** [comment]
You can’t reduce it using PCA etc before computing a windowed context fcm. What is `ntype(train_toks)`? That squared divided by two is roughly the fcm cell size, although it will be less depending on sparsity.

**Comment by Monduiz** [comment]
You mean what is the number of features? ntype prints out the features. In train_toks its 159571.

**Comment by kbenoit** [comment]
`ntype()` prints the number of _unique_ tokens. Your number of _documents_ is 159571, but what is the number of unique types found in `train_toks`? That's what determines the dimensionality of the `fcm` object you are trying to create.

**Comment by Monduiz** [comment]
If I do ntype(train_toks) I get a long output of all unique tokens per document.

e.g.:

```
 text1    text2    text3    text4    text5    text6    text7    text8    text9   text10 
      26       13       22       44        5        5        4        6       37        3 
  text11   text12   text13   text14   text15   text16   text17   text18   text19   text20 
     134        5       24       58       15       50        7        2        8       32 
  text21   text22   text23   text24   text25   text26   text27   text28   text29   text30 
      21        6       43        8      110       10       20       31       10        7 
  text31   text32   text33   text34   text35   text36   text37   text38   text39   text40 
       7        5        8       50       23       52       85       33       15       65 
  text41   text42   text43   text44   text45   text46   text47   text48   text49   text50 
      19       18       50        5       22       58        7        9       50       88 
  text51   text52   text53   text54   text55   text56   text57   text58   text59   text60 
     164        9       14       40        5       12        6       49      139       30 
  text61   text62   text63   text64   text65   text66   text67   text68   text69   text70 
       8       25        3       60       11       23        8       11       19       11 
[..., 159571]
```

**Comment by kbenoit** [comment]
Sorry, my bad. I meant to ask the output of:
```r
length(types(train_toks))
```

**Comment by Monduiz** [comment]
80285

**Comment by Monduiz** [comment]
I was getting other weird errors and I updated all packages in R. I had quanta version 1.0 but its possible that a dependency was causing these errors. I can compute the FCM now.

I should always consider the basics before raising something: is everything up-to-date.
