### ISSUE TITLE
corpus_subset by corpus elements

### ISSUE THREAD

**Issue by contefranz** [quanteda/quanteda#1255]
How do I subset a corpus by the number of Sentences detected? Let's consider the `data_corpus_inaugural` corpus. This contains 58 documents and 3 docvars.

### Data and Request
    data_corpus_inaugural
    ## Corpus consisting of 58 documents and 3 docvars.

In principle, I would like to use `corpus_subset()` over `Sentences` but apparently I can't:

    mycorp = corpus_subset( data_corpus_inaugural, Sentences > 50 )
    ## Error in eval(e, documents(x), parent.frame()) : 
    ##  object 'Sentences' not found

----

### Bad Workaround
The only, very bad, workaround I came up with is to first convert the corpus to a `data.table` object which can be pretty expensive with very large corpora. Then I use `docvars()` to call the original `Sentences` variable to attach to the corpus. Here is the code:
    
    dt = as.data.table( summary( data_corpus_inaugural, n = ndoc( data_corpus_inaugural ) ) )
    docvars( data_corpus_inaugural, "n_sentences" ) = dt[ , Sentences ]
    data_corpus_inaugural
    ## Corpus consisting of 58 documents and 4 docvars.

At this point the number of sentence is visible by `corpus_subset()` so that I can easily do: 

    mycorp = corpus_subset( data_corpus_inaugural, n_sentences > 50 )
    mycorp
    ## Corpus consisting of 42 documents and 4 docvars.

----

### Side request
Do you think it is possible to define a function which explicitly allows one to convert a corpus into a `data.table` without calling `summary()`? This is a critical step in my workflow and it is really computationally expensive. 

----

I am aware of the warning in the `corpus()` function documentation, but I can't get access to corpus elements the way I want. 
Any suggestions or just best practice?

**Comment by kbenoit** [comment]
Your first approach is on the right track, but will only work if you have a docvar named `Sentences`. Barring that, you can subset on the return of the `nsentence()` function, which returns a (named) numeric vector:
```r
nsentence(data_corpus_inaugural) %>% head()
## 1789-Washington 1793-Washington      1797-Adams  1801-Jefferson  1805-Jefferson    1809-Madison 
##              23               4              37              41              45              21 
```

So this works:
```r
corpus_subset(data_corpus_inaugural, nsentence(data_corpus_inaugural) > 50)
## Corpus consisting of 42 documents and 3 docvars.
```
As for the conversion to a `data.table`, this would be very easy, but you should file a new issue stating what columns you would want in this object. Texts? docnames? all docvars?
