### ISSUE TITLE
Comparison of performance to other packages

### ISSUE THREAD

**Issue by stefan-mueller** [quanteda/quanteda#1258]
While we have the [article](http://docs.quanteda.io/articles/pkgdown/comparison.html) that compares **quanteda** to alternative R packages for quantitative text analysis in terms of functions, we do not provide detailed information about **quanteda**'s performance compared to other packages. 

We could use @koheiw's comparison of **quanteda**, **tidytext**, **tm** and **gensim** (maybe also NLTK) from the LondonR event and write a document that compares execution times for:
- building a corpus
- tokenisation
- removing stopwords
- creating a document-feature matrix

If you like the idea, @koheiw maybe collect the existing code and I'm happy to help with writing the document.

**Comment by koheiw** [comment]
We should do this. The code for the benchmark that I presented in London R is here:

```r
rm(list=ls())
require(microbenchmark)
require(quanteda)
require(tm)
require(tidytext)
require(dplyr)
require(stopwords)

txt <- texts(quanteda.corpora::download('data_corpus_guardian'))

stopword <- stopwords::stopwords('en')
stopword_ti <- data_frame(word = stopword)

corp_qu <- corpus(txt)
corp_tm <- Corpus(VectorSource(txt))
corp_ti <- data_frame(txt = txt, document = seq_along(txt))

times <- list()

times$token <- microbenchmark(
    quanteda = tokens(corp_qu, what = "fastestword"),
    tm = Boost_tokenizer(corp_tm),
    tidytext = unnest_tokens(corp_ti, 'token', 'txt', to_lower = FALSE),
    times = 10
)

toks_qu <- tokens(corp_qu, what = "fastestword")
toks_tm <- scan_tokenizer(corp_tm)
toks_ti <- unnest_tokens(corp_ti, 'token', 'txt', to_lower = FALSE)

# Token selection

times$remove <- microbenchmark(
    quanteda = tokens_remove(toks_qu, stopword),
    tm = tm_map(corp_tm, removeWords, stopword),
    tidytext = anti_join(toks_ti, stopword_ti, by = c('token' = 'word')),
    times = 10
)

# DFM construction

tidy_dfm <- function(x) {
    temp <- unnest_tokens(x, token, txt, to_lower = FALSE)
    temp <- count(temp, token, document)
    cast_dfm(temp, document, token, n)
}

times$dfm <- microbenchmark(
    quanteda = dfm(corp_qu, what = "fastestword"),
    tm = TermDocumentMatrix(corp_tm, control = list(tokenize = Boost_tokenizer)),
    tidytext = tidy_dfm(corp_ti),
    times = 10
)

#saveRDS(times, 'r-packages_benchmark.rds')
#times <- readRDS('r-packages_benchmark.rds')

plot_benchmark <- function(x, ...) {
    x$time <- x$time / 1e9
    plot(x, ylab = 'Execution time (sec)', xlab = '', ...)
    grid()
    text(1:3, rep(par("usr")[4] * 0.1, 3), labels = round(aggregate(x$time, list(x$expr), median)$x, 1))
}

print(times)

svg('tokenize.svg', width = 6, height = 4)
par(mar = c(4.1, 4.1, 1.1, 1.1))
plot_benchmark(times$token, ylim = c(0, 2))
dev.off()

svg('remove.svg', width = 6, height = 4)
par(mar = c(4.1, 4.1, 1.1, 1.1))
plot_benchmark(times$remove, ylim = c(0, 1))
dev.off()

svg('dfm.svg', width = 6, height = 4)
par(mar = c(4.1, 4.1, 1.1, 1.1))
plot_benchmark(times$dfm, ylim = c(0, 8))
dev.off()
```

**Comment by kbenoit** [comment]
Yes, and it should be a markdown article for the blog roll for a quanteda Initiative site, from Rmd source. And we should do our best to reproduce Patrick Perry's benchmarks of his **corpus** package, which (I think...) is [here](https://github.com/patperry/bench-term-matrix).

**Comment by koheiw** [comment]
Comparing with non-R packages is more difficult as we have to benchmark scripts on the OS. I know how to do this on Linux (use `time` and `sed` commands) but not sure about Mac. I can send you my shell script, if you want to try.

**Comment by kbenoit** [comment]
For the developers' workshop, one idea is a [performance contest](https://github.com/ropensci/textworkshop18/issues/2) to issue a series of steps that each package should perform, with timings, and we would collect these and run them all on the same machine before the event. Maybe we should issue the text(s), the tasks, and a demo .Rmd code for **quanteda**.

**Comment by stefan-mueller** [comment]
Ok, how should we proceed? Shall we first create a blog-post like comparison of **quanteda** and the other packages based on @koheiw's code, or start with drafting a template for the performance contest? If you prefer the second option, should we use similar benchmarks as in the code from the London event (creating corpus from data.frame, tokenise text, remove tokens, create dfm) and add the **quanteda** code for these functions?

**Comment by koheiw** [comment]
We could add a performance comparison page under Features on the documentation site. I found it difficult to find functions that all the three packages have., but you might find more.
