### ISSUE TITLE
Add ability to record dictionary weights

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#1263]
Many sentiment dictionaries are associated not with categories only (as per our existing implementation) but instead with polarity weights. 

For instance:
```r
> head(tidytext::sentiments[tidytext::sentiments$lexicon == "AFINN", ], 20)
# A tibble: 20 x 4
   word       sentiment lexicon score
   <chr>      <chr>     <chr>   <int>
 1 abandon    NA        AFINN      -2
 2 abandoned  NA        AFINN      -2
 3 abandons   NA        AFINN      -2
 4 abducted   NA        AFINN      -2
 5 abduction  NA        AFINN      -2
 6 abductions NA        AFINN      -2
 7 abhor      NA        AFINN      -3
 8 abhorred   NA        AFINN      -3
 9 abhorrent  NA        AFINN      -3
10 abhors     NA        AFINN      -3
11 abilities  NA        AFINN       2
12 ability    NA        AFINN       2
13 aboard     NA        AFINN       1
14 absentee   NA        AFINN      -1
15 absentees  NA        AFINN      -1
16 absolve    NA        AFINN       2
17 absolved   NA        AFINN       2
18 absolves   NA        AFINN       2
19 absolving  NA        AFINN       2
20 absorbed   NA        AFINN       1
> lexicon::hash_sentiment_vadar
              x    y
   1:       aas  2.5
   2:      aayf  2.7
   3:   abandon -1.9
   4: abandoned -2.0
   5: abandoner -1.9
  ---               
7232:      ywia  2.5
7233:    zealot -1.9
7234:   zealots -0.8
7235:   zealous  0.5
7236:       zzz -1.2
```

#### Suggestion:

Implement an alternative dictionary method that works more like the above formats.

This could be just like an existing dictionary except that instead of a character vector of values, we would have a numeric vector of weights, and the numeric elements would have a name containing the value pattern. For example:
```r
dictionary(list(sentiment = c(zealots = -.8, zealous = 0.5, zzz = -1.2)))
```
Note: A different solution to implementing weighted dictionaries is already described here: https://stackoverflow.com/questions/44132313/can-the-anew-dictionary-be-used-for-sentiment-analysis-in-quanteda/44142200#44142200.

**Comment by koheiw** [comment]
I don't think we have to deal with weighs of dictionary words in lookup functions. Users only need to select features by a dictionary and give the weight to `dfm_weight()`.

**Comment by kbenoit** [comment]
It would have to be implemented at the lookup stage, since each value has a different weight. A dfm that has been run through a lookup function only records the keys, and it's not keys but rather individual values that have weights.

**Comment by koheiw** [comment]
How common for a weighted dictionary to have more than one dimension? I suppose sentiment dictionaries are one dimensional, and a word has only one value. 

Relatedly, I do not think dictionary is the right object for weighted dictionaries, because features will be names of vector elements here, while unweighted dictionaries have features are vector elements. If we support only one dimension, named numeric vector should be fine for weight. If uses want scale documents on multiple dimensions, just use `cbind()` on dfms.

**Comment by kbenoit** [comment]
Each dictionary key is a "dimension", and what is why in the example above, the feature "zzz" has different weights in key/dimension `sentiment1` and `sentiment2`. Without using these weights at the lookup stage, we cannot distinguish the dimensions.

**Comment by koheiw** [comment]
AFINN has no duplication, so named numeric vector should be enough.
`sum(duplicated((tidytext::sentiments[tidytext::sentiments$lexicon == "AFINN", 'word'])))`
Others are categorical so existing dictionary should work.

**Comment by koheiw** [comment]
My preferred approach to weighted dictionary words is to create a `textmodel` object with weight as coeffcients. Here is a simple funciton for this

https://github.com/koheiw/LSS/blob/e76577a2aa1c1181a7880d4e6cab9b9ea9f1e5b8/R/textmodel_lss.R#L284-L301

**Comment by kbenoit** [comment]
Weights should provide the value that is summed to form the key's "count", based on feature matches. I was thinking of this:
```r
weighteddict <- dictionary(list(sentiment1 = c(zealots = -.8, zzz = -1.2),
                                sentiment2 = c(zzz = 5)))

library(testthat)
testthat::test_that("two different ways of creating dictionaries are equivalent", {
    expect_equivalent(
        dictionary(list(sentiment1 = c(zealots = -.8, zzz = -1.2), sentiment2 = c(zzz = 5))),
        dictionary(list(sentiment1 = c("zealots", "zzz"), sentiment2 = c("zzz")),
                   weights = list(sentiment1 = c(zealots = -.8, zzz = -1.2), sentiment2 = c(zzz = 5)))
    )
})

weighteddict
# Weighted dictionary object with 2 key entries.
# - [sentiment1]:
#     - zealots (-.8), zzz (-1.2)
# - [sentiment2]:
#     - zzz (5)

dfm(c("The zealots snored loundly zzz zzz.", "Zealots zealots."), 
    dictionary = weighteddict)
# Document-feature matrix of: 2 documents, 2 features (25% sparse).
# 2 x 2 sparse Matrix of class "dfm"
#        features
# docs    sentiment1 sentiment2
#   text1       -3.2         10
#   text2       -1.6          0

str(weighteddict)
# Formal class 'dictionary2' [package "quanteda"] with 3 slots
# ..@ .Data       :List of 2
# .. ..$ :List of 1
# .. .. ..$ : chr [1:2] "zealots" "zzz"
# .. ..$ :List of 1
# .. .. ..$ : chr "zzz"
# ..@ concatenator: chr " "
# ..@ valuetype   : chr "fixed"
# ..@ weights     : List of 2
# .. ..$ : Named num [1:2] -0.8 -1.2
# .. .. ..- attr(*, "names")= chr [1:2] "zealots" "zzz"
# .. ..$ : Named num 5
# .. .. ..- attr(*, "names")= chr "zzz"


# create a dictionary without weights

unweighteddict <- dictionary(weighteddict, weights = NULL)
# Dictionary object with 2 key entries.
# - [sentiment1]:
#     - zealots, zzz
# - [sentiment2]:
#     - zzz
dfm(c("The zealots snored loundly zzz zzz.", "Zealots zealots."),  
    dictionary = weighteddict)
# Document-feature matrix of: 2 documents, 2 features (25% sparse).
# 2 x 2 sparse Matrix of class "dfm"
#        features
# docs    sentiment1 sentiment2
#   text1          3          2
#   text2          2          0
```

**Comment by kbenoit** [comment]
We also need to be able to read in weights for `dictionary(file = "")`, since files that are Wordstat (for instance) have weights (this is usually set to `(1)`).

**Comment by kbenoit** [comment]
Checklist:
- [ ] everything in `dictionaries.R`
- [ ] `tokens_lookup()` should be modified to warn that weights cannot be applied in the conversion of values to keys
- [ ] `dfm_lookup()` should provide the option of applying weights
- [ ] `dfm(x, dictionary = xxx)` should use weights

**Comment by kbenoit** [comment]
Moved to #1314.
