### ISSUE TITLE
Need a way to record the valuetype for pattern matching in a dictionary

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#1264]
Here's a case where our default `valuetype  = "glob"` assumption would be broken:

```r
data(data_dictionary_HuLiu, package = "quanteda.dictionaries")
data_char_HuLiu <- unlist(as.list(data_dictionary_HuLiu))

# detect what could appear to be a glob pattern
asterisks_index <- stringi::stri_detect_fixed(data_char_HuLiu, "*")
data_char_HuLiu[asterisks_index]
## negative468  negative811 negative1560 negative3765 
##  "bull****"       "d*mn"       "f**k"       "sh*t"

# but it's a literal
damn_index <- stringi::stri_detect_regex(data_char_HuLiu, "^d.*mn")
data_char_HuLiu[damn_index]
## negative811 negative816 negative817 negative818 negative819 negative820 negative821 
##      "d*mn"      "damn"  "damnable"  "damnably" "damnation"    "damned"   "damning" 
```

### Solution

Record this a slot called `@valuetype`. This will be the default for matching on a dictionary unless the user overrides it by specifying an explicit `valuetype` for any matching operation.

**Comment by kbenoit** [comment]
I started branch `issue-1264`, but it still needs:

- [ ] friendly way to trap existence of older dictionary objects without the slot - maybe handling the same way we did for dfm calls starting with `as.dfm()`. (Would need to add a method for `as.dictionary.dictionary()` or `dictionary.dictionary2()`.)
- [ ] The `lookup` and selection arguments that take dictionaries as values need to use the `valuetype` slot as the default when `valuetype` is not supplied explicitly.
- [ ] Needs tests.

**Comment by koheiw** [comment]
If we add `@valuetype` to a dictionary, but still allow users' to choose when it is applied, we need to set the `valuetype = NULL` at least in `dfm_lookup` and `tokens_lookup`. Non-lookup functions also take a dictionary, but we should not set `valuetype = NULL` in those. This might cause some confusion.

It might be enough just raise warning when `@valuetype` is not the same as the `valuetype` argument.

**Comment by kbenoit** [comment]
Yes I thought of that too, and it's a problem. One option would be to create an extractor/replacement function `valuetype.dictionary2(x)` and `valuetype.dictionary2(x)<-`, and then make the default (e.g.)

```r
dfm_lookup(x, dictionary, valuetype = valuetype(dictionary))
```
For `dfm()` this can just be`dfm(..., valuetype = NULL)` with an explanatory note stating that the defaults would be taken from `dictionary` or `thesaurus`. But maybe there is a better way for that.

**Comment by koheiw** [comment]
Raise warnings when the dictionary's attribute and `valuetype` argument are different.

**Comment by kbenoit** [comment]
- [ ] add a `valuetype` slot to the `dictionary2` object class, that will default to "glob" but that the user can set
- [ ] add a `valuetype` argument to `dictionary()` constructor to record non-default values for a given dictionary
- [ ] make sure that no `*_lookup()` functions remove the new `valuetype` slot
- `tokens_lookup()`:
    * add a warning if `the supplied `valuetype` argument, including the `"glob"` default, is different from the slot recorded in the dictionary.
- do the same for the other functions that take dictionaries.  We can (probably) do this through `pattern2fixed()`, but we should test this for each of:
    - [ ] `dfm_lookup()` 
    - [ ]  `kwic()`
    - [ ]  `tokens_compound()`
    - [ ]  `tokens_select()`
    - [ ]  `tokens_remove()` 
    - [ ] `tokens_keep()`
    - [ ] `dfm_select()`
    - [ ] `dfm_remove()` 
    - [ ] `dfm_keep()` 
    - [ ] `fcm_select()` 
    - [ ] `fcm_remove()`
    - [ ] `fcm_keep()`
