### ISSUE TITLE
Improve error messages for invalid dfm indexing

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#1267]
We could make these messages friendlier. In solving #1266, I have dropped error checking for `selection` indexing and prefer to reply on errors returned by sending an invalid index argument to `[.dfm` methods.
```r
> d <- dfm(c("a a b c", "b b a c c"))
> d
Document-feature matrix of: 2 documents, 3 features (0% sparse).
2 x 3 sparse Matrix of class "dfm"
       features
docs    a b c
  text1 2 1 1
  text2 1 2 2
> d[3, ]
Error in intI(i, n = x@Dim[1], dn[[1]], give.dn = FALSE) : 
  index larger than maximal 2
> d["text3", ]
Error in intI(i, n = x@Dim[1], dn[[1]], give.dn = FALSE) : 
  invalid character indexing
> d[c(TRUE, TRUE, TRUE), ]
Error in intI(i, n = x@Dim[1], dn[[1]], give.dn = FALSE) : 
  logical subscript too long (3, should be 2)
> d[, c(TRUE, TRUE, TRUE, FALSE)]
Error in intI(j, n = x@Dim[2], dn[[2]], give.dn = FALSE) : 
  logical subscript too long (4, should be 3)
> d[, c("a", "d")]
Error in intI(j, n = x@Dim[2], dn[[2]], give.dn = FALSE) : 
  invalid character indexing
```

**Comment by koheiw** [comment]
How does a friendly message look like?
```r
> dim(x)
[1]  3 16
> x[5, 10]
  Error in x[5, 10] : Row index is too large. 
```
I thought "Document index is too large" is better, but it is also used by `fcm`, so row/column seems better.

**Comment by kbenoit** [comment]
Probably just like indexing for `matrix` which states `"subscript out of bounds", although we could add "docname subscript out of bounds" or "featname subscript out of bounds" as appropriate.

**Comment by koheiw** [comment]
If we use "docname subscript out of bounds" for rows, the error message will look funny for fcm, so I think just 
```r
 Error in x[5, 10] : Subscript out of bounds
```
would be the best. Much less scaly than 
```r
Error in intI(j, n = x@Dim[2], dn[[2]], give.dn = FALSE) : 
  logical subscript too long (4, should be 3)
```
