### ISSUE TITLE
Dfm attribute "smooth" is not set by dfm_smooth

### ISSUE THREAD

**Issue by chmue** [quanteda/quanteda#1274]
The class documentation for `dfm` describes a `smooth` slot which holds the value of smoothed feature counts. As far as I understand, this value should be changed by `dfm_smooth` and `dfm_weight` if any smoothing is done. At the moment, neither function actually changes it.

**Comment by chmue** [comment]
I'm tracking this in the `issue-1274` branch.

**Comment by chmue** [comment]
Do you want to set the `smooth` slot in cases where you "smooth" floor logarithms at 0 as well?

E.g. in the following case ([from here](https://github.com/quanteda/quanteda/blob/74148b7ace3da96453805a50d311bfc87242b50d/R/dfm_weight.R#L172-L176))
```r
} else if (scheme == "logcount") {
  x@x <- 1 + log(x@x, base)
  x@x[is.infinite(x@x)] <- 0
```
one could argue that the amount of "smoothing" is `base^(-1)`---`exp(-1)` in the default case. However, it is not really smoothing as in `dfm_smooth()` as it the smoothing values is only added to the counts that are zero and not all the counts.

What do you think @kbenoit ?

**Comment by kbenoit** [comment]
No, the smooth parameter is just for a constant added via `dfm_smooth()`.
