### ISSUE TITLE
Levels argument to dfm is not passed to tokens_lookup

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda#1277]
`dfm` has `dictionary`, but we cannot choose dictionary levels because `...` is not passed to underlying `tokens_lookup()`. I think it should.

**Comment by kbenoit** [comment]
We are starting to see strain with the one-command-does-all dfm approach, that includes arguments passed to other functions. Namely, it's hard to include them all in dfm and not be inconsistent with lower functions, or be incomplete. For `dfm(...)` we have two arguments, `dictionary` and `thesaurus`, that produce the `TRUE` and `FALSE` states of the `tokens_lookup(..., exclusive = )` arguments. 

We either keep going down the rabbit hole and adding ways to make this approach work better, or consider a redesign.

The `...` in `dfm()` is currently reserved for additional `tokens()` arguments. We have a few choices to change this:
* Trap and parse `...` and figure out which arguments are for `tokens_lookup()` and which are for `tokens()`, which is messy and not necessarily intuitive, or robust.
* Implement another parameter to pass through to `tokens_lookup()`.
* Keep existing behaviour but recommend `tokens() %>%  tokens_lookup() %>% dfm()` for better control. If we were to redo `dfm()` from scratch I might even recommend this approach.

**Comment by koheiw** [comment]
`tokens() %>% tokens_lookup() %>% dfm()` is the way for me to do the task now. We might consider unloading some functions from `dfm()` instead of making it even more complex.
