### ISSUE TITLE
nsyllable does not count all caps words inside quotes

### ISSUE THREAD

**Issue by JEbertPrime** [quanteda/quanteda#1282]
For some reason nsyllable can understand words that are first letter capitalized and words in lowercase inside quotation marks, but does not count all-caps words in quotes. Maybe this is something I'm just doing wrong.
```
all_caps=c("\"NO\"","\"DOG CAT\"")
nsyllable(all_caps)
# [1] NA NA
 all_caps=c("\"NO\"","\"DOG Cat\"")
 nsyllable(all_caps)
# [1] NA  1
 all_caps=c("\"NO\"","\"DOg Cat\"")
 nsyllable(all_caps)
# [1] NA  1
 all_caps=c("\"NO\"","\"Dog Cat\"")
 nsyllable(all_caps)
# [1] NA  2
```

**Comment by kbenoit** [comment]
It's a 🐞 , thanks @JEbertPrime. The problem has to do with a) failure to remove the punctuation and b) when matching a word not looked up in the syllable dictionary, failure to count vowels accurately for uppercase "non-words". (The first problem causes quoted recognised words to be unrecognised.)

We can see this:
```
# these are fine
nsyllable("cat")
## [1] 1
nsyllable("CAT")
## [1] 1

# these are broken for uppercase
nsyllable("'cat'")
## [1] 1
nsyllable("'CAT'")
## [1] NA
nsyllable('"cat"')
## [1] 1
nsyllable('"CAT"')
## [1] NA

# broken for words not in dictionary generally, when uppercased 
nsyllable("notword")
# [1] 2
nsyllable("NOTWORD")
# [1] NA
```
