### ISSUE TITLE
Consider new policy that pkgdown site should only match CRAN

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#1284]
I think we should consider adopting a policy that the pkgdown site would only and always match CRAN releases. 

a) This prevents a difference between the released versions and the documentation site, which could otherwise cause confusion, and 
b) it prevents the annoying merge conflicts that occur when we try to update a PR with changes to the pkgdown site that have occurred from another branch.

**Comment by koheiw** [comment]
I totally agree. Tutorials website is only rebuilt only using CRAN version. However, does this mean that we can not add pages or correct typo?

**Comment by kbenoit** [comment]
I’m fine with adding those as long as they match the release version. I suppose we can just ensure that the pkgdown output is based on the release build, so that the docs/ master is based on the release, even if this is out of sync with the code in the master. 

Maybe reviving the gh-pages branch approach oils make this easier!

**Comment by koheiw** [comment]
Yes, I think we need a website branch to isolate the website from the master.

**Comment by kbenoit** [comment]
There is still the question of how to keep a website branch current with bug fixes but not current with any new features or API changes that would alter the documentation or output from the examples. Even with a website branch, we would want to merge the former from the master, but not the latter. 

We would probably have the same problem if we created a `newfeatures` branch and kept it parallel to the master but separate, since it’s hard to distinguish the two types of commits.

This would be a good question for the rOpenSci #general channel.

**Comment by koheiw** [comment]
We should only try to make the website identical to https://cran.r-project.org/web/packages/quanteda/quanteda.pdf even if the CRAN version has bugs. I tried to rebuild the website for v1.1.1, which is on CRAN, but found it difficult identify the commit ID for that version. We need to keep track of CRAN versions and the last commit ID or create a branch for every CRAN version for the website.

**Comment by kbenoit** [comment]
You can always install the [CRAN release](https://github.com/quanteda/quanteda/releases) using (e.g.):
```r
devtools::install_github("quanteda/quanteda@v1.1.1")
```
and then build the **pkgdown** site.

**Comment by kbenoit** [comment]
Ah right. I meant then you can check out the tagged commit using git and then build it.

**Comment by koheiw** [comment]
I see. It is really easy to find out commit IDs on this page!
https://github.com/quanteda/quanteda/releases

**Comment by koheiw** [comment]
It seems that Github pages allows only 'docs' in `master` or the root directory in `gh_pages`. However, there is a way to copy docs to a `gh_pages` branch: https://gist.github.com/cobyism/4730490. If it seems too complex, we could revive `dev` branch, setting aside `master` for CRAN versions.

**Comment by kbenoit** [comment]
Here's how to get the new docs into master:
1. checkout the commit from the release page for the version for which you wish to build the docs.
2. `pkgdown::build_site()`
3. Switch to the master branch, without staging the changes.
4. Stage the changes, commit, push. They will then go to `master`.

Have not tried it but I think this will work. 🤞

**Comment by koheiw** [comment]
After the step 3, `git status` says:
```
On branch master
Your branch is behind 'origin/master' by 19 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
nothing to commit, working directory clean
```

**Comment by kbenoit** [comment]
Did you pull master first?

You can stash the changes from your pkgdown branch, `git stash`, then checkout and pull master, then `git stash apply`, stage, commit, push.

**Comment by koheiw** [comment]
What we have to do is just run `git subtree push --prefix docs origin gh-pages` after building the site using a CRAN version. The documentation is for v1.1.1 now.

**Comment by kbenoit** [comment]
These instructions would be good to have in the Wiki, along with contributor guidelines, style rules, etc.

**Comment by kbenoit** [comment]
https://github.com/quanteda/quanteda/wiki, but it lacks a central page. (It used to have one, but I am not sure what happened to it.) @amatsuo knows more about GitHub's wikis. I think it might even be a specialised branch, but I am not sure - I clearly need a refresher on the topic.
