### ISSUE TITLE
Export regex2fixed() for extension packages

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda#1287]
`textmodel_lss` in my LSS packages uses `regex2fixed()` but through `:::`. We should export it to facilitate development of extension packages. Relatedly `flatten_dictionary` would be useful too.

**Comment by kbenoit** [comment]
I’m fine with that. I think we should revise the Wiki to suggest guidelines for extending quanteda, for contributing, and for using exported utility objects that are designed for extending the package.

We could consider naming these something like `quanteda_regex2fixed()`, `quanteda_flatten_dictionary()`, to avoid namespace conflicts and to make it clear where these came from. I agree with Hadley’s [dictum ](http://r-pkgs.had.co.nz/namespace.html#exports) in _R Packages_:
> it’s a really good idea to only export needed functions. This reduces the chances of a conflict with another package.

**Comment by koheiw** [comment]
Even if there are `regex2fixed` in other packages, users can specify which one one use by `quanteda::regex2fixed()`, so I don't think we need the `quanted_` prefix. Also users should not import all the exported functions of dependencies in principle.

**Comment by kbenoit** [comment]
I'm happy with that.
