### ISSUE TITLE
Providing own list for lemmatizing/tokenizing?

### ISSUE THREAD

**Issue by vtmiller** [quanteda/quanteda#1291]
First of all, thank you very much for developing quanteda - I've used it in multiple projects and usually it does everything i need in quantitative text analysis - and it does it very fast too!

Today I encountered a little problem: Snowball, and therefore quanteda, understandably only provide stemming for some languages. I have to work with multiple other languages that are not supported. However, there are lemmatization lists for these languages available on the internet (lists containing a huge number of words and their corresponding lemmas in two columns). Is there a way to tell quanteda to take my tokens and my list and replace the tokens with the corresponding lemmas?

Thank you in advance!

**Comment by koheiw** [comment]
Thanks for the kind words. Please check if `tokens_replace()` works for you.

**Comment by kbenoit** [comment]
Can you point us to these Internet sources of lemmas?

**Comment by kbenoit** [comment]
We are unlikely to build this into **quanteda**, but we could easily provide this as part of a tutorial.
