### ISSUE TITLE
Add tokens()'s removal defaults to quanteda_options()?

### ISSUE THREAD

**Issue by luke-a** [quanteda/quanteda#1301]
Does it make sense to to add the logical removal arguments `remove_numbers = FALSE, remove_punct = FALSE, remove_symbols = FALSE, remove_separators = TRUE, remove_twitter = FALSE, remove_hyphens = FALSE, remove_url = FALSE`  from `tokenize()` to `quanteda_options()`, in order to change the defaults easily? I feel like I often have to touch these. But maybe I am alone. :-) Could be something like 

```
get_options_default <- function(){
  opts <- list(threads = min(RcppParallel::defaultNumThreads(), 2),
               verbose = FALSE,
               print_dfm_max_ndoc = 20L,
               print_dfm_max_nfeat = 20L,
               base_docname = "text",
               base_featname = "feat",
               base_compname = "comp",
               language_stemmer = "english",
               tokenize_remove_numbers = FALSE,
               tokenize_remove_punct = FALSE, 
               tokenize_remove_symbols = FALSE, 
               tokenize_remove_separators = TRUE,
               tokenize_remove_twitter = FALSE, 
               tokenize_remove_hyphens = FALSE, 
               tokenize_remove_url = FALSE
            )
  return(opts)
}
```

Just an idea.

**Comment by kbenoit** [comment]
Thanks for the suggestion @luke-a. We'd want to implement the settings record for tokens objects first, since this is one step further away from reproducibility, but I can see the use case.

**Comment by luke-a** [comment]
Thanks for considering, @kbenoit.
