### ISSUE TITLE
More friendly errors for tokens object

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda#1308]
```r
require(quanteda)
toks <- tokens(data_corpus_inaugural)
toks[1:100]

# Error in qatd_cpp_tokens_recompile(x, types(x)) : 
#     Not compatible with requested type: [type=NULL; target=double].
should be like
# Error: subscript out of bounds
```
https://github.com/quanteda/quanteda/blob/7c5790e9494c68df80347f62fae192c18bcbe644/R/dfm-subsetting.R#L49

```

**Comment by EruIluvatar** [comment]
Sorry to write on a closed issue, but I experienced something similiar which has to do with `qatd_cpp_tokens_recompile`.

The following code:
```R
news_corp <- download("data_corpus_guardian")
docvars(news_corp, 'year') <- year(docvars(news_corp, 'date'))
docvars(news_corp, 'month') <- month(docvars(news_corp, 'date'))
docvars(news_corp, 'week') <- week(docvars(news_corp, 'date'))

news_corp <- corpus_subset(news_corp, 'year' >= 2016)
news_toks <- tokens(news_corp)
```
generates the error message:

> Error in .Call(\`_quanteda_qatd_cpp_tokens_recompile\`, texts_, types_,  : 
> Incorrect number of arguments (4), expecting 2 for '_quanteda_qatd_cpp_tokens_recompile'

Is this an internal error/bug of quanteda or an unfriendly error because of bad library usage from my side?
