### ISSUE TITLE
Travis CI cross-platform tests

### ISSUE THREAD

**Issue by tpaskhalis** [quanteda/quanteda#1311]
The current Travis CI setup tests quanteda on one version of Ubuntu. Travis [allows](https://docs.travis-ci.com/user/multi-os/) testing on multiple platforms (Linux and OSX) and different versions of R using matrices. [RMySQL](https://github.com/r-dbi/RMySQL/blob/master/.travis.yml) provides a good example. Jeroen Ooms also has this nice [write-up](https://ropensci.org/blog/2016/07/12/travis-osx).

There was a similar discussion for Rcpp - https://github.com/RcppCore/Rcpp/issues/517 and the decision was negative, due to the increase in time it takes for tests for finish and the possibility of random breaks, but I thought it might be something to consider.

**Comment by kbenoit** [comment]
Thanks Tom - Is that something you would interested in configuring for the quanteda / spacyr / readtext? Would be great to have them test on macOS automatically too.

Appveyor has just added Linux testing too.

**Comment by tpaskhalis** [comment]
Yes, I can look into it. Can't promise how soon, but it shouldn't be too difficult. Though, `spacyr` might be trickier.

**Comment by kbenoit** [comment]
Made obsolete by transition to GitHub actions for CI.
