### ISSUE TITLE
Japanese characters cannot display in network plot

### ISSUE THREAD

**Issue by SyuuGenn** [quanteda/quanteda#1317]
Dear quanteda team,

I'm learning doing Japanese text analysis through your examples(http://docs.quanteda.io/articles/pkgdown/examples/japanese_speech_ja.html). When I draw the network plot by running `textplot_network(speech_fcm, min_freq = 0.85, edge_alpha = 0.9, vertex_size = size / max(size) * 3)`, the plot I get is problematic. All the Japanese characters became 'tofu' as the following picture shows.
![rplot](https://user-images.githubusercontent.com/35292602/38767492-5bcced5c-401d-11e8-8302-a8a1060a632e.png)
I added the font code `vertex_labelfont = "MS Gothic"`, but it returns:

>Error in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  : 
  polygon edge not found
In addition: Warning messages:
1: In grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  :
  no font could be found for family "MS Gothic"
2: In grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  :
  no font could be found for family "MS Gothic"

I do have MS Gothic in my font book, and my work environment is:

> R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.4

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] topicmodels_0.2-7 lubridate_1.7.3   stringr_1.3.0    
[4] dplyr_0.7.4       quanteda_1.1.1   

loaded via a namespace (and not attached):
 [1] NLP_0.1-11            Rcpp_0.12.16         
 [3] sna_2.4               quanteda.corpora_0.85
 [5] highr_0.6             pillar_1.2.1         
 [7] compiler_3.4.3        plyr_1.8.4           
 [9] bindr_0.1.1           tools_3.4.3          
[11] stopwords_0.9.0       extrafont_0.17       
[13] tibble_1.4.2          gtable_0.2.0         
[15] lattice_0.20-35       pkgconfig_2.0.1      
[17] rlang_0.2.0           Matrix_1.2-13        
[19] fastmatch_1.1-0       parallel_3.4.3       
[21] ggrepel_0.7.0         bindrcpp_0.2.2       
[23] Rttf2pt1_1.3.6        knitr_1.20           
[25] xml2_1.2.0            stats4_3.4.3         
[27] grid_3.4.3            glue_1.2.0           
[29] data.table_1.10.4-3   R6_2.2.2             
[31] extrafontdb_1.0       ggplot2_2.2.1        
[33] spacyr_0.9.6          magrittr_1.5         
[35] scales_0.5.0          modeltools_0.2-21    
[37] assertthat_0.2.0      colorspace_1.3-2     
[39] stringi_1.1.7         network_1.13.0.1     
[41] RcppParallel_4.4.0    lazyeval_0.2.1       
[43] munsell_0.4.3         tm_0.7-3             
[45] slam_0.1-42           statnet.common_4.0.0

Hope you can help me to fix the problem.
Best wishes!

**Comment by kbenoit** [comment]
This is a font issue, and for some reason there was a change in the fonts installed by default during a recent macOS upgrade. The call to
```r
textplot_network(speech_fcm, min_freq = 0.85, edge_alpha = 0.9, 
                 vertex_size = size / max(size) * 3,
                 vertex_labelfont = if (Sys.info()["sysname"] == "Darwin") "SimHei" else NULL)
```
was designed to have it work with the latest version - and does work on my macOS 10.13.4. For your system, you might need to change that font.

@amatsuo uses macOS and can advise more.

**Comment by amatsuo** [comment]
@SyuuGenn 
You can first try `extrafont::font_import()` to install ms-gothic font to R. That worked in my system.

@kbenoit, @koheiw 
I am not fond of the current implementation of how quanteda checks the existence of a font. Not all fonts are installed by `font_import()`. And therefore, fonts exist in the system but not recoginized by `extrafont` package cannot be used by the package. 

**Example:**

```r
library(ggplot2)
colnames(speech_dfm) %>% head(100) -> tmp
df <- data.frame(txt = tmp, x = rnorm(100), y = rnorm(100))

ggplot(df) + aes(x = x, y = y, label = txt) + 
    geom_text(family = "HiraKakuPro-W3")
```
This works perfectly in my system (`Hirakaku` is a font coming with MacOS and beloved by a lot of Japanese Mac users). But this does not work:

```r
textplot_network(speech_fcm, min_freq = 0.95, edge_alpha = 0.9, vertex_size = size / max(size) * 3, 
vertex_labelfont = "HiraKakuProN-W3")
## Error in check_font(vertex_labelfont) : HiraKakuProN-W3 is not found on your system. Run
## extrafont::import_font() to use custom fonts.
```
(By the way `import_font()` is a typo `font_import()` is the right one).

**Comment by SyuuGenn** [comment]
@kbenoit @amatsuo 
Thanks for your replying. I had tried `extrafont::font_import()`, and checked the fonts in R by running `extrafont::fonts()`. The results are as following

>  [1] ".Keyboard"             "System Font"          
 [3] "Andale Mono"           "Apple Braille"        
 [5] "AppleMyungjo"          "Arial Black"          
 [7] "Arial"                 "Arial Narrow"         
 [9] "Arial Rounded MT Bold" "Arial Unicode MS"     
[11] "Bodoni Ornaments"      "Bodoni 72 Smallcaps"  
[13] ""                      "Brush Script MT"      
[15] "Comic Sans MS"         "Courier New"          
[17] "DIN Alternate"         "DIN Condensed"        
[19] "Georgia"               "Impact"               
[21] "Khmer Sangam MN"       "Lao Sangam MN"        
[23] "Luminari"              "Microsoft Sans Serif" 
[25] "MS Gothic"             "Tahoma"               
[27] "Times New Roman"       "Trattatello"          
[29] "Trebuchet MS"          "Verdana"              
[31] "Webdings"              "Wingdings"            
[33] "Wingdings 2"           "Wingdings 3"

The 25th font is MS Gothic. However, when I ran `textplot_network(speech_fcm, min_freq = 0.85, edge_alpha = 0.9, vertex_size = size / max(size) * 3, vertex_labelfont = "MS Gothic")`, it still returns

> Error in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  : 
  polygon edge not found
In addition: Warning message:
In grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  :
  no font could be found for family "MS Gothic"

**Comment by SyuuGenn** [comment]
I ran your code, but the same error appeared.

> Warning messages:
1: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
2: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
3: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
4: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
5: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
6: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
7: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
8: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
9: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
10: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
11: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
12: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
13: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
14: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
15: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
16: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
17: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
18: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
19: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
20: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
21: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
22: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
23: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
24: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
25: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
26: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
27: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
28: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
29: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
30: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
31: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
32: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
33: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
34: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
35: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
36: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
37: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
38: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
39: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
40: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
41: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
42: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
43: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
44: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
45: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
46: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
47: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
48: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
49: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
50: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "MS Gothic"
There were 50 or more warnings (use warnings() to see the first 50)

The plot I got is as following.
![rplot](https://user-images.githubusercontent.com/35292602/38785558-400e771c-415c-11e8-9eeb-26b13026d47b.png)

**Comment by koheiw** [comment]
Do you need this `loadfonts()`?

**Comment by amatsuo** [comment]
I don't think so. Not sure why this is happening. The problem seems deeper than I originally thought.

@SyuuGenn 
What does this return?
```r
extrafont::fonttable() %>% filter(stringr::str_detect(FamilyName, "^MS.*Gothic"))
```

Mine looks like this:
```
  package           afmfile                                fontfile   FullName FamilyName
1      NA  MS Gothic.afm.gz  /Library/Fonts/Microsoft/MS Gothic.ttf  MS Gothic  MS Gothic
2      NA MS PGothic.afm.gz /Library/Fonts/Microsoft/MS PGothic.ttf MS PGothic MS PGothic
    FontName  Bold Italic Symbol afmsymfile
1  MS-Gothic FALSE  FALSE  FALSE         NA
2 MS-PGothic FALSE  FALSE  FALSE         NA
```

**Comment by SyuuGenn** [comment]
@amatsuo 
It returns

>   package          afmfile
1      NA MS Gothic.afm.gz
                                     fontfile  FullName FamilyName
1 /Users/yuanzhou/Library/Fonts/MS Gothic.ttf MS Gothic  MS Gothic
   FontName  Bold Italic Symbol afmsymfile
1 MS-Gothic FALSE  FALSE  FALSE         NA
Warning message:
package ‘bindrcpp’ was built under R version 3.4.4 

Maybe I should update my R version?

**Comment by amatsuo** [comment]
Did you check whether the file exists?

**Comment by SyuuGenn** [comment]
@amatsuo 
Oh, that's the problem. My fonts are saved in '/Library/Fonts/'. I copied them to '/Users/yuanzhou/Library/Fonts/', and then the Japanese characters can display correctly.
Thanks a lot!
