### ISSUE TITLE
liwcalike: WPS double-column crashes write.csv and alike

### ISSUE THREAD

**Issue by EruIluvatar** [quanteda/quanteda#1324]
We found that liwcalike() produces a data.frame that cannot be converted to a matrix in a straight-forward fashion and thus breaks the export of csv files.
This is because the function creates the WPS column, which itself contains 2 lists (document, meanSentenceLength).

`str(dict_analysis)
`
> 'data.frame':	1804 obs. of 28 variables:
> $ docname : chr "text1" "text2" "text3" "text4" ...
> $ Segment : int 1 2 3 4 5 6 7 8 9 10 ...
> $ WC : int 1 1 1 5 1 5 5 1 5 5 ...
> $ WPS :Classes 'readability', 'textstat' and 'data.frame':	1804 obs. of 2 variables:
> ..$ document : chr "text1" "text2" "text3" "text4" ...
> ..$ meanSentenceLength: num 1 1 1 5 1 5 5 1 5 5 ...
> $ Sixltr :Class 'AsIs' chr [1:1804] "100.000" "100.000" "100.000" "40.000" ...
> [...]

Trying to export it leads to a crash in as.matrix.data.frame:
https://github.com/wch/r-source/blob/af7f52f70101960861e5d995d3a4bec010bc89e6/src/library/base/R/dataframe.R#L1468

`temp <- as.matrix(dict_analysis[4])`
> Error in ncol(xj) : object 'xj' not found

Similar problems exist with simple dplyr usage:
```R
min_ <- dict_analysis %>% 
  filter(X_id %in% c(2315968))
```
> Error: Column WPS must be a 1d atomic vector or a list

**Comment by stefan-mueller** [comment]
`liwcalike()` is not a function of the **quanteda** package and has been moved from **LIWCalike** to the [**quanteda.dictionaries**](https://github.com/kbenoit/quanteda.dictionaries) package (not on CRAN yet). I used `data_corpus_inaugural()` to replicate your problem, and it seems to work. 

```r
# the devtools package needs to be installed for this to work
devtools::install_github("kbenoit/quanteda.dictionaries") 

library(quanteda.dictionaries)
library(quanteda)
library(dplyr)

dict_analysis <- quanteda.dictionaries::liwcalike(data_corpus_inaugural)

temp <- as.matrix(dict_analysis[4])

head(temp)

# WPS
# [1,] 62.21739
# [2,] 33.75000
# [3,] 62.72973
# [4,] 42.19512
# [5,] 48.13333
# [6,] 56.04762


min <- dict_analysis %>% 
    dplyr::filter(docname %in% c("2009-Obama", "2013-Obama"))

nrow(min)
# [1] 2
```

Please let us know whether `quanteda.dictionaries::liwcalike()` also works for your corpus.

**Comment by EruIluvatar** [comment]
whoops, thanks for the pointer!

**Comment by EruIluvatar** [comment]
Can confirm, everything works as expected using `quanteda.dictionaries`.
