### ISSUE TITLE
Problem with french accents when using "dfm"

### ISSUE THREAD

**Issue by atrolle** [quanteda/quanteda#1326]
Hi,

I have a problem with french accents when using "dfm".
In particular, the accents are not correctly displayed when inspecting the dfm.
For instance: "qualité" is displayed as "qualitÃ©"
Here is the code I'm using to create the dfm:

```r
com <- as.String(readLines("Caracteristiques.txt", encoding = "UTF-8")

vec.com <- unlist(strsplit(com,"\n"))

vec.com.tol <- char_tolower(vec.com)

vec.com.tok <- tokens(vec.com.tol, remove_punct = TRUE,
                       remove_symbols = TRUE)

vec.com.tok <- tokens_remove(vec.com.tok, stopwords("french"))
 
DFM_com <- dfm(vec.com.tok)
```
Note that I saved my input text file "Caracteristiques.txt" using a "UTF-8" encoding.
Everything's going fine until I'm using "dfm".
Any idea about the origin of this problem?

Thank you in advance for your feedback,
Best,

**Comment by kbenoit** [comment]
I think it's the way you are using `readLines()`.  Try this instead:
```r
library("readtext")
corp <- readtext("Caracteristiques.txt") %>%
    corpus()
toks <- tokens(corp, remove_punct = TRUE, remove_symbols = TRUE) %>%
    tokens_remove(stopwords = "french") %>%
    tokens_tolower()
DFM_com <- dfm(toks)
```

**Comment by atrolle** [comment]
Unfortunately, I've got the same issue when using "readtext": everything's going fine until I'm using "dfm".

**Comment by koheiw** [comment]
@atrolle Why don't you share Caracteristiques.txt with us?

**Comment by amatsuo** [comment]
For the following code, I didn't see any issue with my Mac:

```r
library(rvest)
library(quanteda)
library(dplyr)

scraping_wiki <- read_html(url)
url <- "https://fr.wikipedia.org/wiki/Emmanuel_Macron"


scraping_wiki %>%
  html_nodes("p") %>%
  html_text() -> txt
head(txt)

Encoding(txt) %>% table()
dfm_txt <- txt %>% dfm()

dfm_select(dfm_txt, pattern = "é", valuetype = "regex") %>% topfeatures()

## présidentielle      président     république      également     l'économie        déclare 
##            38             35             27             22             21             21 
##       général     l'élection            été         l'état 
##            19             18             17             17 
```

What's the OS you use? Could you paste the results from `sessionInfo()`?

Also, when do you see the mojibake? On console output? Rstudio's `View()`?

Or maybe unicode normalization would help.

```r
vec.com <- unlist(strsplit(com,"\n"))
vec.com <- stringi::stri_trans_nfkd(vec.com)
```

**Comment by atrolle** [comment]
Thank you for your feeback/
Here is the file.
[Caracteristiques.txt](https://github.com/quanteda/quanteda/files/1954276/Caracteristiques.txt)

**Comment by atrolle** [comment]
Here the results from `sessionInfo()`:
`R version 3.4.2 (2017-09-28)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252 LC_NUMERIC=C                  
[5] LC_TIME=French_France.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] coreNLP_0.4-2  RWeka_0.4-37   stringr_1.2.0  igraph_1.1.2   openNLP_0.2-6  tm_0.7-3       NLP_0.1-11     rJava_0.9-9   
 [9] readtext_0.50  quanteda_1.2.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.16        pillar_1.1.0        compiler_3.4.2      plyr_1.8.4          RWekajars_3.9.2-1   tools_3.4.2        
 [7] stopwords_0.9.0     lubridate_1.7.4     tibble_1.4.1        gtable_0.2.0        lattice_0.20-35     pkgconfig_2.0.1    
[13] rlang_0.1.6         Matrix_1.2-12       fastmatch_1.1-0     yaml_2.1.18         parallel_3.4.2      openNLPdata_1.5.3-4
[19] httr_1.3.1          xml2_1.1.1          grid_3.4.2          data.table_1.10.4-3 R6_2.2.2            XML_3.98-1.11      
[25] ggplot2_2.2.1       spacyr_0.9.9        magrittr_1.5        scales_0.5.0        colorspace_1.3-2    stringi_1.1.7      
[31] RcppParallel_4.4.0  lazyeval_0.2.0      munsell_0.4.3       slam_0.1-43`

**Comment by koheiw** [comment]
Please check what is the OS non-Unicode program language. On Windows 10, go to Windows’ Control Panel > Clock, Language, and Region > Change date, time, or number formats > Administrative > Language for non-Unicode program > Change system locale. It should be French.

See https://koheiw.net/?p=490

**Comment by kbenoit** [comment]
This might explain some of it:
```r
Running under: Windows 7 x64 (build 7601) Service Pack 1
```

I tried to replicate the problem now on my Windows 7 (SP 2 however) VM, but got stuck with not being able to install data.table on R 3.5. (But I'm told a CRAN binary update is imminent.)

**Comment by atrolle** [comment]
@koheiw I checked OS non-Unicode program language. Indeed, it is French.

**Comment by koheiw** [comment]
Thanks for the input. Windows 7 is beyond our knowledge. I encourage you to install Ubuntu in VirtualBox  to solve encoding issues entirely.

**Comment by atrolle** [comment]
Ok. Thank you very much for the advice.

Best,
