### ISSUE TITLE
Is there a way to normalize rows in an fcm (i.e., transform counts into values from 0 to 1)?

### ISSUE THREAD

**Issue by fire-elf** [quanteda/quanteda#1332]
Good day,

I have an fcm of dimensions 94966 x 94966 (named fcm2, for illustration). I am able to select rows (class: fcm object) by the feature name or row number, e.g.:

a1 <- fcm2[1,]

and perform a normalization calculation on that particular row:

a2 <- a1/(max(a1)-min(a1))

My objective is to normalize each row in my original fcm. The strategy I attempted was to initialize an empty matrix and then use a for loop to go through the rows and perform the calculation. The initialization fails because of memory issues (Windows 10, 12 Gb RAM, R version 3.4.4):

> fcm3 <- matrix(data = NA, nrow = 94966, ncol = 94966)
Error: cannot allocate vector of size 33.6 Gb

I had been able to accomplish the normalization by using a dataframe structure, but there is not enough memory to store the entire fcm2 as a dataframe:

#Extract a "sub-matrix" based on a list of keywords, convert to dataframe, drop unneeded columns 
     m <- fcm2[keywords(),]
      df_m1 <- as.data.frame(m)
      df_m1 <- subset(df_m1, select = -c(document, rt))

#Normalization
      k <- 0 # initialize counter
      df2 <- data.frame() # initialize
      n4 <- nrow(df_m1) # count rows of the extracted sub-matrix as df (df_m1)
    
      for(k in 1:n4){
        a1 <- df_m1[k,] # store the (n4)th row 
        max_k <- max(a1)
        min_k <- min(a1)
        a2 <- a1/(max_k-min_k) # normalize so max is 1, 0s are still 0s
        df2 <- rbind(df2, a2) # append normalized results into a row of a data.frame
      }

Is there a more efficient way to normalize each row for the entire fcm?

Kind thanks,

JHH

**Comment by kbenoit** [comment]
This belongs on the [quanteda SO channel](https://stackoverflow.com/questions/tagged/quanteda).

**Comment by fire-elf** [comment]
Apologies for posting to the wrong place! I am a learning R programming on my own in my free time, and while I search GitHub and SO frequently (most of my questions have been asked and answered by others), this is my first time venturing to post my own question. If anyone here with expertise would be willing to consider my question, please, I have reposted it as directed on SO: 

https://stackoverflow.com/questions/50206469/is-there-a-way-to-normalize-rows-in-an-fcm-i-e-transform-counts-into-values-f

With appreciation,

J

**Comment by kbenoit** [comment]
Thanks, I see you already have multiple answers there, including one of my own.
