### ISSUE TITLE
textplot_scale1d(margin = "documents") for Wordscores does not plot confidence intervals

### ISSUE THREAD

**Issue by stefan-mueller** [quanteda/quanteda#1340]
Because `se.fit = FALSE` is the (new) default setting in `predict.textmodel_wordscores()`, confidence intervals are not plotted anymore for the `textplot_scale1d()` examples for Wordscores document positions. 

Either we use `se.fit = TRUE` as the default (but this means that the predict method does not match `predict.lm` anymore), or I change the examples/vignettes and add `se.fit = TRUE`. Let me know what you prefer (I presume option 2, but I wanted to ask before I make changes).

```r
library(quanteda)
ie_dfm <- dfm(data_corpus_irishbudget2010)

doclab <- apply(docvars(data_corpus_irishbudget2010, c("name", "party")), 
                1, paste, collapse = " ")

refscores <- c(rep(NA, 4), 1, -1, rep(NA, 8))
ws <- textmodel_wordscores(ie_dfm, refscores, smooth = 1)

# plot estimated document positions (with the default setting of se.fit)
ws %>% 
    predict() %>% 
    textplot_scale1d(margin = "documents", doclabels = doclab)

# plot estimated document positions with confidence intervals 
# (setting se.fit = TRUE)
ws %>% 
    predict(se.fit = TRUE) %>% 
    textplot_scale1d(margin = "documents", doclabels = doclab)
```

**Comment by kbenoit** [comment]
Option 2
