### ISSUE TITLE
Japanese word cloud

### ISSUE THREAD

**Issue by SyuuGenn** [quanteda/quanteda#1344]
I want to plot a word cloud when I do Japanese text analysis. I drew out the graph, but it seems not as beautiful as English word cloud.
![rplot](https://user-images.githubusercontent.com/35292602/40039135-1d281ba8-5850-11e8-81a6-9f4a79da0e0f.png)
The code I ran is `textplot_wordcloud(speech_dfm, font = "MS Gothic", min_count = 50, random_order = FALSE, min_size = 0.5, max_size = 2.8, max_words = 100, color = RColorBrewer::brewer.pal(8,"Dark2"))` .
Do you have any advice to improve the quality of Japanese word cloud?

**Comment by koheiw** [comment]
You can use `adjust` for non-English words. Also, the same sizes of texts suggest that frequencies are the same for all the words.

**Comment by SyuuGenn** [comment]
@koheiw Thank you! It's the frequency problem. In the example I posted, the frequencies of all the words are almost the same. In another case I analyzed, I set `padding = TRUE` when removing non-text parts and entries only with hiraganas. So, compared to the huge number of spaces, the frequencies of all the other characters were like to be same.  I removed the spaces and used `adjust`, then got a nice plot.
![rplot07](https://user-images.githubusercontent.com/35292602/40051783-eefaaf94-5876-11e8-8fa0-ace5cf5b74c2.png)

**Comment by koheiw** [comment]
Looks like a wordcloud this time. Why don't you use a font other than MS Gothic to make it nicer?

**Comment by SyuuGenn** [comment]
@koheiw Good idea! But I know only a few Japanese fonts like MS Gothic, MS Mincho. Do you have any recommendation?

**Comment by koheiw** [comment]
Looks better. You should remove numbers.

**Comment by SyuuGenn** [comment]
@koheiw Yeah. I'm still at the early stage of this work. More things need to be done to make the data tidier. I think I can learn more from you when you come to Kobe University giving us lectures.

**Comment by SyuuGenn** [comment]
@koheiw Sorry, one more question about the word cloud. There is a large blank space around the word cloud, and it looks not good when imported into LaTex. Can I plot a word cloud graph with less blank space using some codes, or I have to cut the blank space manually?

**Comment by neera773** [comment]
Hi! May I know what is your code for R to read a japanese text and what file did you use? Is it csv file, text file etc.?

**Comment by yuanzhouIR** [comment]
> Hi! May I know what is your code for R to read a japanese text and what file did you use? Is it csv file, text file etc.?

You can import csv file using read.csv(). Also, you can use the readtext package to import a variety of text files. See https://tutorials.quanteda.io/import-data/multiple-files/.
