### ISSUE TITLE
strange predictions for bogus observations

### ISSUE THREAD

**Issue by randomgambit** [quanteda/quanteda#1361]
Consider this
```
dtrain <- data_frame(text = c("Chinese Beijing Chinese",
                              "Chinese Chinese Shanghai",
                              "Chinese Macao",
                              "Tokyo Japan Chinese"),
                     doc_id = 1:4,
                     garbage = 1:4)



trainingset <- dfm(corpus(dtrain, docid_field = 'doc_id', text_field = 'text'))
trainingclass <- factor(c("Y", "Y", "Y", "N"), ordered = TRUE)

nb_test <- textmodel_nb(trainingset, trainingclass, prior = "docfreq")
predict(nb_test, trainingset)$nb.predicted

```
Now that I have my model, I am going to try to predict new observations. Note how my new dataframe `dtest` contains a few bogus observations that are `''`, `NA` .

The issues is that `predict`  returns a positive prediction for these missing obs whereas, I believe, it should return an `NA`. Is that expected?

```
dtest <- data_frame(text = c("japan is back",
                             NA,
                             ''),
                    otherid = 11:13,
                    garbagestuff = c('bla', 'bla', 'blo'),
                    randomstuff = 1:3)
testcorp <- dfm(corpus(dtest))
testcorp <- dfm_select(testcorp, trainingset)
predict(nb_test, testcorp)$nb.predicted
[1] "N" "Y" "Y"
```

**Comment by randomgambit** [comment]
hello the dream team @stefan-mueller @amatsuo @kbenoit , any ideas why we have these wrong predictions here? is this a bug or am I missing a key parameter in `quanteda`? Thanks again!

**Comment by koheiw** [comment]
Hi @randomgambit 

It is partially because NA is tokenized as "NA". I will fix this.
```r
tokens(c("a b c", "", NA))
```
```
tokens from 3 documents.
text1 :
[1] "a" "b" "c"

text2 :
character(0)

text3 :
[1] "NA"
```

**Comment by kbenoit** [comment]
Technically speaking, the prediction on `` is not wrong; rather, it reflects your priors on `nb_test`, in the absence of new data from `testcorp`.

We can see this by fitting a slightly different NB model with different priors.

```r
packageVersion("quanteda")
## [1] ‘1.2.3’

predict(nb_test, testcorp, type = "probability")
##               N         Y
## text1 0.5090909 0.4909091
## text2 0.2500000 0.7500000
## text3 0.2500000 0.7500000
```
Those are the priors from the model, and explain why the prediction for the `text2` and `text3` are `Y` even though all feature counts are zero.

If we change the prior, we get different results:
```r
nb_test2 <- textmodel_nb(trainingset, trainingclass, prior = "uniform")
predict(nb_test2, testcorp, type = "probability")
##               N         Y
## text1 0.7567568 0.2432432
## text2 0.5000000 0.5000000
## text3 0.5000000 0.5000000
```
