### ISSUE TITLE
RStudio Session Aborted Estimating Wordfish Model

### ISSUE THREAD

**Issue by dewalter815** [quanteda/quanteda#1365]
I am trying to estimate a wordfish model using textmodel_wordfish on a dfm.  I ran the following command:

wf <- textmodel_wordfish(dfm, dir = c(6,5))

Every time I do this, the computer works hard for a bit and then I get the following message:

R Session Aborted 
R encountered a fatal error.
The session was terminated.
Start New Session

I tried uninstalling RStudio and reinstalling, but that didn't change the result.  Incidentally, I've also had the same issue when trying to predict "sophistication scores" using the Bradley-Terry model from in this paper (https://www.nyu.edu/projects/spirling/documents/BMS_complex.pdf).  There I ran the following command and got the same result:_

preambleresults <- predict_readability(data_BTm_bms, newdata = preamblecorpus, baseline_year = lubridate::year(docvars(preamblecorpus, "yearpub")), bootstrap_n = 0, verbose = TRUE)

I was able to get traditional readability scores, so that makes me doubt that it's a problem with the spacyr install, although I did get the following error message in the otherwise successful spacyr install:

Command "/anaconda3/envs/spacy_condaenv/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/7j/2sn1kv4s5l11npfr2p15l3nm0000gn/T/pip-build-34_qp9yr/murmurhash/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/7j/2sn1kv4s5l11npfr2p15l3nm0000gn/T/pip-5_nhr2f5-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/7j/2sn1kv4s5l11npfr2p15l3nm0000gn/T/pip-build-34_qp9yr/murmurhash/
You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Error: Error 1 occurred installing packages into conda environment spacy_condaenv

Is this just a problem with my machine's power (macbook pro 13 2017, 120gb hard drive, 8gb 2133 MHz LPDDR3, 2.3 GHz Intel Core i5)? Sorry if I'm not providing enough information.  I'm new to R.

**Comment by kbenoit** [comment]
Let's focus on first on some examples that are reproducible. 

First, what is the output of `sessionInfo()`?

Second, can you run the examples from `textmodel_wordfish()` without R crashing?

**Comment by dewalter815** [comment]
I replicated the example in the tutorials with the following code, and it ran without issue:

irish_dfm <- dfm(data_corpus_irishbudget2010, remove_punct = TRUE)
wf <- textmodel_wordfish(irish_dfm, dir = c(6,5))
summary(wf)

Here's the output from session info:

> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.4

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets 
[6] methods   base     

other attached packages:
[1] quanteda_1.2.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.17       magrittr_1.5      
 [3] devtools_1.13.5    stopwords_0.9.0   
 [5] munsell_0.4.3      colorspace_1.3-2  
 [7] lattice_0.20-35    R6_2.2.2          
 [9] rlang_0.2.0        fastmatch_1.1-0   
[11] httr_1.3.1         stringr_1.3.1     
[13] plyr_1.8.4         tools_3.5.0       
[15] grid_3.5.0         data.table_1.11.2 
[17] gtable_0.2.0       git2r_0.21.0      
[19] withr_2.1.2        spacyr_0.9.9      
[21] yaml_2.1.19        lazyeval_0.2.1    
[23] RcppParallel_4.4.0 digest_0.6.15     
[25] tibble_1.4.2       Matrix_1.2-14     
[27] ggplot2_2.2.1      curl_3.2          
[29] memoise_1.1.0      stringi_1.2.2     
[31] compiler_3.5.0     pillar_1.2.2      
[33] scales_0.5.0       lubridate_1.7.4

Given that it worked for the replication data, it seems like the problem could be one of a couple of things.  First, the DFMs I've been trying to analyze are all far bigger than the replication data.  For instance, the one I'm working with now has 99426910 elements and is 18.1 Mb.  Some of the others are even bigger.  Second, I'm only working with about 12 Gb of space on my hard drive, and sometimes (not every time) R aborts with this operation, I get a message that my "disk space is critically low....Older terminal scroll back contents may be automatically discarded to conserve VM backing store." I'm considering doing a clean factory reset on my machine, as I think my operating system is running at about 90gb, which seems high.  Maybe if I can clear some space things would work...I don't know.

**Comment by kbenoit** [comment]
Sounds like a number of issues, including one for the **spacyr** repo. If you want us to try to diagnose your problem with the dfm, you will need to save it and send us a link to it, as in https://github.com/quanteda/quanteda/issues/1369.

**Comment by dewalter815** [comment]
Sorry for the delayed response.  Here's the dfm:

[http://s000.tinyupload.com/?file_id=02873818550799272598](url)

**Comment by kbenoit** [comment]
That link does not work for me...

**Comment by kbenoit** [comment]
Yes that worked. The problem is that `textmodel_wordfish()` is having trouble with your _very_ sparse matrix. Trimming it a bit solves this issue, but so does using a sparse method for computing the model (although this is not deterministic - so your results will vary with each run).

```r
library("quanteda")

load("/Users/kbenoit/Downloads/trimeconsigdfm.rda")
## Document-feature matrix of: 1,210 documents, 82,171 features (98.9% sparse).

# this crashes!
wf <- textmodel_wordfish(trimeconsigdfm)
# this works
wf <- textmodel_wordfish(trimeconsigdfm, sparse = TRUE)
```
The model fails in the first case because the matrix is almost 99% zeroes. Using the `sparse = TRUE` makes it possible to fit, although you will want to set a seed. I did not set one so that you could run this code and see that the plot at the bottom is slightly different!

The other solution is simply trimming the very rarely occurring features.
```r
trimeconsigdfm2 <- dfm_trim(trimeconsigdfm, min_termfreq = 5, min_docfreq = 10,
                            verbose = TRUE)
## Removing features occurring: 
##   - fewer than 5 times: 54,334
##   - in fewer than 10 documents: 70,552
## Total features removed: 70,552 (85.9%).
trimeconsigdfm2
## Document-feature matrix of: 1,210 documents, 11,619 features (93.5% sparse).
wf2 <- textmodel_wordfish(trimeconsigdfm2)
```
Comparing the results:
```r
# compare
cor(coef(wf, "documents"), coef(wf2, "documents"))
plot(coef(wf, "documents"), coef(wf2, "documents"),
     xlab = "Sparse wordfish on entire dfm",
     ylab = "Regular wordfish on trimmed dfm")
```
![wordfishcompare](https://user-images.githubusercontent.com/2182246/40730933-cd1146d8-6427-11e8-8f7d-d80ff5d882a9.png)

**Comment by dewalter815** [comment]
Thanks for breaking that down so clearly! It makes sense that this was causing a problem.  

As I mentioned in the initial post, I also ran into a similar abort problem when trying to run the Bradley-Terry model on my corpus (the corpus from which I extracted this dfm) for sophistication scores.  I suppose there's no real way around it in that context, though, because you can't trim the corpus like you can with the dfm. Or is there a sparse option available for the sophistication package that could shrink the corpus?

**Comment by kbenoit** [comment]
You should not need a sparse option for the **sophistication** package since it operates on the (entire) source text rather than constructing a dfm. I suggest you file an issue with that repo with a very specific description of your problem, and we will try to solve it there.
