### ISSUE TITLE
Add textstat_entropy

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda#1366]
We should add `textstat_entropy()`, which @kbenoit posted to [SO](https://stackoverflow.com/questions/48724588/term-document-entropy-calculation).

I improved it a bit to make it work with larger matrices.
```r
textstat_entropy <- function(x, base = exp(1), k = 1) {
    x <- t(t(x) / colSums(x))
    y <- x
    y@x <- log(y@x, base = base)
    k - colSums(x * y / log(ndoc(x), base = base), na.rm = TRUE)
}
```
It works with both DFM and FCM.

**Comment by kbenoit** [comment]
Agreed, this would be a good addition. 

```r
textstat_entropy(x, selection = NULL, margin = c("documents", "features"),
    method = c("ml", "mm", "jeffreys", "laplace", "sg","minimax", "cs", "nsb", "shrink"), 
    unit = c("nat", "log", "log2", "log10"))
```
Similar to 
https://cran.r-project.org/web/packages/entropy/entropy.pdf but implemented for sparse dfm and fcm objects.

**Comment by jiongweilua** [comment]
Does this functionality still need to be built? If so, I can work on this after I'm done with `textstat_lexdiv`.

**Comment by kbenoit** [comment]
@jiongweilua feel free to take on this one. The key is the sparsity. @koheiw's solution is the right track (but has an error in the computation). Also the method of using `dfm_weight(x, scheme = "prop")` to get P(x) is more efficient than dividing by `colSums()` because it's entirely sparse.

Here's some code that uses that with a more efficient computation of P(x) but a less efficient application of the formula:

``` r
library("quanteda")
x <- dfm(c(
  d1 = "a a a b c d e f f",
  d2 = "b b b c c d e f",
  d3 = "a a d d d f"
))
x
## Document-feature matrix of: 3 documents, 6 features (22.2% sparse).
## 3 x 6 sparse Matrix of class "dfm"
##     features
## docs a b c d e f
##   d1 3 1 1 1 1 2
##   d2 0 3 2 1 1 1
##   d3 2 0 0 3 0 1

ent <- function(x, base = 2) {
  # get relative weights across documents of each feature
  x <- t(x) %>%
    dfm_weight(scheme = "prop")
  apply(x, 1, function(y) {
    # remove zeros
    y <- subset(y, y != 0)
    # entropy formula
    -1 * sum(y * log(y, base = base))
  })
}

ent(x)
##         a         b         c         d         e         f 
## 0.9709506 0.8112781 0.9182958 1.3709506 1.0000000 1.5000000
apply(x, 2, entropy::entropy, unit = "log2")
##         a         b         c         d         e         f 
## 0.9709506 0.8112781 0.9182958 1.3709506 1.0000000 1.5000000


textstat_entropy <- function(x, base = 2, k = 1) {
  x <- t(t(x) / colSums(x))
  y <- x
  y@x <- log(y@x, base = base)
  k - colSums(x * y / log(ndoc(x), base = base), na.rm = TRUE)
}

textstat_entropy(x)
##        a        b        c        d        e        f 
## 1.612602 1.511860 1.579380 1.864974 1.630930 1.946395
```

**Comment by kbenoit** [comment]
A substantive question is what this means, for either a documents or features margin. For features, it's a measure of how diverse a feature is across documents. For documents, ... ? anyone?

@conjugateprior ?

**Comment by koheiw** [comment]
I think we only need `textstat_entropy.fcm()` and `textstat_entropy.dfm()` on features. 

Computing document entropy only makes sense when it is applied to chunks of documents taken from a corpus (eg by `tokens_chunk()`. Here high document entropy means heterogeneity/inconsistency of content within a corpus.

**Comment by koheiw** [comment]
document entropy looks like a kind of lexical diversity measure similar to R or CTTR.
```r
require(quanteda)
textstat_entropy <- function(x, base = 2, k = 1) {
    x <- t(t(x) / colSums(x))
    y <- x
    y@x <- log(y@x, base = base)
    k - colSums(x * y / log(ndoc(x), base = base), na.rm = TRUE)
}

lex <- textstat_lexdiv(mt)
mt <- dfm(data_corpus_inaugural)
lex$ent <- textstat_entropy(t(mt))
cor(lex[,-1])[,"ent",drop = FALSE]
```
```
               ent
TTR   -0.811005773
C     -0.615149176
R      0.938249108
CTTR   0.938249108
U      0.144493601
S     -0.015507404
K     -0.370818573
D     -0.153011328
Vm     0.002671163
Maas  -0.151276802
lgV0   0.774168426
lgeV0  0.774168426
ent    1.000000000
```

**Comment by kbenoit** [comment]
I think that's right, although **document-level** entropy is not a very widely used measure of lexical diversity. But there is some work on this, e.g. this paper comparing entropy to Shannon's D: 
https://link.springer.com/article/10.1007/BF02404461

Beyond that it might be interesting to have the functionality to use this on a `dfm_select()`ed matrix to judge specific feature entropies, say the mentions of proper nouns (country names, etc).

For **features**, entropy is sometimes used for stopword detection, e.g. http://www.cs.cityu.edu.hk/~lwang/research/hangzhou06.pdf.

**Comment by koheiw** [comment]
We also want `textstat_entropy.fcm()`.

**Comment by koheiw** [comment]
Here is the correct version:
```r
mt <- dfm(c(d1 = "a a a b c d e f f",
            d2 = "b b b c c d e f",
            d3 = "a a d d d f"))

textstat_entropy <- function(x, base = 2) {
    x <- t(dfm_weight(t(x), "prop"))
    x <- as(x, "dgTMatrix")
    result <- unlist(lapply(split(x@x, x@j),
                            function(y) sum(y * log(y, base)) * -1), use.names = FALSE)
    names(result) <- colnames(x)
    return(result)
}

textstat_entropy(mt)
#         a         b         c         d         e         f 
# 0.9709506 0.8112781 0.9182958 1.3709506 1.0000000 1.5000000 

apply(mt, 2, entropy::entropy, unit = "log2")
#         a         b         c         d         e         f 
# 0.9709506 0.8112781 0.9182958 1.3709506 1.0000000 1.5000000 

```

**Comment by kbenoit** [comment]
Looks good. Should we add a `margin = c("features", "documents")` argument? For the above function we just transpose `x` inside the function scope if `margin == "documents"`.

**Comment by koheiw** [comment]
OK, that is easy, but it shouldn't it be `margin = c("documents", "features")` to make it consistent with other functions?

**Comment by kbenoit** [comment]
I thought of that too. The feature entropy use case is probably more common, but you're right, let's opt for consistency with the dist and simil arguments.

**Comment by jiongweilua** [comment]
Is there a need for us to support entropy estimators other than the maximum likelihood estimator?

When I was working on this issue previously, I simply assumed we needed to support all the other estimators as in the `entropy` package (below). But on second thought I think the need for other estimators will only arise in very specialised use cases, and maybe there's no need to incorporate this into the quanteda package.

```r
entropy(y, lambda.freqs, method=c("ML", "MM", "Jeffreys", "Laplace", "SG",
"minimax", "CS", "NSB", "shrink"), unit=c("log", "log2", "log10"), verbose=TRUE, ...)
```

**Comment by kbenoit** [comment]
My thinking is probably not at this stage. if there is demand we could add it later.
