### ISSUE TITLE
Wordfish: NaN theta & se 

### ISSUE THREAD

**Issue by chuddl** [quanteda/quanteda#1369]
I am using the [ConVote ](http://www.cs.cornell.edu/home/llee/data/convote.html) dataset and when trying to calculate a Wordfish model, I receive NaNs for both the theta and se values for all cases. Here is my code:

speech_data <- readtext(paste0(data_dir, "/*.txt"),
                    docvarsfrom = "filenames", 
                    docvarnames = c("Bill", "Speaker", "Record", "PartyReferenceVote"),
                    dvsep = "_", 
                    encoding = "ISO-8859-1")
speech_corpus <- corpus(speech_data)
speech_dfm <- dfm(speech_corpus, remove_punct = TRUE, tolower = TRUE,
                  stem = TRUE, remove = stopwords("english"))
wf <- textmodel_wordfish(speech_dfm, dir = c(6,5))

I played around with the setting of the global identification a bit, however, the issue still remains. Perhaps this is where the problem lies?

![screenshot_wf1](https://user-images.githubusercontent.com/39518827/40585057-310974f4-61ac-11e8-99bb-1d4862ada561.PNG)
![screenshot_wf2](https://user-images.githubusercontent.com/39518827/40585293-478ba02c-61b0-11e8-9180-c35ad1a5d199.PNG)

Many thanks for your help!

**Comment by kbenoit** [comment]
Can you save 

```r
save(speech_dfm, file = "speech_dfm.rda")
```  
and send us a link to the file so we can try to reproduce the error?

**Comment by chuddl** [comment]
Thanks for the quick response!

The file should be available here: 

[RDA - Tinyupload](http://s000.tinyupload.com/?file_id=04096235838889844721)
