### ISSUE TITLE
Nested (overlapped) elements to tokens_lookup()

### ISSUE THREAD

**Issue by R01010010R** [quanteda/quanteda#1375]
tokens_lookup() returns more than value if a dictionary has overlapping elements (see https://github.com/koheiw/newsmap/issues/13#issuecomment-393322971).

There is a workaround which works.
1. Use `tokens_lookup` with the option `valuetype = 'glob'`.
2. Check if the tokens also return at least one of the values when I use `tokens_lookup` with the option `valuetype = 'fixed'`. And then drop the other values from (1).

However, an option such as the one @koheiw suggested might be more efficient and easier to implement.

**Comment by plugrafico** [comment]
Can dictionaries by assembled so that categories follow logical commands to ignore hits by neighboring categories?
For instance (just exemplifying, not really sure how the logical expressions should look like):
```
dict <- dictionary(list(
guinea_bissau="guinea bissau", 
equatorial_guinea="equatorial guinea",
guinea="guinea(NOT 'guinea_bissau' NOT 'equatorial_guinea')")

**Comment by kbenoit** [comment]
Really should be a SO question, but anyway:

The easiest way would be to compound the tokens you want treated as single items. You can also look up sequences and match them using dictionaries.

``` r
library("quanteda")
## Package version: 1.4.3

txt <- c("I spent one guinea while visiting Equatorial Guinea and then went to Guinea Bissau")
toks <- tokens(txt)

# method 1: compound the tokens first
tokens_compound(toks, phrase(c("equatorial guinea", "guinea bissau")))
## tokens from 1 document.
## text1 :
##  [1] "I"                 "spent"             "one"              
##  [4] "guinea"            "while"             "visiting"         
##  [7] "Equatorial_Guinea" "and"               "then"             
## [10] "went"              "to"                "Guinea_Bissau"

# method 2: define just the compound word dictionaries
dict <- dictionary(list(
  Equatorial_Guinea = "equatorial guinea",
  Guinea_Bissau = "guinea bissau"
))
tokens_lookup(toks, dict, exclusive = FALSE)
## tokens from 1 document.
## text1 :
##  [1] "I"                 "spent"             "one"              
##  [4] "guinea"            "while"             "visiting"         
##  [7] "EQUATORIAL_GUINEA" "and"               "then"             
## [10] "went"              "to"                "GUINEA_BISSAU"
```

Set `capkeys = FALSE` to turn off the capitalization.

**Comment by plugrafico** [comment]
Thanks for clearing that, @kbenoit
