### ISSUE TITLE
Unused arguments min_termfreq and max_termfreq in dim_trim()

### ISSUE THREAD

**Issue by contefranz** [quanteda/quanteda#1378]
I am running into a potential bug in `dfm_trim()`. Here is a reproducible example taken from the documentation:

    mydfm <- dfm(data_corpus_inaugural[1:5])
    ## Document-feature matrix of: 5 documents, 1,948 features (69.5% sparse).

    dfm_trim(mydfm, min_termfreq = 10, min_docfreq = 2)
    ## Error in dfm_trim(mydfm, min_termfreq = 10, min_docfreq = 2) : 
             unused argument (min_termfreq = 10)
    dfm_trim(mydfm, max_termfreq = 10, min_docfreq = 2)
    ## Error in dfm_trim(mydfm, min_termfreq = 10, min_docfreq = 2) : 
             unused argument (min_termfreq = 10)
    dfm_trim(mydfm, min_docfreq = 2)
    ## Document-feature matrix of: 5 documents, 569 features (44.2% sparse).

Am I missing something?

**Comment by stefan-mueller** [comment]
Are you using the latest **quanteda** version? It works fine with v.1.3.0.

```r
library(quanteda)
packageVersion("quanteda")
#> [1] '1.3.0'

mydfm <- dfm(data_corpus_inaugural[1:5])

dfm_trim(mydfm, min_termfreq = 10, min_docfreq = 2)
#> Document-feature matrix of: 5 documents, 107 features (16.3% sparse).

dfm_trim(mydfm, max_termfreq = 10, min_docfreq = 2)
#> Document-feature matrix of: 5 documents, 476 features (50% sparse).

dfm_trim(mydfm, min_docfreq = 2)
#> Document-feature matrix of: 5 documents, 569 features (44.2% sparse).
```

**Comment by contefranz** [comment]
I then updated the package and the problem seems gone. 
Thank you
