### ISSUE TITLE
package install failing on RHEL7 R 3.4.1 

### ISSUE THREAD

**Issue by tk80332** [quanteda/quanteda#1400]
## Consider StackOverflow

If you have a question on how to use **quanteda**, please first search [our StackOverflow channel](https://stackoverflow.com/questions/tagged/quanteda). If it does not solve you problem, please post your question there. We monitor the channel and should respond to your question very quickly. 

## Report a bug

If you know how to use **quanteda** but not seeing what you expect, please check [existing issues](https://github.com/quanteda/quanteda/issues?utf8=%E2%9C%93&q=is%3Aissue). If it does not help, please [open an issue](https://github.com/quanteda/quanteda/issues/new?template=bug_report.md).

## Other questions

Please write your questions here.

Hi,

I'm trying to install quanteda for a customer of mine but the package is failing with the following error:

```
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/tuple:94: error: cannot convert ‘std::_Head_base<1ul, long unsigned int, false>’ to ‘unsigned int’ in initialization
make: *** [ca_mt.o] Error 1
ERROR: compilation failed for package ‘quanteda’
* removing ‘/usr/lib64/R/library/quanteda’

The downloaded source packages are in
        ‘/tmp/Rtmpao856r/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("quanteda") :
  installation of package ‘quanteda’ had non-zero exit status

```

My environment is:

R version 3.4.1
RHEL7
gcc version 4.4.7 20120313 (Red Hat 4.4.7-18) (GCC)

Do you folks have any suggestions or see anything missing?  Thanks in advance!

**Comment by amatsuo** [comment]
I can't guarantee that this is the cause, but I'd update gcc. 

You are using 4.4.7 which is 6 years old.

**Comment by tk80332** [comment]
Doh, sorry should have checked that.  I have gcc 4.8.2 also installed so I switched to that and it went through no problem.  Thank you!!
