### ISSUE TITLE
Quanteda: error message while tokenizing “unable to find an inherited method for function ‘tokens’ for signature ‘”corpus“’”

### ISSUE THREAD

**Issue by valentinaIHEID** [quanteda/quanteda#1408]
I have been trying to tokenise and clean my 400 txt documents before using structured topic modelling (STM). I wanted to remove punctuations, stopwords, symbols, etc. However, I get the following error message: "Error in (function (classes, fdef, mtable): unable to find an inherited method for function ‘tokens’ for signature ‘"corpus"’". This is my original code:

`answers2 <- tokens(answers_corpus, what = c("word"), remove_numbers = TRUE, remove_punct = TRUE,
   remove_symbols = TRUE, remove_separators = TRUE,
   remove_twitter = TRUE, remove_hyphens = TRUE, remove_url = TRUE,
   ngrams = 1L, verbose = quanteda_options("verbose"), include_docvars = TRUE, text_field = "text")`

I also tried to tokenize a simple string text - just to check if it was an encoding problem while importing my txt files - but I got the same error message, plus a couple of extra ones when I tried to tokenise the the text directly, without converting it to corpus: "Error: Unable to locate Ciao bella ciao" and "Error: No language specified!". Here is my example code in case someone wants to replicate the error message:

`prova <- c("Ciao bella ciao")
prova2 <- "Ciao bella ciao"
prova_corpus <- corpus(prova)
prova2_corpus <- corpus(prova2)
prova_tok <- tokens(prova2_corpus)
prova2_tok <- tokens(prova_corpus)`

The packages that are loaded are: data.table, ggplot2, quanteda, readtext, stm, stringi, stringr, tm, textstem. Any suggestion on how I could proceed to tokenise and clean my texts?

**Comment by stefan-mueller** [comment]
The **textstem** package also has a `tokens()` function. If you load **textstem** after **quanteda**, you get the error. The safest option is to use `quanteda::tokens()` to access **quanteda**'s `tokens()` function if you have loaded both packages.

```r
library(textstem)
#> Loading required package: koRpus.lang.en
#> Loading required package: koRpus
#> Loading required package: data.table
library(quanteda)
#> Package version: 1.3.4
#> Parallel computing: 2 of 4 threads used.
#> See https://quanteda.io for tutorials and examples.
#> 
#> Attaching package: 'quanteda'
#> The following objects are masked from 'package:koRpus':
#> 
#>     tokens, types
#> The following object is masked from 'package:utils':
#> 
#>     View

prova_corpus <- corpus("Ciao bella ciao")

prova_tok <- quanteda::tokens(prova_corpus)
prova_tok
#> tokens from 1 document.
#> text1 :
#> [1] "Ciao"  "bella" "ciao"
```

**Comment by NevergiveupGJ** [comment]
Thanks so much!
