### ISSUE TITLE
dfm() crash with document > 600MB caused by stri_replace_all_fixed()

### ISSUE THREAD

**Issue by enrico200165** [quanteda/quanteda#1412]
Is there a way to avoid text copied when creating a dfm?

My code using a very large text (> 500MB) crashes with the error  

<font color="red">Error in stri_replace_all_fixed(x, c("“", "”", "<U+201F>", "‘", "<U+201B>",  : 
  A result would not fit in the supplied buffer. (U_BUFFER_OVERFLOW_ERROR)  </font>

that I GUESS is caused by dfm copying the originary text when making some replacements/removals.

I changed my code as follows trying to avoid the  problem without success

```
  # dfm_ret <- dfm(txts_par
  #   ,ngrams = n
  #   ,remove_numbers = T
  #   ,remove_punct = T
  #   ,remove_symbols = T
  #   ,remove_separators = T
  #   ,remove_twitter = T
  #   ,remove_hyphens = FALSE
  #   ,remove_url = FALSE,
  #   )

    dfm_ret <- dfm(txts_par
    ,ngrams = n
    ,remove_numbers = F
    ,remove_punct = F
    ,remove_symbols = F
    ,remove_separators = F
    ,remove_twitter = F
    ,remove_hyphens = F
    ,remove_url = F,
    )

```

Attempt to print out stack

Browse[1]> where
where 1: eval(substitute(browser(skipCalls = pos), list(pos = (length(sys.frames()) - 
    frame) + 2)), envir = sys.frame(frame))
where 2: eval(substitute(browser(skipCalls = pos), list(pos = (length(sys.frames()) - 
    frame) + 2)), envir = sys.frame(frame))
where 3: .rs.breakOnError(TRUE)
where 4: (function () 
{
    .rs.breakOnError(TRUE)
})()
where 5: stri_replace_all_fixed(x, c("“", "”", "‟", 
    "‘", "‛", "’"), c("\"", "\"", 
    "\"", "'", "'", "'"), vectorize_all = FALSE)
where 6: corpus.character(x)
where 7: corpus(x)
where 8: tokens(corpus(x), ...)
where 9: dfm.tokens(tokens(corpus(x), ...), tolower = tolower, stem = stem, 
    select = select, remove = remove, dictionary = dictionary, 
    thesaurus = thesaurus, valuetype = valuetype, groups = groups, 
    verbose = verbose)
where 10: dfm.character(txts_par, ngrams = n, remove_numbers = F, remove_punct = F, 
    remove_symbols = F, remove_separators = F, remove_twitter = F, 
    remove_hyphens = F, remove_url = F, )
where 11 at 02_pred_ngram_bare_dtf.R#61: dfm(txts_par, ngrams = n, remove_numbers = F, remove_punct = F, 
    remove_symbols = F, remove_separators = F, remove_twitter = F, 
    remove_hyphens = F, remove_url = F, )
where 12 at 02_pred_ngram_bare_dtf.R#88: build_dfm_ngrams(txts_merged, n)
where 13:

**Comment by kbenoit** [comment]
Can you include the output of `sessionInfo()`? Also we need at the very least the function call that produced the error.

Have you tried using `tokens(yourtext)` first, and see if the crash is occurring there?

**Comment by enrico200165** [comment]
Very likely that the crash was caused by stri_replace_all_fixed() along with the fact that all text (> 500MB) was in a single text vector, that stri_replace_all_fixed() tried to duplicate without finding enough contiguous memory, so if there were a problem in Quanteda that would be the call to stri_... when, at least for user code needs it seemes not be necessary (I set all flags that seemed to require replacements not to require replacement, hoping that would avoid the call to stri_replace_all_fixed, but it was called anyway).
Splitting the text (> 600MB) in 3 fixes the problem, probably by reducing the need for contiguous memory.
If there is a problem in Quanteda that would be calling stri_replace_all_fixed when not necessary for user code, but obviously it maybe necessary for internal purposes (unfortunately not time to look into packages source).

sessionInfo() output
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Italian_Italy.1252  LC_CTYPE=Italian_Italy.1252    LC_MONETARY=Italian_Italy.1252 LC_NUMERIC=C                   LC_TIME=Italian_Italy.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.1 R6_2.2.2       tools_3.5.1    yaml_2.2.0

**Comment by kbenoit** [comment]
That might well be it. How much RAM go you have?

@koheiw this is a problem that could be fixed using the tokenized corpus idea we discussed recently, where the normalization of quotes etc would have already been handled using other tools.

**Comment by enrico200165** [comment]
16GB RAM (intel I7 4 Cores 8 threads)
Same crash on both (64bits) Windows 10 and Linux  same machine in dual boot
