### ISSUE TITLE
Allow asymmetic window sizes in fcm()

### ISSUE THREAD

**Issue by enrico200165** [quanteda/quanteda#1413]
posted question [here on stackoverflow](https://stackoverflow.com/questions/51765064/quanteda-how-to-get-ngrams-and-their-frequences-given-n-1-predecessor-words-t
) without answer yet 
Is there a way to access a dfm using the n-1 precedessor types as indexes values?

[abstract pasted from link above] "For next word prediction using ngrams I would need to find all the ngrams (and their frequencies) given n-1 predecessor words.
In dfm I could not see any way to do that, so started implementing it manually on texstat_frequency (data.frame). ...
(Implicitly maybe wrongly excluding using regexes, that I normally love, becauses of prejudice that running them on hundred thousands strings might be too slow/heavy)

**Comment by koheiw** [comment]
I thought this can be done by using asymmetric `window` values in `fcm()` but it raises error:

```r
> require(quanteda)
> txt <- c("a b c", "b d e")
> fcm(tokens(txt), "window", window = c(0, 1), tri = FALSE,)
Error in try(if (window < 2) stop("The window size is too small.")) : 
  The window size is too small.
In addition: Warning message:
In if (window < 2) stop("The window size is too small.") :
  the condition has length > 1 and only the first element will be used
Error in qatd_cpp_fcm(x, length(types), count, window, weights, ordered,  : 
  Expecting a single value: [extent=2].
```

**Comment by koheiw** [comment]
Alternatively, the size of the window could be only an integer, but we could record words before/after in upper/lower triangle when a new argument `asymmetric = TRUE`.

**Comment by kbenoit** [comment]
That’s what `ordered = TRUE` already does: shows in rows a term and then in columns, the counts of the words that occur following the row word, within the (one-sided/asymmetric) window size.

**Comment by kbenoit** [comment]
Yes, that's what I found. If this did work, and we removed the`window >=2` condition, then it could easily serve as a generator for a bigram transition matrix. 

We need better substantive tests on this, clearly - should start a new issue to fix this.

**Comment by enrico200165** [comment]
I installed today 20th August from github, I am still unable to see/find the  a simple way, updated question [on SO](url
![image](https://user-images.githubusercontent.com/250743/44348556-083e8000-a49b-11e8-9144-7d5e6ae67bce.png)
) to include my unsuccessful/wrong way and a simple text to be used if you reply with some sample code to illustrate how to do it

**Comment by koheiw** [comment]
Don't you see something like this?
```r
> require(quanteda)
> require(Matrix)
> 
> packageVersion("quanteda")
[1] ‘1.3.5’
> 
> txt <- c("a b c", "b a e")
> toks <- tokens(txt)
> mt <- fcm(toks, "window", window = 1, ordered = TRUE, tri = FALSE)
> mt[lower.tri(mt)] <- 0
> mt
4 x 4 sparse Matrix of class "dgCMatrix"
        features
features a b c e
       a . 1 . 1
       b . . 1 .
       c . . . .
       e . . . .
```

**Comment by enrico200165** [comment]
I see exactly that, but that is not what I asked (or meant to ask) except when n-1 is 1.  
My question is not "given an ngram find subsequent ngrams and their frequencies (as continuations of the given ngram), my question is "given an (n-1)gram get the next words and their frequencies as successors), possibly avoiding searches that imply regex matching as I guess that they might be slow, happy to be informed/corrected on that).  
so, copying from the linked updated SO question, given the text
"a b 1 2 3 a b 2 3 4 a b 3 4 5" using   "a","b" as the given (n-1)gram  I would lik a way to get something like:
next word = "1" frequency (as successor "a","b") = 1
next word = "2" frequency (as successor "a","b") = 1
next word = "3" frequency (as successor "a","b") = 1
The goal is next word prediction. 
[Link to the SO question where I enclosed that text and code similar to yours.](https://stackoverflow.com/questions/51765064/quanteda-how-to-get-ngrams-and-their-frequences-given-n-1-predecessor-words-t)

**Comment by koheiw** [comment]
You should not run this on a large corpus, but it does the job:
```r
> require(quanteda)
> ngms <- tokens("a b 1 2 3 a b 2 3 4 a b 3 4 5", n = 2:5)
> fmt <- 
+     ngms %>%
+     as.list() %>%
+     unlist() %>% 
+     stringi::stri_replace_last_fixed("_", " ") %>% 
+     tokens() %>% 
+     fcm(ordered = TRUE)
> fmt[33:39, 1:6]
Feature co-occurrence matrix of: 7 by 6 features.
7 x 6 sparse Matrix of class "fcm"
         features
features  a b 1 2 3 4
  3_a_b_2 0 0 0 0 1 0
  a_b_2_3 0 0 0 0 0 1
  b_2_3_4 1 0 0 0 0 0
  2_3_4_a 0 1 0 0 0 0
  3_4_a_b 0 0 0 0 1 0
  4_a_b_3 0 0 0 0 0 1
  a_b_3_4 0 0 0 0 0 0
```

**Comment by enrico200165** [comment]
Thank you, very kind and very useful. I posted a simplified version of your code on SO so other people can also benefit from it
