### ISSUE TITLE
Improve handling of empty dfm

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda#1419]
`textmodel_*` crash when a DFM has no features. We should add a check and raise error like "dfm must have at least one non-zero feature" instead.
 
```r
(emptydfm <- dfm_trim(data_dfm_lbgexample, 1000))
# Document-feature matrix of: 6 documents, 0 features.
# 6 x 0 sparse Matrix of class "dfm"
#     features
# docs
#   R1
#   R2
#   R3
#   R4
#   R5
#   V1

textmodel_wordscores(emptydfm, c(seq(-1.5, 1.5, .75), NA))
# Error in as(e1, "dgCMatrix")/e2 : <Matrix> / numeric(0) is undefined 

textmodel_wordfish(emptydfm)
#  Error in qatd_cpp_wordfish_dense(as.matrix(x), as.integer(dir), 1/(priors^2),  :   mean(): object has no elements 
```

**Comment by kbenoit** [comment]
Also:
```r
textmodel_ca(emptydfm)
# Error in fun(A, k, nu, nv, opts, mattype = "dgeMatrix") : 
#  nrow(A) and ncol(A) should be at least 3 

textmodel_lsa(emptydfm)
# Error in fun(A, k, nu, nv, opts, mattype = "dgCMatrix") : 
#     nrow(A) and ncol(A) should be at least 3 
```

But:
```r
textmodel_affinity(emptydfm, y = c(-1, NA, NA, NA, 1, NA))
# Call:
# textmodel_affinity.dfm(x = emptydfm, y = c(-1, NA, NA, NA, 1, 
#     NA))
# 
# Training documents per class:-1: 1, 1: 1; total training features: 0
```

**Comment by koheiw** [comment]
Make sure that we have tests for 
- [ ] `dfm_group()`
- [ ] `dfm_lookup()`
- [ ] `dfm_replace()`
- [ ] `dfm_sample()`
- [ ] `dfm_select()`
- [ ] `dfm_smooth()`
- [ ] `dfm_sort()`
- [ ] `dfm_subset()`
- [ ] `dfm_tfidf()`
- [ ] `dfm_tolower()`
- [ ] `dfm_toupper()`
- [ ] `dfm_trim()`
- [ ] `dfm_weight()`
- [ ] `dfm_wordstem()`
- [ ] `dfm()`
- [ ] `textmodel_affinity()`
- [ ] `textmodel_ca()`
- [ ] `textmodel_lsa()`
- [ ] `textmodel_nb()`
- [ ] `textmodel_wordfish()`
- [ ] `textmodel_wordscores()`
- [ ] `textplot_network()`
- [ ] `textplot_wordcloud()`
- [ ] `textstat_dist()`
- [ ] `textstat_frequency()`
- [ ] `textstat_keyness()`
- [ ] `textstat_lexdiv()`
- [ ] `textstat_simil()`
- [ ] `topfeatures()`
