### ISSUE TITLE
Remove row.names from docvars

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda#1422]
It can be done easily by 
```r
result@docvars <- data.frame(matrix(ncol = 0, nrow = ndoc(x)))
```
instead of current
```r
result@docvars <- data.frame(row.names = docnames(x)) 
```
I partially started this in #1421

**Comment by koheiw** [comment]
I started working on this, and thought that it is time to upgrade the Corpus object. I propose four changes:

1. Remove `corpuszip` and its methods
2. Remove `metacorp` and its methods
3. Add `_document`, `_docid` and `_segid` as compulsory internal document variable
4. Stop using `rownames` of `docvars`

Very few people use 1 and 2, so impact is minimal. Users should not notice 3 and 4. We will ensure backward compatibility using `as.corpus()` (like `as.dfm()`).

**Comment by koheiw** [comment]
I was intending only to change the 4, which involves 3. Without 1 and 2, amount of work will be much more. I don't think we will introduce more advanced corpus structures soon, but we need to solve the mess in corpus objects and docvars to prepare for future upgrade (e.g. internal document variable will be the primary keys in an off-memory corpus object).

**Comment by koheiw** [comment]
My suggested structure of the objects will have no document name at all but dovars has _docname. Subsetting methods for coprus, tokens or DFM objects translate document names (character vectors) to keys (integer vector) looking up `_docname` in docvars.

![new quanteda objects](https://user-images.githubusercontent.com/6572963/46457806-98881880-c7ee-11e8-90d0-3c61fb3dd6af.png)

By the way, I created this diagram using https://www.draw.io. The file is in QI Google Drive.

**Comment by kbenoit** [comment]
This is the right track but 

1.  It only makes sense to redesign the corpus object with the docvars table staying document-level, but possibly the texts being sub-document level (as with `corpus_reshape(x, to = "sentences"). See https://github.com/quanteda/quanteda/wiki/Proposal-for-changing-docvars for my updated, detailed thoughts on the redesign of the corpus object.

2. Docvars for tokens and dfm objects should always correspond 1:1 to the document as defined by an element of the top-level tokens list object or a row of the dfm. List elements for tokens should retain the docname as the document identifier, and the dfm should continue to use docnames as row.names.  For the attached docvars, we can move the docnames from row.names of that data.frame to _docname, but we don't want to change the definition of token or dfm objects beyond that. This is similar to what we have already done with the output of `textstat_*()` functions.

3. I am not sure what the `some-external-data` is or where it fits into the scheme for the docvars object.

**Comment by koheiw** [comment]
How do document variables relate to tokens and dfm objects?

**Comment by koheiw** [comment]
I am thinking of overhauling docvars with some possibility for extension... Since our ideas are too different, it is better not touching on this now. We can discuss this in-person at a point next year.

**Comment by kbenoit** [comment]
Why not edit or comment on the RFC for the corpus redesign about your idea? So far I don't see the details on how the extension would work.

This issue is still a good one, to remove row.names from docvars, and it's something we would need to do anyway as a precursor to any move to data.table or a more relational structure, since it's really only data.frames that allow row.names (among non-matrix but rectangular data objects).

**Comment by koheiw** [comment]
Saving the document names in a column instead of row.names is the main purpose of the new design. Extension (relational structure, pos etc.) of corpus object is an entirely different thing that should be considered separately.

**Comment by koheiw** [comment]
`row.names` will be save in an internal-only column `_docname`. Users can access the column only via `docnames()` or `[]`, but there should be no change in behavior.

When if users try to extract documents:

1. in accessor functions, document names are match against the `_docname` column using `match()` (or `fmatch()`).
2. using the numeric indices from `match()`, underlying objects `character`, `list`, `Matrix` as well as the data.frame itself will be subset.

This design allows

1. existence of duplicated document names in all the three quanteda objects
2. fully consistent structure and handling of docvars (just pass the data.frame to the downstream object).
3. (potentially) glob or regex pattern matching on document names

**Comment by kbenoit** [comment]
Sounds good, but why would we not want `_docname` to be to unique?

**Comment by koheiw** [comment]
There is a prototype
```
> corp <- corpus2(data_char_ukimmig2010)
> corp[c("BNP", "Conservative", "PC")]
[1] "IMMIGRATION: AN UNPARALLELED CRISIS WHICH ONLY THE BNP CAN SOLVE. \n\n- At current immigration and bir"
[2] "Attract the brightest and best to our country.\n\nImmigration has enriched our nation over the years a"
[3] "As a welcoming nation, Plaid Cymru recognises the invaluable contribution that migrants have made to"  
$class
[1] "corpus2"

$docvars
      _docname _docid _segid
1          BNP      1      1
3 Conservative      3      1
7           PC      7      1

$created
[1] "Wed Oct 10 17:49:37 2018"

$source
                      directory                         machine                            user 
"/home/kohei/packages/quanteda"                        "x86_64"                         "kohei" 
```
I am not sure what the best way to deal with corpus meta data such as `created` and `source`, but the code is much clearer in this structure.

**Comment by koheiw** [comment]
I put all the meta data into one a list. `_docid` is unique but `_docmane` is original name, which has duplicates when `corpus_reshape()` is applied.
```
> corpus_subset(as.corpus2(data_corpus_inaugural), Year > 2000)
[1] "President Clinton, distinguished guests and my fellow citizens, the peaceful transfer of authority i"  
[2] "Vice President Cheney, Mr. Chief Justice, President Carter, President Bush, President Clinton, Membe"  
[3] "My fellow citizens:\n\nI stand here today humbled by the task before us, grateful for the trust you ha"
[4] "Vice President Biden, Mr. Chief Justice, Members of the United States Congress, distinguished guests"  
[5] "Chief Justice Roberts, President Carter, President Clinton, President Bush, President Obama, fellow "  
$class
[1] "corpus2"

$docvars
       _docid   _docname _docnum _segnum Year President FirstName
54  2001-Bush  2001-Bush      54       1 2001      Bush George W.
55  2005-Bush  2005-Bush      55       1 2005      Bush George W.
56 2009-Obama 2009-Obama      56       1 2009     Obama    Barack
57 2013-Obama 2013-Obama      57       1 2013     Obama    Barack
58 2017-Trump 2017-Trump      58       1 2017     Trump Donald J.

$meta
$meta$source
[1] "character"

$meta$`package-version`
[1] ‘1.3.10’

$meta$`r-version`
[1] ‘3.4.4’

$meta$system
 sysname  machine     user 
 "Linux" "x86_64"  "kohei" 

$meta$directory
[1] "/home/kohei/packages/quanteda"

$meta$created
[1] "2017-06-13 14:51:47 JST"
```

**Comment by kbenoit** [comment]
Looks good, and looks a lot like the scheme in the wiki. I like the approach to make everything work as it is already.

How about we keep the name "corpus" for this new class, and have each corpus method  check the object structure for the "old corpus" and then coerce it to the new one, much as we did when we transitioned dfm by adding more attributes. This gives us the option to keep modifying the corpus and have older versions automatically updated.

**Comment by koheiw** [comment]
I am still thinking if we should class it `corpus` or `corpus2`. The same technique as `as.dfm()` should work, but there will be a problem if someone try to apply functions in older **quanteda**  on a new corpus object. If classed differently, he or she will only see a friendly error that there is not method for `corpus2`.

**Comment by kbenoit** [comment]
Good point. But I like the idea that we could have a way to keep modifying corpus that would automatically update the objects (as with dim). Since the real changeover is the point at which we add this function, it’s just this change that matters. Maybe if we increment the minor version (to 1.4 for instance) and put up a News post, anyone googling the error would qauickly arrive to that solution, which would be: update to v1.4.

**Comment by koheiw** [comment]
That is a great way to promote the blog. The error that user will see is
```
Error in x$documents : $ operator is invalid for atomic vectors 
```
I am ok to use `corpus` for the new object.

**Comment by kbenoit** [comment]
That plus:
a) We recruit a user to post a SO question on this
b) you answer it and link to the blog
😄
