### ISSUE TITLE
Errors for examples on pkgdown website

### ISSUE THREAD

**Issue by stefan-mueller** [quanteda/quanteda#1428]
Currently, almost all examples in the reference sections on the quanteda [pkgdown website](http://docs.quanteda.io/index.html) raise the following error: `Error in .setupMethodsTables(fdef): trying to get slot "group" from an object of a basic class ("NULL") with no slots`.

**Comment by kbenoit** [comment]
@stefan-mueller I am not seeing that, can you point to a specific page where this is happening?

**Comment by stefan-mueller** [comment]
Of course. The errors appear, amongst others, in the "Examples" sections of [`textmodel_wordfish()`](http://docs.quanteda.io/reference/textmodel_wordfish.html ), [`textmodel_nb()`](http://docs.quanteda.io/reference/textmodel_nb.html), and [`textplot_wordcloud()`](http://docs.quanteda.io/reference/textplot_wordcloud.html).

**Comment by kbenoit** [comment]
I see this in the console too:

```r
(ws <- textmodel_wordscores(data_dfm_lbgexample, c(seq(-1.5, 1.5, .75), NA)))
 Error in .setupMethodsTables(fdef) : 
  trying to get slot "group" from an object of a basic class ("NULL") with no slots 
```

When did this happen?
