### ISSUE TITLE
linker error when installing from source

### ISSUE THREAD

**Issue by syd-doyen** [quanteda/quanteda#1438]
## Describe the bug

When I  "R CMD INSTALL quanteda", it compiles all the src files but when it links, I get the
following string inserted into the command "profile: Setting repository" . Not sure
how that string was added to the command, either through some flag or pkg-config
call. The problem is I can't just remove the string and I run the command. 

You can see the command and error below:

icpc -shared -L/usr/local/R/3.4.0-intel/lib64/R/lib -shared -L/usr/local/R/3.4.0-intel/lib64/R/lib -L/usr/local/proj/4.9.3/lib -L/usr/local/mpc/1.0.3/lib -L/usr/local/mpfr/3.1.4/lib -L/usr/local/gmp/5.1.3/lib -L/usr/local/R/3.4.0-intel/lib -L/usr/local/nlopt/2.4.2/lib -L/usr/local/libtiff/4.0.3/lib -L/usr/local/readline/6.3/lib -L/usr/local/zlib/1.2.8/lib -L/usr/local/bzip2/1.0.6/lib -L/usr/local/libxml2/2.9.2/lib -L/usr/local/openssl/1.0.1s/lib -L/usr/local/libcurl/7.40.0/lib -L/usr/local/pcre/8.39/lib -L/usr/local/openmpi/1.10.3-intel/lib -L/usr/local/xz/5.2.2/lib -L/usr/local/netcdf/4.4.0/lib -o quanteda.so RcppExports.o ca_mt.o collocations_mt_.o dist_mt.o fcm_mt.o kwic_mt.o tokens_compound_mt.o tokens_lookup_mt.o tokens_ngrams_mt.o tokens_recompile_mt.o tokens_segment_mt.o tokens_select_mt.o utility.o wordcloud.o wordfish_dense.o wordfish_mt.o -L/usr/local/R/3.4.0-intel/lib64/R/lib -lRlapack -L/usr/local/R/3.4.0-intel/lib64/R/lib -lRblas -liomp5 -lpthread -lifport -lifcore -limf -lsvml -lm -lipgo -lirc -lirc_s -ldl profile: Setting repository -L/usr/local/R/3.4.0-intel/lib64/R/lib -lR
icpc: error #10236: File not found:  'profile:'
icpc: error #10236: File not found:  'Setting'
icpc: error #10236: File not found:  'repository'
make: *** [quanteda.so] Error 1 

I got the same error with the latest from the repo or the version that is in CRAN.

I do not enough about creating packages in R to know where the rules are being
defined for the linker and compile. 

I'm using an intel compiler
icpc (ICC) 15.0.1 20141023
Copyright (C) 1985-2014 Intel Corporation.  All rights reserved.

and the

> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS release 6.9 (Final)

Matrix products: default
BLAS: /usr/local/R/3.4.0-intel/lib64/R/lib/libRblas.so
LAPACK: /usr/local/R/3.4.0-intel/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_3.4.0

Thanks for any info on how to get around the problem or fix the problem. 
Aldo

**Comment by koheiw** [comment]
We are testing our package with gcc (Linux) and clang (Mac) but not icpc. Please try gcc if you are using CentOS.
