### ISSUE TITLE
What is correct computation of "chi-squared distance"?

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#1444]
Picks up the thread from #1442.

Not sure why the Greenacre pdf has a different value, but it does.
```r
mt <- dfm(c("a a b c", "a b b d", "b d d e e", "e e e"))
mtprof <- dfm_weight(mt, "prop")
avgp <- colMeans(mtprof)

# canned methods
#
textstat_dist(mt, method = "chisquared")
##          text1    text2    text3
## text2 1.916667                  
## text3 3.708667 1.325333         
## text4 5.783333 4.866667 2.165333
as.dist(ExPosition::chi2Dist(as.matrix(mt))$D)
##          text1    text2    text3
## text2 1.916667                  
## text3 3.708667 1.325333         
## text4 5.783333 4.866667 2.165333

# based on http://www.econ.upf.edu/~michael/stanford/maeb4.pdf Eq 4.8
#
# difference between text1 and text2
sqrt(sum((mtprof[1, ] - mtprof[2, ])^2 / avgp))
## [1] 1.407518
# difference between text1 and text3
sqrt(sum((mtprof[1, ] - mtprof[3, ])^2 / avgp))
## [1] 1.945666
# difference between text1 and text4
sqrt(sum((mtprof[1, ] - mtprof[4, ])^2 / avgp))
## [1] 2.335302
```

**Comment by koheiw** [comment]
I emailed the developers of **ExPosition** on Friday asking where their formula came from, but haven't heard from them. If they do not respond, we should temporarily remove that measure.

**Comment by kbenoit** [comment]
Last update was 2013 and the code repo is Google, now frozen, so I am not 🤞 optimistic.

**Comment by kbenoit** [comment]
Probably better to remove it as a measure of distance, and but add `"chisquared"` to `scheme` in  `dfm_weight()`, as we discussed in https://github.com/quanteda/quanteda/issues/1442#issuecomment-426860065.

**Comment by koheiw** [comment]
I like this approach, but what would be the fomula? Deviation from the expect?

**Comment by kbenoit** [comment]
The idea for dfm_weight would be the "remove the chi2 residuals step" done before sending a dfm to SVD for correspondence analysis - or for getting your weights and then sending to the distance measure, since chi2 distance is supposed to be the Euclidean distance of that weighted matrix.

I just found https://www.umass.edu/landeco/teaching/multivariate/readings/McCune.and.Grace.2002.chapter6.pdf, where at the top of its 6th page is a different formula from my reading of Eq 4.8 from chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/http://www.econ.upf.edu/~michael/stanford/maeb4.pdf, where it looks like x_i and y_i are counts and not proportions. In the McCune and Grace text it's clear they are proportions ("column profiles" and "row profiles").

**Comment by koheiw** [comment]
This might be one of the original papers on Chi-square distance https://www.sciencedirect.com/science/article/pii/0302352476900414
According Chardy, the distance between document 1 and 2 is
```r
require(quanteda)
x <- dfm(c("a a b c", "a b b d", "b d d e e", "e e e"))
sum((1 / colSums(x)) * ((x[1,] / sum(x[1,]) - x[2,] / sum(x[2,])) ^ 2))
# [1] 0.1197917
```
