### ISSUE TITLE
tokens(x, remove_punct) too aggressive?

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#1445]
The `remove_punct = TRUE` option seems to remove more than just punctuation characters, as defined in the "P" categories of http://www.fileformat.info/info/unicode/category/index.htm.

```r
> tokens("Today: €5 beers! ±0.50", remove_punct = TRUE)
tokens from 1 document.
text1 :
[1] "Today" "5"     "beers" "0.50" 

> stringi::stri_detect_charclass(c(":", "€", "±", "!"), "\\p{P}")
[1]  TRUE FALSE FALSE  TRUE

> spacy_parse("Today: €5 beers! ±0.50", remove_punct = TRUE)
  doc_id sentence_id token_id token lemma   pos  entity
1  text1           1        1 Today today  NOUN        
2  text1           1        2     :     : PUNCT        
3  text1           1        3     €     €   SYM        
4  text1           1        4     5     5   NUM MONEY_B
5  text1           1        5 beers  beer  NOUN        
6  text1           1        6     !     ! PUNCT        
7  text1           1        7 ±0.50 ±0.50   ADJ 
```

**Comment by koheiw** [comment]
Here is why it removes more than `\p{P}`:
https://github.com/quanteda/quanteda/blob/bedca07dde76c84fc41a97fbe3fe08007887b933/R/tokens.R#L632-L633

I want `tokens()` to remove currency marks etc. by default, so we can change that to as below and set `remove_symbols = TRUE` by default to keep current behavior.
```
if (remove_punct)
    regex <- c(regex, "^[\\p{P}]+$")
if (remove_symbols)
    regex <- c(regex, "^[\\p{S}]+$")
```

**Comment by kbenoit** [comment]
Actually matching the current behaviour if we restrict punctuation to punctuation, would be
```r
tokens(x, ..., remove_punct = FALSE, remove_symbols = remove_punct, ...)
```
That would preserve the current behaviour of 
```r
> tokens("The movie cost $15.", remove_symbols = TRUE)
tokens from 1 document.
text1 :
[1] "The"   "movie" "cost"  "15"    "."
```

**Comment by kbenoit** [comment]
The second test currently fails - but if we change https://github.com/quanteda/quanteda/blob/bedca07dde76c84fc41a97fbe3fe08007887b933/R/tokens.R#L633 to remove only `\p{P}` then and change the defaults to `remove_punct = FALSE, remove_symbols = remove_punct` then it will pass.

```r
test_that("tokens remove_punct and remove_symbols work as expected", {
    txt <- c(doc = "I bet ± £100!")

    expect_identical(
        as.character(tokens(txt, remove_punct = FALSE, remove_symbols = FALSE)),
        c("I", "bet", "±", "£", "100", "!")
    )
    
    expect_identical(
        as.character(tokens(txt, remove_punct = TRUE, remove_symbols = FALSE)),
        c("I", "bet", "±", "£", "100")
    )
    
    expect_identical(
        as.character(tokens(txt, remove_punct = FALSE, remove_symbols = TRUE)),
        c("I", "bet", "100", "!")
    )
    
    expect_identical(
        as.character(tokens(txt, remove_punct = TRUE, remove_symbols = TRUE)),
        c("I", "bet", "100")
    )
  
    # test defaults
    expect_identical(
        as.character(tokens(txt)),
        c("I", "bet", "±", "£", "100", "!")
    )
    expect_identical(
        as.character(tokens(txt, remove_punct = TRUE)),
        c("I", "bet", "100")
    )
    expect_identical(
        as.character(tokens(txt, remove_symbols = TRUE)),
        c("I", "bet", "100", "!")
    )
})
```

**Comment by koheiw** [comment]
I don't this we should use a variable default value (i.e. `remove_symbols = remove_punct`) unless there is a reason other than mimicking existing (wrong) behavior. If we have many functions like this, their behavior will be unpredictable. If this is only transitional (raise warnings), it is OK, however.

**Comment by kbenoit** [comment]
I don't think it's wrong behaviour to separate punctuation and symbols, as we adhere pretty well to the Unicode category definitions elsewhere. The mixing of punctuation of symbols originally was incorrect. 

I agree on not wanting to set arguments with the values of other arguments generally, but this fix ensures continuity with existing behaviour and for those who want it, means they can remove symbols when they remove punctuation but also have the option of preserving symbols. I can see many reasons for preserving symbols, to keep currency values for instance.

**Comment by koheiw** [comment]
This is too bad
https://github.com/quanteda/quanteda/blob/0dc5b345b4370ca8bc90c8cd0ecd6e4eb687e995/R/tokens.R#L221-L225

Substitution by `tokens_lookup` should be better than re-tokenizing entire corpus.
```r
require(quanteda)
require(stringi)
toks <- tokens("a b c-d e e-f-g")

dict <- dictionary(list("c" = "c-d", "d" = "c-d", "e" = "e-f-g", "f" = "e-f-g", "g" = "e-f-g"))
tokens_lookup(toks, dict, exclusive = FALSE, capkeys = FALSE)
# tokens from 1 document.
# text1 :
# [1] "a" "b" "c" "d" "e" "e" "f" "g"

type <- types(toks)
type <- type[stri_detect_fixed(type, "-")]
key <- stri_split_fixed(type, "-")
value <- as.list(rep(type, lengths(key)))
names(value) <- unlist(key)

tokens_lookup(toks, dictionary(value), exclusive = FALSE, capkeys = FALSE)
# tokens from 1 document.
# text1 :
# [1] "a" "b" "c" "d" "e" "e" "f" "g"
```
More broadly, this a question of how to replace single tokens by multiple tokens. Extending `tokens_replace()` would be away.

**Comment by kbenoit** [comment]
See #1500.  (1500 issues already, damn!) I totally agree with the above comment (although unsure how it relates to this issue...).

**Comment by kbenoit** [comment]
Here's another reason to separate punctuation removal and symbol removal: emoji are considered symbols.

We don't want to kill emoji when `remove_punct = TRUE`.

``` r
library("quanteda")
## Package version: 1.4.3
## Parallel computing: 2 of 12 threads used.
## See https://quanteda.io for tutorials and examples.
## 
## Attaching package: 'quanteda'
## The following object is masked from 'package:utils':
## 
##     View

txt <- "👏 Rock on❗ 💪️🎸"
tokens(txt) %>%
  as.character() %>%
  cat()
## 👏 Rock on ❗ 💪 🎸
tokens(txt, remove_punct = FALSE, remove_symbols = TRUE) %>%
  as.character() %>%
  cat()
## Rock on
tokens(txt, remove_punct = TRUE, remove_symbols = FALSE) %>%
  as.character() %>%
  cat()
## Rock on

# emoji are included in Symbol, other
tokens(txt) %>%
  tokens_select("\\p{So}", valuetype = "regex") %>%
  as.character() %>%
  cat()
## 👏 ❗ 💪 🎸
```
