### ISSUE TITLE
how to merge the dtm back to the dataframe?

### ISSUE THREAD

**Issue by randomgambit** [quanteda/quanteda#1452]
Hello there!
Again, thanks for this wonderful package

Consider this simple example:

```
library(quanteda)
library(dplyr)
library(microbenchmark)

dtrain <- data_frame(text = c("Chinese Beijing Chinese",
                              "Chinese Chinese Shanghai",
                              "Chinese Macao",
                              "Tokyo Japan Chinese"),
                     numeric_one = 1:4,
                     numeric_two = 3:6)
```
I can easily create the `dfm` out of the `text` column.

```
> dfm(corpus(dtrain, text_field = 'text'))
Document-feature matrix of: 4 documents, 6 features (62.5% sparse).
4 x 6 sparse Matrix of class "dfm"
       features
docs    chinese beijing shanghai macao tokyo japan
  text1       2       1        0     0     0     0
  text2       2       0        1     0     0     0
  text3       1       0        0     1     0     0
  text4       1       0        0     0     1     1
```
My question is: how can I efficiently create a `sparse` matrix that contains `numeric_one`, `numeric_two` and the columns in the `dtm` I just created?

The idea would be to combine the `dtm` created by `quanteda` with other numeric variables into a big sparse matrix that I can feed to other machine learning algos (`glmnet`, etc).

What do you think?
Thanks!

**Comment by randomgambit** [comment]
Hi @koheiw thanks! but what I meant is how can I add the two numeric columns in the original dataframe to the sparse matrix created by as(mt, "sparseMatrix")?

**Comment by kbenoit** [comment]
`cbind()` ?

**Comment by randomgambit** [comment]
yeah, that seems to work

```
mydfm <-  dfm(corpus(dtrain, text_field = 'text')) %>% as(., 'sparseMatrix')
mynumeric <- dtrain %>% select(numeric_one,numeric_two) %>% as.matrix()
cbind(mynumeric, mydfm)

```
Thanks!
