### ISSUE TITLE
quanteda install failing on Ubuntu 18.04

### ISSUE THREAD

**Issue by chuk-yong** [quanteda/quanteda#1453]
Encountered many errors when installing quanteda on my new Ubuntu machine.  Solved one relating to xml2.  Not sure how to resolve these complaints about lgfortran and RSpectra. 

`g++ -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o RSpectra.so eigs_gen.o eigs_sym.o matops.o register_routines.o svds.o -lblas -lgfortran -lm -lquadmath -L/usr/lib/R/lib -lR
/usr/bin/x86_64-linux-gnu-ld: cannot find -lgfortran
collect2: error: ld returned 1 exit status
/usr/share/R/share/make/shlib.mk:6: recipe for target 'RSpectra.so' failed
make: *** [RSpectra.so] Error 1
ERROR: compilation failed for package ‘RSpectra’
* removing ‘/home/chubuntu/R/x86_64-pc-linux-gnu-library/3.4/RSpectra’
Warning in install.packages :
  installation of package ‘RSpectra’ had non-zero exit status
ERROR: dependency ‘RSpectra’ is not available for package ‘quanteda’
* removing ‘/home/chubuntu/R/x86_64-pc-linux-gnu-library/3.4/quanteda’
Warning in install.packages :
  installation of package ‘quanteda’ had non-zero exit status`

**Comment by chuk-yong** [comment]
Thanks!  Just filed the issue with RSpectra.  Hope it would be resolve soon.

**Comment by kbenoit** [comment]
I created a 18.04 vm this weekend it installed fine for me. Closing unless @chuk-yong you report more problems.
