### ISSUE TITLE
Sparse distance matrix assignment of zeroes is misleading or wrong

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#1455]
This is a substantive issue to consider before we accept PR #1451.

The goal of using a sparse matrix format to represent distances or similarities is a good one: to avoid huge n^2 dense objects when the number of distance nodes n is large. 

The implementation via sparse matrices, however, does not make sense in many cases, since these are treated as zeroes, rather than just being ignored.

### 1. It makes no sense for metrics that are signed, such as the Pearson's correlation default for `textstat_simil()`.  Consider this example:

```r
library("quanteda")
library("Matrix")

testdfm <- as.dfm(
    matrix(c(1, 2, 0, 5, 6,
             1, 3, 2, 6, 5,
             1, 2, 0, 5, 5, 
             2, 2, 0, 5, 6,
             6, 5, 0, 2, 1),
           nrow = 5)
) %>% 
    dfm_weight("prop")

textstat_simil(testdfm, method = "correlation") %>% 
    as.matrix()
#            text1       text2       text3      text4      text5
# text1  0.0000000  0.90212515 -0.30942637 -0.9580710 -0.9231344
# text2  0.9021252  0.00000000  0.08574929 -0.8091548 -0.9616447
# text3 -0.3094264  0.08574929  0.00000000  0.5160468  0.1078328
# text4 -0.9580710 -0.80915478  0.51604685  0.0000000  0.8903482
# text5 -0.9231344 -0.96164474  0.10783277  0.8903482  0.0000000

textstat_simil(testdfm, method = "correlation", min_simil = -0.5)
# 5 x 5 sparse Matrix of class "dsCMatrix"
#            text1      text2       text3     text4     text5
# text1  1.0000000 0.90212515 -0.30942637 .         .        
# text2  0.9021252 1.00000000  0.08574929 .         .        
# text3 -0.3094264 0.08574929  1.00000000 0.5160468 0.1078328
# text4  .         .           0.51604685 1.0000000 0.8903482
# text5  .         .           0.10783277 0.8903482 1.0000000
```

Here, there are some strong negative correlations. Setting `min_simil = -0.50` means that:
- the strongest negative correlations become zero
- the strongest positive correlations remain as is
- the weakest negative and positive correlations remain as is

Setting `min_simil = 0.50` means that all except the strongest positive correlations become zero.

`method = "cosine"` can also range from [0, 1]. Although this will not happen with word counts, it could happen with other (negatively valued) data.

Note: This also affects the `rank` option: The top `rank` items will, in the above example, exclude the strongest negative correlations only.

Distance measures are always bounded at zero so this will not affect them.

### 2. It violates a basic principle of distance, by considering equidistant two items that are not the same.

```r
textstat_dist(testdfm, method = "euclidean") %>% 
    as.matrix()
#           text1     text2     text3      text4      text5
# text1 0.0000000 0.2399963 1.0833068 0.52188883 0.56489944
# text2 0.2399963 0.0000000 0.8978432 0.30304576 0.36304866
# text3 1.0833068 0.8978432 0.0000000 0.83405766 0.89315820
# text4 0.5218888 0.3030458 0.8340577 0.00000000 0.08695652
# text5 0.5648994 0.3630487 0.8931582 0.08695652 0.00000000

textstat_dist(testdfm, method = "euclidean", min_dist = 0.5) %>% 
    as.matrix()
#           text1     text2     text3     text4     text5
# text1 0.0000000 0.0000000 1.0833068 0.5218888 0.5648994
# text2 0.0000000 0.0000000 0.8978432 0.0000000 0.0000000
# text3 1.0833068 0.8978432 0.0000000 0.8340577 0.8931582
# text4 0.5218888 0.0000000 0.8340577 0.0000000 0.0000000
# text5 0.5648994 0.0000000 0.8931582 0.0000000 0.0000000
```

For distance, since it says that treating anything less distant that 0.50 will be considered as identical to the item itself, but they are not equal to or equivalent to the item itself. text1 and text1 have a zero distance, and so do text1 and text2, but that implies text1 = text2, which is false.

See the "identity of indiscernibles" property 2 of the distance at https://en.wikipedia.org/wiki/Metric_(mathematics).

### Solution

Keep the advantage of sparseness by not recording pairs below the cutoff (or rank), but do not use the sparse format that implies zeros. The solution below also means we could keep all of the internal `textstat_proxy()` code but not (ever) return sparse matrixes to the user via `textstat_dist()` or `textstat_simi()` - but we would still never need to hold the fully dense object in memory.

This format would consist of pairwise distances equivalent to a long data.frame format of the sparse triplet matrix. e.g.

```r
(tmp <- textstat_dist(testdfm, method = "euclidean", rank = 2))
# 5 x 5 sparse Matrix of class "dgCMatrix"
#           text1     text2     text3     text4     text5
# text1 .         .         1.0833068 0.5218888 0.5648994
# text2 .         .         0.8978432 .         .        
# text3 1.0833068 0.8978432 .         0.8340577 0.8931582
# text4 .         .         .         .         .        
# text5 0.5648994 0.3630487 .         .         .        

dframefmt <- function(x) {
    # hard-wired for dgCMatrix input but could be adapted of course for dsCMatrix
    x <- as(x, "dgTMatrix")
    data.frame(document1 = rownames(x)[x@i+1],
               document2 = colnames(x)[x@j+1],
               distance = x@x)
}

dframefmt(tmp)
#    document1 document2  distance
# 1      text3     text1 1.0833068
# 2      text5     text1 0.5648994
# 3      text3     text2 0.8978432
# 4      text5     text2 0.3630487
# 5      text1     text3 1.0833068
# 6      text2     text3 0.8978432
# 7      text1     text4 0.5218888
# 8      text3     text4 0.8340577
# 9      text1     text5 0.5648994
# 10     text3     text5 0.8931582
```

This still does not solve the signed issue for `min_simil` but I think we can solve this by considering all min values to apply to the absolute value of the metric, and do the same thing for rank as well.

#### Additional considerations

- This still does not solve the signed issue for `min_simil` but I think we can solve this by considering all min values to apply to the absolute value of the metric, and do the same thing for rank as well.
- This probably also makes sense to replace our existing `dist_selection` object. This restores the fact that any matrix returned from `textstat_dist/simil()` will be symmetric (or dist).
- The list format is also an alternative that is similarly efficient to the above pairwise data.frame format, and that we already have via `as.list.dist()`. We would rewrite this to work on the sparse object so that it never goes fully dense as an intermediate step.
```r
textstat_dist(testdfm) %>% as.list(n = 3)
$text1
    text3     text5     text4 
1.0833068 0.5648994 0.5218888 

$text2
    text3     text5     text4 
0.8978432 0.3630487 0.3030458 

$text3
    text1     text2     text5 
1.0833068 0.8978432 0.8931582 

$text4
    text3     text1     text2 
0.8340577 0.5218888 0.3030458 

$text5
    text3     text1     text2 
0.8931582 0.5648994 0.3630487
```

**Comment by koheiw** [comment]
It is true that `min_simil` is created for `textstat_simil(method = "cosine")`, which is by far the fastest.  We can drop `min_dist` argument from `textstat_dist()`. We could add `max_simil`, but I cannot think of any use case.

**Comment by koheiw** [comment]
`data.frame` is not bad for sparse similarity, but I expect many of the users will continue to use the function for all-to-all similarity, so the resulting format should be good with dense data, which is probably a symmetric Matrix (e.g. dsCMatrix). I don't think we should stick with `dist` object as it does not record diagonals even for dense matrix, or change the format based on the argument values in principle.

**Comment by koheiw** [comment]
This is why we don't need `min_dist`.
```r
> dim(mt)
[1] 5016 9357

Unit: milliseconds
                                                                          expr        min         lq       mean
           textstat_simil(mt, method = "cosine", value = "sparse", rank = 100)   416.1033   429.5484   478.5401
 textstat_simil(mt, method = "correlation", value = "sparse",      rank = 100)   525.6042   530.1822   575.1390
         textstat_dist(mt, method = "euclidean", value = "sparse", rank = 100) 45634.8168 48810.7132 49012.3131
     median         uq        max neval
   451.4354   467.3212   627.8106    10
   535.4006   627.9490   713.0701    10
 49494.8600 49581.3436 49958.8932    10
```

**Comment by kbenoit** [comment]
I'm ok with a symmetric matrix as per `philentropy::distance()`, as long as we can coerce to/from dist. 

The problem with using the sparse format however is that applying a threshold that replaces values about which we don't care with zeros produces a set of distance relations that violate the properties of distance. The same principle  applies to similarity however, that simil(A, B) = simil(A, C) implies that A = C (at least in some proportional aspect that affects that similarity measure). So if we call two things both 0 similarity because their actual similarity < min_simil, then this will be wrong.

Anyone who wants a symmetric-appearing matrix from one whose values below min_simil are set to zero would be getting something that is substantively wrong. 

The solution? the data.frame or list format.

I'd be happy with `value = c("dist", "matrix", "list", "data.frame")` and defaulting to 
- dist/matrix if there are no sparse values
- data.frame if we use `selection` or `min_simil/dist` or `rank`
- list iff a user asks for it.

But this means we never return a sparse format.

**Comment by koheiw** [comment]
I think it is users who should be aware of the implication of the `min_simil` (I don't think beginners will ever use that). We can remove `min_dist`, however. I agree that flooring distance is wrong.

By the way, we have asymmetric measure already, which is always wrong when coerced to `dist`.
```r
> mt <- dfm(c("a a b c", "a b b d", "b d d e e", "e e e"))
> textstat_dist(mt, method = "kullback", value = "sparse")
4 x 4 sparse Matrix of class "dsCMatrix"
           text1     text2       text3      text4
text1 .          0.1732868  0.05578589  .        
text2 0.17328680 .          0.34064446  .        
text3 0.05578589 0.3406445  .          -0.3665163
```
Also a similarity measure with diagonal elements smaller than 1. `dist` cannot handle this either.
```r
> textstat_simil(mt, method = "faith", value = "sparse")
4 x 4 sparse Matrix of class "dsCMatrix"
      text1 text2 text3 text4
text1   0.8   0.5   0.2   0.1
text2   0.5   0.8   0.5   0.1
text3   0.2   0.5   0.8   0.4
text4   0.1   0.1   0.4   0.6
```

**Comment by koheiw** [comment]
Our matrix has been "column-oriented", when `selection` is used.
```r
> textstat_simil(mt, c("text1", "text2"))
           text1      text2
text1  1.0000000  0.2857143
text2  0.2857143  1.0000000
text3 -0.8964215  0.0000000
text4 -0.5345225 -0.5345225
```
Following the same logic, users go through column-by-column...
```r
> textstat_simil(mt, c("text1", "text2"), rank = 2)
4 x 2 sparse Matrix of class "dgCMatrix"
          text1     text2
text1 1.0000000 0.2857143
text2 0.2857143 1.0000000
text3 .         .        
text4 .         .        
```

**Comment by kbenoit** [comment]
That's correct, but in the sparse version, it implies the simil(text3, text1) = simil(text3, text2) = 0. That's wrong. In the data.frame or list versions, where those pairs are simply absent, we don't have that problem.

If we had a sparse matrix where the non-recorded values were NA rather than 0, this would solve that problem, but we don't have such a sparse matrix format. Instead, the values shown as . are treated in all matrix operations as zero, and that's the core problem with a sparse format for returning subsets of the distance pairs.

**Comment by koheiw** [comment]
It is OK that simil(text3, text1) = simil(text3, text2) = 0 is wrong because we are not interested in the relationship when `rank` is used. If you do not want to show that to users, better to separate `textstat_proxy()` as a separate package.

**Comment by kbenoit** [comment]
A separate package is of course option but a) we still need to figure out how to format the dist and simil returns in **quanteda** and b) you would still have the misleading zeros problem in a separate package. I think that this is the reason why no one uses a sparse matrix format to represent distance or similarity matrices.

The efficiency of computing only what is needed is great, but the sparse representation of what is not needed as zeros is not a problem I see going away.

**Comment by koheiw** [comment]
By the way, I found that we can record zeros in a sparse matrix, if we wanted
```r
> as(Matrix::spMatrix(10, 10, i=1:8, j=2:9, x = c(0:2, 3:-1)), "CsparseMatrix")
10 x 10 sparse Matrix of class "dgCMatrix"
                          
 [1,] . 0 . . . . . .  . .
 [2,] . . 1 . . . . .  . .
 [3,] . . . 2 . . . .  . .
 [4,] . . . . 3 . . .  . .
 [5,] . . . . . 2 . .  . .
 [6,] . . . . . . 1 .  . .
 [7,] . . . . . . . 0  . .
 [8,] . . . . . . . . -1 .
 [9,] . . . . . . . .  . .
[10,] . . . . . . . .  . .
```
There is a `Matrix::drop0()` to remove explicit zeros.

**Comment by kbenoit** [comment]
That's not the issue though - the issue is that all operations and conversions for the sparse values treat them as zeros. We can also represent explicit NAs but these take the same storage space as a numeric, so there is no point.

**Comment by koheiw** [comment]
If `textstat_proxy()` returns a matrix with zero, `textstat_dist()` and `textstat_simil()` returns `data.frame` or `dist`, your problem will be solved. I am looking for a way to get a sparse matrix from `textstat_proxy()`.

**Comment by kbenoit** [comment]
OK, so how about we modify the PR so that it continues to use the high-performance `textstat_proxy()` method, but for the user-facing API, does the following:

```r
textstat_simil(x, selection = NULL, margin = c("documents", "features"), 
  method = ..., upper = FALSE, diag = FALSE, 
  min_simil = NULL, max_rank = nfeat(x), 
  value = c("diag", "matrix", "list", "data.frame"))

textstat_dist(x, selection = NULL, margin = c("documents", "features"), 
  method = ..., upper = FALSE, diag = FALSE, 
  min_dist = NULL, max_rank = nfeat(x), 
  value = c("diag", "data.frame", "matrix", "list"))
```
where the **return values** are the following core object classes, with additional attributes to mark them as special objects (for coercion methods) similar to how we tag `dist_selection`:

*  iff is.null(min_dist/simil) && max_rank = nfeature(x);
    -  default return object is a dist, for consistency (for now) with existing behaviour; or
    -  a symmetric matrix of class `dsCMatrix` where the diagonals are NA if `diag = FALSE` but zeroes represent real zeroes. 
        We could use a regular matrix format too, but the symmetric sparseMatrix format is consistent with other return objects (dfm, fcm) that we already return and it is twice as efficient as a regular matrix that is symmetric (as for example the format returned by `philentropy::distance()`). But we do not return this with the `.` entries representing values that were removed because of min_dist, min_simil, or max_rank settings. 

*  return object is a data.frame of pairwise values as per my suggestion in the "Solution" section of https://github.com/quanteda/quanteda/issues/1455#issue-372370642 if any of these are TRUE:
    -  `!is.null(selection)`
    -  `!is.null(min_dist)` or `!is.null(min_simil)`
    -  `max_rank < nfeat(x)`
    -  `value = "data.frame"`. (This can apply to any configuration of the other settings.)

*  return object is a list if `value = "list"`.  (This can apply to any configuration of the other settings.) The `max_rank` would operate in the same way that `n` does in `as.list.dist()`.

We would also make it clear that the `min_simil` and `max_rank` are applied to the absolute values of the similarity measures if < 0 (as with correlation). This is theoretically possible but very unlikely to apply to other methods (e.g. cosine).

If you still want the sparse matrix format that is not symmetric or contains the zeroes that I think are wrong, it would be easy to write a `sparseMatrix.dist_data.frame()` `sparseMatrix.dist_list` method to produce that.

**Comment by koheiw** [comment]
I think it is too early to expose the `min_simil` and `max_rank` etc. because I haven't used those myself yet with real data. I might find practical issues and need to change them again.

The best solution at the moment seems to change `textstat_dist()` and `textstat_simil()` only internally (have no new argument and return `dist`), and export `textstat_proxy()` to allow me and @kasperwelbers to field test. We can make it `@keyword internal` and/or "put [Experimental]" in the title.

After field tests, we can agree on the API design more easily...

**Comment by kbenoit** [comment]
That’s a good interim solution. So the API for `textstat_dist` and `texstat_simil()` would go back to their current form, but use `textstat_proxy()` for computation but converted to the current output formats. Meanwhile we export `textstat_proxy()` but keep it internal and marked experimental.
