### ISSUE TITLE
Call for feedback on textstat_proxy()

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda#1472]
We added ` textstat_proxy()` function for computing document similarity with minimum threshold, but kept it experimental until we decide the format of the resulting objects. There are technological discussion #1455 #1469 on the issue, but we want to learn users perspective.

~~Since the function is experimental, you can only access it using `quanteda:::textstat_proxy()`.~~

**Comment by koheiw** [comment]
I started using the function myself in a real project, where I want to compute similarity between two sets of documents (say, corpus A and corpus B). In doing so, I noticed that the `textstat_proxy()` is not very useful yet, because it can only compute similarity within corpus A or B, not between A and B. 

It currently has these arguments `textstat_proxy(x, selection, margin, method , min_proxy, rank)` but I suggest to change it to be `textstat_proxy(x, y, margin, method , min_proxy, rank)`, where `y` can be either feature-selected `x` or a DFM of entirely different set of documents.

**Comment by kbenoit** [comment]
Do you mean sth like this?
``` r
library("quanteda")
## Package version: 1.3.16
## Parallel computing: 2 of 12 threads used.
## See https://quanteda.io for tutorials and examples.

dfm1 <- dfm(data_corpus_inaugural)[1:2, ]
dfm2 <- dfm(data_corpus_dailnoconf1991)[1:2, ]

rbind(dfm1, dfm2) %>%
  textstat_simil()
##                       1789-Washington 1793-Washington Haughey_FF_Taois.txt
## 1793-Washington             0.8362466                                     
## Haughey_FF_Taois.txt        0.8946073       0.7951655                     
## Spring_Lab_Leader.txt       0.8815240       0.7905395            0.9575113
```

**Comment by koheiw** [comment]
I know that combining two DFM has been the recommended approach, but it leads to computation of pair that I am not interested parties in.

We might need a mode to exclude selected features or documents from computation so that the pairs will be only selected and non-selected.

**Comment by koheiw** [comment]
Additionally, the function holds x and transposed x for quick multiplication internally, so it makes more sense to pass two matrix instead of combining.

**Comment by kbenoit** [comment]
OK so what do you mean exactly by "compute similarity...between corpus A and B"? Is it

a) combining all documents or features within a corpus to make one "document" per corpus and then comparing those? (that could use `dfm_group() %>% rbind()`.

b) for features, combining the two corpora to get feature similarity? (That could use `rbind()` as above.)

In either case you have to supply all documents and features in `x` as a dfm/matrix, _or_ combine `x` with `y` in order to get a matrix with the same features.

The **proxy** functions have such an argument signature, e.g. `proxy::dist(x, y = NULL, ...)` but the `x` and `y` must conform in features.

``` r
set.seed(10)
x <- matrix(sample(c(FALSE, TRUE), 8, rep = TRUE), ncol = 2)
proxy::dist(x, method = "Jaccard")
##   1 2 3
## 2 1    
## 3 1 0  
## 4 0 1 1
proxy::dist(x, x, method = "Jaccard")
##      [,1] [,2] [,3] [,4]
## [1,]    0    1    1    0
## [2,]    1    0    0    1
## [3,]    1    0    0    1
## [4,]    0    1    1    0
proxy::dist(x, x[-1], method = "Jaccard")
## Error in proxy::dist(x, x[-1], method = "Jaccard"): x and y must be conform in columns.
```

**Comment by koheiw** [comment]
That would be something like this
```r
require(quanteda)
dfm1 <- dfm(data_corpus_inaugural)[1:2, ]
dfm2 <- dfm(data_corpus_dailnoconf1991)[1:2, ]

f <- union(featnames(dfm1), featnames(dfm2))
dfm1 <- quanteda:::pad_dfm(dfm1, f)
dfm2 <- quanteda:::pad_dfm(dfm2, f)

Matrix::tcrossprod(dfm1, dfm2) # will be done in C++

# 2 x 2 sparse Matrix of class "dgCMatrix"
#                 Haughey_FF_Taois.txt Spring_Lab_Leader.txt
# 1789-Washington               140183                135583
# 1793-Washington                14906                 14545
```

**Comment by koheiw** [comment]
Only issue here is that computing similarities between documents in different corpora makes sense, but dosing so with features does not, so `y` should be `NULL` when `margin = features`.

For backward compatibility, we could use `select` for the `y` input. This is similar to `dfm_select()` which takes a DFM as `pattern`, but not sure it is user-friendly.
