### ISSUE TITLE
Add tokens_sample()

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda#1478]
We have `dfm_sample()` and `corpus_sample()`, but why not `tokens_sample()`?
I am tied of doing
```r
toks <- tokens(data_corpus_big)
toks[sample(seq_along(toks), 10)]
```
just to check how tokenization is going.

**Comment by kbenoit** [comment]
Good idea. Let's  add a 
```r
tokens_sample(x, size = ndoc(x), replace = FALSE, prob = NULL, by = NULL, ...)
```
that works just as `corpus_sample()` does to sample from documents.
