### ISSUE TITLE
textstat_lexdiv should raise warning if dfm argument contains punctuations

### ISSUE THREAD

**Issue by jiongweilua** [quanteda/quanteda#1487]
## Describe the bug

The `textstat_lexdiv` function computes lexical diversity statistics without checking for the validity of the tokens and types in the `dfm` argument.

## Reproducible code

```r
> library(quanteda)
> test_dfm <-  corpus(c(d1 = "a a b b c c",
+                       d2 = "a a , b b . c c / ")) %>% dfm()
> 
> 
> textstat_lexdiv(test_dfm['d1'], 'all')
  document TTR         C        R      CTTR        U        S     Maas      lgV0    lgeV0
1       d1 0.5 0.6131472 1.224745 0.8660254 2.011492 2.950093 0.705084 0.6039749 1.390704
> 
> textstat_lexdiv(test_dfm['d2'], 'all')
  document       TTR         C R     CTTR        U        S      Maas     lgV0   lgeV0
1       d2 0.6666667 0.8154649 2 1.414214 5.171062 5.355425 0.4397543 1.344406 3.09561
```

## Expected behavior

We would expect that the two documents produce the same lexdiv statistics, since punctuation marks should not contribute to lexical diversity. 

Right now within the textstat_lexdiv function, there are no checks to ensure that the `n_tokens` and `n_types` measures are computed for meaningful vocabulary words. 

### Proposed Fixes
We can either raise an error under two conditions. 
- The first, stronger condition one is to raise an error as long as any feature of the dfm is a punctuation. 
- The second, weaker condition (but a bit more complicated to implement) is to raise an error if the dfm contains at least one a feature that is a punctuation, and has a positive frequency.

**Comment by jiongweilua** [comment]
I can work on these problems and create some tests. Will raise a PR when I am done.

**Comment by kbenoit** [comment]
I suggest starting with the tokens method for the existing measures, and implementing the `remove_*` arguments, adding tests. The moving average functions can be done separately (separate PR) once we have the tokens method working.

You have access to the repo now, so no need to work from your fork - create a branch in this repo if you prefer.

**Comment by kbenoit** [comment]
Re 1:
* Here you would use, for `textstat_lexdiv.dfm()`, simply:
```r
if (remove_punct)
    dfm_remove(x, “\\p{P}”, valuetype = “regex”)
```

Re 2:`textstat_lexdiv.tokens(x, ...)` will
a.  Call `tokens(x, ...)` where `...` are the remove_* arguments
b.  Call `dfm(x) %>% textstat_lexdiv()`.
