### ISSUE TITLE
textstat_lexdiv does not support Yule's K despite being in documentation 

### ISSUE THREAD

**Issue by jiongweilua** [quanteda/quanteda#1488]
## Describe the bug

Although the [documentation](https://quanteda.io/reference/textstat_lexdiv.html) of `textstat_lexdiv` suggests that Yule's K is supported as a lexdiv measure, it is actually not accepted as a possible value for the `measure` argument.

## Reproducible code
```r
> library(quanteda)
> library(data.table)
> test_dfm <-  corpus(c(d1 = "a a b b b c c d e f",
+                     d2 = "apple orange grape fruit french french") ) %>% dfm()
> 
> textstat_lexdiv(test_dfm, measure = 'K')
Error in textstat_lexdiv.dfm(test_dfm, measure = "K") : 
  Invalid measure(s): K
```

## Proposed Fix
The formula for Yule's K references this [paper](https://www.jstor.org/stable/30204534?seq=4#metadata_info_tab_contents).
The variable `M` is a vector of length `ndoc(x)` and ordered by `docnames(x)`.
Its computation relies on `quanteda::textstat_frequency` and `dplyr`. 

```r
 if ('K' %in% measure){
    
    # Yule's K is defined as 10^4 * (M-N)/N^2 where M = V(i) * i^2, with
    # V(i) being the number of types with exactly i counts, and 
    # N being the number of tokens
    
    M <- textstat_frequency(x, groups = docnames(x)) %>%  
      group_by(group, frequency) %>% 
      count() %>% ungroup() %>% 
      group_by(group) %>%
      summarize(temp_M = sum(frequency^2 * n)) %>% 
      select(temp_M)

    temp[, K := 10^4 * (M - n_tokens) / (n_tokens^2)]
  }
```
After adding this chunk to the current version of `textstat_frequency` and adding `'K'` to the list of accepted values for `measure`, the same test case was run. 

```r
> textstat_lexdiv_withYuleK(test_dfm, measure = 'K')
  document         K
1       d1 1000.0000
2       d2  555.5556
```

**Comment by jiongweilua** [comment]
@kbenoit Thanks!

-  Noted about avoiding **`dplyr`** dependencies, will try to work with base R and quanteda functions as much as I can. 
- And yes, I think the new notation on the html documentation you did up is much better then the current one. I was quite confused what the individual X and bold **X** was referring to. 
- Will work on testing the measures re-implemented from the **koRpus** package

**Comment by kbenoit** [comment]
Take a look at 64c31ea since I missed checking multiple documents. I think I've now implemented it as efficiently as possible without doing it in C++ (which would in fact be fairly simple).

Have no idea if the implementation of _D_ and _Vm_ are actually correct. The problem with many of these textual statistics is that they were developed in the pre-digital age, and very few reliable examples exist against which to test our results.
