### ISSUE TITLE
Some (internal, dontrun) examples fail because of local file references

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#1507]
Many internal functions have `\dontrun{}` examples that do not actually run, because they rely on local files on @kbenoit's or @koheiw's local machines. e.g.

https://github.com/quanteda/quanteda/blob/master/R/dictionaries.R#L701-L705

https://github.com/quanteda/quanteda/blob/master/R/dictionaries.R#L782

https://github.com/quanteda/quanteda/blob/master/R/dictionaries.R#L594-L596

We should change these to refer to copies of these or similar example files in the package structure, so that `devtools::run_examples()` passes without errors.

**Comment by kbenoit** [comment]
@koheiw can you please send me these files:
- [ ] /home/kohei/Documents/Dictionary/LaverGarry.txt
- [ ] /home/kohei/Documents/Dictionary/Wordstat/ROGET.cat
- [ ] /home/kohei/Documents/Dictionary/Wordstat/WordStat Sentiments.cat

**Comment by koheiw** [comment]
These are available in https://provalisresearch.com/products/content-analysis-software/wordstat-dictionary/ but not sure we can redistribute.
