### ISSUE TITLE
Removing FLIBS from Makevars

### ISSUE THREAD

**Issue by jeroen** [quanteda/quanteda#1524]
Installation from source on my macos machine failed because I don't have fortran installed:

```
clang++ -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o quanteda.so RcppExports.o ca_mt.o collocations_mt_.o dist_mt.o fcm_mt.o kwic_mt.o simil_mt.o tokens_compound_mt.o tokens_lookup_mt.o tokens_ngrams_mt.o tokens_recompile_mt.o tokens_segment_mt.o tokens_select_mt.o utility.o wordcloud.o wordfish_dense.o wordfish_mt.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [quanteda.so] Error 1
ERROR: compilation failed for package ‘quanteda’
```

This happens because of `$(FLIBS)` in your Makevars. Why is this here? You are not using any fortran code? If you remove this flag, I can compile the package.

**Comment by koheiw** [comment]
Thanks @jeroen. I think we have `$(FLIBS)` for `$(BLAS_LIBS)`. 

http://www.hep.by/gnu/r-patched/r-exts/R-exts_11.html
> A macro containing the BLAS libraries used when building R. This may need to be included in PKG_LIBS. Beware that if it is empty then the R executable will contain all the double-precision and double-complex BLAS routines, but no single-precision or complex routines. If BLAS_LIBS is included, then FLIBS also needs to be(17), as most BLAS libraries are written at least partially in FORTRAN. 

If I remove the former, R check raises a warning. That said, I am not sure how important BLAS is for our package. Any thought?

**Comment by kbenoit** [comment]
Wish we could get rid of it! 

But `$(FLIBS)` is required by **RcppArmadillo**, which provides things we cannot do without (like `arma::sp_mat`). See ``?RcppArmadillo::`RcppArmadillo-package` `` which makes it pretty clear that this is required.

**Comment by jeroen** [comment]
Ah okay I guess you need to keep it there then. On MacOS it doesn't seem to be needed but perhaps on other systems it is. Thanks for the info.
