### ISSUE TITLE
fcm with word locations

### ISSUE THREAD

**Issue by adamlauretig** [quanteda/quanteda#1528]
## Requested feature

Hi all,

Thanks for the awesome package, it's been incredibly useful! 

Is it possible to extend the fcm function to create a list of fcm's with different word locations, or alternatively, specify co-occurrence distance?

This would allow a user to return those words that are only, say 5 (or -5) tokens apart, rather than all co-occurrences -5:5.

## Use case

This would allow for a three-variable PMI or exponential PCA, along the lines of http://www.aclweb.org/anthology/E17-2028.

Thank you for considering this, and let me know if you have any questions!

Best,

Adam

**Comment by koheiw** [comment]
Is this what you want to do?
```r
require(quanteda)
toks <- tokens(c("a b c d a", "a b e e c"))
fcm(toks, context = "window", window = 1)
```
In this setting, there is not cooccurances of "a" and "c" because they are more than one token apart. 
```
Feature co-occurrence matrix of: 5 by 5 features.
5 x 5 sparse Matrix of class "fcm"
        features
features a b c d e
       a 0 2 0 1 0
       b 0 0 1 0 1
       c 0 0 0 1 1
       d 0 0 0 0 0
       e 0 0 0 0 1
```

**Comment by kbenoit** [comment]
To count only words that are a certain distance apart, you can use the weights feature to turn off the counts of the ones closest to the target. I think this is what you meant:

```r
txt <- paste(letters[1:10], collapse = " ")
toks <- tokens(txt)

fcm(toks, context = "window", window = 5, 
    count = "weighted", weights = c(0, 0, 0, 0, 1))
#> Feature co-occurrence matrix of: 10 by 10 features.
#> 10 x 10 sparse Matrix of class "fcm"
#>         features
#> features a b c d e f g h i j
#>        a 0 0 0 0 0 1 0 0 0 0
#>        b 0 0 0 0 0 0 1 0 0 0
#>        c 0 0 0 0 0 0 0 1 0 0
#>        d 0 0 0 0 0 0 0 0 1 0
#>        e 0 0 0 0 0 0 0 0 0 1
#>        f 0 0 0 0 0 0 0 0 0 0
#>        g 0 0 0 0 0 0 0 0 0 0
#>        h 0 0 0 0 0 0 0 0 0 0
#>        i 0 0 0 0 0 0 0 0 0 0
#>        j 0 0 0 0 0 0 0 0 0 0
```

**Comment by adamlauretig** [comment]
@kbenoit, that's what I had in mind, but I was wondering if it would be possible to weight on either side of the window.

It would be similar to

```r
txt <- paste(letters[1:10], collapse = " ")
toks <- tokens(txt)

fcm(toks, context = "window", window = 5, 
    count = "weighted", weights = c(0, 0, 0, 0, 1), tri = FALSE, ordered = TRUE)
```
however, `ordered`, as I understand it, only looks backwards. This could be a way of setting weights so that 5 before and 5 after would be different `fcm` matrices.

**Comment by adamlauretig** [comment]
@kbenoit, that's what I had in mind. Sorry for my lack of clarity, and thank you for all your help!

**Comment by kbenoit** [comment]
It gives us a warm glow to see that we designed `fcm()` in a manner that is flexible enough to handle use-cases we had not anticipated!
