### ISSUE TITLE
Bootstrap_dfm and sentiment analysis

### ISSUE THREAD

**Issue by AdaemmerP** [quanteda/quanteda#1529]
Is it possible to find the total number of words of a new bootstrapped document when combining *bootstrap_dfm()* with a dictionary?

When I use: 

               bootstrap_dfm(text,   n = 1,  dictionary  = data_dictionary_LSD2015)

it only shows how many *positive*, *negative*, *neg_positive* and *neg_negative* words were found. Using rowSums() would thus only show the total number of sentiment words.

First using *bootstrap_dfm()* and then applying the dictionary would not count *neg_positive* and *neg_negative* words because the dfm are unigrams, right?

**Comment by koheiw** [comment]
How about doing in this way?
```r
require(quanteda)

corp <- corpus_reshape(data_corpus_inaugural, "sentences")
toks <- tokens(corp)
n <- nfeat(dfm(toks))

mt <- dfm(toks, dictionary = data_dictionary_LSD2015)
out <- bootstrap_dfm(mt, n = 3)

topfeatures(out[[1]]) / n
#    positive     negative neg_negative neg_positive 
#  1.23704179   0.53895479   0.01047344   0.00630544 

topfeatures(out[[2]]) / n
#    positive     negative neg_negative neg_positive 
#  1.27316448   0.53435930   0.01111467   0.00748103 
```

**Comment by AdaemmerP** [comment]
Great, thanks!
