### ISSUE TITLE
how to use quanteda package in R for analyzing text in Gujarati language?

### ISSUE THREAD

**Issue by BChandrakant** [quanteda/quanteda#1531]
## Consider StackOverflow

If you have a question on how to use **quanteda**, please first search [our StackOverflow channel](https://stackoverflow.com/questions/tagged/quanteda). If it does not solve you problem, please post your question there. We monitor the channel and should respond to your question very quickly. 

## Report a bug

If you know how to use **quanteda** but not seeing what you expect, please check [existing issues](https://github.com/quanteda/quanteda/issues?utf8=%E2%9C%93&q=is%3Aissue). If it does not help, please [open an issue](https://github.com/quanteda/quanteda/issues/new?template=bug_report.md).

## Other questions

Please write your questions here.

**Comment by kbenoit** [comment]
This is a very broad question, and we would need an example and something more specific in terms of "analyzing text" in order to begin to answer this question. Please reformulate and supply an example and a more specific question. Such as: "How to tokenize text in Gujarati?"

**Comment by BChandrakant** [comment]
Dear Prof. Benoit,
Yes, it was a very broad question. Actually, I am working on a personal research project to develop a readability formula for /in Gujarati language. I have prepared a text corpus of 50 documents of Gujarati. each document is a 1000-word passage. the corpus is in the plain text format and is encoded in UTF-8 encoding. I want to analyze the documents of the corpus for about more than 10 readability features at word, sentence, and discourse levels. At the moment, I do not know much, but I want to use Support Vector Machine (SVM) algorithm of machine learning with an appropriate model equation. During my literature search, I came to know that R package e1071 can be applied for SVM. After presenting my broad question yesterday, I tried to analyze three Gujarati documents from my text corpus using quick guide for the package Quanteda. I was partially successful, the documents were tokenized and a word cloud was created. But I don't know how to wordstem and stopwords. Although I could understand that for stopwords there must be a list of Gujarati stop words as a data object in the package, I do not know how to convert a list of Gujarati stop words into a data object for the package. I know that the list must be in UTF-8 format, the ISO-639-1 language code will form the name of the list. Being a native speaker of Gujarati and M. A. in Gujarati language and literature, I think that I can prepare a 'raw' list of stop words in Gujarati. Now my questions are: (1) how to prepare the list of stop words as a _data object _? (2) how to prepare word stems for Gujarati text? and (3) how quanteda or any other R package can be useful for analyzing Gujarati text for readability features (specialy important for Gujarati language such as consonant conjucts)? I am attaching herewith one 1000-word Gujarati text (.txt and UTF-8) from my text corpus. I do not know coding or programming. I am tremendously indebted to you and GITHUB. 
[AConstrictivismandLiteraryCriticism.txt](https://github.com/quanteda/quanteda/files/2712562/AConstrictivismandLiteraryCriticism.txt)

**Comment by kbenoit** [comment]
For stop words in Gujarati, I found these: https://github.com/gujarati-ir/Gujarati-Stop-Words
We'd happily add these to the **stopwords** package if you file an issue [there](https://github.com/quanteda/stopwords/issues).

For a stemmer, it looks like this is available in Python http://github.nisargjhaveri.com/indicNLP/ but I have not tried it. It's unlikely to be integrated soon into **quanteda** I am afraid since we rely on the **SnowballC** package, and its languages are only 

```r
> SnowballC::getStemLanguages()
 [1] "danish"     "dutch"      "english"    "finnish"    "french"     "german"    
 [7] "hungarian"  "italian"    "norwegian"  "porter"     "portuguese" "romanian"  
[13] "russian"    "spanish"    "swedish"    "turkish"
```
