### ISSUE TITLE
Memory Usage of tokens_compound()

### ISSUE THREAD

**Issue by jogrue** [quanteda/quanteda#1539]
I start with a corpus of 189602 Facebook postings and Tweets, each is one document. The corpus has a size of 431.2 Mb

I create the following tokens object which then has 189602 (short) elements and is about 447.1 Mb in size.

```r
tok <- tokens(corpus, 
              remove_numbers = TRUE,
              remove_punct = TRUE,
              remove_symbols = TRUE,
              remove_separators = TRUE,
              remove_twitter = TRUE,
              remove_hyphens = FALSE,
              remove_url = TRUE,
              verbose = TRUE) %>%
    tokens_tolower()

[...]
...tokenizing 19 of 19 blocks
...preserving hyphens
...removing URLs
...serializing tokens 231536 unique types
...total elapsed:  9.87800000000004 seconds.
```

I then try to create compound tokens for certain multi-word dictionary entries. My dict_compounds is a dictionary object that includes 250 multi-word terms separated by blanks (e.g., "angeblich* elite", "angeblich* expert", ...).
```r
    tok <- tokens_compound(tok, pattern = dict_compounds,
                           concatenator = " ",
                           # case_insensitive = TRUE,
                           valuetype = "glob",
                           join = FALSE)
```

However, this never runs through because it is eating up all my memory (16 GB; also tried with an additional 16 GB swap file on an SSD). I tried it with setting only one thread through the options and also with the latest version on CRAN and on GitHub (currently I am at 1.3.18).

I am now wondering if this is to be expected with tokens of this size or if this is a bug or possible memory leak?

What I want to to do is to create tokens to look at KWIC and then create a dfm for dictionary-based analysis without including n-grams but only compounds for features that are also in the dictionary. If there is a better way to do this, I would be very happy to hear about it. For now I wrote the function below, it basically runs `tokens_compound()` in steps of 10000 elements.

Also, I am very sorry if my issue is not really an issue with quanteda but what is to be expected. I am just not sure how much memory it takes to run tokens_compound (or kwic) and if this depends only on the text or also the size of the dictionary. But since it was so easy for me to write a work-around, I was wondering if there is something going wrong when I run `tokens_compound()`.

```r
# Creates tokens from a corpus, using this function makes sure that the same
# settings are applied all the time.
# The dictionary is used to create compound tokens (n-grams).
get_pop_tokens <- function(corpus, full_dict) {
  library(quanteda)
  library(dplyr)
  
  # If dictionary is a Quanteda dictionary it is unlisted.
  if (is.dictionary(full_dict)) {
    full_dict <- unlist(full_dict)
  }
  
  # Only keep multi-word terms
  dict_compounds <- full_dict[str_detect(full_dict, " ")] %>%
    unique() %>%
    list(comp = .) %>%
    dictionary()
  
  ### Here settings for the tokenizer should be made ###
  toks <- tokens(corpus, 
                 remove_numbers = TRUE,
                 remove_punct = TRUE,
                 remove_symbols = TRUE,
                 remove_separators = TRUE,
                 remove_twitter = TRUE,
                 remove_hyphens = FALSE,
                 remove_url = TRUE,
                 verbose = TRUE) %>%
    tokens_tolower()
  
  # Compound tokens are created in a loop
  max <- length(toks)
  step <- 10000
  first <- 1 - step
  comp_toks <- NULL
  repeat {
    first <- first + step
    last <- first + step - 1
    if (last > max) {
      last <- max
    }
    tmp <- toks[first:last]
    print(paste0("Creating compounds for elements ", first, " to ", last, "."))
    tmp <- tokens_compound(tmp, pattern = dict_compounds,
                           concatenator = "_",
                           # case_insensitive = TRUE,
                           valuetype = "glob",
                           join = FALSE)
    if (is.null(comp_toks)) {
      comp_toks <- tmp
    } else {
      comp_toks <- c(comp_toks, tmp)
    }
    if (last == max) {
      break
    }
  }
  return(comp_toks)
}
```

**Comment by koheiw** [comment]
Hi @jogrue 

I suspect that this is the issue of glob-id conversion. `tokens_compound()`'s underlying C++ function takes only integers IDs of tokens, so it calls `pattern2list()`. But, if your dictionary contains patterns that match too many (possible) combination of tokens, it takes can fail. In the extreme case, "* *" (sequence of any two) produces ` length(types(toks)) ^ 2` combinations as in the third example.
```r
toks <- tokens(data_corpus_inaugural)

quanteda:::pattern2list(dictionary(list(key = "a b*")), types(toks), "glob", TRUE) %>% 
    length() # 728

quanteda:::pattern2list(dictionary(list(key = "a* b*")), types(toks), "glob", TRUE) %>% 
    length() # 290836

quanteda:::pattern2list(dictionary(list(key = "* *")), types(toks), "glob", TRUE) %>% 
    length() # 101143249
```
Why don't you run this command to find which pattern is causing the problem?
```r
quanteda:::pattern2list(data_dictionary_LSD2015, types(toks), "glob", TRUE) %>% 
    names() %>% table()
```

**Comment by jogrue** [comment]
I think you are right. I have a few patterns that produce 207,510 (possible) combinations, but I have two patterns that amount to 18,260,880 combinations each. Changing or removing these patterns helped a lot with memory consumption. I was just trying to run an extended list of patterns without thinking about that aspect at all.

Sorry for opening an issue on GitHub, since it seems my problem was not really an issue with quanteda but more a question about usage.

**Comment by koheiw** [comment]
You are always welcome.

**Comment by Spiritspeak** [comment]
I also ran into this problem, and there's not really a way to simplify my dictionary/pattern. However, I have found a bizarrely simple solution... breaking the tokens input into smaller pieces. I want to recommend that this be added to quanteda:

```
tokens_compound_stepwise<-function(x, pattern, stepsize=100, concatenator = "_", 
                                   valuetype = c("glob", "regex", "fixed"), 
                                   case_insensitive = TRUE, join = TRUE){
  valuetype<-match.arg(valuetype)
  output<-list()
  lx<-length(x)
  mxsteps<-ceiling(lx/stepsize)
  for(i in seq_len(mxsteps)){
    cat("\rCompounding tokens... ",round(100*(i-1)/mxsteps,digits=2),"%",sep="")
    range<-(1+(i-1)*stepsize):min(i*stepsize, lx)
    currcomp<-tokens_compound(x[range],pattern,concatenator,valuetype,case_insensitive,join)
    output<-c(output,currcomp)
  }
  cat("\rCompounding tokens... finished.")
  output
}
```
