### ISSUE TITLE
textstat_dist/simil() should return NA for empty feature dfms

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#1540]
We discussed this in #1530 and established that:

* Definitionally, dist or simil for an empty dfm (documents in rows but no features) should be NA for the document margin, and produce an error for the features margin (since by design it should be impossible to have an "empty" dfm with features but no documents).

There are skipped tests for this in 
https://github.com/quanteda/quanteda/blob/c27aeab9c83b02c1f971093aeb784a14b6f122a2/tests/testthat/test-textstat_simil.R#L180-L253 but accepted the PR while skipping those tests.

Note also that some of our benchmark tests against e.g. **proxy** were shown to be wrong, such as 
https://github.com/quanteda/quanteda/pull/1530#issuecomment-451014579.

**Comment by koheiw** [comment]
See `?getOption("matprod")`:

> matprod:
a string selecting the implementation of the matrix products %*%, crossprod, and tcrossprod for double and complex vectors:
> 
> "internal"
uses an unoptimized 3-loop algorithm which correctly propagates NaN and Inf values and is consistent in precision with other summation algorithms inside R like sum or colSums (which now means that it uses a long double accumulator for summation if available and enabled, see capabilities).
> 
> "default"
uses BLAS to speed up computation, but to ensure correct propagation of NaN and Inf values it uses an unoptimized 3-loop algorithm for inputs that may contain NaN or Inf values. When deemed beneficial for performance, "default" may call the 3-loop algorithm unconditionally, i.e., without checking the input for NaN/Inf values. The 3-loop algorithm uses (only) a double accumulator for summation, which is consistent with the reference BLAS implementation.
> 
> "blas"
uses BLAS unconditionally without any checks and should be used with extreme caution. BLAS libraries do not propagate NaN or Inf values correctly and for inputs with NaN/Inf values the results may be undefined.
> 
> "default.simd"
is experimental and will likely be removed in future versions of R. It provides the same behavior as "default", but the check whether the input contains NaN/Inf values is faster on some SIMD hardware. On older systems it will run correctly, but may be much slower than "default".

**Comment by kbenoit** [comment]
This is still unresolved, although it works for "cosine" and "correlation", it returns zeros for the other types. See the skipped tests in `test-textstat_simil.R` and `test-textstat_dist.R`.
