### ISSUE TITLE
Argument Font size in textplot_network

### ISSUE THREAD

**Issue by guilhermeparreira** [quanteda/quanteda#1564]
First of all! Congratulations for your package!

I am able to control the vertex size, but not the **vertex label size** in `textplot_network`. Can you guys make it?

This is what I have got so far:

```
    library(quanteda)
    toks <- corpus_subset(data_corpus_irishbudget2010) %>%
      tokens(remove_punct = TRUE) %>%
      tokens_tolower() %>%
      tokens_remove(stopwords("english"), padding = FALSE)
    myfcm <- fcm(toks, context = "window", tri = FALSE)
    feat <- names(topfeatures(myfcm, 30))
    myfcm <- fcm_select(myfcm, feat, verbose = FALSE)
      
    textplot_network(myfcm, vertex_size = rowSums(myfcm)/min(rowSums(myfcm)),
                     vertex.cex = rowSums(myfcm)/min(rowSums(myfcm)))
```
It would be nice to make the label of the words bigger, so that I can focus on the *label* of the word, and not in the "vertex" of the word (which can overlap the label, as it is shown in the graph above).

Thanks in advance!

[![enter image description here][1]][1]

 [1]: https://i.stack.imgur.com/ydVhs.png

**Comment by jiongweilua** [comment]
Hi, yes it is indeed possible to add an argument for the vertex label size. 

May I check if this is the desired output? If so, I can add an argument `vertex_labelsize` and issue a pull-request. But as I am new to the quanteda team, I will have Ken / Kohei review this first.

```r
library(quanteda)
toks <- corpus_subset(data_corpus_irishbudget2010) %>%
    tokens(remove_punct = TRUE) %>%
    tokens_tolower() %>%
    tokens_remove(stopwords("english"), padding = FALSE)
myfcm <- fcm(toks, context = "window", tri = FALSE)
feat <- names(topfeatures(myfcm, 30))
myfcm <- fcm_select(myfcm, feat, verbose = FALSE)

textplot_network(myfcm, vertex_size = rowSums(myfcm)/min(rowSums(myfcm)),
                 vertex.cex = rowSums(myfcm)/min(rowSums(myfcm)),
                 vertex_labelsize =  rowSums(myfcm)/min(rowSums(myfcm)))
```
![image](https://user-images.githubusercontent.com/28591528/51492322-55f04900-1da9-11e9-87c4-85f13cb83f96.png)

**Comment by guilhermeparreira** [comment]
Yes @jiongweilua, exactly!

Thank you very much!

**Comment by jiongweilua** [comment]
Hi @guilhermeparreira I have raised PR #1565 but will have to wait for Ken or Kohei's approval.

**Comment by jiongweilua** [comment]
Hi @guilhermeparreira, PR #1565 has been approved and will soon be committed to the Master branch on this repo. Thanks for your suggestions, and please consider [leaving a feedback or testimonial here](https://github.com/quanteda/quanteda/issues/461)!
