### ISSUE TITLE
dfm_subset() and tokens_subset() should take only logicals as `subset()` values

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#1566]
In fixing #1481, I am finding it very inconsistent that we allow `subset` to be a tokens in `tokens_subset()` and a dfm in `dfm_subset()`. What we are really doing is reordering the document index as if - e.g. in the example for `dfm_subset()` - we used `dfm1[docnames(dfm2), ]` and this did not return a Subscript out of bounds error but instead added the empty documents. 

Problems are:
1. Unlike the common-sense meaning of "subset" and the accepted R usage everywhere else (e.g. `base::subset()`, our arguments to `subset` can result in the *addition* of documents not present already.  This is not a subset, or a selection, but rather something very different - more like our recent `dfm_match()` but for documents rather than features.
2. It's inconsistent to allow an argument to have `logical` or a complex object class.

Our solution for the features margin in #1555 was to add `dfm_match()`. We had some discussion as to whether to call it `dfm_featurematch()`, to emphasize the margin it was matching. What if we take the document matching function out of `dfm_subset()` and move it to:
```r
dfm_match(x, select, margin = c("features", "documents")
```
where the existing `features` becomes the same fixed match but called `select`, and we allow a single margin argument?

Other option would be `
```r
[.dfm(i, j, pad = FALSE) 
```
where if `pad = TRUE` it adds document elements not present. This is more technical but I see this feature of matching documents as unlikely to be used except by the most technical users anyway.

For creating an equivalent for `tokens_subset()`, do we really need that functionality? If we did, the index operator solution would work nicely since it operates only on documents and not the tokens contents (which is `[[`).

I'll leave the fix for #1481 unfinished until we resolve these questions.

**Comment by koheiw** [comment]
Please have a look at `dev-corpus2` in which I rewrote all the subsetting functions.
