### ISSUE TITLE
Could make example object names more consistent

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#1569]
This is mostly cosmetic, but as we expand tutorials, blog posts, writings, etc it would make sense to adopt a consistent naming scheme for example objects, for our core object classes. 

Right now we use a variety of conventions across the examples and tutorials, such as `mydfm`, `dfm1`, `mt`, etc. We should recommend one consistent example name and change the existing code to match.

**Comment by koheiw** [comment]
I have been thinking about it too. I prefer `corp`, `toks`, `mt`. There are many `mt1`, `mt2`, `mt3` or `mt_pres`, `mt_inaug`. We should not use the same name as the function for objects (i.e. `dfm`).

**Comment by kbenoit** [comment]
Just curious, what does "mt" signify? "matrix"?

**Comment by koheiw** [comment]
Exactly, I used name a DFM object `mx` but it looks like max (or Mexico).

**Comment by stefan-mueller** [comment]
Good idea. I can update the **quanteda** documentation next week in combination with #1561. 

Just to summarise how we could rename output of the following objects:
-  `chars`: characters
- `corp`: corpus
- `toks`: tokens
- `mt`: dfm
- `tmodel`: textmodel
- `tstat`: textstat
- (`tplot`: textplot)

Do you agree or prefer different naming conventions? And what about `kwic()`?
If we have more than one of the objects above, I would add numbers: `corp1`, `corp2`, etc. 
Once we agree on the object names, I will add the list to the [style guide](https://github.com/quanteda/quanteda/wiki/Style-guide).

**Comment by kbenoit** [comment]
How about:
- `corp`: corpus
- `toks`: tokens
- ~~`mt`~~  `dfmat` and `fcmat`: dfm and fcm
- ~~`tmodel`~~ `tmod`: textmodel
- `tstat`: textstat
- (`tplot`: textplot)
- `dict`: dictionary
- `kw`: kwic
- `coll`: collocations

**Comment by koheiw** [comment]
`mat` for matrix is acceptable, but I don't think we should always use `dmat` because matrices are 90% of time a DFM. We should distinguish them only when DFMs (`dmat`) and FCMs (`fmat`) appear in the same code. I think KWIC can just `kw`. Should a list be `lis`?

**Comment by stefan-mueller** [comment]
I summarised the discussions (here and in #1561) and updated the [style guide](https://github.com/quanteda/quanteda/wiki/Style-guide). Please have a look and make changes if necessary. I will update the documentation accordingly next week.

**Comment by kbenoit** [comment]
@koheiw are you ok with `dfmat`, `fcmat`, and `mat` then? 

@stefan-mueller we can start using these for tests but no real need to change the test code, just the examples and vignettes. And keep in mind that in some vignettes, like the Jockers and Imai replications, we are often purposefully using their (unfortunate) object names, so we would not want to overwrite those.

**Comment by koheiw** [comment]
`data.frame` would be `dat`.

**Comment by koheiw** [comment]
I also propose change to [Google's R Style Guide](https://google.github.io/styleguide/Rguide.xml). I have no plan (or psychological capacity) to follow **tidyverse** style.

**Comment by kbenoit** [comment]
The two style guides are almost entirely in agreement, and the tidyverse guide is more complete. Some things in the Google guide, furthermore, we clearly reject, e.g. 

> Objects and Methods: avoid S4 objects and methods when possible; never mix S3 and S4

or

> `variable.name` is preferred, `variableName` is accepted 

And we clearly use the tidyverse function documentation guidelines, which are much newer than the older Google suggestions, which apparently were pre-roxygen. (And our roxygen headers are all pre-Markdown support, unfortunately - markdown Rd would be much simpler to read and write.)

@koheiw to what parts of the tidyverse style guide do you object? We are pretty much following it already! I think our best course is our current one: recommend the tidyverse style guide but then list our local preferred exceptions or additions.

**Comment by kbenoit** [comment]
On `return()`, I'm agnostic. I'm all for consistency and clarity, but in some cases, adding to the endf of short functions seems to increase verbosity without any gains. For instance in https://github.com/quanteda/quanteda/blob/master/R/nfunctions.R, it looks like only the very last one uses `return()`. Would any of the other short functions be better with explicit returns? I think it's easier to read and understand them without the `return()`. And surely we are not proposing that a one-line S3 generic should be (e.g.):
```r
ndoc <- function(x) {
    return(UseMethod("ndoc"))
}
```

There's a big debate about this here: https://stackoverflow.com/questions/11738823/explicitly-calling-return-in-a-function-or-not. Maybe we could say: use `return()` at the end if there are other `return()`s in the function or if you wish to and think it improves clarity. I'm not fussed either way but do think that for short functions it's actually more clear and more consistent with R's functional approach and style to omit them.

On pipes, you mean in code, right, not in examples? I don't think we use it much in code. In examples, it works pretty nicely in https://quanteda.io/articles/pkgdown/examples/japanese_speech_ja.html for instance. 😄

**Comment by koheiw** [comment]
Done

**Comment by koheiw** [comment]
Will we really allow `dictlg` prefix without underscore? It should be `dict_lg` in my view.
>  generally without underscores, e.g. dictlg, dfmat1

**Comment by kbenoit** [comment]
We could state that if a specifier is alpha, then after the name of our generic example object it should be preceded by an underscore. But I thought we could try to avoid that since underscores have such a significant meaning in the **quanteda** function naming grammar.

**Comment by stefan-mueller** [comment]
I agree with @kbenoit that we should try to avoid underscores (although it is more readable). Otherwise, users might mix up object names with the **quanteda** function naming grammar.

**Comment by kbenoit** [comment]
Better to provide specific examples, but I agree that being more specifically descriptive in the vignettes is the better approach. Our goal for the examples is consistency, but our main goal for the vignettes is clarity in terms of the example's lesson.

**Comment by stefan-mueller** [comment]
Following up on the vignettes, I was thinking about using with the name of the object type (according to our conventions described in the [wiki](https://github.com/quanteda/quanteda/wiki/Style-guide)) and adding a short descriptive term, separated by an underscore (`corp_pres`; `dfmat_weighted`). 

The question is whether we allow two or more underscores or limit it to one (`corp_pres_since_1980` or `corp_pressince1980`)?

**Comment by kbenoit** [comment]
I don't think it's vital to be as consistent with the vignettes as it is with the examples, and that clarity is more important. Either one is fine but in this case, I'd suggest the second (with the single underscore). But I could live with either.
