### ISSUE TITLE
Is there an easy way to access docvars?

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda#1576]
In v2.0, I want to make docvars more accessible to enhance user experience.

In the branch, there are only two ways to extract a docvar, say `year`:
```r
docvars(corp, "year")
docvars(corp)$year
```
but I often find it is tedious to type docvars many times, so, for eample,
```r
corp$year
```
would be much better if we can define `$.corpus` separately from `[[]].corpus`.

**Comment by kbenoit** [comment]
Totally agree that it's awkward at the moment to access docvars. And right now, the `$` gives too easy access to the list elements of our existing list-based corpus (although our own functions rely on this too). So what you propose sounds like a good solution. 

Is there a way to define double operators such as `$$.corpus()`?

In general this points to the need for strict encapsulation, in our own code but also probably in a new wiki/guide for "Using quanteda in your own package". The more people dig into our object internals the more headaches we will face with CRAN, if we are trying to improve our object structures (as we are!!).

**Comment by koheiw** [comment]
We can use`[].corpus` for corpus subsetting and `[[]].corpus` (and `$.corpus`) for docvars access because users should extract elements of corpus (character vector) using `texts()`.

**Comment by koheiw** [comment]
It also seems possible to overwite `$` operator keeping `[]`:
```r
> `$.list2` <- function(x, value) {
+     return(123)
+ }
> 
> lis <- list("aaa" = 999, "bbb" = 888)
> class(lis) <- "list2"
> lis$aaa
[1] 123
> lis["aaa"]
$aaa
[1] 999

> lis["bbb"]
$bbb
[1] 888
```

**Comment by koheiw** [comment]
```r
> corp <- data_corpus_irishbudget2010
> toks <- tokens(corp, include_docvars = TRUE)
> dfmat <- dfm(toks)
> corp$party
 [1] "FF"    "FG"    "LAB"   "SF"    "FF"    "FG"    "FG"    "LAB"   "LAB"   "LAB"   "Green" "Green" "Green" "SF"   
> toks$party
[1] "party"
 [1] "FF"    "FG"    "LAB"   "SF"    "FF"    "FG"    "FG"    "LAB"   "LAB"   "LAB"   "Green" "Green" "Green" "SF"   
> dfmat$party
 [1] "FF"    "FG"    "LAB"   "SF"    "FF"    "FG"    "FG"    "LAB"   "LAB"   "LAB"   "Green" "Green" "Green" "SF"   
```

**Comment by kbenoit** [comment]
That looks good to me. Individual list elements in a `tokens` object can still be accessed with `[`.

**Comment by koheiw** [comment]
The result looks good but RStudio's code completion pop up shows names of documents as I type `tok$`. Not very user friendly... Overwriting `names()` might fix this but it is a wild solution. Any idea?

**Comment by kbenoit** [comment]
Good question to put to the Slack rOpenSci channel.
