### ISSUE TITLE
Revise headings and subheadings for function reference on pkgdown page

### ISSUE THREAD

**Issue by stefan-mueller** [quanteda/quanteda#1580]
1. The [subheading for`textmodel()` functions](https://quanteda.io/reference/index.html#section-text-plot-functions) on the **pkdown** page is "_Plot functions_ for fitting analytic models from text matrixes." We need to change it to something like "Fitting analytic models from text matrixes"?
2. The headings do not follow the same pattern (some headings have the first character of all words in uppercase, some don't). I'd say we follow the prevailing pattern and only use uppercase for the first letter of the first word?

**Comment by kbenoit** [comment]
Yes on (1)

On (2) we already do that, from all of the headers I can see. The only title case function titles belong that way, such as Lexicoder Sentiment Dictionary and Latent Semantic Analysis.

**Comment by stefan-mueller** [comment]
On (2): 
- The headings "Text Model Functions" and "Text Statistics" need to be adjusted. 
- Moreover, we should change the [order on the reference page](https://quanteda.io/reference/index.html#section-text-plot-functions) and put 
"Text model functions" before "Text plot functions". Users first need to run a text model before they can create a text plot.
