### ISSUE TITLE
dev-corpus2 breaks LexisNexisTools

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#1585]
From revdepcheck:

# LexisNexisTools

Version: 0.2.2

## Newly broken

*   checking tests ...
    ```
     ERROR
    Running the tests in ‘tests/testthat.R’ failed.
    Last 13 lines of output:
      	...processing date 2010-01-09: 0 duplicates found [0.025 secs]. 		
      	...processing date 2010-01-10: 0 duplicates found [0.041 secs]. 		
      	...processing date 2010-01-11: 9 duplicates found [1.89 secs]. 		
      Threshold = 0.99; 4 days processed; 4 duplicates found; in 1.89 secsChecking similiarity for 10 articles over 3 dates...
      	...quanteda dfm construced for similarity comparison [0.027 secs].
      	...processing date 2010-01-08: 0 duplicates found [0.027 secs]. 		
      	...processing date 2010-01-10: 0 duplicates found [0.043 secs]. 		
      	...processing date 2010-01-11: 9 duplicates found [1.86 secs]. 		
      Threshold = 0.99; 3 days processed; 4 duplicates found; in 1.86 secsCreating LNToutput from input 1 files...
      ══ testthat results  ════════════════════════════════════════════════════════════════════════════════════
      OK: 48 SKIPPED: 0 FAILED: 1
      1. Error: Convert LNToutput to quanteda (@test-lnt_convert.R#19) 
      
      Error: testthat unit tests failed
      Execution halted
    ```

**Comment by kbenoit** [comment]
It's because of `metacorpus()`:

https://github.com/JBGruber/LexisNexisTools/blob/master/R/LexisNexisTools.R#L1333-L1336

**Comment by kbenoit** [comment]
This test fails from `test-lnt_convert.R#19`:
```r
test_that("Convert LNToutput to quanteda", {
  expect_equal({
    corpus <- lnt_convert(x = readRDS("../files/LNToutput.RDS"),
                          to = "quanteda", what = "Articles", collapse = FALSE)
    quanteda::metacorpus(corpus, "created") <- "Wed Jul 25 19:33:20 2018"
    quanteda::metacorpus(corpus, "source") <-
      "/home/johannes/Documents/Github/LexisNexisTools/tests/testthat/* on x86_64 by johannes"
    corpus
  }, readRDS("../files/quanteda.RDS"))
})
```

**Comment by JBGruber** [comment]
Recently stumbled across this issue. I installed the dev version and checked the problem (`dev-v2` to be precise). My test compares a corpus converted from my own S4 class to a corpus saved in an `.RDS` file. Since the new corpus class seems to be quite different from the old one, I need to change the test before the next quanteda version. Probably with a different outcome depeding on the installed quanteda version. 

I will skip the test entirely for now for `packageVersion("quanteda") > "1.4.89"`. The next version of `LexisNexisTools` will be on CRAN in a couple of weeks.

**Comment by kbenoit** [comment]
Thanks @JBGruber. Your current master branch is passing in our `dev-v2` and should be fine going forward, if you change that test. If we break anything new we will try to fix it. 😄
