### ISSUE TITLE
Deprecate $ for tokens

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda#1590]
In preparation for v2.0, we will deprecate `[[]]` and `$` operators for tokens

**Comment by kbenoit** [comment]
More specifically:
* deprecate `[[.corpus` 
* deprecate `$.tokens` with a warning that its behaviour will soon change to returning docvars, not behaving the same as `[[.tokens`, which we want to keep.

Have we considered that using `$` for docvars will mean we cannot index more than one docvar, e.g. what is now possible using:
```r
> data_corpus_irishbudget2010[[c("foren", "name")]]
                               foren     name
Lenihan, Brian (FF)            Brian  Lenihan
Bruton, Richard (FG)         Richard   Bruton
Burton, Joan (LAB)              Joan   Burton
Morgan, Arthur (SF)           Arthur   Morgan
Cowen, Brian (FF)              Brian    Cowen
Kenny, Enda (FG)                Enda    Kenny
ODonnell, Kieran (FG)         Kieran ODonnell
Gilmore, Eamon (LAB)           Eamon  Gilmore
Higgins, Michael (LAB)       Michael  Higgins
Quinn, Ruairi (LAB)           Ruairi    Quinn
Gormley, John (Green)           John  Gormley
Ryan, Eamon (Green)            Eamon     Ryan
Cuffe, Ciaran (Green)         Ciaran    Cuffe
OCaolain, Caoimhghin (SF) Caoimhghin OCaolain
```

**Comment by koheiw** [comment]
I noticed that `str()` calls `[[]]` and produces the deprecation message. We might need define `str.tokens()`.  
```r
> toks <- tokens(c(d1 = "one two three", d2 = "four five six", d3 = "seven eight"))
> toks[c(1,3)]
tokens from 2 documents.
d1 :
[1] "one"   "two"   "three"

d3 :
[1] "seven" "eight"

> str(toks)
List of 3
 $ d1: chr [1:3] "one" "two" "three"
 $ d2: chr [1:3] "four" "five" "six"
 $ d3: chr [1:2] "seven" "eight"
 - attr(*, "types")= chr [1:8] "one" "two" "three" "four" ...
 - attr(*, "padding")= logi FALSE
 - attr(*, "class")= chr "tokens"
 - attr(*, "what")= chr "word"
 - attr(*, "ngrams")= int 1
 - attr(*, "skip")= int 0
 - attr(*, "concatenator")= chr "_"
 - attr(*, "docvars")='data.frame':	3 obs. of  0 variables
There were 14 warnings (use warnings() to see them)
```

**Comment by kbenoit** [comment]
All the more reason to leave the tokens operators alone until we consider this more carefully. In fact this is getting too complicated for 1.4 so probably needs more consideration.

**Comment by koheiw** [comment]
Why do we need `[[]]` for tokens (apart from  `str()`)?

**Comment by kbenoit** [comment]
How else would we get tokens from a specific document? I prefer letting it behave like a list.

**Comment by koheiw** [comment]
`as.list(toks[10])` but why do people want to extract a document? We can keep that if you want but I have never used that operator...

**Comment by koheiw** [comment]
Let's deprecate only `$.tokens` now.

**Comment by kbenoit** [comment]
I think it should be:
* `corpus`: a special `character` for which `[` returns the text for a given index, by number or name. `[[.` should not work for a corpus or it should work in the same way that it works for a `character`, which is basically the same as `[`. 
* `tokens`: a special `list` for which `[` and `[[` also work as for a list
* `dictionary2`: a special `list` for which `[` and `[[` also work as for a list
* `dfm`: a special matrix for which `[i,j]` works as for a matrix

Additionally we are proposing that `$` for `corpus`, `tokens`, and `dfm` will work to extract single named docvars, as a vector. Fancier indexing (by number(s) or multiple names) will need to use `docvars()`.

**Comment by kbenoit** [comment]
Does deprecating `$tokens` mess up `str()`?
