### ISSUE TITLE
Might need to change JSTOR URLs

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#1593]
From the submission of v1.4 to CRAN:

```
Check: CRAN incoming feasibility, Result: NOTE
 Maintainer: âKenneth Benoit <kbenoit@lse.ac.uk>â

 Found the following (possibly) invalid URLs:
   URL: https://www.jstor.org/stable/1433978
     From: man/textstat_readability.Rd
     Status: 403
     Message: Forbidden
   URL: https://www.jstor.org/stable/40031755
     From: man/textstat_readability.Rd
     Status: 403
     Message: Forbidden
   URL: https://www.jstor.org/stable/998915
     From: man/textstat_readability.Rd
     Status: 403
     Message: Forbidden
   URL: https://www.jstor.org/stable/pdf/1473669
     From: man/textstat_readability.Rd
     Status: 403
     Message: Forbidden
   URL: https://www.jstor.org/stable/pdf/41384251
     From: man/textstat_readability.Rd
     Status: 403
     Message: Forbidden
   URL: https://www.jstor.org/stable/pdf/747086.pdf
     From: man/textstat_readability.Rd
     Status: 403
     Message: Forbidden
```

I am not sure which of https://cran.r-project.org/web/packages/URL_checks.html apply in our case but we should investigate.

**Comment by jiongweilua** [comment]
Hi @kbenoit , I just went to test all the links and the only one that is indeed broken is the last one:

```
URL: https://www.jstor.org/stable/pdf/747086.pdf
     From: man/textstat_readability.Rd
     Status: 403
     Message: Forbidden
```

There is an extra **".pdf"** behind. This corresponds to the reference for **Klare, G.R.(1975)**.  The rest are fine. This was due to my negligence. Should I issue a PR to fix this?

**Comment by kbenoit** [comment]
Yes please do.

On the rest, it’s not an issue with us, apparently. I received this reply from Uwe Ligges:

> Keep it for now:
> The problem is that jstor blocks too many read requests, and CRAN check srvers send thousands of requests a day during package checks, hence our servers are typcally blacklisted at jstor. So this part is not a problem in your package.
