### ISSUE TITLE
update help on `tokens_compound`?

### ISSUE THREAD

**Issue by conjugateprior** [quanteda/quanteda#1607]
## Describe the bug

Help page for `tokens_compound` says `pattern` arg can be "a character vector, list of character vectors, dictionary, collocations, or dfm." but character vectors don't seem to work.

## Reproducible code

Please paste minimal code that reproduces the bug. If possible, please upload the data file as `.rds`.
```r
tokens_compound(tokens("United States of America"), pattern = list(c("united", "states", "of", "america"))) # compounds
tokens_compound(tokens("United States of America"), pattern = c("united", "states", "of", "america")) # doesn't compound
```

## Expected behavior

Both cases compound to `"United_States_of_America"`

## System information

Please run `sessionInfo()` and paste the output.
```
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS  10.14.3

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rvest_0.3.2    xml2_1.2.0     quanteda_1.3.4

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.18       bindr_0.1.1        pillar_1.3.0       compiler_3.5.1    
 [5] plyr_1.8.4         stopwords_0.9.0    tools_3.5.1        digest_0.6.16     
 [9] lubridate_1.7.4    evaluate_0.11      tibble_1.4.2       gtable_0.2.0      
[13] lattice_0.20-35    pkgconfig_2.0.2    rlang_0.2.2.9000   fastmatch_1.1-0   
[17] Matrix_1.2-14      rstudioapi_0.7     curl_3.2           yaml_2.2.0        
[21] bindrcpp_0.2.2     httr_1.3.1         stringr_1.3.1      dplyr_0.7.6       
[25] knitr_1.20         hms_0.4.2          tidyselect_0.2.4   rprojroot_1.3-2   
[29] grid_3.5.1         glue_1.3.0         data.table_1.11.4  R6_2.2.2          
[33] rmarkdown_1.10     selectr_0.4-1      spacyr_0.9.91      purrr_0.2.5       
[37] readr_1.1.1        ggplot2_3.0.0      magrittr_1.5       backports_1.1.2   
[41] scales_1.0.0       htmltools_0.3.6    assertthat_0.2.0   colorspace_1.3-2  
[45] stringi_1.2.4      RcppParallel_4.4.1 lazyeval_0.2.1     munsell_0.5.0     
[49] crayon_1.3.4   
```

## Additional info

Probably just the help page needs adjusting. I don't think there's anything particularly wrong with not working with character vectors, but perhaps you intended it to.

**Comment by kbenoit** [comment]
Can't see the version of **quanteda** you are using. (Check out `reprex::reprex()`!) But dfm is not part of `pattern` any more. Anyway, the reason the character vector does not work is by design. Each element is something that would be compounded, and unless the separate `character` elements are elements of a list, we don't assume that they are parts of the compound sequence.

So these are all equivalent:
``` r
library("quanteda", warn.conflicts = FALSE)
## Package version: 1.4.1
## Parallel computing: 2 of 12 threads used.
## See https://quanteda.io for tutorials and examples.
toks <- tokens("United States of America")

tokens_compound(toks, phrase(c("united states of america")))
## tokens from 1 document.
## text1 :
## [1] "United_States_of_America"
tokens_compound(toks, list(c("united", "states", "of", "america")))
## tokens from 1 document.
## text1 :
## [1] "United_States_of_America"
tokens_compound(toks, dictionary(list(USA = c("united states of america"))))
## tokens from 1 document.
## text1 :
## [1] "United_States_of_America"
tokens_compound(toks, textstat_collocations(toks, size = 4, min_count = 1, tolower = FALSE))
## tokens from 1 document.
## text1 :
## [1] "United_States_of_America"
```

However this is a bug! The `case_insensitive = TRUE` default in `tokens_compound()` should mean that this will be compounded even when `textstat_collocations()` lowercases it. I will open an issue.
```
tokens_compound(toks, textstat_collocations(toks, size = 4, min_count = 1, tolower = TRUE))
## tokens from 1 document.
## text1 :
## [1] "United"  "States"  "of"      "America"
```

And we should also add a clarifying note about your question to the man page for `textstat_collocations()`, plus add an example where `pattern` is a `character`.

**Comment by conjugateprior** [comment]
Re my quanteda version: you asked for `sessionInfo()` in the bug report, so that's where you got it! 

It was 7 months old, so I updated to 1.4.0, reproduced the behavior above, and confirmed the man page still says you can use a character vector. 

So it seems to me that just having the help page be a bit clearer about what sort of character vector is allowed - "a character vector of length one" maybe, or perhaps specifying that it ought to be a `phrase` - would suffice for this particular issue.

**Comment by kbenoit** [comment]
Sorry you are right, I missed that! Noted on the manual, we will try to clarify.

(But **reprex** is still awesome.)
