### ISSUE TITLE
tokens_compound(x, case_insensitive = TRUE) not working when pattern is collocations

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#1608]
Discovered in #1607. Case matters with this setting, when it should not.

``` r
library("quanteda", warn.conflicts = FALSE)
## Package version: 1.4.1
## Parallel computing: 2 of 12 threads used.
## See https://quanteda.io for tutorials and examples.

toks <- tokens("United States")

tokens_compound(toks,
  pattern = textstat_collocations(toks, min_count = 1, tolower = FALSE),
  case_insensitive = TRUE
)
## tokens from 1 document.
## text1 :
## [1] "United_States"
tokens_compound(toks,
  pattern = textstat_collocations(toks, min_count = 1, tolower = TRUE),
  case_insensitive = TRUE
)
## tokens from 1 document.
## text1 :
## [1] "United" "States"
```

**Comment by koheiw** [comment]
Wen `pattern` is collocations, `tokens_compound()` works case-sensitive exact match. It is only to make conversion from characters to token IDs fast. It is not a bug at least. This is a general performance issue of `pattern2id()`.

**Comment by kbenoit** [comment]
Nonetheless, the behaviour is inconsistent with the other pattern types. Is this something to be found in other functions that take a collocations input as `pattern`?

It should be easy to implement `case_insensitive = TRUE` for this situation: just lowercase both the pattern values and the tokens to be matched. Can you implement that?

**Comment by koheiw** [comment]
This is the performance difference in a small corpus.
```
> corp <- data_corpus_inaugural
> toks <- tokens(corp)
> cols <- textstat_collocations(toks, size = 2, min_count = 2, tolower = FALSE)
> 
> microbenchmark::microbenchmark(
+     cs = tokens_compound(toks, cols), # case-sensitive
+     ci = tokens_compound(toks, phrase(cols$collocation)) # case-insensitive
+ )
Unit: milliseconds
 expr      min        lq      mean    median        uq       max neval
   cs 277.4033  300.9415  332.8363  316.7841  342.7075  572.9524   100
   ci 913.7380 1003.4549 1103.6370 1051.4882 1160.5316 1742.4227   100
```
I will think if there is anything that I can do but this is not an easy problem to solve.

**Comment by koheiw** [comment]
Possible change for the sake of consistency is to use the slow routine for `case-insensitive = TRUE`. No body would find how to make it faster...
