### ISSUE TITLE
Make sure units attribute is being set correctly

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#1612]
tokens_chunk(), corpus_reshape(), corpus_segment()

**Comment by koheiw** [comment]
There are multiple functions to copy attributes.

- `set_dfm_slots()`
- `set_fcm_slots()`
- `slots()`

We have to redeign/reorganize them.

**Comment by kbenoit** [comment]
Will the solution here solve the breaking tests in PR https://github.com/quanteda/quanteda/pull/1793? Those failures are caused by attributes not being robustly copied.

**Comment by koheiw** [comment]
It might, becasue it makes `as.dfm()` more robust.
https://github.com/quanteda/quanteda/blob/981ec34294773c751ea353a920d81b29eeec6198/R/dfm-methods.R#L74-L79
