### ISSUE TITLE
[.corpus needs handling for repeated indexes

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#1625]
Repeating an index for a corpus leads to duplicate documents, which will need special handling under the new rules for disallowing duplicated document names.

``` r
library("quanteda")
## Package version: 1.4.9000
## Parallel computing: 2 of 12 threads used.
## See https://quanteda.io for tutorials and examples.
## 
## Attaching package: 'quanteda'
## The following object is masked from 'package:utils':
## 
##     View

corp <- corpus(c(d1 = "x y z", d2 = "a b b"),
  docvars = data.frame(dv = 1:2)
)
corp[c(2, 2)]
## Corpus consisting of 2 documents and 1 docvar.
```

**Comment by kbenoit** [comment]
For v2, we are talking about indexing a corpus via `[` that will retrieve the document and its docvars and the metadata. So what will we do with the repeated indexing, while still keeping docname unique?

I propose we move this to v2 essentials.

**Comment by koheiw** [comment]
Do we want to make docnames of tokens objects unique? I think it is nice to do so for the sake of consistency.

**Comment by koheiw** [comment]
I killed element names but looks strange in the Environment pane (11, 12, 13, ...). Is there a way to customize how objects appear?

![Screenshot_20191215_081845](https://user-images.githubusercontent.com/6572963/70859435-b7665c80-1f13-11ea-9d2f-a018d259ca21.png)

**Comment by kbenoit** [comment]
I don't know about the appearance question in the Environment pane.

For a constraint, I think we should make document names unique for all objects. We allow duplicated feature names but that is because this is how we combine them. I think we can enforce uniqueness on document names however.

**Comment by koheiw** [comment]
I agree that docnames should be unique in all object types. Here is the function for that
https://github.com/quanteda/quanteda/blob/12420b9cb8806d1bc24ad837eb30827bcef2afb3/R/docvars.R#L133-L143
If we need element names makes appearance in R Studio nice, let's keep them.
