### ISSUE TITLE
Hi, I'm using version 1.4 and get this error :  could not find function "as.tokenizedTexts", please help, thank you.

### ISSUE THREAD

**Issue by takje** [quanteda/quanteda#1631]
## Consider StackOverflow

If you have a question on how to use **quanteda**, please first search [our StackOverflow channel](https://stackoverflow.com/questions/tagged/quanteda). If it does not solve you problem, please post your question there. We monitor the channel and should respond to your question very quickly. 

## Report a bug

If you know how to use **quanteda** but not seeing what you expect, please check [existing issues](https://github.com/quanteda/quanteda/issues?utf8=%E2%9C%93&q=is%3Aissue). If it does not help, please [open an issue](https://github.com/quanteda/quanteda/issues/new?template=bug_report.md).

## Other questions

Please write your questions here.

**Comment by kbenoit** [comment]
That's because that function does not exist in the package. These were removed in v1.0. (See https://github.com/quanteda/quanteda/blob/master/NEWS.md#behaviour-changes-6). 

Use `as.tokens()` instead.
