### ISSUE TITLE
Adjust quick start guides and vignettes at https://quanteda.io according to quanteda style guide

### ISSUE THREAD

**Issue by stefan-mueller** [quanteda/quanteda#1637]
While we have adjusted the package documentation and https://tutorials.quanteda.io based on the updated the **quanteda** style guide (see #1569), the vignettes and quick start guides at https://quanteda.io – the place that most new users probably consult when getting to know the package, are still not very systematic. I will take care of this. It entails:
1. Updating the example object names according to the [style guide](https://github.com/quanteda/quanteda/wiki/Style-guide) (but making them more informative than in the examples by choosing names such as `corp_inaug` rather than `corp1`).
2. Specifying all argument names (see #1510).
3. Using one consistent **ggplot2** plotting scheme (possibly `theme_minimal()`) which we set globally for each article through `theme_set(theme_minimal())`.
4. Going through the explanations and making sure that they still correspond to the behaviour of the latest **quanteda** release.
5. _Not_ changing any of the object names in the replication vignettes (but still specifying the argument names in **quanteda** functions). 

Anything else, @kbenoit?

**Comment by kbenoit** [comment]
That sounds good.  Perhaps we should start with the English vignette and also consider whether we want to add or update anything given recent developments or practice.

**Comment by stefan-mueller** [comment]
Ok, I will start with the English quick start vignette and make suggestions if we could change or add functions. From what I see now, we could certainly add a small subsection on compounding tokens and maybe `textstat_collocations()`, since handling multi-word expressions is one of **quanteda**'s major strengths. 

I'll open a new branch and let you know when you can review my proposed changes to the quick start vignette.
