### ISSUE TITLE
add corpus_sort() or an option for controlling grouping order

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#1638]
## Requested feature

What if we want to reshape a set of documents into single "document" but sorted, say by chronological order, and these were never reshaped into smaller documents in the first place?

For instance, what if I had a set of speeches across times, and wanted to plot usages of a term across time for all speeches as a single "document", so that I I could plot a lexical diversity graph for all speeches as a "document", by date?

We would need a way to "group" or reshape the documents into a larger document, while controlling the order. This could be done either with a `corpus_sort()` and then have the grouping documents use that order - which is how for  instance `texts(x, groups = "something")`, by using the existing ordering - or by adding an argument for sort order.

**Comment by koheiw** [comment]
I you used `dfm_group()` with factor properly ordered levels, you can do it. I make DFMs where documents group of all news published on the same day in this manner.

**Comment by kbenoit** [comment]
True but if we wanted a lexical diversity plot, we'd have to group texts in order and then tokenize them.

**Comment by koheiw** [comment]
Then, how about using `tokens_group()`? Do you want `corpus_group()`? I think better to compute things on dfms or tokens if possible.

**Comment by kbenoit** [comment]
Closed because this already works via indexing (`[`), and is also possible via `quanteda.tidy::arrange()`.
