### ISSUE TITLE
How to efficiently edit output of tagging 

### ISSUE THREAD

**Issue by ManfredBernhard** [quanteda/quanteda#1644]
Dear Quanteda-Users,
As the following workflow shows, spay makes mistakes, i.e. "Hänsel" is tagged as a "proper noun", while "Gretel" is tagged as a regular noun, although both are "personal names". What is the most efficient way to correct this problem, and to tag "Gretel" as a "proper noun?
Best,
ManfredBernhard
Read 24 items
objc[3839]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fffac5b1210) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x1216e2dc8). One of the two will be used. Which one is undefined.
> HG.paste<-paste(HG, collapse="")
> library(quanteda)
Package version: 1.4.1
Parallel computing: 2 of 4 threads used.
See https://quanteda.io for tutorials and examples.

Attache Paket: ‘quanteda’

The following object is masked from ‘package:utils’:

    View

> library(spacyr)
> spacy_initialize(model="de")
Found 'spacy_condaenv'. spacyr will use this environment
successfully initialized (spaCy Version: 2.0.18, language model: de)
(python options: type = "condaenv", value = "spacy_condaenv")
> HG.paste.parsed<-spacy_parse(HG.paste, tag=TRUE, pos=TRUE)
Warnmeldung:
In spacy_parse.character(HG.paste, tag = TRUE, pos = TRUE) :
  lemmatization may not work properly in model 'de'
> head(HG.paste.parsed, 25)
   doc_id sentence_id token_id      token      lemma   pos    tag entity
1   text1           1        1        Vor        Vor   ADP   APPR       
2   text1           1        2      einem      einer   DET    ART       
3   text1           1        3     großen       groß   ADJ   ADJA       
4   text1           1        4      Walde       Wald  NOUN     NN       
5   text1           1        5     wohnte     wohnen  VERB  VVFIN       
6   text1           1        6        ein      einen   DET    ART       
7   text1           1        7      armer        arm   ADJ   ADJA       
8   text1           1        8 Holzhacker Holzhacker  NOUN     NN       
9   text1           1        9        mit        mit   ADP   APPR       
10  text1           1       10     seiner       sich   DET PPOSAT       
11  text1           1       11       Frau       Frau  NOUN     NN       
12  text1           1       12        und        und  CONJ    KON       
13  text1           1       13     seinen     seinen   DET PPOSAT       
14  text1           1       14       zwei       zwei   NUM   CARD       
15  text1           1       15    Kindern       Kind  NOUN     NN       
16  text1           1       16          ;          ; PUNCT     $.       
17  text1           2        1        das        der   DET    ART       
18  text1           2        2    Bübchen    Bübchen  NOUN     NN       
19  text1           2        3       hieß     heißen  VERB  VVFIN       
20  text1           2        4     Hänsel     Hänsel PROPN     NE  PER_B
21  text1           2        5        und        und  CONJ    KON       
22  text1           2        6        das        der   DET    ART       
23  text1           2        7    Mädchen    Mädchen  NOUN     NN  LOC_B
24  text1           2        8     Gretel     Gretel  NOUN     NN  LOC_I
25  text1           2        9          .          . PUNCT     $.       
>

**Comment by kbenoit** [comment]
This is a **spacyr** issue, could you please file it at https://github.com/quanteda/spacyr/issues?

Also we would need a reproducible example, which you can accomplish by pasting into the code a paragraph from the text. And please enclose your code block with backticks (or use the <> icon from the Write toolbar with the text highlighted).

**Comment by ManfredBernhard** [comment]
Dear Kenneth,
thank you very much for trying to help me with my problems. I posted the following message to the github just a minute ago:


R version 3.5.2 (2018-12-20) -- "Eggshell Igloo"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin15.6.0 (64-bit)

R ist freie Software und kommt OHNE JEGLICHE GARANTIE.
Sie sind eingeladen, es unter bestimmten Bedingungen weiter zu verbreiten.
Tippen Sie 'license()' or 'licence()' für Details dazu.

R ist ein Gemeinschaftsprojekt mit vielen Beitragenden.
Tippen Sie 'contributors()' für mehr Information und 'citation()',
um zu erfahren, wie R oder R packages in Publikationen zitiert werden können.

Tippen Sie 'demo()' für einige Demos, 'help()' für on-line Hilfe, oder
'help.start()' für eine HTML Browserschnittstelle zur Hilfe.
Tippen Sie 'q()', um R zu verlassen.

[R.app GUI 1.70 (7612) x86_64-apple-darwin15.6.0]

[Arbeitsbereich wiederhergestellt aus /Users/MBS/.RData]
[Verlauf wiederhergestellt aus /Users/MBS/.Rapp.history]

> S2<-scan(what="c", sep="\n", file=file.choose())
Read 1 item
> S2
[1] "Vor einem großen Walde wohnte ein armer Holzhacker mit seiner Frau und seinen zwei Kindern; das Bübchen hieß Hänsel und das Mädchen Gretel. Er hatte wenig zu beißen und zu brechen, und einmal, als große Teuerung ins Land kam, konnte er das tägliche Brot nicht mehr schaffen."
> library(quanteda)
Package version: 1.4.1
Parallel computing: 2 of 4 threads used.
See https://quanteda.io for tutorials and examples.

Attache Paket: ‘quanteda’

The following object is masked from ‘package:utils’:

    View

> library(spacyr)
> spacy_initialize(model="de")
Found 'spacy_condaenv'. spacyr will use this environment
successfully initialized (spaCy Version: 2.0.18, language model: de)
(python options: type = "condaenv", value = "spacy_condaenv")
> S2.parsed<-spacy_parse(S2, tag=TRUE, pos=TRUE)
Warnmeldung:
In spacy_parse.character(S2, tag = TRUE, pos = TRUE) :
  lemmatization may not work properly in model 'de'
> S2.parsed
   doc_id sentence_id token_id      token      lemma   pos     tag entity
1   text1           1        1        Vor        Vor   ADP    APPR
2   text1           1        2      einem      einer   DET     ART
3   text1           1        3     großen       groß   ADJ    ADJA
4   text1           1        4      Walde       Wald  NOUN      NN
5   text1           1        5     wohnte     wohnen  VERB   VVFIN
6   text1           1        6        ein      einen   DET     ART
7   text1           1        7      armer        arm   ADJ    ADJA
8   text1           1        8 Holzhacker Holzhacker  NOUN      NN
9   text1           1        9        mit        mit   ADP    APPR
10  text1           1       10     seiner       sich   DET  PPOSAT
11  text1           1       11       Frau       Frau  NOUN      NN
12  text1           1       12        und        und  CONJ     KON
13  text1           1       13     seinen     seinen   DET  PPOSAT
14  text1           1       14       zwei       zwei   NUM    CARD
15  text1           1       15    Kindern       Kind  NOUN      NN
16  text1           1       16          ;          ; PUNCT      $.
17  text1           2        1        das        der   DET     ART
18  text1           2        2    Bübchen    Bübchen  NOUN      NN
19  text1           2        3       hieß     heißen  VERB   VVFIN
20  text1           2        4     Hänsel     Hänsel PROPN      NE  PER_B
21  text1           2        5        und        und  CONJ     KON
22  text1           2        6        das        der   DET     ART
23  text1           2        7    Mädchen    Mädchen  NOUN      NN  LOC_B
24  text1           2        8     Gretel     Gretel  NOUN      NN  LOC_I
25  text1           2        9          .          . PUNCT      $.
26  text1           3        1         Er        ich  PRON    PPER
27  text1           3        2      hatte      haben   AUX   VAFIN
28  text1           3        3      wenig      wenig  PRON     PIS
29  text1           3        4         zu         zu  PART   PTKZU
30  text1           3        5     beißen     beißen  VERB   VVINF
31  text1           3        6        und        und  CONJ     KON
32  text1           3        7         zu         zu  PART   PTKZU
33  text1           3        8    brechen    brechen  VERB   VVINF
34  text1           3        9          ,          , PUNCT      $,
35  text1           3       10        und        und  CONJ     KON
36  text1           3       11     einmal     einmal   ADV     ADV
37  text1           3       12          ,          , PUNCT      $,
38  text1           3       13        als        als   ADP    APPR
39  text1           3       14      große       groß   ADJ    ADJA
40  text1           3       15   Teuerung   Teuerung  NOUN      NN
41  text1           3       16        ins        ins   ADP APPRART
42  text1           3       17       Land       Land  NOUN      NN
43  text1           3       18        kam     kommen  VERB   VVFIN
44  text1           3       19          ,          , PUNCT      $,
45  text1           3       20     konnte     können  VERB   VMFIN
46  text1           3       21         er        ich  PRON    PPER
47  text1           3       22        das        der   DET     ART
48  text1           3       23   tägliche   tägliche   ADJ    ADJA
49  text1           3       24       Brot       Brot  NOUN      NN
50  text1           3       25      nicht      nicht  PART  PTKNEG
51  text1           3       26       mehr       mehr   ADV     ADV
52  text1           3       27   schaffen   schaffen  VERB   VVINF
53  text1           3       28          .          . PUNCT      $.
> #### see "Mädel" und "Gretel": both are "NOUN" in the analysis, though "Gretel", just as well as "Hänsel" should be  "PROPN".
> S2.parsed.noun<-with(S2.parsed, subset(token, pos=="NOUN"))
> S2.parsed.noun
 [1] "Walde"      "Holzhacker" "Frau"       "Kindern"    "Bübchen"    "Mädchen"    "Gretel"     "Teuerung"   "Land"       "Brot"
> S2.parsed.proper.noun<-with(S2.parsed, subset(token, pos=="PROPN"))
> S2.parsed.proper.noun
[1] "Hänsel"
> Question: What is the most efficient and economic way to correct this problem either inside or outside R/spacyr. It is clear to me that taggers are not foolproof and that we  therefore need a good strategy to correct the mistakes. Also: Lemmatization has several mistakes, e.g. token: das Mädchen, and lemma "der Mädchen" (=genitive and dative plural).

Best,
Manfred B. Sellner (ret.)
University of Salzburg
Department of Linguistics

Am 11.03.2019 um 01:20 schrieb Kenneth Benoit <notifications@github.com<mailto:notifications@github.com>>:


This is a spacyr issue, could you please file it at https://github.com/quanteda/spacyr/issues?

Also we would need a reproducible example, which you can accomplish by pasting into the code a paragraph from the text. And please enclose your code block with backticks (or use the <> icon from the Write toolbar with the text highlighted).
