### ISSUE TITLE
delete empty rows from corpus

### ISSUE THREAD

**Issue by ktmanis** [quanteda/quanteda#1647]
Hello,

I have created a dfm from a corpus where the dfm has created some empty rows due to the parameters I have set. Is there a way to subset the corpus and remove the empty rows provided by the dfm. The dfm is to be used with the stm package to conduct a topic model with covariates. When attempting to use the findThoughts function in stm, the function requires the number of corpus documents to match the number of documents used in the stm. Hence, I am running into trouble when conducting analysis and plotting visualizations.

**Comment by kbenoit** [comment]
Sure, just use `dfm_subset()` to remove the documents that have no counts, which you can get from `ntoken()`. (`rowSums()` will do the same.)

``` r
library("quanteda")
## Package version: 1.4.1

dfmat <- as.dfm(matrix(c(0, 1, 2, 0, 3, 2, 0, 0, 1, 0, 2, 0), nrow = 3))
dfmat
## Document-feature matrix of: 3 documents, 4 features (50.0% sparse).
## 3 x 4 sparse Matrix of class "dfm"
##        features
## docs    feat1 feat2 feat3 feat4
##   text1     0     0     0     0
##   text2     1     3     0     2
##   text3     2     2     1     0

dfm_subset(dfmat, ntoken(dfmat) > 0)
## Document-feature matrix of: 2 documents, 4 features (25.0% sparse).
## 2 x 4 sparse Matrix of class "dfm"
##        features
## docs    feat1 feat2 feat3 feat4
##   text2     1     3     0     2
##   text3     2     2     1     0
```

**Comment by ktmanis** [comment]
my_corpus <- corpus(test.text.2)
toks<-tokens_remove(toks, sw)
toks <- tokens_tolower(toks)
toks<-tokens(toks, remove_punct =TRUE)
toks<-tokens(toks, remove_ignorable = TRUE)
toks<-tokens(toks, remove_separators =TRUE)
toks<-tokens(toks, remove_symbols =TRUE)
toks <- tokens_compound(toks, pattern = phrase(multiword))
toks <- tokens_wordstem(toks)
tok.1.dfm <- dfm(comp_toks,remove_numbers = TRUE,
              remove_separators = TRUE, tolower = TRUE,
              stem = TRUE, remove = stopwords("english"))
rowTotals <- apply(tok.1.dfm, 1, sum) #Find the sum of words in each Document
my_dfm.new   <- tok.1.dfm[rowTotals> 0, ]           #remove all docs without words
dfm2stm.1 <- convert(my_dfm.new, to = "stm")
model.stm.1 <- stm(dfm2stm.1$documents, dfm2stm.1$vocab, 
                 K = 20, data = dfm2stm.1$meta, init.type = "Spectral")
bio<- (my_corpus$documents$texts)
thoughts1 <- findThoughts(model.stm.1, texts = bio,
                          n = 2, topics = 20)$docs[[1]]
**Error in findThoughts(model.stm.1, texts = corpus, n = 2, topics = 20) : 
  Number of provided texts and number of documents modeled do not match**

**Comment by ktmanis** [comment]
Thank you for your help!

**Comment by ktmanis** [comment]
Still having trouble because the function you provided does this for the dfm but not the corpus. Need the corpus to match the same documents in the subsetted dfm.

**Comment by ktmanis** [comment]
my_corpus <- corpus(test.text.2)
tok.1.dfm <- dfm(comp_toks,remove_numbers = TRUE,
              remove_separators = TRUE, tolower = TRUE,
              stem = TRUE, remove = stopwords("english"))
tok.1.dfm<-dfm_subset(tok.1.dfm, ntoken(tok.1.dfm) > 0)
dfm2stm.1 <- convert(tok.1.dfm, to = "stm")
model.stm.1 <- stm(dfm2stm.1$documents, dfm2stm.1$vocab, 
                 K = 20, data = dfm2stm.1$meta, init.type = "Spectral")
bio<- (my_corpus$documents$texts)
thoughts1 <- findThoughts(model.stm.1, texts = bio,
                          n = 2, topics = 20)$docs[[1]]
Error in findThoughts(model.stm.1, texts = tok.1.dfm, n = 2, topics = 20) : 
  Number of provided texts and number of documents modeled do not match

**Comment by ktmanis** [comment]
Let me know if I need to provide more info.

Thanks,

KT

**Comment by kbenoit** [comment]
Ah I see. You should send the original texts by subsetting the original corpus as below, using `texts()`. You might get away with addressing the corpus internals now, but that will break in upcoming v2 (and we warn against this very clearly in `?corpus`...). 

``` r
library("quanteda")
## Package version: 1.4.1

txt <- c(
  doc1 = "",
  doctwo = "a b b b d d",
  docIII = "a a b b"
)
corp <- corpus(txt)

dfmat <- dfm(txt)
dfmat
## Document-feature matrix of: 3 documents, 3 features (44.4% sparse).
## 3 x 3 sparse Matrix of class "dfm"
##         features
## docs     a b d
##   doc1   0 0 0
##   doctwo 1 3 2
##   docIII 2 2 0

dfmatsub <- dfm_subset(dfmat, ntoken(dfmat) > 0)
dfmatsub
## Document-feature matrix of: 2 documents, 3 features (16.7% sparse).
## 2 x 3 sparse Matrix of class "dfm"
##         features
## docs     a b d
##   doctwo 1 3 2
##   docIII 2 2 0

texts(corp)[docnames(dfmatsub)]
##        doctwo        docIII 
## "a b b b d d"     "a a b b"
```

**Comment by ktmanis** [comment]
Thank you! This was successful.
