### ISSUE TITLE
segment(x, ...) function in 1.4.1 Version

### ISSUE THREAD

**Issue by praveen2812** [quanteda/quanteda#1650]
Hi,
I am new to text analytics, struggling to find **segment(x, ...)**,  function in Quanteda 1.4.1.

Thanks,
Praveen

**Comment by praveen2812** [comment]
https://www.rdocumentation.org/packages/quanteda/versions/0.9.0-1/topics/segment

Missed the reference link in above comments

**Comment by jiongweilua** [comment]
Hi @praveen2812, have you taken a look at `corpus_segment` and `char_segment`? 

https://quanteda.io/reference/corpus_segment.html
