### ISSUE TITLE
"lbg" rescaling in predict.textmodel_wordscores vs. "mv"

### ISSUE THREAD

**Issue by tomogradyucl** [quanteda/quanteda#1652]
## Describe the bug

Please describe what the bug is.
When performing re-scaling after a wordscores model, the "lbg" method also re-scales the reference texts, but the "mv" method does not. See the example below with the Irish budget speeche corpus. I think the behaviour should be made consistent across the two re-scaling methods.
## Reproducible code

Please paste minimal code that reproduces the bug. If possible, please upload the data file as `.rds`.
```r
# paste here #
library(quanteda)

dfm_irish <- dfm(data_corpus_irishbudget2010,
                  tolower=T,
                  remove_numbers=T,
                  remove_punct=T,
                  stem=T,
                  remove = stopwords("en"))

irish.info <- docvars(data_corpus_irishbudget2010)

irish.info$ref <- NA
irish.info$ref[irish.info$name == "Cowen"] <- -1
irish.info$ref[irish.info$name == "Kenny"] <- 1
docvars(dfm_irish) <- irish.info

mod_ws <- textmodel_wordscores(dfm_irish, y = docvars(dfm_irish, "ref"), smooth=1)

pred_ws <- predict(mod_ws, se.fit=TRUE,newdata = dfm_irish)
pred_ws[[1]]

pred_ws_lbg <- predict(mod_ws, se.fit=TRUE,newdata = dfm_irish, rescaling="lbg")
pred_ws_lbg[[1]]

pred_ws_mv <- predict(mod_ws, se.fit=TRUE,newdata = dfm_irish, rescaling="mv")
pred_ws_mv[[1]]

## Expected behavior

Please explain what you expected to happen.
I expected both methods to perform in the same way, but they do not
## System information

Please run `sessionInfo()` and paste the output.
```
# paste here #
```

## Additional info

Please add any other information about the issue.

**Comment by tomogradyucl** [comment]
After chatting to Stefan Mueller, I don't think this is actually a bug per se, but it is an area where the documentation could be improved. I think that the method is just applying the rescaling formula to all rows of 'newdata', regardless of whether the row contains the reference documents or not.

It might be helpful to at least mention that the 'newdata' argument should exclude the reference documents. Alternatively, the function could be re-written so that you declare the reference documents, and then they are ignored in the calculation. It took me a while to figure out what was going on. I could imagine this being very confusing for new users of the method

**Comment by kbenoit** [comment]
That's correct, the rescaling procedure applies to everything in `newdata`. But this occurs for both the LBG and MV re-scaling. Reference texts in MV rescaling will always recover their reference values - that's what the rescaling formula enforces. So they are "re-scaled" but this means keeping their original reference scores. This is all exactly how it should be.

But if you think we could clarify by adding a note to `?predict.textmodel_wordscores`, please let us know what you think this should say.

**Comment by tomogradyucl** [comment]
> That's correct, the rescaling procedure applies to everything in `newdata`. But this occurs for both the LBG and MV re-scaling. Reference texts in MV rescaling will always recover their reference values - that's what the rescaling formula enforces. So they are "re-scaled" but this means keeping their original reference scores. This is all exactly how it should be.
> 
> But if you think we could clarify by adding a note to `?predict.textmodel_wordscores`, please let us know what you think this should say.

Something like "Note: reference documents should be excluded from newdata when using "lbg""?
