### ISSUE TITLE
Separate textmodel() functions into a new package

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#1663]
**quanteda** is becoming very large, and it might be time to modularize the packages into a "quanteda-verse" set of packages that split its functionality. This would operate similar to the **tidyverse** package, which loads all of the packages in the tidyverse, i.e.
```r
> library("tidyverse")
── Attaching packages ─────────────────────────────────────────── tidyverse 1.2.1 ──
✔ ggplot2 3.1.0       ✔ purrr   0.3.2  
✔ tibble  2.1.1       ✔ dplyr   0.8.0.1
✔ tidyr   0.8.3       ✔ stringr 1.4.0  
✔ readr   1.3.1       ✔ forcats 0.4.0  
── Conflicts ────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
```
This would involve:

| package                   | depends on            | function                                                                                             |
|:--------------------------|:----------------------|:-----------------------------------------------------------------------------------------------------|
| **quanteda**              |                       | loads all quanteda packages                                                                          |
| **quanteda.core**         |                       | corpus, tokens, dfm functions, `dictionary()`, `kwic()` -- basically, everything not specified below |
| **quanteda.textmodel**    | **quanteda**          | all `textmodel_*()` functions                                                                        |
| **quanteda.textstat**     | **quanteda**          | all `textstat_*()` functions                                                                         |
| **quanteda.textplot**     | **quanteda**          | all `textplot_*()` functions                                                                         |
| **quanteda.dictionaries** | **quanteda**          | (already exists)                                                                                     |
| **quanteda.stm**          | **quanteda**, **stm** | could reimplement the infrastructure needed for **stm**                                              |

**Advantages**

- size management
- isolation of potential errors and easier maintenance
- easier extensibility, especially for others wishing to build functionality based on **quanteda.core** in their own packages but who do not need all of the stat or plot functions

**Comment by kbenoit** [comment]
Interim/experimental/transitional solution for v2:

- move the `textmodel_*()` functions to a **quanteda.textmodel** package, and move the draft **quanteda.classifiers** package functions into **quanteda.textmodel**.
- quanteda would import **quanteda.textmodel**, and re-export (`stopwords::stopwords`-style or `magrittr::`%?%`-style) all of the `textmodel_*()` functions from **quanteda.textmodel**.
- consider moving `textplot_influence()` and `textplot_scale1d()` to this**quanteda.textmodel**, since these only function with objects created from textmodel functions.

Advantage of this approach is that we separate maintenance and the update cycle for the textmodel package from that of the core package, but users will not notice the difference.

**Comment by kbenoit** [comment]
### Updated suggestion

- move the `textmodel_*()` functions to a **textmodel** package, that provides full functionality for sparse Matrix inputs, not necessarily dfm objects. This would not require **quanteda**.

- add methods for dfm inputs for all textmodel functions in **quanteda**, much as we do for extending **spacyr** objects and methods for **quanteda** objects and methods. So **quanteda** would import **textmodels** but not vice-versa, meaning that textmodels can be useful for people not using **quanteda**.

- Liaise or collaborate with @juliasilge to allow this work well with [tidymodels](https://github.com/tidymodels/tidymodels), which (apparently) is replacing **caret**.

### Functions to move

From **quanteda**
- [ ] `textmodel_nb()`
- [ ] `textmodel_wordscores()`
- [ ] `textmodel_wordfish()`
- [ ] `textmodel_lsa()`
- [ ] `textmodel_ca()`
- [ ] `textmodel_affinity()`
- [ ] `textplot_influence()`
- [ ] `textplot_scale1d()`

** From **quanteda.classifiers**
- [ ] `textmodel_svm()`
- [ ] `textmodel_logisitic()`
- [ ] `textmodel_maxent()`
- [ ] `textmodel_nnseq()`
- [ ] `textmodel_cnnlstm()`

### New package authors

- Copy: KB, KW, HW, WL, SM, ERC 
- Move: PP, BL

**Comment by juliasilge** [comment]
I am fully on board with modularizing the excellent work in **quanteda** so that the text models are separate; I think this would make the models more accessible to a wider variety of folks involved in text analysis and would also help with dependency issues. People can only take on the dependencies that they need.

I am agnostic about whether you make this truly independent of **quanteda**. One option is to only `Suggest` **quanteda**, the way that **tidytext** does, so that the `dfm` methods do live in this new package but people who aren't using **quanteda** don't need to install it to use the package.

I would love to see `tidy` methods for these models live in the modeling package itself and I would be happy to collaborate on this. In general, in the tidymodels/**broom** ecosystem, there is some movement toward tidiers living with the models when possible, except for examples like models from **utils** and **stats** and such.

One resource you might check out as you start work on this is the [**hardhat** package](https://github.com/tidymodels/hardhat), a resource for building modeling packages. Not all of it may apply to our subject area here, but I believe some will and it can help build more composable, extensible models.

**Comment by kbenoit** [comment]
Sounds good! I will check those out. I will probably do a test version of this separate package in the coming weeks.

@juliasilge would the "tidymodels"/**hardhat** approach work with a sparseMatrix? (which is not a tidy/tibble object)

**Comment by juliasilge** [comment]
I'm not sure if the hardhat package is 100% useful to someone who has as much modeling package experience as you do, but it is likely worth a look to at least see the scaffolding that is there for creating "predictable" `predict()` implementations (HA), for building the user-facing modeling function, etc. The hardhat package is set up to support models that take multiple kinds of input (dataframe, matrix, [recipes](https://github.com/tidymodels/recipes), etc) but a good bit of the scaffolding it contains applies to models with only one kind of input (say, a sparse matrix).

You can [check out the vignette](https://cran.r-project.org/web/packages/hardhat/vignettes/package.html) for an overview.

**Comment by kbenoit** [comment]
Sounds good, thanks @juliasilge I will check this out. To not hold up quanteda's v2 progress, and to make development and maintenance of the textmodels easier, we split this for now as still requiring quanteda, with the modularization of the new **quanteda.textmodels** package however making easier the sort of generalization we've been discussing here. 

Baby steps but steps!

**Comment by juliasilge** [comment]
Smaller, iterative changes are usually the way to go IMO!
