### ISSUE TITLE
Check for missing values in dictionaries upon dictionary creation

### ISSUE THREAD

**Issue by jogrue** [quanteda/quanteda#1668]
## Describe the bug

This is somewhere between an issue and a feature request, and a rather minor thing.

I am reading a dictionary from a CSV file (with read_csv). I changed the dictionary and switched from glob to regex. When running tokens_compound I got this error: `Error in vector("list", length(value) + sum(is_multi)) : vector size cannot be NA` The error occured inside the `split_values` function because of the line `vector("list", length(value) + sum(is_multi))`

After doing some debugging, I finally figured it out: It had nothing to do with regular expressions or compounds. The error happens because my dictionary (by mistake) includes a missing value. `read_csv` replaces an empty string with `NA` by default. Other functions (dictionary lookup) also fail with this error.

## Reproducible code

```r
library(quanteda)
dict <- dictionary(list(testdict = c("word", "two words", "", NA)))
text <- c("This is the first document. It includes a word.",
          "This is the second document. It includes two words.")
text <- corpus(text)
tokens <- tokens(text)
tokens <- tokens_compound(x = tokens,
                          pattern = dict) # fails 
tokens <- tokens_lookup(tokens, dict) # fails
dfm <- dfm(tokens)
lookup <- dfm_lookup(dfm, dict) # fails
```

## Expected behavior

I think, it would be a good idea, to provide a clear error message or possibly already an error or a warning when creating the dictionary with `dictionary()`. Hopefully, this would save others some debugging time.

**Comment by koheiw** [comment]
Thanks. Value checking was not working as I intended.
