### ISSUE TITLE
"Replacement has x rows, data has y rows" Error when using liwcalike()

### ISSUE THREAD

**Issue by lin-jennifer** [quanteda/quanteda#1673]
I am trying to run some text data (Extracted from ANES) and was using the liwcalike() command after creating a corpus from the dataset. However, I keep getting the following error:
```{r}
Error in `[[<-.data.frame`(`*tmp*`, "WPS", value = c(16, 26, 6, 6.33333333333333,  : 
  replacement has 5165 rows, data has 5914
```
Here is a snippet of my code
```{r}
library(readtext)
like = readtext("anes12.csv", text_field = c("candlik_likewhatdpc", "candlik_dislwhatdpc", "candlik_likewhatrpc", "candlik_dislwhatrpc", "ptylik_lwhatdp", "ptylik_dwhatdp", "ptylik_lwhatrp", "ptylik_dwhatrp"))
summary(like)

#Create Corpus
require(quanteda)
data_like_dislike = corpus(like)
summary(data_like_dislike, 2)

#Load in the data dictionary package
library(quanteda.dictionaries)

MFD <- liwcalike(data_like_dislike, dictionary = data_dictionary_MFD)

head(MFD)
```
Please advise on how I can correct this error.

Thank you!

**Comment by kbenoit** [comment]
Looks like this belongs here instead: https://github.com/kbenoit/quanteda.dictionaries/issues. Can you add a reproducible example and file the issue there?

Also `readtext::readtext()` should not be able to take a vector for the `text_field` argument - in fact I am surprised that did not raise an error message. Only one field can be identified as the text at a time.
