### ISSUE TITLE
ERROR: dependencies ‘Matrix’, ‘sna’ are not available for package ‘quanteda’

### ISSUE THREAD

**Issue by rll307** [quanteda/quanteda#1676]
Hi

I am trying to install Quanteda in my Linux Ubuntu. As I type:

`install.packages("quanteda")`

The following result pops up:

```
install.packages("quanteda", dependencies = FALSE)
Installing package into ‘/home/rodrigo/R/x86_64-pc-linux-gnu-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/quanteda_1.4.3.tar.gz'
Content type 'application/x-gzip' length 4441490 bytes (4.2 MB)
==================================================
downloaded 4.2 MB

ERROR: dependencies ‘Matrix’, ‘sna’ are not available for package ‘quanteda’
* removing ‘/home/rodrigo/R/x86_64-pc-linux-gnu-library/3.4/quanteda’
Warning in install.packages :
  installation of package ‘quanteda’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpGBZs2S/downloaded_packages’
```

I i try to install them manually, a number of errors also show

How should I proceed. 

thanks

**Comment by kbenoit** [comment]
You should update to a newer R version, e.g. 3.5.x, and try it again. The problem appears to be that you are unable to install the **Matrix** package for whatever reason. It's not a **quanteda** issue but rather something to do with your R installation.
