### ISSUE TITLE
Sublists in text lead to higher readability scores

### ISSUE THREAD

**Issue by zamadxarif** [quanteda/quanteda#1678]
## Consider StackOverflow

If you have a question on how to use **quanteda**, please first search [our StackOverflow channel](https://stackoverflow.com/questions/tagged/quanteda). If it does not solve you problem, please post your question there. We monitor the channel and should respond to your question very quickly. 

## Report a bug

If you know how to use **quanteda** but not seeing what you expect, please check [existing issues](https://github.com/quanteda/quanteda/issues?utf8=%E2%9C%93&q=is%3Aissue). If it does not help, please [open an issue](https://github.com/quanteda/quanteda/issues/new?template=bug_report.md).

## Other questions

Hello Quanteda Team,

I am using the textstat_readability function from the package to get the Flesch Kincaid measure for a piece of text.

My text was originally a table and when it is flattened to be used in R, the output is like this:

"Application and Purpose This chapter applies to the FSCS. When must compensation be paid? The FSCS must pay a claim as soon as reasonably possible after: (1) it is satisfied that the conditions in COMP 3.2.1 R have been met; and (2) it has calculated the amount of compensation due to the claimant;and in any event within three months of that date, unless the FSA has granted the FSCS an extension, in which case payment must be made no later than six months from that date."

The text as it would be viewed would be like the following:

"Application and Purpose
 
This chapter applies to the FSCS. When must compensation be paid? The FSCS must pay a claim as soon as reasonably possible after: 

(1) it is satisfied that the conditions in COMP 3.2.1 R have been met; and 

(2) it has calculated the amount of compensation due to the claimant;and in any event within three months of that date, unless the FSA has granted the FSCS an extension, in which case payment must be made no later than six months from that date."

All sublists are showing much higher flesch-kincaid scores than text without sublists. Is there a way to account for this in this function? Intuitively, I would expect sublists to have lower flesch-kincaid scores.

Please could you clarify.

Many thanks,

Zahid

**Comment by kbenoit** [comment]
I'm not 100% sure what you mean by sublists. Instead of the quashed text, you want the second text to be treated as if the first line e.g. "Application and Purpose" were one sentence, and the "This...after:" a sentence, etc.?

This should be a StackOverflow question. If you describe more what you want and how you have input the texts into R, I'm happy to answer it there. (There are some easy solutions to this problem.)
