### ISSUE TITLE
sentiment analysis

### ISSUE THREAD

**Issue by Tate148** [quanteda/quanteda#1680]
With a 4 column dataframe (t4) in which each cell is a sentence,  I coded the following for sentiment analysis:

```r
totalcorpus<-corpus(t4)
mydict <- dictionary(list(negative = c("detriment*", "bad*", "awful*", "terrible*", "horrible*"),
                          postive = c("good", "great", "super*", "excellent")))

# import a LIWC formatted dictionary from http://www.moralfoundations.org
download.file("https://goo.gl/5gmwXq", tf <- tempfile())
dictliwc <- dictionary(file = tf, format = "LIWC")

sum.totalcorpus <- dfm(totalcorpus, dictionary = mydict)
sum.totalcorpus

liwcdfm <- dfm(totalcorpus, dictionary = dictliwc)
liwcdfm[, 1:10]

The results for sum.totalcorpus should be like this:

## Document-feature matrix of: 7 documents, 2 features (14.3% sparse).
## 7 x 2 sparse Matrix of class "dfm"
##               features
## docs           terror economy
##   1993-Clinton      0       8
##   1997-Clinton      1       8
##   2001-Bush         0       4

# But I get this: 
Document-feature matrix of: 878 documents, 2 features (86.7% sparse).
```

What have I done wrong please?

**Comment by stefan-mueller** [comment]
Without providing your text corpus, it is impossible to reproduce the example. Also, the example above mixes up two corpora and two dictionaries. 

The output of a dictionary applied to a `dfm` has as many features as dictionary categories (if the dictionary is hierarchical, you can use the `levels` argument in `dfm_lookup()` to specify the level of entries applied to the dfm). Since your dictionary has two levels ("negative" and "positive"), the number of features equals 2. 

Your corpus (which you do not provide here) contains 878 documents, therefore your dfm object consists of 878 documents and 2 features. Does this solve your question?

```r
library(quanteda)
#> Package version: 1.4.3
#> Parallel computing: 2 of 12 threads used.
#> See https://quanteda.io for tutorials and examples.
#> 
#> Attaching package: 'quanteda'
#> The following object is masked from 'package:utils':
#> 
#>     View

# create dictionary
dict <- dictionary(list(negative = c("detriment*", "bad*", "awful*", "terrible*"),
                        postive = c("good", "great", "super*", "excellent")))

# number of documents in the corpus
ndoc(data_corpus_inaugural)
#> [1] 58

# transform corpus to dfm and apply dictionary
data_corpus_inaugural %>% 
    dfm() %>%
    dfm_lookup(dictionary = dict)
#> Document-feature matrix of: 58 documents, 2 features (34.5% sparse).
```

**Comment by Tate148** [comment]
Apologies for the unreproducible example. 
The data-frame that the corpus is built on has 4 columns of text, and each row is a respondent's answer to Q1 though Q4:
                       Q1                    Q2                      Q3                        Q4
                     sentence        sentence          sentence             sentence
                     sentence        sentence          sentence             sentence                    
                     sentence        sentence          sentence             sentence

The the object "mydict" has two values, negative and positive. 
I am would like to find a way to count how many of the words in these sentences are positive or negative, and it would be great to be able to find negative and positive counts for each question. F

Finding out which words are the most common positive and negative words (if "thrilling was the most common positive word, for example) would also be great. Possibly I need the tidytext sentiment dictionary too. 

Truly not sure how to reach my objectives and grateful for any advice.

**Comment by kbenoit** [comment]
This is more fitting to a StackOverflow question than an issue. 

A data.frame input to construct a corpus can only have one column of text, and the rest will be treated as "docvars". To put them all into one column, you can use **tidyr** to stack them first. See https://stackoverflow.com/questions/55629899/quanteda-calculate-text-similarity-by-row-between-two-dfms?noredirect=1#comment97952697_55629899 for a relevant example (ignore the similarity part).

**Comment by Tate148** [comment]
Ok great, thank you for clearing that up kbenoit. When learning to code, it is hard that few people show the first lines of the dataframe or whatever so you can see what the data format should look like at the different steps.
