### ISSUE TITLE
Unstable behaviour in textstat_simil()

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#1689]
In rare cases, that cannot be reproduced by setting the seed, but can be discovered by re-running the code below, some values are different.

``` r
library("quanteda")
# matrix for testing
mt <- dfm(corpus_subset(data_corpus_inaugural, Year > 1980))
mt <- dfm_trim(mt, min_termfreq = 10)
res <- textstat_simil(mt, c(2, 4), margin = "documents")

set.seed(10)
resv <- list()
for (i in 1:1000) {
  resv[[i]] <- textstat_simil(mt, c(2, 4), margin = "documents")$similarity
}
rescols <- do.call(cbind, resv)

plot(rescols[12, ], type = "b", ylim = c(.8, 1))
```

![](https://i.imgur.com/ldIkOL8.png)

``` r
plot(rescols[1, ], type = "b", ylim = c(.8, 1))
```

![](https://i.imgur.com/Uq6vdaW.png)

**Comment by koheiw** [comment]
Be careful about the order of the values in the output, because they are not unique. You should sort them by documents or features.
