### ISSUE TITLE
dfm() failing on very large tokens object after NAs introduced by integer coercion

### ISSUE THREAD

**Issue by polarimetric** [quanteda/quanteda#1702]
I’m working with quanteda (R 3.6.0, Linux, 64-bit) on a very large text database (> 20 GB). Here is the code I’m running:

~~~
options(echo=TRUE)
library(parallel)
library(doParallel)
registerDoParallel(8)
library(data.table)
library(stringr)
library(tidyr)
library(quanteda)
quanteda_options(threads=8)
data <- fread("county_monthly_baskets.csv")
degreedays <- fread("us_degreedays_long.csv")
data <- merge(data,degreedays,by=c('stcountyfp','month','year'),all=TRUE,allow.cartesian=TRUE)
z_cdd90 <- data[["z_cdd90"]]
heatTokens <- tokens(data$text, remove_punct=TRUE, remove_symbols=TRUE)
heatTokens <- tokens_compound(heatTokens, pattern=phrase(c('not stated','no usda organic seal on pkg','not applicable','n a','non refillable')))
heatTokens <- tokens_compound(heatTokens, pattern=phrase(c('low *','no *', 'rd *', 'reduced *', 'less *', 'not *', 'non *', 'vitamin a d')))
heatTokens <- tokens_remove(heatTokens, pattern=c('na'))
heatTokens <- tokens_remove(heatTokens,pattern=c('NOT_STATED','NO_USDA_ORGANIC_SEAL_ON_PKG','NOT_APPLICABLE','N_A','REGULAR','NON_REFILLABLE','NA'))
heatTokens <- tokens_select(heatTokens, min_nchar=3L)
heatTokens <- tokens_ngrams(heatTokens, n=1:2)
saveRDS(z_cdd90,file="z_cdd90.rds")
saveRDS(heatTokens,file="heatTokens.rds")
heatTokens <- readRDS("heatTokens.rds")
heatDfm <- dfm(heatTokens)
heatDfm <- dfm_trim(heatDfm, min_termfreq=100)
saveRDS(heatDfm,file="heatDfm.rds")
heatDfm_tfidf <- dfm_tfidf(heatDfm, scheme_tf="count", scheme_df="inverse")
saveRDS(heatDfm_tfidf,file="heatDfm_tfidf.rds)
~~~

The tokenization works fine, so everything in the code above up to “heatDfm” runs successfully. However, creating the dfm object fails with the following error:

~~~
Error in if ((lp <- length(p)) < 1 || p[1] != 0 || any((dp <- p[-1] -  :   missing value where TRUE/FALSE needed
Calls: dfm ... initialize -> callNextMethod -> .nextMethod -> sparseMatrix
In addition: Warning message:
In sparseMatrix(j = index, p = cumsum(c(1, lengths(x))) - 1, x = 1L,  :  NAs introduced by coercion to integer range
Execution halted
~~~

I assume this is because the frequency of some tokens exceeds integer.max. Is there any way to use the integer64 class from the bit64 package with dfm() to get around this? I assume calling library(bit64) alone will not suffice. Otherwise, I assume I could simply drop the most frequent tokens before creating the dfm as a workaround, but I’d like to avoid that if possible. I have replicated this issue on the latest quanteda from CRAN (1.4.3) as well as the github development version (1.4.5) as of June 3.

I will send the heatTokens.rds file privately to anyone working on this issue.

**Comment by kbenoit** [comment]
OK thanks, pls send to kbenoit@lse.ac.uk.

**Comment by kbenoit** [comment]
Sorry, I can't even load the object. That's on an iMac with 32GB RAM.

```
> toks <- readRDS("~/Downloads/heatTokens.rds")
Error: vector memory exhausted (limit reached?)
Received memory pressure event 4 vm pressure 0
2019-06-05 16:53:01.047 R[9287:390020] Persistent UI failed to open file 

> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.5
```

**Comment by fitbit-SOS** [comment]
Ah, that makes sense--I've been working with this data on my university cluster with 512 GB RAM, so I wasn't considering that testing with that file would be difficult unless you used a similar resource.

The two dfms idea sounds promising. I'll try that and get back to you.

Thanks!

**Comment by polarimetric** [comment]
Ah, that makes sense--I've been working with this data on my university cluster with 512 GB RAM, so I wasn't considering that testing with that file would be difficult unless you used a similar resource.

The two dfms idea sounds promising. I'll try that and get back to you.

Thanks!

**Comment by polarimetric** [comment]
@kbenoit, I removed the bigrams and tried dfm() again to get the same error. I've emailed you a link to the much smaller file (about 1/4 the size) which you should be able to open.

**Comment by polarimetric** [comment]
@kbenoit: no rush on this—I just wanted to make sure you received and were able to download the smaller tokens file to reproduce this issue. If you haven’t, I probably have to resend it because the download link was set to expire.

Thanks!

**Comment by kbenoit** [comment]
Thanks - I spoke to @koheiw this weekend about the scale issues and will let him investigate.

**Comment by polarimetric** [comment]
Sounds good—let me know if you or @koheiw need anything else from me to aid the process.

**Comment by koheiw** [comment]
I think this is the reason.
```r
> x <- rep(list(seq(1L, 10000L)), 10000000)
> y <- cumsum(c(1L, lengths(x)))
Warning message:
integer overflow in 'cumsum'; use 'cumsum(as.numeric(.))' 
> tail(y)
[1] NA NA NA NA NA NA

> z <- as.integer(cumsum(c(1.0, lengths(x))))
Warning message:
NAs introduced by coercion to integer range 

```
`dgTMatrix` would be the solution.
