### ISSUE TITLE
Similarity object should not be coerced to dist

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda#1716]
In working on #1714, I noticed that similarity object can be coerced to dist object. This is misleading. 
```r
dfmat <- dfm(corpus_subset(data_corpus_inaugural, Year > 2000),
             remove_punct = TRUE, remove = stopwords("english"))
(tstat1 <- textstat_simil(dfmat, method = "cosine", margin = "documents"))
plot(hclust(as.dist(tstat1)))
```
I think similarity object should be converted only to list, data.frame, or matrix.

**Comment by kbenoit** [comment]
True - but this is not functionality from **quanteda** but rather from `stats::as.dist()`. Any matrix can be coerced to a `dist` class, whether it makes sense or not.

```r
> as.dist(matrix(1:9, nrow = 3))
  1 2
2 2  
3 3 6
```

We could prohibit this of course but it could be circumvented by `as.dist(as.matrix(...))`. Intercepting the `as.dist()` call would of course require us to have classed the textstat_simil object using some special S4 class... :grin:.
