### ISSUE TITLE
Frequency counts of MWEs in Chinese-language texts

### ISSUE THREAD

**Issue by nolczak** [quanteda/quanteda#1746]
I'm trying to count the frequency of longer multi-word (four characters or more) expressions in Chinese-language material. I want to know how many times phrases such as "美国总统批评“ (The US President criticised) or "经济情况不好“ (the economic Situation is not good) appear in text article from media sources. 

When using 'tokens_compound' still seems to only count two-character words....  

Here are the commands I am typing into R (sorry, I don't know why the example contains these error messages)

![Rplot](https://user-images.githubusercontent.com/48314849/62739881-534bfd00-ba36-11e9-96c6-6f45c025e412.png)

Thank you for your help and for the excellent package!

**Comment by jiongweilua** [comment]
In the problem you described above, I think it's because you did not load the `quanteda` package in with `library(quanteda)`

I was able to solve the problem like this

```r
> library(quanteda)
> txt <- c("美国总统批评中国因为经济情况不好")
> toks <- quanteda::tokens(txt)
> toks
tokens from 1 document.
text1 :
[1] "美国" "总统" "批评" "中国" "因为" "经济"
[7] "情况" "不好"

> dfmat <- dfm(toks)
> topfeatures(dfmat)
美国 总统 批评 中国 因为 经济 情况 不好 
   1    1    1    1    1    1    1    1 
```

As for the issue of only counting two character words, I suspect that is due to the way quanteda tokenizes Chinese texts more generally. In this context, for example, tokenizing 中国 (China) as single token would make more sense rather than splitting it into 中(Middle) and 国(Country) as separate tokens. I am not sure about how exactly the tokenization was implemented, but I hope the above solves your problem.

**Comment by nolczak** [comment]
@jiongweilua thank you very much for your reply! That makes sense regarding the two character tokenization (I guess it's based on some kind of a dictionary, as it also recognizes three character words e.g. 葡萄牙). However, really I was hoping to be able to count longer multi character phrases (such as 美国总统批评) by including them as items in the tokenization. That's why I was trying with "tokens_compound" - but it doesn't seem to work. I think I could write a loop to iterate through the documents and find / count regular expressions in Python, but it'd be nice to use Quanteda to do this instead, as I'm using it for other parts of the text analysis.

**Comment by kbenoit** [comment]
@nolczak are you trying to discover the multi-word expressions and then compound them? For this, you should 

1.  tokenize using `tokens()`
2.  detect MWEs using `textstat_collocations()`
3.  Use `tokens_compound()` on the tokens with the (selected) `textstat_collocations()` return as `pattern`.

**Comment by nolczak** [comment]
@kbenoit thank you! I'll try that, and think it could work for what I want to do. However what about if I already know the multi-word expressions I want to count? In the example above, I have "美国总统“ (United States President). Is there any way to count the frequency of these known multi-word expressions (using them as the `pattern` rather than the `textstat_collocations()` return)? When I try to put them in as `pattern = compound` it doesn't seem to work.

**Comment by kbenoit** [comment]
That's even easier, if you know the list of MWEs. Is this what you are thinking of?

``` r
library("quanteda")
## Package version: 1.5.1

txt <- c("美国总统批评中国因为经济情况不好")
toks <- tokens(txt)
toks
## tokens from 1 document.
## text1 :
## [1] "美国" "总统" "批评" "中国" "因为" "经济" "情况" "不好"

mwes <- phrase(c("美国 总统", "批评 中国"))

tokens_compound(toks, mwes, concatenator = "")
## tokens from 1 document.
## text1 :
## [1] "美国总统" "批评中国" "因为"     "经济"     "情况"     "不好"
```

**Comment by nolczak** [comment]
@kbenoit that works perfectly now! Thank you. I think my problem may have been specifying the wrong thing in the `concatenator =`. Thank you for developing such an excellent research tool.
