### ISSUE TITLE
Are there "ground truth readability scores"?

### ISSUE THREAD

**Issue by p15e** [quanteda/quanteda#1752]
I've computed readability scores using `textstat_readability.R` as well as various online tools and ended up with somewhat different results for the same text. 

For example, the following text 
 > Existing computer programs that measure readability are based largely upon subroutines which estimate number of syllables, usually by counting vowels. The shortcoming in estimating syllables is that it necessitates keypunching the prose into the computer. There is no need to estimate syllables since word length in letters is a better predictor of readability than word length in syllables. Therefore, a new readability formula was computed that has for its predictors letters per 100 words and sentences per 100 words. Both predictors can be counted by an optical scanning device, and thus the formula makes it economically feasible for an organization such as the U.S. Office of Education to calibrate the readability of all textbooks for the public school system.

should give a `Coleman.Liau.short` score of 14.53 according to [Wikipedia](https://en.wikipedia.org/wiki/Coleman%E2%80%93Liau_index). 

The score obtained with `quanteda` is a bit different: 14.33

**My questions are:**
 - Why are these scores different?
 - Do you know of a collection of texts with known readability scores that could be used to test the accuracy of `textstat_readability.R`?

### Code used to compute `Coleman.Liau.short` for the above example
```
text <- "Existing computer programs that measure readability are based largely upon subroutines which estimate number of syllables, usually by counting vowels. The shortcoming in estimating syllables is that it necessitates keypunching the prose into the computer. There is no need to estimate syllables since word length in letters is a better predictor of readability than word length in syllables. Therefore, a new readability formula was computed that has for its predictors letters per 100 words and sentences per 100 words. Both predictors can be counted by an optical scanning device, and thus the formula makes it economically feasible for an organization such as the U.S. Office of Education to calibrate the readability of all textbooks for the public school system."

textstat_readability(text, 
                     measure = "Coleman.Liau.short",
                     remove_hyphens = FALSE)
```

**Comment by kbenoit** [comment]
Ah, if only there were such a thing as "ground truth" in this case. Not only do pre-computing era indexes tend to have ambiguities, but so do many implementations such as those in Wikipedia.

For instance, in the Wikipedia entry count, it is counting _100_ as a word with three "letters". The original Coleman and Liau (1975) mentions letters, not digits. Should we then count the two _100_ tokens?

Another issue is how `quanteda::tokens(x, remove_punct = TRUE)` handles internal punctuation.  The standard sentence parser actually fails on the "U.S. Office", thinking that a new sentence has begun with _Office_. And removing the punctuation does not remove the internal ".", so that 

```r
> tokens("U.S. Office", remove_punct = TRUE)
tokens from 1 document.
text1 :
[1] "U.S"    "Office"
```

**However** if we pre-treat that by just changing the text to "US Office" then it works perfectly.

``` r
library("quanteda")
## Package version: 1.5.1

txt <- "Existing computer programs that measure readability are based largely upon subroutines which estimate number of syllables, usually by counting vowels. The shortcoming in estimating syllables is that it necessitates keypunching the prose into the computer. There is no need to estimate syllables since word length in letters is a better predictor of readability than word length in syllables. Therefore, a new readability formula was computed that has for its predictors letters per 100 words and sentences per 100 words. Both predictors can be counted by an optical scanning device, and thus the formula makes it economically feasible for an organization such as the US Office of Education to calibrate the readability of all textbooks for the public school system."
toks <- tokens(txt, remove_punct = TRUE)

(Letters <- sum(nchar(as.character(toks))))
## [1] 639
(Words <- ntoken(toks))
## text1 
##   119

(L <- Letters / Words * 100)
##    text1 
## 536.9748

(Sentences <- nsentence(txt))
## text1 
##     5

(S <- Sentences / Words * 100)
##    text1 
## 4.201681

# compare

(CLI <- 0.0588 * L - 0.296 * S - 15.8)
##    text1 
## 14.53042

textstat_readability(txt, measure = "Coleman.Liau.short")
##   document Coleman.Liau.short
## 1    text1           14.53042
```

**Comment by p15e** [comment]
Thanks a lot for your great explanation; makes a lot of sense.
