### ISSUE TITLE
matrix2fcm

### ISSUE THREAD

**Issue by fkrauer** [quanteda/quanteda#1759]
Hi

I have a co-occurrence matrix (it's not made with `fcm()`, and I don't have the original data it is made from) and I would like to use `textplot_network()` to plot the co-occurrences. However this function only takes an fcm as input. How can I convert a normal matrix object to a quanteda fcm object? In the docs I found the function `matrix2fcm()`, but when I call it, I get

`Error: 'matrix2fcm' is not an exported object from 'namespace:quanteda'`

I am using quanteda 1.4.3, is this function only available in a later package version? Is there another workaround to plot the network of a co-occurrence matrix without making a fcm object? I tried to use the igraph plotting, but it is less pretty than textplot_network. 

Cheers, Fabienne
R 3.4.4

**Comment by kbenoit** [comment]
Hi - It's not exported but you should be able to call 
```r
quanteda:::matrix2fcm()
```

But since it's an internal function, we cannot guarantee that it will work easily. For that, we would need a write an `as.fcm()` function that would check that the coerced object fits the criteria defining an fcm object. @koheiw maybe worth considering?

**Comment by fkrauer** [comment]
Worked like a charm, thank you! Of note, I had some NA's (i.e. no co-occurence) in some matrix cells, which I had to set to 0, otherwise they would be ignored in the plot.

**Comment by koheiw** [comment]
I don't think there is a reason for not exporting `quanteda:::as.fcm()` if there are people who want to use it. Only need to check `x` has the same column and row names.

**Comment by kbenoit** [comment]
Yes, and some of the symmetry conditions, when applicable, and setting the slots appropriately.

**Comment by koheiw** [comment]
I can do this, but when are we going switch `master` to `dev-v2`? I have been using the latter in my projects, and it is working well.
