### ISSUE TITLE
Add padding to tokens

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda#1802]
We have to use two commands to keep sentences to separate by padding.
```r
tokens("This is sentence. This is sentence2.", remove_punct = FALSE) %>% 
    tokens_remove("[\\p{P}]", valuetype = "regex", padding = TRUE)

# tokens from 1 document.
# text1 :
# [1] "This"      "is"        "sentence"  ""          "This"      "is"        "sentence2" ""
```
Let's make it possible by adding `padding` to `tokens()` as we switch to post-processing in #1801.
```r
tokens("This is sentence. This is sentence2.", remove_punct = TRUE, padding = TRUE) 
```

**Comment by kbenoit** [comment]
This is good, and we can do it for all items subject to a `remove_*` argument.

This implies however that we will split items in the tokenization stage, but remove them in the tokens.tokens() stage, for the default tokenizer drafted in the `new-tokens-approach` branch.
