### ISSUE TITLE
Update text2vec code for compatibility with forthcoming text2vec update

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#1825]
This affects
- https://github.com/quanteda/quanteda/blob/master/vignettes/pkgdown/replication/text2vec.Rmd
- https://github.com/quanteda/quanteda/blob/master/tests/testthat/test-fcm.R

From @dselivanov on 19 December:

> Dear package authors, I'm planning to release a new version of text2vec soon (which your packages depend on / import). 
> 
> It comes with several breaking changes. Notably:
> We drop support for `itoken_parallel` on windows. So itoken_parallel will be sequential on windows. Reason for that is that anyway on windows communication between processes was usually dominating computation time.
> tf-idf formula has changed - see https://github.com/dselivanov/text2vec/issues/280
> GloVe object constructor has changed syntax. Now it is exported from rsparse package
> truncated SVD which is algorithm behind LSA now is exported from rsparse package. So it will lead to a bit different results for LSA model.
> Please take a look to the latest version from github - https://github.com/dselivanov/text2vec and check whether it breaks something.
> 
> text2vec was stable for quite some time, but now it is time to update it (keeping in mind warnings and errors here https://cran.r-project.org/web/checks/check_results_text2vec.html). 
> 
> Thanks in advance and let me know if any help is need.
> 
> -- 
> Cheers
> Dmitriy Selivanov

**Comment by dselivanov** [comment]
also keep in mind that for glove you don't need text2vec anymore - now it is part of https://cran.r-project.org/web/packages/rsparse/ and just re-imported in text2vec
