### ISSUE TITLE
Add new category of object metadata: properties

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#1845]
We currently have a problem with maintaining consistency across the attributes and slots, and after a lengthy discussion, @koheiw and I settled on the following scheme for v2:

1. `meta$system` remains exactly the same as it is now, which is _always_ updated when the object is created. This means calling `meta_system_defaults()` to get information from the current state of the user's system, and is never affected by the function call or the state of the object itself. 

    Note that this means that the `@version` slot for a dfm is removed, since this is already part of the `meta$system` list.

2. `meta$user` is unchanged.

3. Add a third "type" to the `meta` attribute/slot for all core objects: **properties**.

    This means moving the current slots (dfm) and attributes (corpus and tokens) from top-level slots or attributes, to list elements of `meta$properties`. This will include `unit`, `weightTf`, `weightDf`, `smooth`, `ngrams`, `skip`, and `concatenator`.

4. `dictionary2` class objects will also get the same structure of `meta` slot, with the "concatenator" slot moving to meta$properties. The addition of user-level metadata for dictionary objects will solve #1827.

In this way, objects now will carry a minimal set of slots and attributes, namely

| Attribute/slot | corpus | tokens | dfm | dictionary |
|----------------|:------:|:------:|:---:|:----------:|
| docvars        |    ✓   |    ✓   |  ✓ (slot)  |            |.
| meta           |    ✓   |    ✓   |  ✓ (slot)  |      ✓ (slot)    |
| types          |        | ✓      |     |            |
| padding      |        | ✓      |     |            |

(plus base object slots such as "names" or those inherited from **Matrix**, in the case of a dfm)

**Comment by koheiw** [comment]
Started working on this. My understanding was this for corpus
```r
    structure(x,
              names = names,
              class = "corpus",
              properties = list(
                  "version" = unlist(utils::packageVersion("quanteda")),
                  "unit" = unit
                  ),
              meta = list(
                  "system" = meta_system_defaults(source),
                  "user" = meta
                  ),
              docvars = docvars)
```
The difference from your outline is that `properties` is the one of the three top-level slots. We could make them to two, but `meta` should be under `properties` in this case, because the latter has a greater importance.

**Comment by koheiw** [comment]
How about this?
```r
structure(x,
          names = names,
          class = "corpus",
          meta = list("system" = meta_system_defaults(source),
                      "object" = list(unit, skip, ngram, etc),
                      "user" = list()),
          docvars = docvars)
```

**Comment by kbenoit** [comment]
“Object” is fine with me. I like putting it all into `meta` since this minimises the potential attr v. slot problem, and maximises flexibility to extend it.

“names” is element names or rownames depending on the object base class?

**Comment by kbenoit** [comment]
Another thought: If eventually we add a history - where each upstream function call that produces an object is pushed to a history stack - we could save that as `meta$history`. Using meta in this way provides flexibility for extension, working through a single attribute/slot.

**Comment by koheiw** [comment]
Why do we need `source`? What is it for? I suggest to drop it, because it only makes tests like this difficult.
```
expect_identical(
        dfm(corp, stem = TRUE),
        dfm(dfmt, stem = TRUE)
    )
```
These tests passed because `source` were not updated until now, but they fail in due to the new `meta$object`.

**Comment by kbenoit** [comment]
The idea is to record the previous object type from which the dfm was built. Not sure we really need it, but the `expect_identical()` hassle is not a great reason to remove it. Don't "system"  and "directory" already complicate the identical test?

In any case, "source" is apparently not working - the second below should be "tokens" not "character".
```r 
> dfm("one") %>% meta("source", type = "system")
[1] "character"
> dfm(tokens("one")) %>% meta("source", type = "system")
[1] "character"
```

**Comment by koheiw** [comment]
Source is the only problem in meta. Others are all fine. I haven't finished dfm because I cannot proceed without extensive test changes. Let's drop it. We can bring it back when needed.

**Comment by kbenoit** [comment]
Fine with me

Sent from my iPhone

On 8 Feb 2020, at 11:53, Kohei Watanabe <notifications@github.com> wrote:

﻿

Source is the only problem in meta. Others are all fine. I haven't finished dfm because I cannot proceed without extensive test changes. Let's drop it. We can bring it back when needed.
