### ISSUE TITLE
Remove Greek letters?

### ISSUE THREAD

**Issue by swilloughby78** [quanteda/quanteda#1847]
## Consider StackOverflow

If you have a question on how to use **quanteda**, please first search [our StackOverflow channel](https://stackoverflow.com/questions/tagged/quanteda). If it does not solve you problem, please post your question there. We monitor the channel and should respond to your question very quickly. 

## Report a bug

If you know how to use **quanteda** but not seeing what you expect, please check [existing issues](https://github.com/quanteda/quanteda/issues?utf8=%E2%9C%93&q=is%3Aissue). If it does not help, please [open an issue](https://github.com/quanteda/quanteda/issues/new?template=bug_report.md).

## Other questions

Hi Ken,
Is there a way to remove Greek symbols from text files?  I am reading in documents from ArXiv, and they tend to have a lot of symbols.
Thank you,
Shannon

**Comment by kbenoit** [comment]
Yep, you want a version of a regular expression that filters Greek letters only. I don't know exactly what your text is, but in a simple tests, this worked:

``` r
library("quanteda", warn.conflicts = FALSE)
## Package version: 1.9.9009
## Parallel computing: 2 of 12 threads used.
## See https://quanteda.io for tutorials and examples.

txt <- "A test to compare ξ and μ"
toks <- tokens(txt)
toks %>%
  as.list()
## $text1
## [1] "A"       "test"    "to"      "compare" "ξ"       "and"     "μ"

# remove Greek characters removal
tokens(toks) %>%
  tokens_remove("\\p{script=greek}", valuetype = "regex") %>%
  as.list()
## $text1
## [1] "A"       "test"    "to"      "compare" "and"
```

Note here we are using the development (pre-v2) package version but I made this compatible with the current CRAN v1.5.2 by print the tokens objects as lists.

**Comment by swilloughby78** [comment]
Thank you much, I will give that a try!
Shannon
