### ISSUE TITLE
Why not max_ndoc = 0 only for corpus?

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda#1881]
I think inspecting content of objects is generally good to thing to do, but `max_ndoc = 0` by default only for corpus. I think it should be 6 like for other objects.

https://github.com/quanteda/quanteda/blob/a1f65a8b71a1027146d645345292f3d6213bafcd/R/quanteda_options.R#L142

**Comment by kbenoit** [comment]
Mainly for continuity, but I can see your point.

**Comment by koheiw** [comment]
I think visible changes are important when releasing new products. People never see in their eyes the new docvars, meta, and tokenizers....
