### ISSUE TITLE
corpus/char_segment() keeps pre-pattern text when extract_pattern = FALSE

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#1891]
There is a difference in behaviour with the text before the first pattern in `corpus_segment()` and `char_segment()` depending on how the pattern is treated. The question is: Is this what we intended? If so, we should update the documentation to make this behaviour more clear.

(From this [SO question](https://stackoverflow.com/questions/60379256/quanteda-corpus-segment-documentation).)

``` r
library("quanteda")
## Package version: 2.0.0

txt <- "start middle end"
corp <- corpus(txt)

corpus_segment(corp, " ", extract_pattern = FALSE)
## Corpus consisting of 3 documents.
## text1.1 :
## "start"
## 
## text1.2 :
## "middle"
## 
## text1.3 :
## "end"
corpus_segment(corp, " ", extract_pattern = TRUE)
## Corpus consisting of 2 documents and 1 docvar.
## text1.1 :
## "middle"
## 
## text1.2 :
## "end"

char_segment(txt, " ", remove_pattern = FALSE)
## [1] "start"  "middle" "end"
char_segment(txt, " ", remove_pattern = TRUE)
## [1] "middle" "end"
```

**Comment by koheiw** [comment]
This is the intended behavior related to `pattern_position`. Since there are only two " " in the text, first or the last word need to be dropped. 
https://github.com/quanteda/quanteda/blob/d1a94cd3da737b56b604c4b5504950ccf32492f2/R/corpus_segment.R#L305
```r
> corpus_segment(corp, " ", extract_pattern = TRUE, pattern_position = "before")
Corpus consisting of 2 documents and 1 docvar.
text1.1 :
"middle"

text1.2 :
"end"

> corpus_segment(corp, " ", extract_pattern = TRUE, pattern_position = "after")
Corpus consisting of 2 documents and 1 docvar.
text1.1 :
"start"

text1.2 :
"middle"
```

I prefer to separate segmentation and extraction functions to avoid complex interaction between them.

**Comment by kbenoit** [comment]
OK, I'm happy with that. I'll close the issue.
