### ISSUE TITLE
dfm.corpus(x, verbose = TRUE) never completes the verbose output

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#1894]
Unlike the `tokens()` sequence, where we always end with `tokens.tokens()`, `dfm()` does not end with `dfm.dfm()`. When `verbose = TRUE`, we don't get the ending.

Should look like:
```r
> dfm(data_dfm_lbgexample, remove = "A*", verbose = TRUE)
Creating a dfm from a dfm input...
   ... removed 1 feature
   ... lowercasing
   ... created a 6 x 36 sparse dfm
   ... complete. 
Elapsed time: 0.011 seconds.
```

but instead we don't see the final two/three lines:
```r
> dfmat <- dfm(data_corpus_inaugural, remove = stopwords("en"), verbose = TRUE)
Creating a dfm from a corpus input...
   ... lowercasing
   ... found 58 documents, 9,399 features
   ... removed 136 features
```

**Comment by koheiw** [comment]
Do we still need elapsed time?
```
Elapsed time: 0.011 seconds.
```
I want to remove these lines
https://github.com/quanteda/quanteda/blob/d360d8236a948ac39f86b890101aa27dcff8dad7/R/dfm.R#L142-L143
If users are interested  in timing, they just use `system.time()`.

**Comment by kbenoit** [comment]
Yes I very much like the elapsed time and closing message. It tells us something about the timings and sequence, good for diagnostics and for some users who want to know the precise sequences and/or timing without wrapping the function, it's useful.

```r
> tokens(data_corpus_inaugural, remove_punct = TRUE, 
+        remove_symbols = TRUE, remove_numbers = TRUE,
+        verbose = TRUE)
Creating a tokens object from a corpus input...
...starting tokenization
...preserving hyphens
...preserving social media tags (#, @)
...tokenizing 1 of 1 blocks
...segmenting tokens
...serializing tokens 10062 unique types
...removing separators, punctuation, symbols, numbers 
...total elapsed:  0.406 seconds.
Finished constructing tokens from 58 texts.
```

**Comment by koheiw** [comment]
Have you ever really used the elapsed time for diagnosis? I don't think so, because elapsed time for single execution doesn't mean anything. When we want to find slow functions, we use `profvis::profvis()`.

I like this part
```
...starting tokenization
...preserving hyphens
...preserving social media tags (#, @)
...tokenizing 1 of 1 blocks
...segmenting tokens
...serializing tokens 10062 unique types
...removing separators, punctuation, symbols, numbers
```
but not this
```
...total elapsed:  0.406 seconds.
```
