### ISSUE TITLE
add ngrams back to dfm()?

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#1896]
We removed this from `tokens()`, but since `dfm()` is still a convenience function, and since it used to allow ngram creation from a tokens or text input as convenience (since this was passed through to `tokens()` via `...`), we should either add this back via a separate call to `tokens_ngrams()`, or remove the examples showing how this is done - see `?dfm`.

I favour the latter.

**Comment by Gustavo-CR** [comment]
Hi Kenneth, 

So would you recommend the following pipeline for 2-gram tf-idf creation on v2.0.0?
`data %>% 
   corpus() %>% 
   tokens() %>% 
   tokens_ngrams(2) %>% 
   dfm() %>% 
   dfm_tfidf()`

or is there an easier / more efficient way to do so?

**Comment by kbenoit** [comment]
Yes exactly, that's the recommended sequence.
