### ISSUE TITLE
t() not transposing dimnames

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#1903]
The dimnames should swap, but don't. But everything else looks ok.

``` r
library("quanteda")
## Package version: 2.0.0.9000

x <- dfm(c(d1 = "one two three", d2 = "two two three"))
x
## Document-feature matrix of: 2 documents, 3 features (16.7% sparse).
##     features
## docs one two three
##   d1   1   1     1
##   d2   0   2     1
t(x)
## Document-feature matrix of: 3 documents, 2 features (16.7% sparse).
##        features
## docs    d1 d2
##   one    1  0
##   two    1  2
##   three  1  1

featnames(t(x))
## [1] "d1" "d2"
docnames(t(x))
## [1] "one"   "two"   "three"
```

**Comment by koheiw** [comment]
This is interesting one. I think a transposed DFM should be treated as reglar Matrix.

**Comment by kbenoit** [comment]
We could do that, but still we'd want to swap the `names(x@Dimnames)`. I think this is another unintended consequence of the stronger `build_dfm()`/`rebuild_dfm()` functions.

Another way to go would be to access the dimensions through their Dimnames by name, rather than by fixed index position assuming they are always doc, feature, then it would not matter if they are transposed. But I prefer enforcing that documents are rows, it keeps things simpler.
