### ISSUE TITLE
tokens_tortl() needs to be fixed

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#1905]
Currently broken:
https://github.com/quanteda/quanteda/blob/8029f2d98717f03336f051dc1f010a0fa610459e/R/directionchange-functions.R#L21-L24

which is why the test is skipped in `test-directionchange.R`.

**Comment by koheiw** [comment]
It works on my system
```r
setequal(types(tokens_tortl(toks)), types(tokens(char_tortl(txt[1]))))
[1] TRUE
```

**Comment by kbenoit** [comment]
Hmmm... Works on mine too. Is your system Windows? Maybe the test is ok now.

**Comment by koheiw** [comment]
Works on Windows machine too.

**Comment by kbenoit** [comment]
Solution: deprecate this, make it internal only, with an eye to eventual removal. Issue an invitation to email us if a user finds this helpful and would prefer it to be kept.

**Comment by kbenoit** [comment]
Closed because we removed these functions.
