### ISSUE TITLE
Bring back data_corpus_irishbudget2010?

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda#1907]
I approved #1898, but noticed that it is inconvenient not to have a corpus with multiple groups, so how about bringing back only `data_corpus_irishbudget2010`? It is relatively small in file size. `data_char_ukimmig2010` has similar structure but it is a character vector.

**Comment by kbenoit** [comment]
The inaugural corpus got a new docvar in v2: Party. Works well to demo grouping.
```r
> tail(docvars(data_corpus_inaugural), 4)
   Year President FirstName      Party
55 2005      Bush George W. Republican
56 2009     Obama    Barack Democratic
57 2013     Obama    Barack Democratic
58 2017     Trump Donald J. Republican
> print(dfm(data_corpus_inaugural, groups = "Party"), max_ndoc = 0)
Document-feature matrix of: 6 documents, 9,360 features (66.9% sparse) and 1 docvar.
```
