### ISSUE TITLE
I obtained very large value of readability (average 400)

### ISSUE THREAD

**Issue by Ahmedmohammed88** [quanteda/quanteda#1914]
Dear Professor Kenneth,
I hope you are fine.
As per your discussion with my supervisor via email, I used quanteda to obtain the fog index for some statements in the annual reports of the FTSE 350 such as the chairman statement, CEO … etc. The thing which is surprising is that I obtained very large values of the readability measure (the fog index). Most values are greater than 100 with an average of 400. Usually, the average should be around 17-18. What would be the reason?
Thank you very much,
I appreciate your help and support.

Kindly see the commands which I used:

readtext(paste0(".txt"), docvarsfrom = "filenames",docvarnames = c("text","company","year"))
ChairmanStatement <- readtext(paste0(".txt"), docvarsfrom = "filenames",docvarnames = c("text","company","year"))

gsub(pattern="\W", replace=" ", ChairmanStatement)
ChairmanStatement1 <- gsub(pattern="\W", replace=" ", ChairmanStatement)
gsub(pattern="\d", replace=" ", ChairmanStatement1)
ChairmanStatement2 <- gsub(pattern="\d", replace=" ", ChairmanStatement1)
ChairmanStatement2

#corpus
ChairmanStatement3 <- corpus(ChairmanStatement2)
summary(ChairmanStatement3)

#Document-term matrix and The Creation of a Document-Feature Matrix (dfm)
dfm(ChairmanStatement3, removePunct = TRUE, verbose = FALSE, tolwoer = TRUE, remove_numbers = TRUE, removeSeparators = TRUE, toLower = TRUE, remove_symbols = TRUE, ignoredFeatures = stopwords("english"), stem = TRUE, language = "english")
dtm <- dfm(ChairmanStatement3, removePunct = TRUE, verbose = FALSE, remove_numbers = TRUE, removeSeparators = TRUE, toLower = TRUE, remove_symbols = TRUE, ignoredFeatures = stopwords("english"), stem = TRUE, language = "english")
mydfm <- dfm(ChairmanStatement3, removePunct = TRUE, verbose = FALSE, remove_numbers = TRUE, removeSeparators = TRUE, toLower = TRUE, remove_symbols = TRUE, ignoredFeatures = stopwords("english"), stem = TRUE, language = "english")

dim(mydfm)
docnames(mydfm)
plot(mydfm)

##plot(mydfm)
if (require(RColorBrewer))
plot(mydfm, max.words = 100,
colors = brewer.pal(6, "Dark2"), scale = c(8, .5))

Top 40 features

topfeatures(mydfm, 40)

#the frequency count to a proportion within documents
dfm_weight(mydfm, scheme = "prop")
prop_mydfm <- dfm_weight(mydfm, scheme = "prop")
topfeatures(prop_mydfm, 40)

Head of doc frequency

head(docfreq(mydfm))

demonstrate Zipf's law

plot(log10(1:100), log10(topfeatures(mydfm, 100)), xlab="log10(rank)", ylab="log10(frequency)", main="Top 100 Words")

regression to check if slope is approx -1.0

regression <- lm(log10(topfeatures(mydfm, 100)) ~ log10(1:100))
abline(regression, col="red")
confint(regression)

#Tokenization
toks <- tokens(ChairmanStatement3)
toks

#Normalization: Lowercasing and stemming
toks <- tokens_tolower(toks)
toks <- tokens_wordstem(toks)
toks

#Removing stopwords
sw <- stopwords("english")
head(sw)

#Filtering and weighting
doc_freq <- docfreq(dtm)
dtm <- dtm[, doc_freq >= 2]
dtm <- dfm_weight(dtm, "tfidf")
head(dtm)

#Analysis
dtm <- dfm(data_corpus_inaugural, removePunct = TRUE, verbose = FALSE, remove_numbers = TRUE, removeSeparators = TRUE, toLower = TRUE, remove_symbols = TRUE, ignoredFeatures = stopwords("english"), stem = TRUE, language = "english")

Dictionary

tokens_lookup(tokens(ChairmanStatement3), dictionary = data_dictionary_LSD2015, exclusive = FALSE)

tokens from 1 document.

text1 :

[1] "This" "NEGATIVE" "policy" "will" "NEG_POSITIVE" "POSITIVE" "."

dfm(ChairmanStatement3, dictionary = data_dictionary_LSD2015)

mydata <- dfm(ChairmanStatement3, dictionary = data_dictionary_LSD2015)

Readability

textstat_readability(ChairmanStatement3, c("Flesch.Kincaid", "FOG"))
read <- textstat_readability(ChairmanStatement3, c("Flesch.Kincaid", "FOG"))
plot(read$Flesch.Kincaid, type = "b",xlab = "", ylab = "Readability Index")
write.xlsx(read, "//Users/ahmed/Desktop/read.xlsx")

**Comment by kbenoit** [comment]
The key to being able to diagnose this would be to have your input tests to the `textstat_readability()` call. Without that I cannot do much. Note that if your text cannot be parsed into sentences, then the ASL (average sentence length) will be too large and could be causing your problem.

For the test texts, it works in the expected ranges:

``` r
library("quanteda")
## Package version: 2.0.0.9000
## Parallel computing: 2 of 12 threads used.
## See https://quanteda.io for tutorials and examples.
## 
## Attaching package: 'quanteda'
## The following object is masked from 'package:utils':
## 
##     View
textstat_readability(data_corpus_inaugural, c("FOG", "FOG.PSK", "FOG.NRI"))
##           document       FOG   FOG.PSK    FOG.NRI
## 1  1789-Washington 32.909319 18.713936  622.22935
## 2  1793-Washington 22.092593 11.194674   31.06875
## 3       1797-Adams 32.847170 18.786085 1008.76230
## 4   1801-Jefferson 23.028338 12.866143  475.72683
## 5   1805-Jefferson 25.587590 14.509155  684.88133
## 6     1809-Madison 29.589821 16.844384  446.60071
## 7     1813-Madison 21.780357 11.620805  299.59864
## 8      1817-Monroe 18.011229  9.195239  631.38645
## 9      1821-Monroe 20.620421 10.996900 1037.46543
## 10      1825-Adams 23.718266 12.559762  801.58216
## 11    1829-Jackson 25.955801 14.085469  353.59440
## 12    1833-Jackson 23.813072 12.784604  327.85707
## 13   1837-VanBuren 24.312214 12.886393 1092.21916
## 14   1841-Harrison 23.441281 12.644298 2328.04150
## 15       1845-Polk 20.153127 10.325207 1041.72902
## 16     1849-Taylor 27.755704 15.291266  376.13477
## 17     1853-Pierce 20.153203 10.440256  731.11063
## 18   1857-Buchanan 19.624870 10.262107  605.10337
## 19    1861-Lincoln 17.311489  8.858958  649.07233
## 20    1865-Lincoln 14.893032  8.265039  112.41250
## 21      1869-Grant 17.357745  9.095519  206.74537
## 22      1873-Grant 17.987504  9.743280  264.94186
## 23      1877-Hayes 24.194438 13.157307  716.45686
## 24   1881-Garfield 17.448990  8.888069  535.30824
## 25  1885-Cleveland 23.326879 12.281810  451.11443
## 26   1889-Harrison 18.316489  9.285524  833.22984
## 27  1893-Cleveland 22.046971 11.364414  492.63284
## 28   1897-McKinley 19.326401  9.973975  822.14369
## 29   1901-McKinley 16.537109  7.855154  339.00555
## 30  1905-Roosevelt 16.841266  9.257688  182.66379
## 31       1909-Taft 20.966124 10.997796 1268.23777
## 32     1913-Wilson 14.982539  7.967353  265.43882
## 33     1917-Wilson 14.682648  8.034722  239.38229
## 34    1921-Harding 16.475187  7.902052  515.21338
## 35   1925-Coolidge 15.191103  7.269574  563.47865
## 36     1929-Hoover 16.613440  7.946280  555.36788
## 37  1933-Roosevelt 14.784779  7.413741  268.36818
## 38  1937-Roosevelt 13.651785  6.599170  224.00130
## 39  1941-Roosevelt 12.640389  6.485161  162.96581
## 40  1945-Roosevelt 11.820036  6.576996   68.26750
## 41     1949-Truman 14.546797  6.934406  297.68461
## 42 1953-Eisenhower 13.127929  6.754606  314.11546
## 43 1957-Eisenhower 10.374018  5.631373  171.89783
## 44    1961-Kennedy 14.611946  8.081022  214.98548
## 45    1965-Johnson 10.381757  5.288200  141.57204
## 46      1969-Nixon 12.052687  6.484276  259.15398
## 47      1973-Nixon 15.182744  8.265070  292.74154
## 48     1977-Carter 14.553118  7.603790  180.04231
## 49     1981-Reagan 12.932697  6.429385  291.96188
## 50     1985-Reagan 13.479606  6.883269  335.96988
## 51       1989-Bush  9.975369  5.259602  221.42255
## 52    1993-Clinton 13.176235  6.612487  198.20370
## 53    1997-Clinton 12.688532  6.439325  259.79297
## 54       2001-Bush 11.583401  5.638195  160.67655
## 55       2005-Bush 14.087287  7.039065  277.51742
## 56      2009-Obama 12.691956  6.844239  312.00568
## 57      2013-Obama 14.510999  7.653996  312.72477
## 58      2017-Trump 12.160556  5.795810  150.49432
```

**Comment by Ahmedmohammed88** [comment]
Thank you very much for your help and support.

Kindly have a look on the following:
For Example, this is one of the files which give the FOG score "905".
I want to check with you does it gives you the same measure or I do something wrong which give me the high score of readability.


[chairman statement_3i_2013.txt](https://github.com/quanteda/quanteda/files/4332875/chairman.statement_3i_2013.txt)

**Comment by kbenoit** [comment]
Works correctly for me.

``` r
txt <- readtext::readtext(
  "https://github.com/quanteda/quanteda/files/4332875/chairman.statement_3i_2013.txt"
)$text

library("quanteda")
## Package version: 2.0.0
## Parallel computing: 2 of 12 threads used.
## See https://quanteda.io for tutorials and examples.
## 
## Attaching package: 'quanteda'
## The following object is masked from 'package:utils':
## 
##     View
textstat_readability(txt, "FOG")
##   document      FOG
## 1    text1 21.04692
```

**Comment by Ahmedmohammed88** [comment]
I have changed all commands and rerun all of them again, and it gave me the same result of FOG (21.04692), and my other results are reasonable.
Thank you very much for your help and support.

**Comment by kbenoit** [comment]
Great to hear. Because it relies on sentence parsing (which is inexact) and because FOG calls for excluding proper nouns, every computer implementation differs slightly, and **quanteda**’s is certainly not perfect, but it should at least produce values within the expected range.

**Comment by Ahmedmohammed88** [comment]
Thank you very much for your notes and support, really I appreciate it.
