### ISSUE TITLE
Error in transforming a data.frame to a corpus 

### ISSUE THREAD

**Issue by kaskitid** [quanteda/quanteda#1915]
Hello,

I have been trying to transform a data frame into a corpus and although I make sure that I have a character vector as a _text_field_, for some reason I get an error message. 

> class(x)
[1] "data.table" "data.frame"

> class(x$lemma)
[1] "character"

> corp <- corpus(x, text_field = x$lemma)
Error in corpus.data.frame(x, text_field = x$lemma) : 
  text_field must refer to a single column

However, it works when I transform a character vector into a corpus.
> corp <- corpus(x$lemma)

Thanks in advance,
Konstantinos

**Comment by kbenoit** [comment]
That's because you have to specify a column name as `text_field`,  not the value itself. 

`corpus(x, text_field = x$lemma)` calls `corpus.data.frame()` with an illegal value for `text_field`. From `?corpus':

> `text_field`  the character name or numeric index of the source data.frame indicating the variable to be read in as text, which must be a character vector. 

`corpus(x$lemma)` works because it calls `corpus.character()`.
