### ISSUE TITLE
RcppParallel and TBB update

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#1916]
We can fix the warnings using some environment variables in the startup function. We should update this in https://github.com/quanteda/quanteda.textmodels as well.

From Kevin Ushey on 17 March 2020:

> This e-mail concerns the release RcppParallel 5.0.0. You are receiving
> this e-mail because you are maintaining one or more packages on CRAN
> that depend on the RcppParallel package.
> 
> Packages depending on RcppParallel often have issues with ASAN / UBSAN
> warnings, originating from use of RcppParallel's bundled TBB library
> (https://software.intel.com/en-us/tbb). Unfortunately, these issues
> have not been resolved upstream, and I have not been able to resolve
> these warnings myself as well.
> 
> To alleviate this, with RcppParallel 5.0.0, it is now possible to
> configure the parallel backend used by RcppParallel by setting the
> RCPP_PARALLEL_BACKEND environment variable. For example:
> 
>    RCPP_PARALLEL_BACKEND=tbb
>    RCPP_PARALLEL_BACKEND=tinythread
> 
> This explicitly affects the C++ 'parallelFor' and 'parallelReduce'
> APIs provided by RcppParallel.
> 
> To avoid ASAN / UBSAN warnings in future CRAN submissions, it is
> highly recommended that you call:
> 
>    Sys.setenv(RCPP_PARALLEL_BACKEND = "tinythread")
> 
> before your test suite is run.
> 
> If your package explicitly requires TBB-specific functionality, you
> will likely need to explain this in your submission as you will almost
> certainly see the aforementioned ASAN / UBSAN errors during testing.

**Comment by koheiw** [comment]
We are using TBB objects directly, so this workaround does not help. 
> If your package explicitly requires TBB-specific functionality, you
will likely need to explain this in your submission as you will almost
certainly see the aforementioned ASAN / UBSAN errors during testing.
