### ISSUE TITLE
'stopword` package does not exist

### ISSUE THREAD

**Issue by KEEEEitarou** [quanteda/quanteda#1931]
When I tried to install and library 'quanteda', R says package 'stopword' does not exist and failed to library 'quanteda'.

Does this relate to the thesedays update on package 'stopwords'? I was able to use quanteda without any issue the other day.

**Comment by kbenoit** [comment]
Might - have you tried (re)installing the **stopwords** package?

**Comment by KEEEEitarou** [comment]
Thank you for your reply. 
Yes, I tried to install the stopwords package, but R studio replies the following error and does not show 'stopwords' in the list of packages.

==
ERROR: installing package DESCRIPTION failed for package 'stopwords'
* removing 'C:/Users/rmkhi/OneDrive/ドキュメント/R/win-library/3.6/stopwords'
Warning in install.packages :
  installation of package ‘stopwords’ had non-zero exit status

**Comment by kbenoit** [comment]
try
```r
install.packages("stopwords")
```

**Comment by koheiw** [comment]
@KEEEEitarou I can see that your R libraries are installed under the OneDrive folder. You should unsync and reinstall all the packages because OneDrive destroys packages continuously.

**Comment by KEEEEitarou** [comment]
@koheiw Thank you very much. It solves the issue.
