### ISSUE TITLE
Feature request: customize legend position of keyness plot

### ISSUE THREAD

**Issue by yuanzhouIR** [quanteda/quanteda#1937]
The default position of legend of `textplot_keyness()` is on the right. However, sometimes it is better to put the legend on the top, especially when the legend label is very long. So would you please add an argument like `legend.position` to allow users customize the position of legend?

**Comment by kbenoit** [comment]
You should be able to do this using ggplot2 on the plot object. Have you tried?

**Comment by yuanzhouIR** [comment]
> You should be able to do this using ggplot2 on the plot object. Have you tried?

Oh, thank you very much. I tried `keyplot + theme(legend.position="top")` and it worked.
