### ISSUE TITLE
Add an argument with group names to textplot_wordcloud

### ISSUE THREAD

**Issue by kadyb** [quanteda/quanteda#1938]
## Requested feature

It would be great if you could pass an argument with group names in the textplot_wordcloud function.

```r
# suppose we compare two groups
textplot_wordcloud(dfmat, comparison = TRUE, docnames = c("happy", "sad"))
```

## Use case

I currently have binary coded grouping variables, but the text group names look better for visualizing word clouds

**Comment by kbenoit** [comment]
You can do this by changing the docnames in the dfmat before calling `textplot_wordcloud()`:

``` r
library("quanteda")
## Package version: 2.0.2
## Parallel computing: 2 of 8 threads used.
## See https://quanteda.io for tutorials and examples.
## 
## Attaching package: 'quanteda'
## The following object is masked from 'package:utils':
## 
##     View

dfmat <- dfm_group(data_dfm_lbgexample, groups = c("a", "a", "a", "b", "b", "b"))
dfmat
## Document-feature matrix of: 2 documents, 37 features (23.0% sparse).
##     features
## docs A B  C  D  E  F   G   H   I   J
##    a 2 3 10 22 45 80 118 156 180 191
##    b 0 0  0  0  0  0   0   2   3  10
## [ reached max_nfeat ... 27 more features ]

textplot_wordcloud(dfmat, comparison = TRUE)
```

![](https://i.imgur.com/ZoO10uE.png)

``` r

docnames(dfmat) <- c("happy", "sad")
textplot_wordcloud(dfmat, comparison = TRUE)
```

![](https://i.imgur.com/W6EZAm3.png)

**Comment by kadyb** [comment]
Yeah, but in my workflow after visualizing the word cloud I would like to return to the binary data form (0-1 instead of sad-happy). It seems to me that it would be better if the function just took such an argument instead of making the change and back again. But this issue is not necessary.

**Comment by kbenoit** [comment]
Perhaps write a quick wrapper function then to reassign the docnames temporarily before calling `textplot_wordcloud()`. We didn't do this in the package version of the function because the idea is to use **ggplot2** and make all of the objects editable and (re)configurable after creation, like any other ggplot. But `textplot_wordcloud()` is the only plot function that is still not 100% ggplot. We aim to get there eventually though.
