### ISSUE TITLE
Update the quanteda cheatsheet

### ISSUE THREAD

**Issue by stefan-mueller** [quanteda/quanteda#1944]
The [quanteda cheatsheet](https://github.com/quanteda/quanteda/blob/master/tests/cheatsheet/quanteda-cheatsheet.pdf) has not been updated since 11/2018. Required changes:

- [ ]  Check and update printed code outputs (esp. from `corpus()` and `dfm()`)
- [ ] Include **quanteda.textmodels** in the extension packages and add `quanteda.textmodels::` when calling functions from this package in the vignette
- [ ] Add `textmodel_svm()` after `textmodel_nb()`
- [ ] Check whether any argument names have changed
- [ ] Change date from 11/2018 to 5/2020

Once the cheat sheet is updated in the **quanteda** repo, I will also send the new version to RStudio in order to update their [collection of cheatsheets](https://rstudio.com/resources/cheatsheets/)

**Comment by koheiw** [comment]
@stefan-mueller can you work on this?
