### ISSUE TITLE
performance issue with tokenization

### ISSUE THREAD

**Issue by randomgambit** [quanteda/quanteda#1964]
Hello there,

Thanks for this beautiful package. I have a quick question about performance. I am a bit surprised by the following performance comparison between `quanteda` and `tidytext`. Do you know why `quanteda` take much more time here?

```
tib <- tibble(text =rep('\nworst-case, scenario!!', 1000000)) 

tic()
tib %>% 
  unnest_tokens(input = 'text', output = 'word')
toc()
4.945 sec elapsed

tic()
tokens(tib$text)
toc()
52.755 sec elapsed

```

Thanks!

**Comment by kbenoit** [comment]
Thanks for the praise, we're glad you like the design (and functionality!).

With **quanteda** v2, you can use almost any tokenizer you want. But to answer the question, there are several differences, but your test is not necessarily a good one, see below.

1. The default **quanteda** tokenizer is smarter. Sometimes this is more important than speed. If you want the closest equivalent, then try wrapping the output of `tokenizers::tokenize_words()` (what **tidytext** uses) with `as.tokens()`.

2. `tokens()` also indexes the tokens into an efficient type-to-integer table, which **tidytext** does not do. This can slow things down, although below, that does not seem to happen.

### Demo

``` r
library("quanteda", warn.conflicts = FALSE)
## Package version: 2.0.9000
library("tidytext")

txt <- "The passer-by Tweeted #nicefind to the https://coolstuff.com?p=123 website."

tokens(txt)
## Tokens consisting of 1 document.
## text1 :
## [1] "The"                         "passer-by"                  
## [3] "Tweeted"                     "#nicefind"                  
## [5] "to"                          "the"                        
## [7] "https://coolstuff.com?p=123" "website"                    
## [9] "."

tibble::tibble(text = txt) %>%
  unnest_tokens(output = "word", input = "text")
## # A tibble: 12 x 1
##    word         
##    <chr>        
##  1 the          
##  2 passer       
##  3 by           
##  4 tweeted      
##  5 nicefind     
##  6 to           
##  7 the          
##  8 https        
##  9 coolstuff.com
## 10 p            
## 11 123          
## 12 website
```

To get the equivalent in **quanteda**:
```r
# equivalent
tokenizers::tokenize_words(txt) %>%
  as.tokens()
## Tokens consisting of 1 document.
## text1 :
##  [1] "the"           "passer"        "by"            "tweeted"      
##  [5] "nicefind"      "to"            "the"           "https"        
##  [9] "coolstuff.com" "p"             "123"           "website"
```

### Speed

This seems to depend on the complexity of the task, but in my tests with real texts (admittedly small ones), **quanteda** was faster even with the token indexing:

```r
microbenchmark::microbenchmark(
  quan_default = tokens(data_corpus_inaugural),
  quan_tokenize_words = tokenizers::tokenize_words(data_corpus_inaugural) %>%
    as.tokens(),
  tt_default = tibble::tibble(text = data_corpus_inaugural) %>%
    unnest_tokens(output = "word", input = "text"),
  times = 10
)
## Unit: milliseconds
##                 expr       min        lq      mean    median        uq
##         quan_default 125.99906 130.38167 137.29266 137.90083 142.36261
##  quan_tokenize_words  59.02781  59.50703  68.63949  66.30853  76.24065
##           tt_default 252.96963 258.11159 297.52231 260.75804 349.49990
##        max neval cld
##  146.99523    10  b 
##   87.11902    10 a  
##  386.63018    10   c
```

**Comment by randomgambit** [comment]
thank you this is great! but do you get the same performance when `times = 100000` for instance?

**Comment by randomgambit** [comment]
Actually, that was easy to test. Perhaps the table creation is a bottleneck here?
```

tib <- c(text =rep('\nworst-case, scenario!!', 100000)) 

microbenchmark::microbenchmark(
  quan_default = tokens(tib),
  quan_tokenize_words = tokenizers::tokenize_words(tib) %>%
    as.tokens(),
  tt_default = tibble::tibble(text = tib) %>%
    unnest_tokens(output = "word", input = "text"),
  times = 3
)

Unit: milliseconds
                expr       min        lq      mean    median        uq       max neval cld
        quan_default 2707.5465 2725.7791 2864.6399 2744.0117 2943.1866 3142.3616     3   c
 quan_tokenize_words 1478.3133 1486.9511 1569.0079 1495.5889 1614.3551 1733.1214     3  b 
          tt_default  265.9074  269.2584  272.7632  272.6094  276.1911  279.7727     3 a  
```

**Comment by randomgambit** [comment]
@kbenoit the more I think about it the more I am convinced there should be some inefficiency hiding somewhere... how is it possible that the performance deteriorates so much as we increase the number of rows?

**Comment by koheiw** [comment]
**quanteda** is slower with many short texts, but your texts are too artificial.
```r
> corp <- quanteda.corpora::download("data_corpus_guardian")
> txt <- texts(corp)
> length(txt)
[1] 6000
> microbenchmark::microbenchmark(
+   quan_default = tokens(txt),
+   quan_tokenize_words = tokenizers::tokenize_words(txt) %>% as.tokens(),
+   tt_default = tibble::tibble(text = txt) %>% unnest_tokens(output = "word", input = "text"),
+   times = 10
+ )
Unit: seconds
                expr      min       lq      mean    median        uq       max neval
        quan_default 9.288622 9.972312 10.151973 10.195680 10.335622 10.861557    10
 quan_tokenize_words 6.100503 6.344891  6.975111  7.016457  7.165157  8.367452    10
          tt_default 6.779827 6.798557  7.209031  7.119476  7.391036  8.131829    10
> 
> txt_sent <- texts(corpus_reshape(corp))
> length(txt_sent)
[1] 200582
> microbenchmark::microbenchmark(
+   quan_default = tokens(txt_sent),
+   quan_tokenize_words = tokenizers::tokenize_words(txt_sent) %>% as.tokens(),
+   tt_default = tibble::tibble(text = txt_sent) %>% unnest_tokens(output = "word", input = "text"),
+   times = 10
+ )
Unit: seconds
                expr       min        lq      mean    median        uq       max neval
        quan_default 15.462341 15.543736 16.227101 16.269259 16.590961 17.784403    10
 quan_tokenize_words 10.659561 11.663705 12.024980 11.869362 11.966259 14.926220    10
          tt_default  7.046386  7.122876  7.439154  7.356464  7.682318  8.326542    10
```

**Comment by randomgambit** [comment]
thank you @koheiw for the clarification. i guess one key question is how to make good use of the indexing (which costs a little extra processing). Which `quanteda` function takes advantage of it?

**Comment by kbenoit** [comment]
Every one of the `tokens_*()` functions, and `dfm.tokens()`!

**Comment by randomgambit** [comment]
@kbenoit interesting. Do we have an idea which `tokens_` operation is most expensive computationally (that is, without indexing)? That could be one additional argument in favor of using `quanteda` in some textual processing tasks

**Comment by koheiw** [comment]
The slowest function is `tokens()` because it serializes (convert to integers) tokens and runs without parallelization.

**Comment by lduart** [comment]
Hi, this is my code, I am trying to analyze some tweets. First, I worked with 16000 tweets. This worked very easy. Now I wanted to run the same code through 359920 tweets, but the tokens() does not work. I've let it run the whole night, but it didn't work

qunateda_options("threats"=8)

# Read data 
load("~/DNR_SR_Jan_Okt_2019.RData")
p_color <- read_csv("Parteifarben.csv")
dat <- data.frame(
  id = seq(1, nrow(NR_SR_Jan_Okt_2019)), 
  firstname = NR_SR_Jan_Okt_2019$First_Name,
  lastname = NR_SR_Jan_Okt_2019$Last_Name,
  gender = NR_SR_Jan_Okt_2019$Gender, 
  birth = as.Date(NR_SR_Jan_Okt_2019$Year.of.Birth,"%y/%m/%d"), 
  party = NR_SR_Jan_Okt_2019$Party_Short,
  party_g = NR_SR_Jan_Okt_2019$Party,
  canton = NR_SR_Jan_Okt_2019$Canton, 
  tweet = NR_SR_Jan_Okt_2019$Text,
  language = NR_SR_Jan_Okt_2019$Language, 
  is_retweet = NR_SR_Jan_Okt_2019$Is_retweet,
  created_at = as.Date(NR_SR_Jan_Okt_2019$Datum,"%y/%m/%d"),
  stringsAsFactors = FALSE
)

# construct corpus 
corp <- corpus(dat, text_field = "tweet")
summary(corp,40)

# create Id & doc id 
id<- seq(1, length(corp))
docid<- paste(
  corp$lastname,
  corp$birth, 
  corp$party, 
  sep = "."
)
docnames(corp) <- id
print(corp)

##Tokens corpus into tokens (words or sentences) by word boundaries
toks <- tokens(corp, remove_punct = TRUE,
                    include_docvars = TRUE)
print (toks)

**Comment by koheiw** [comment]
Thanks for sharing the code. I am developing a version that is optimized for large corpus (https://github.com/quanteda/quanteda/pull/1966).
Can you install this version and try again?
```r
devtools::install_github("quanteda/quanteda", ref = "dev-tokens")
```
