### ISSUE TITLE
noLD issue (C++)

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#1971]
Received this today

> This concerns packages
> 
> DNAtools FFTrees JSM PerformanceAnalytics analogue bmotif clubSandwich
> diseq infer lightr mlr3measures portalr quanteda radiant.model round
> rrcov simplexdesign ssdtools xpose zalpha
> 
> which are showing a 'noLD' additional issue.
> 
> You should not be using == to compare floating-point quantities, and not relying on ix86/x86_64 extended-precision arithmetic.  'Writing R Extensions' discusses the use of appropriate tolerances (and help("==") that a tolerance is needed).
> 
> This will become more important as Apple transitions Macs to ARM-based hardware which does not have extended-precision instructions (currently, and AFAWK not planned although 'Apple Silicon' is a closed book).
> 
> Please correct ASAP and before Jul 23 to safely retain the package on CRAN.

**Comment by koheiw** [comment]
Any idea where it is happening?

**Comment by kbenoit** [comment]
Maybe here: https://www.stats.ox.ac.uk/pub/bdr/noLD/quanteda.out

**Comment by koheiw** [comment]
Says
```
See
  ‘/data/gannet/ripley/R/packages/tests-noLD/quanteda.Rcheck/00check.log’
for details.
```
I want know in which file...

**Comment by koheiw** [comment]
It is just change to `expect_equal()`, isn't it? Not really C++ problem.
```r
  ── 1. Failure: test textstat_entropy is working (@test-textstat_entropy.R#11)  ─
  unname(apply(mt, 1, entropy::entropy, unit = "log10")) not identical to textstat_entropy(mt, "documents", base = 10)[["entropy"]].
  Objects equal but not identical
```

**Comment by kbenoit** [comment]
I set the test conditions to `expect_equal()`, let's hope that does the trick.
