### ISSUE TITLE
Chinese Text Tokenisation Improvement

### ISSUE THREAD

**Issue by justinchuntingho** [quanteda/quanteda#1984]
## Current State

I believe the built in tokenisation for Chinese has room for improvement. Here are two real life cases:
```r
library(quanteda)
txt <- c(doc1 = "兒子生性病母倍感安慰",
         doc2 = "今日下午三時半，高等法院就行政長官對梁頌恆、游蕙禎兩人的立法會議員資格提出司法覆核之案件頒發判詞，並判梁、游二人敗訴，亦即二人之議員資格被撤銷。")
tokenize_word(txt)
```
The output:
```r
$doc1
[1] "兒子" "生"   "性病" "母"   "倍感" "安慰"

$doc2
 [1] "今日"     "下午"     "三"       "時半"     "，"       "高等法院"
 [7] "就"       "行政長官" "對"       "梁"       "頌"       "恆"      
[13] "、"       "游"       "蕙"       "禎"       "兩人"     "的"      
[19] "立法"     "會"       "議員"     "資格"     "提出"     "司法"    
[25] "覆核"     "之"       "案件"     "頒發"     "判"       "詞"      
[31] "，"       "並"       "判"       "梁"       "、"       "游"      
[37] "二人"     "敗訴"     "，"       "亦即"     "二人"     "之"      
[43] "議員"     "資格"     "被"       "撤銷"     "。"   
```
The first one is a tricky case from the title of a news article. The correct tokenisation should be `"兒子" "生性"   "病母"  "倍感" "安慰"`. This is a tricky case since "性病" is a valid noun (sexually transmitted disease) and therefore misidentified; the correct case should mean "生性" (well behavour) and  "病母" (sick mother). The second is an excerpt from a news article, the tokeniser is performing reasonably well but the names are mistaken:  "梁頌恆" "游蕙禎".

There can be two workarounds. The first one is what I usually do: use another package built for Chinese tokenisation (I find jieba performing quite well) and add whitespace between all words, and then use `what = "fastestword"` to tokenise by whitespace. Another workaround would be to use `textstat_collocations()` to identify the mistaken cases and join them like a multi-word expression (but it might not work if the terms are infrequent). An improved workaround would be to supplement the tokenisation with a user defined list of words, and use `text_compound()` to merge the tokens back together afterwards.

## Requested features
1. It would be great to have a wraper function to perform the above-mentioned workaround: `textstat_collocations()` first, and then `text_compound()` to merge tokens back together using a user-defined list of words (most other packages accept a .txt). Being able to accept a user-defined word list would be very useful especially for dealing with names since they are usually infrequent but known.

2. I am aware that the current tokeniser is dependent on stringi, but it would be great if we could choose our tokeniser. Jieba and Stanford Word Segmenter are two popular choices among people who analyse Chinese texts.

Thanks a lot for the great package!

**Comment by amatsuo** [comment]
I'm not sure this is what you want, but (as a developer of `spcayr`) I'd suggest using `spacyr`. New `spaCy` (v2.3) has a Chinese language model, and the tokenization works fine for doc1. Obviously named entity recognition is an issue for the model (I also tried udpipe but didn't perform any better, also jiebeR seems not particularly accurate). 

You could try a bigger language model (`zh_core_web_md` or `zh_core_web_sm`) which might work better.

``` r
library(spacyr)
# spacy_download_langmodel("zh_core_web_sm")
spacy_initialize("zh_core_web_sm")
#> Found 'spacy_condaenv'. spacyr will use this environment
#> successfully initialized (spaCy Version: 2.3.1, language model: zh_core_web_sm)
#> (python options: type = "condaenv", value = "spacy_condaenv")

txt <- c(doc1 = "兒子生性病母倍感安慰",
         doc2 = "今日下午三時半，高等法院就行政長官對梁頌恆、游蕙禎兩人的立法會議員資格提出司法覆核之案件頒發判詞，並判梁、游二人敗訴，亦即二人之議員資格被撤銷。")
tok <- spacy_tokenize(txt)
tok
#> $doc1
#> [1] "兒子" "生性" "病母" "倍感" "安慰"
#> 
#> $doc2
#>  [1] "今日"   "下午"   "三時半" "，"     "高等"   "法院"   "就"     "行政"  
#>  [9] "長官"   "對梁"   "頌恆"   "、"     "游蕙"   "禎兩人" "的"     "立法"  
#> [17] "會議"   "員"     "資格"   "提出"   "司法"   "覆核"   "之"     "案件"  
#> [25] "頒發"   "判詞"   "，"     "並"     "判梁"   "、"     "游二"   "人"    
#> [33] "敗訴"   "，"     "亦"     "即"     "二"     "人"     "之"     "議員"  
#> [41] "資格"   "被"     "撤銷"   "。"

quanteda::as.tokens(tok)
#> Tokens consisting of 2 documents.
#> doc1 :
#> [1] "兒子" "生性" "病母" "倍感" "安慰"
#> 
#> doc2 :
#>  [1] "今日"   "下午"   "三時半" "，"     "高等"   "法院"   "就"     "行政"  
#>  [9] "長官"   "對梁"   "頌恆"   "、"    
#> [ ... and 32 more ]
```

**Comment by koheiw** [comment]
Hi @justinchuntingho , we already have

1. `tokens_compound()`: takes a dictionary object constructed from a YAML file.
2. `as.tokens()`: converts list of character vector from external tokenizer (as in @amatsuo example).

At the end of the day, we should to send feed back to [CLRD](http://cldr.unicode.org/development/development-process#TOC-Filing-tickets) to improve segmentation by ICU.

**Comment by justinchuntingho** [comment]
@amatsuo @koheiw  Thanks a lot for your tips! I didn't realise the spacyr has a Chinese language model and the result looks promising!

**Comment by mpr1255** [comment]
This is fantastic and might I suggest  putting the spacyR suggestion somewhere in the docs for Chinese-language uses? I had been struggling with this tokenisation problem with Chinese and came up with far more awkward workarounds...

**Comment by kbenoit** [comment]
@mpr1255 We would be delighted if you wanted to write a short tutorial for this. We could include it in the spacy.quanteda.io documentation as an article.

**Comment by justinchuntingho** [comment]
On a related note, I have been working on a package that could be used in conjunction with `quanteda`. The idea is to collect a list of Cantonese names/entites (which often can't be tokenised correctly) as the basis with the option to add custom terms, pretokenised the sentences, and then pass it on to `quanteda` functions.

https://github.com/justinchuntingho/songotsti

**Comment by mpr1255** [comment]
> @mpr1255 We would be delighted if you wanted to write a short tutorial for this. We could include it in the spacy.quanteda.io documentation as an article.

Would love to! Let me get more acquainted with it all and I'll do a little tutorial with some reprex and whatnot.

**Comment by kbenoit** [comment]
@justinchuntingho @mpr1255 that all sounds great. Let me know if I can assist in any way.
