### ISSUE TITLE
textmodel functions gone

### ISSUE THREAD

**Issue by eduardolazzari** [quanteda/quanteda#1997]
## Describe the bug
Although I've uploaded the `quanteda` package in my R Library, no textmodel function is available to me (`textmodel`, `textmodel_wordfish`, `textmodel_wordscores`). I'm using the latest versions of R and RStudio, are those functions deprecated?

## Reproducible code
`library(quanteda)`

> Package version: 2.1.1
> Parallel computing: 2 of 4 threads used.
> See https://quanteda.io for tutorials and examples.
> 
> Attaching package: ‘quanteda’
> 
> The following objects are masked from ‘package:tm’:
> 
>     as.DocumentTermMatrix, stopwords
> 
> The following objects are masked from ‘package:NLP’:
> 
>     meta, meta<-
> 
> The following object is masked from ‘package:utils’:
> 
>     View
> 

Not even using ??textmodel_wordscores R is able to find a function.

Does anyone have an idea on why that is happening?

Thanks!

**Comment by kbenoit** [comment]
See https://github.com/quanteda/quanteda/blob/master/NEWS.md#changes-4

> All textmodels and related functions have been moved to a new package **quanteda.textmodels**.
