### ISSUE TITLE
trouble running quanteda

### ISSUE THREAD

**Issue by michellerh330** [quanteda/quanteda#2011]
## Describe the bug

0

Despite downloading quanteda, when I go to open it, it states that there is no package. Can anyone help?

I have tried so many things, but I am still getting error messages after installing quanteda (see code below).
Error in library(quanteda) : there is no package called ‘quanteda’

Error in library(quanteda) : there is no package called ‘quanteda’ aside from install.packages("quanteda")

I have tried the following (below), but none of them work. Thank you so much for reading my message and for your help.

Error: Failed to install 'quanteda' from GitHub: (converted from warning) unable to access index for repository https://RcppCore.github.io/drat/bin/macosx/contrib/4.0: cannot open URL 'https://RcppCore.github.io/drat/bin/macosx/contrib/4.0/PACKAGES'

```r
install.packages("quanteda", dependencies = T)
remotes::install_version("quanteda", version = "2.0.1", repos='https://demo.rstudiopm.com/cran/linux/xenial/latest')

devtools::install_github("quanteda/quanteda")

install.packages("quanteda", dependencies = T)

devtools::install_github("quanteda/quanteda", lib = "/kaggle/working")
```

**Comment by kbenoit** [comment]
1. Can you provide the output of `sessionInfo()`?
2. Can you provide the full output from running each of the above commands?

Why are you not installing the latest version from CRAN (v2.1.2)?

**Comment by michellerh330** [comment]
Dear Kenneth, 
Thanks so much for your answer. I was not able for some reason to install from cran but I found a workaround. However, I have another question for you. For some reason, stop words is not working for my corpus, entirely in French. I've been trying repeatedly over the past few days, but many words that should have been filtered simply are not. I am not sure if anyone else has a similar issue? I read somewhere that it could be because of the accents.

This is one example of code I tried, I would be extremely grateful for any advice you can offer as I've tried several approaches. Thank you so, so much!

text_corp <- quanteda::corpus(data, 
                             text_field="text")

head(stopwords("french"))

summary(text_corp)

my_dfm <- dfm(text_corp) 
myStemMat <- dfm(text_corp, remove = stopwords("french"), stem = TRUE, remove_punct = TRUE, remove_numbers = TRUE, remove_separators = TRUE)

myStemMat[, 1:5]

topfeatures(text_corp 20) 

In this last step, there are still words like "etre" (to be), "plus" (more), comme ("like"), avant ("before"), avoir ("to have")

I also tried to filter stop words in a different way, through token creation:

tokens <- 
  tokens(
    text_corp,
    remove_numbers = TRUE,
    remove_punct = TRUE,
    remove_symbols = TRUE,
    remove_url = TRUE,
    split_hyphens = TRUE,
    include_docvars = TRUE,
  )


mydfm <- dfm(tokens,
             tolower = TRUE,
             stem = TRUE,
             remove = stopwords("french")
             )


topfeatures(mydfm, 20)

**Comment by kbenoit** [comment]
You should file a StackOverflow issue on this, since it's a useful question but not one relevant to this issue.

Hint: Try `stringi::stri_trans_general(x, "Latin-ASCII")`.
