### ISSUE TITLE
Solve revdep issues with modularised v3 release

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#2016]
I have identified revdep issues with the following, so far, related to them calling functions from **quanteda** that will soon be relocated to the modular packages.

| package         | fix status         | new dependency     | branch                                                          |
|:-----------------|:--------------------|:--------------------|:-----------------------------------------------------------------|
| LSX             | Fixed GitHub but not CRAN | quanteda.textstats |              |
| collector       | PR submitted | quanteda.textstats | https://github.com/kbenoit/collector/tree/fix-quanteda-v3       |
| LexisNexisTools | Fixed on CRAN | quanteda.textstats |  |
| newsmap         |    Fixed on CRAN                | quanteda.textstats |                                                                 |

**Comment by koheiw** [comment]
newsmap and LSX has been updated on CRAN.
