### ISSUE TITLE
Add text_field to corpus.corpus

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda#2017]
If `text_field` is specified in `corpus.corpus()`, the corresponding field in docvars should be the texts.

**Comment by kbenoit** [comment]
This would be a good addition, to add `text_field` to `corpus.corpus()`. One use case: Say you had a corpus of articles, where the main text was the "text" and the rest docvars. But one docvar was the abstract text. If you wanted to change the abstract to the text, and make the former "text" a docvar, you could just call 

```r
corpus(oldcorpus, text_field = "abstract")
```

but then how do we shift the older text to the docvars while naming it appropriately?

**Comment by koheiw** [comment]
Just drop the original texts because `oldcorpus` has them.

**Comment by kbenoit** [comment]
Back in prehistoric days of quanteda v0.20 when we still wore bearskins, lived in caves, and used Windows 7, there was a toggle to move the "text" pointer between columns in the corpus of what was then a data.frame. We had more examples of these use cases, such as a corpus that had translations of the text, and we wanted to move between languages but not by making copies of the corpus. That sort of functionality would still be useful.

Maybe an optional field that specifies the name of the former text as docvar, but `NULL` by default, to drop it? or default to `former_text`?

**Comment by kbenoit** [comment]
Closing this issue. Easy to do already this way:

``` r
library("quanteda")
## Package version: 2.9.9000
## Unicode version: 10.0
## ICU version: 61.1
## Parallel computing: 12 of 12 threads used.
## See https://quanteda.io for tutorials and examples.

df <- data.frame(
  doc_id = paste0("d", 1:2),
  en = c("The room.", "The car."),
  fr = c("La chambre.", "La voiture.")
)

corp <- corpus(df,
  text_field = "en",
  meta = list(title = "Example for changing text of a corpus.")
)
corp
## Corpus consisting of 2 documents and 1 docvar.
## d1 :
## "The room."
## 
## d2 :
## "The car."
docvars(corp)
##            fr
## 1 La chambre.
## 2 La voiture.

corp2 <- convert(corp, to = "data.frame") %>%
  corpus(text_field = "fr", meta = meta(corp))
corp2
## Corpus consisting of 2 documents and 1 docvar.
## d1 :
## "La chambre."
## 
## d2 :
## "La voiture."
docvars(corp2)
##        text
## 1 The room.
## 2  The car.
meta(corp2)
## $title
## [1] "Example for changing text of a corpus."
```

<sup>Created on 2021-02-23 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>
