### ISSUE TITLE
Inconsistency in how size affect dfm_sample and corpus_sample

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda#2023]
As I add input value checks, I noticed that the default value for `size` are `dfm_sample(x, size = ndoc(x))` but `corpus_sample(x, size = NULL)`. The easy solution seemed setting the default to `ndoc(x)` in both, but it was not because of sampling by group, that it is only possible in `corpus_sample()`. i.e. `size` is passed to `quanteda:::sample_bygroup()` that interprets it as `size` within each group, so the result will become multiple times of larger than `ndoc()`. 

https://github.com/quanteda/quanteda/blob/65b31c9473c3290af7a3ef2593c011fbe1dffbf9/R/corpus_sample.R#L46-L53

We need to add group to `dfm_sample()` and make their behaviors and default values for `size` the same. This is also related to `bootstrap_dfm()`.

https://github.com/quanteda/quanteda/blob/65b31c9473c3290af7a3ef2593c011fbe1dffbf9/R/bootstrap_dfm.R#L78-L80

**Comment by kbenoit** [comment]
Excellent point. We need a way for the default to be the size of each group, or a single value, or a vector of length equal to the group sizes.

We probably want the default to be the vector `as.integer(table(groups))` but that's a bit ugly for an argument default.

**Comment by koheiw** [comment]
OK, let's set `size` to be `as.integer(table(groups))` when NULL (default).

**Comment by kbenoit** [comment]
That's a bit non-literal - since `NULL` actually means a vector of specific values - but we can explain this clearly in the documentation. We could also argue that it's appropriate since `groups = NULL` by default anyway, so this could not be the default when `groups = NULL`.

So OK but let's make sure we explain it very clearly.
