### ISSUE TITLE
Implement NSE consistently for functions that reference docvars

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#2028]
As it works for the `*_subset()` functions, we would want to extend this functionality to arguments that take `group`, or `by`, or (in `textstat_keyness()`), `target`/`reference`, etc.

- `subset` - (logical expression) - Status ✅
    - `corpus_subset()`
    - `tokens_subset()`
    - `dfm_subset()`
 
- `by`- (docvar name(s)) - Status ✅ (see #2081)
    - `corpus_sample()` 
    - `dfm_sample()`
    - `tokens_sample()`

- `groups` - (docvar name(s)) - Status ✅ (see #2081)
    - `dfm_group()`
    - `tokens_group()`
    - `dfm_group()`
    - `texts()` - See #2076 
    - `topfeatures()` - We will remove this

There are also methods in **quanteda.textmodels** -- anything with `y` -- and `textstat_keyness()` in **quanteda.textstats** where this functionality should be applied.

**Comment by kbenoit** [comment]
This is not so hard to do, and I have it working in a test branch, BUT: it breaks arguments such as:

```r
dfm_group(dfm(data_corpus_inaugural[1:8]), groups = "Party")
```

_although_ this already does not work:

```r
dfm_subset(dfm(data_corpus_inaugural[1:8]), subset = "Party" == "none")
```

**Comment by koheiw** [comment]
We are very good in NSE in `*_subset()`. I think the easiest way to upgrade `*_group()` is adding `by` with full NSE while deprecating `groups`.

**Comment by koheiw** [comment]
By the way, we should remove `groups` from `texts()` and `topfeatures()`.

**Comment by kbenoit** [comment]
OK I'll get the NSE for `*_group()` and `*_sample()` working, but with a trap and warning for passing docvar names as characters (but making them work).

Will remove `groups` from topfeatures. `textstat_frequency()` does this now.

On the groups from texts, I find this a really useful building function for some of my work. We could drop it if we were to write a `corpus_group()`. Should we add that and then drop the `groups` from `texts()`?

**Comment by koheiw** [comment]
It is probably the time to export `tokens_group()` and add `corpus_group()`. They will look very similar to each other.

**Comment by kbenoit** [comment]
Agreed. Let me keep working on the NSE for the existing ones first, we can add corpus_group once I've fixed the others.

The tricky thing is how to manage group interactions. This works easily now with `groups` being a vector of docvar names. It's not as straightforward however using NSE. With the `*_subset()` commands, it's simpler since `subset` takes an expression that evaluates to a logical, once it's evaluated within  the function. For NSE on multiple groups, I think we'd need to pass something like `groups = interaction(grp1, grp2)` where that only is evaluated within the function, once we can specify that it should take place within the "envir" of the docvars.

Here's some test code to play with illustrating the issue, for `tokens_group()`. (But the same issues will apply to the sample functions too.)

```r
corp <- corpus(c("a b c", 
                 "a b c",
                 "c b d",
                 "a d b",
                 "a a b",
                 "a d d"),
               docvars = data.frame(grp1 = rep(c(1:2), each = 3),
                                    grp2 = rep(c("a", "b", "c"), each = 2)))
toks <- tokens(corp)
dfmat <- dfm(toks)

# inspect
convert(corp)
dfmat

# tokens_group
# works
quanteda:::tokens_group(toks, groups = "grp1")
# works
quanteda:::tokens_group(toks, groups = rep(c(1:2), each = 3))
# works
quanteda:::tokens_group(toks, groups = c("grp1", "grp2"))

# for combinations
# fails
quanteda:::tokens_group(toks, groups = docvars(toks))
# works
quanteda:::tokens_group(toks, groups = interaction(docvars(toks)))

# for NSE
# can be made to work easily
quanteda:::tokens_group(toks, groups = grp1)
# no natural method for multiple groups with NSE, as above
quanteda:::tokens_group(toks, groups = c(grp1, grp2))
# this could be made to work
quanteda:::tokens_group(toks, groups = interaction(grp1, grp2))
```

**Comment by koheiw** [comment]
Interaction between variables made it difficult to address #2037. I fancy the idea to drop the function to group by two or more variables as far as users can do it manually.

**Comment by kbenoit** [comment]
I agree. We can make it so that users will have to do this: `groups = interaction(grp1, grp2)` and do it at their own risk. (Risk if they do that for continuous variables for instance.) OK so that's easier to do, and I should be able to solve this soon.
