### ISSUE TITLE
fcm.dfm() might be wrong

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda#2031]
When I was trying to increase test coverage, I noticed something suspicious. Can anyone explain why the occurance of the-the is 0 in `fcmat1` and 2 in `fcmat2`?
``` r
require(quanteda)
#> Loading required package: quanteda
#> Package version: 2.9.9000
#> Unicode version: 13.0
#> ICU version: 66.1
#> Parallel computing: 6 of 6 threads used.
#> See https://quanteda.io for tutorials and examples.
#> 
#> Attaching package: 'quanteda'
#> The following object is masked from 'package:utils':
#> 
#>     View
txt <- c("The quick brown fox jumped over the lazy dog.",
         "The dog jumped and ate the fox.")
toks <- tokens(char_tolower(txt), remove_punct = TRUE)
dfmat <- dfm(toks)
fcmat1 <- fcm(dfm_weight(dfmat, scheme = "boolean"))
fcmat1
#> Feature co-occurrence matrix of: 10 by 10 features.
#>         features
#> features the quick brown fox jumped over lazy dog and ate
#>   the      0     1     1   2      2    1    1   2   1   1
#>   quick    0     0     1   1      1    1    1   1   0   0
#>   brown    0     0     0   1      1    1    1   1   0   0
#>   fox      0     0     0   0      2    1    1   2   1   1
#>   jumped   0     0     0   0      0    1    1   2   1   1
#>   over     0     0     0   0      0    0    1   1   0   0
#>   lazy     0     0     0   0      0    0    0   1   0   0
#>   dog      0     0     0   0      0    0    0   0   1   1
#>   and      0     0     0   0      0    0    0   0   0   1
#>   ate      0     0     0   0      0    0    0   0   0   0

fcmat2 <- fcm(dfmat, count = "boolean")
fcmat2
#> Feature co-occurrence matrix of: 10 by 10 features.
#>         features
#> features the quick brown fox jumped over lazy dog and ate
#>   the      2     1     1   2      2    1    1   2   1   1
#>   quick    0     0     1   1      1    1    1   1   0   0
#>   brown    0     0     0   1      1    1    1   1   0   0
#>   fox      0     0     0   0      2    1    1   2   1   1
#>   jumped   0     0     0   0      0    1    1   2   1   1
#>   over     0     0     0   0      0    0    1   1   0   0
#>   lazy     0     0     0   0      0    0    0   1   0   0
#>   dog      0     0     0   0      0    0    0   0   1   1
#>   and      0     0     0   0      0    0    0   0   0   1
#>   ate      0     0     0   0      0    0    0   0   0   0
```
The code is originally from 

https://github.com/quanteda/quanteda/blob/a879166c493c948f861784bc439e5cc7c6248cbc/tests/testthat/test-fcm.R#L172-L182

The underlying code is 

https://github.com/quanteda/quanteda/blob/a879166c493c948f861784bc439e5cc7c6248cbc/R/fcm.R#L154-L172

The code is hard to understand, especially L156 and L159. What they are doing?

**Comment by kbenoit** [comment]
Here's my experience: Every time I let the fcm code sit for more than a month, it does my head in for about an hour trying to get back into it. It's like people smarter than we wrote it. Except we were those people!

But it's correct in these examples. In the first, we are looking for the co-occurrence of "the" with (another) "the".
```r
> dfm_weight(dfmat, scheme = "boolean")
Document-feature matrix of: 2 documents, 10 features (30.0% sparse).
       features
docs    the quick brown fox jumped over lazy dog and ate
  text1   1     1     1   1      1    1    1   1   0   0
  text2   1     0     0   1      1    0    0   1   1   1
```
Where "the" occurs in the context (by default, document), there is no other occurrence of "the", so the value is zero. So in the fcmat1, it's 0 + 0 = 0.

In the second case, the input is:
```r
> dfmat
Document-feature matrix of: 2 documents, 10 features (30.0% sparse).
       features
docs    the quick brown fox jumped over lazy dog and ate
  text1   2     1     1   1      1    1    1   1   0   0
  text2   2     0     0   1      1    0    0   1   1   1
```
so once in each document, "the" co-occurs with another "the", and the total in fcmat2 is 1 + 1 = 2.

**Comment by koheiw** [comment]
Thanks for explaining. Sounds like diagonal elements of a fcm should be all zero if `x` is a boolean dfm. 

Do you know why `x <- dfm_weight(x, "boolean") ` and `temp@x <- choose(temp@x, 2)` are needed? I might try to simplify the old code.

**Comment by kbenoit** [comment]
I'm not completely sure why we did it that way, but the code is made harder to follow by the reassignment of `temp` in line 169.  In\
https://github.com/quanteda/quanteda/blob/27e4344e67c224ae763a1724eef2a08dc8ebf0b4/R/fcm.R#L174-L176
lines 174-175 zero the miscomputed diagonal, which is then added back correctly from `temp`, which is a sparseMatrix containing just the (correctly computed) diagonal.

The `x <- dfm_weight(x, "boolean")` for Boolean counts is needed to compute the crossprod correctly - it needs to be 0/1 not counts.

`temp@x <- choose(temp@x, 2)` is the correct way to compute (diagonal) co-occurrences of terms with themselves, since it shows the combinations of each word co-occurring with other instances of itself.
```r
> choose(1:4, 2)
[1] 0 1 3 6
```
a single term has no self-cooccurrences, two terms have one, three have three, four have six.

🤯
