### ISSUE TITLE
Dictionary input to pattern2id

### ISSUE THREAD

**Issue by odelmarcelle** [quanteda/quanteda#2039]
## Describe the bug

My initial intention was to apply pattern matching to the types of a tokens object, to identify which types are "tagged" by the dictionary. After some search, I found out that the exported `pattern2id` could do the job.

However, I believe that dictionary input is not allowed for pattern2id, contrary to what the documentation suggests in `?pattern2id`.
Although no error occurs, the function returns an empty list without matching the dictionary values.

After browsing the source code, I found out a routine to manage dictionary input in the unexported `pattern2list`. Applying the routine before calling `pattern2id` indeed resolves the issues.

## Reproducible code

```r
library(quanteda)

toks <- tokens(data_corpus_inaugural)

## return an empty list
pattern2id(data_dictionary_LSD2015, types(toks))

## from `pattern2list`
x <- as.dictionary(data_dictionary_LSD2015)
temp <- quanteda:::flatten_dictionary(x, 1)
key <- names(temp)
temp <- quanteda:::split_values(temp, " ", "_")

## pattern matching occurs
head(pattern2id(temp, types(toks)))
```

I don't know if dictionary objects are meant to be used with `pattern2id`. If not, perhaps should this be clarified in the documentation `?pattern2id`? Or maybe insert the routine inside `pattern2id`.

On an unrelated note, thanks a lot for this amazing package!

Kind regards,
Olivier

**Comment by kbenoit** [comment]
Thanks @odelmarcelle ! `pattern2id()` is meant to be an internal function but still, it should work as advertised for developers.

This is one for @koheiw.

**Comment by odelmarcelle** [comment]
Thanks for the quick answer. This leads to quick question.. since these functions are designed to be internal, should I refrain from using them, possibly as part of a package?

**Comment by kbenoit** [comment]
This is a great question. Right now @koheiw and I are working on a version 3 release that modularises the statistics, model, and plotting functions into extension packages, with the core **quanteda**  being the one that most extension package developers would import and extend. This will inevitably include the functions keyworded as internal, but especially for those not exported, these are likely to undergo changes as we continue to tidy up the code and make the functions more robust and extensible.

We are currently working on some guidelines for developers, so your input here would be very useful. Perhaps if you described more about what you are seeking to do, we could advise?

Also note that CRAN will reject calls to functions in another package references by `:::`, but they can be assigned in your package as your own functions.  E.g. https://github.com/quanteda/quanteda.textstats/blob/master/R/utils.R

**Comment by koheiw** [comment]
`pattern2id` does not know hot to handle dictionary, so `pattern2list` is the function to be used (although not exported). I will make it more accessible if there are people who want to use. Thanks for filing an issue.

**Comment by odelmarcelle** [comment]
# Long story
I'd like to implement a Joint Sentiment/Topic (JST) model in a package. This is similar to https://github.com/maxboiten/rJST, but due design difference I started to work on my own package.

I use a `tokens` object as the main input for texts in the model. Through `unclass()`, it gives a nice list of integers to be processed with C++ code.

In addition, a JST model can incorporate sentiment information (i.e., list of positive or negative words). Currently, I import sentiment information as vector of size equal to `type(toks)`, filled with -1, 1 depending on the sentiment orientation of each type (basically a factor).

This factor needs to be created by matching between the types of a tokens and an external lexicon. Until now, I've created this factor using `grep()` for wildcard pattern matching from lexicons in `data.table` format. My naive approach is however slow.

For consistency (and speed), I'd like to take a `dictionary` object as a second input for my functions. I then need to rebuild my factor of sentiment orientation corresponding to each type. To not reinvent the wheel, I looked for quanteda-ways of doing this.

# Short story

I'd like to obtain a factor representing to which dictionary entry the types of a tokens belong.
For example:

```r
library(quanteda)

txt <- c(doc1 = "A sentence, showing how tokens() works.",
         doc2 = "A second sentence, for this example only.")

toks <- tokens(txt)

dict <- dictionary(list(positive = c("sent*", "example", "tokens"), negative = c("second", "only")))
matches <- quanteda::pattern2id(dict, types(toks), "glob", TRUE) ## I don't know why this is suddenly working

types_orientations <- rep(NA, length(types(toks)))
types_orientations[matches$positive] <- 1
types_orientations[matches$negative] <- -1

types(toks)
types_orientations
```

**Comment by kbenoit** [comment]
Have you seen [**quanteda.sentiment**](https://github.com/quanteda/quanteda.sentiment)? You can set the polarity for dictionary categories, and there are some supporting functions for working with that. It's still under development but could be useful.

I think it makes a lot of sense to use **quanteda** functions since you can work with that dictionary format and use all of the matching and lookup functions for dictionaries.

**Comment by odelmarcelle** [comment]
The polarised dictionary of quanteda.sentiment are probably a better input! I'll look how to work with them. However, I still need to use `pattern2id`/`pattern2list` to obtain matches with the tokens types.

I've currently built something around `pattern2list` that seems promising. I'll pay attention to your future release in case the logic of this function changes.
