### ISSUE TITLE
Consider removing "shortcut" methods

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#2058]
Right now we have lots of methods for constructing things that skip the tokenisation step. This is convenient, but leads to inconsistencies and in the case of #2045, inefficiencies. We should give serious consideration to dropping methods for pre-tokenization objects that allow users to do things that require tokenization internally.

https://github.com/quanteda/quanteda/pull/2045#issuecomment-779235429, is correct, because of memory management, but only if there is a tokens object for the tokens attribute of the new kwic object to point to. When we run kwic on a corpus or character, however, the tokens inside the kwic will be a duplicate.

Which ones? These are the methods for corpus and character that allow the user to leapfrog tokenization.

- `dfm()`, `fcm()`. Removing `dfm.tokens()` would mean we could also remove some of the convenience arguments (see #1602)
- `kwic()`
- `ntoken()`, `ntype()`, `nsentence()`. These are very useful but we could keep equivalent functionality in `textstat_summary.corpus()`, with a health warning.

Actually that list is not as bad as I thought! But we would have to give serious consideration to the code we would break, and consider deprecating these first.

The only reason to keep the corpus methods would be in case we implement tokenization within a corpus, similar to what happens with you call `nlp()` from spaCy, but even then we would probably want users to extract them into a tokens object after applying `remove_*` options.

Here's another thought: We could introduce a new `quanteda_option(strict = TRUE)` in v3 that when TRUE, would not allow skipping the creation of a tokens object. When `FALSE`, it will still allow the earlier behaviour. This provides a way to provide backward compatibility without all of the deprecation warnings that simply using `.Deprecate()` would create. But we'd make users turn this on, so that they are at least aware.

**Comment by koheiw** [comment]
I think it is a good idea to add `strict = TRUE` (or `compatibility = "v2"`) in the package option or the function itself for this and other changes. With the option, we can remove `dfm.character()` and `dfm.corpus()` straight away.
