### ISSUE TITLE
Problem with LSD dictionary and tokens_lookup when ngrams are created

### ISSUE THREAD

**Issue by mscottodivettimo** [quanteda/quanteda#2059]
Dears,

I am using quanteda to run a sentiment analysis with the LSD sentiment dictionary by Young and Soroka, but when i tokenise the corpus i ngrams (I am using 4-grams, but the problem remains even for any n>1) the tokens_lookup function finds more matches than there really are. See example below.

```r
library(quanteda) 
library(corpustools)

text<-c('originally these notes represented a promise to pay a fixed amount of precious metal. the first of these currency standards was based on silver, but in the early 18th century gold became the standard for fixing the value of the pound, until 1931.')

c<-corpus(text)

tcorp_ex=create_tcorpus(text)
tcorp_ex$code_dictionary(data_dictionary_LSD2015,column='sent',sep=' ',case_sensitive=F)
tcorp_ex$set('sentiment',1,subset=sent %in% c('positive'))
browse_texts(tcorp_ex,scale='sentiment',select='random')
# So we should have only 2 positive keys in the text

# Create tokens and 4-grams
tok<-tokens(c,remove_numbers=T,remove_punct=T,remove_symbols=T) %>%
  tokens_ngrams(n=1:4,concatenator="_")

# dfm_lookup on tokenised corpus
print(dfm_lookup(dfm(tok),data_dictionary_LSD2015,case_insensitive=T,valuetype="glob")) # Not fine, finds 5

# tokens_lookup on tokenised corpus
print(convert(dfm(tokens_lookup(tok,data_dictionary_LSD2015,case_insensitive=T,valuetype="glob")),to='data.frame')) # Not fine, finds 5

# Why? 
w<-tokens_lookup(tok,data_dictionary_LSD2015,case_insensitive=T,valuetype='glob',capkeys=T,exclusive=F)
w[["text1"]]

```
Precious is a positive key, so it is matched (13th element). However, it is matched also when it appears in "precious_metal" (55th element) and when part of 3-grams. Same for "gold". I guess that it is because the dictionary key contains the *, so my question is how I can apply the LSD dictionary to a tokenised corpus where ngrams have been constructed without "double-counting" these keys?
dfm_lookup() method leads to correct count if applied on corpus (not tokens) directly, but as I need 4-grams (I think that) it is not a viable solution. nested_scope option in tokens_lookup() does not lead to desired results either.

Any sort of hint will be much appreciated.

Best wishes,

Michele

**Comment by kbenoit** [comment]
This really belongs on StackOverflow... But since it could be the basis for a feature request, we can look at it here. What are you expecting from applying a dictionary to ngrams? If you could indicate what output you would prefer from the below simplified example, we will have a more precise idea of what you mean.

``` r
library("quanteda")

# the pattern includes a wildcard
grep("^precio", data_dictionary_LSD2015$positive, value = TRUE)
## [1] "precious*"

txt <- "amount of precious metal.  the first"

toks <- tokens(txt,
  remove_numbers = TRUE, remove_punct = TRUE,
  remove_symbols = TRUE, padding = TRUE
) %>%
  tokens_ngrams(n = 1:2, concatenator = "_")

toks
## Tokens consisting of 1 document.
## text1 :
##  [1] "amount"         "of"             "precious"       "metal"         
##  [5] "the"            "first"          "amount_of"      "of_precious"   
##  [9] "precious_metal" "the_first"

tokens_lookup(toks, data_dictionary_LSD2015, exclusive = FALSE)
## Tokens consisting of 1 document.
## text1 :
##  [1] "amount"      "of"          "POSITIVE"    "metal"       "the"        
##  [6] "first"       "amount_of"   "of_precious" "POSITIVE"    "the_first"
```

Yes, it matched "precious_metal". What would you have wanted instead?

<sup>Created on 2021-02-17 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by mscottodivettimo** [comment]
Just figured out my mistake. I did not realise that I did not need to create ngrams in the first place, as when I tokenise the corpus the order of the features remains the same, so I could match multi-word keys even without creating ngrams...

Thanks anyway for your very quick reply, and sorry I the post did not really belong to github :)
