### ISSUE TITLE
Default tokenizer splits multiple ##

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#2060]
Did we intend this??

```r
> tokens("This is a ##TEST")
Tokens consisting of 1 document.
text1 :
[1] "This"  "is"    "a"     "#"     "#TEST"
```

**Comment by koheiw** [comment]
Yes
```
$pattern_hashtag
[1] "#\\w+#?"
```

**Comment by kbenoit** [comment]
Of course...

But it means the default tag format for `corpus_segment()` does not survive our default tokenizer, but that should be ok since they are designed to work pre-tokens anyway (using `corpus_segment()` on a corpus, obviously).
