### ISSUE TITLE
make `groups` required with no default

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#2093]
Current default is `docid(x)`, although this is not documented. As per the discussion starting https://github.com/quanteda/quanteda/pull/2091#issuecomment-803298706, we should either:

- require it, with no default
- change to `groups = docid(x)` but then document `docid(x)`

Alternative is to leave as is, which is how 2.1.2 operated as well, but this is inconsistent and at least needs documentation.

**Comment by koheiw** [comment]
I and my students are the heaviest users of the grouping function. If it raises error when `groups` is not given, it should be fine as users notice the change. Setting `docid(x)` as the visible default value also helps to promote the the package's bi-directional reshaping capability.

**Comment by kbenoit** [comment]
OK so shall I change this to `groups = docid()` for the three `groups` functions, and document `docid()` more clearly?
