### ISSUE TITLE
Make window a two-element vector

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#2105]
As implemented in `tokens_select()`, we could add this to the `window` argument in:

- [ ] `kwic()`
- [x] `fcm()` - since `ordered = TRUE` is already like `window = c(0, 5)`. See workaround [here](https://stackoverflow.com/questions/67055841/fcm-function-of-quanteda-any-possibility-of-selecting-one-side-of-the-window).
- [x] `tokens_compound()` - in fact, this looks like it's already available in `qatd_cpp_tokens_compound()`

**Comment by koheiw** [comment]
I don't think we need window to be two-elements in `kwic()`, but you can do it easily.

**Comment by kbenoit** [comment]
I agree we don't need it in kwic. Let's close this.
