### ISSUE TITLE
textplot_ & textstat_ functions appear to not be working

### ISSUE THREAD

**Issue by tbritton44** [quanteda/quanteda#2108]
New to the quanteda package and am excited to get to know it better.  

From what I gather there is a bug with the textplot_ & textstat_ functions. Specifically, I am trying to make a word cloud--though key words would suffice so was also trying textstat_keyness, receiving the same error: Error in textplot_wordcloud(wordcloud) : 
  could not find function "textplot_wordcloud". I tried uninstalling and reinstalling the package to no avail. Here is my code.

`set.seed(30)
> wordcloud <- transcript_corpus %>%
+     tokens(remove_punct = TRUE) %>%
+     tokens_remove(stopwords("en")) %>%
+     dfm() %>%
+     dfm_trim(min_termfreq = 3) 
> 
> textplot_wordcloud(wordcloud)`
Error in textplot_wordcloud(wordcloud) : 
  could not find function "textplot_wordcloud"

**Comment by kbenoit** [comment]
See https://github.com/quanteda/quanteda/blob/master/NEWS.md#changes-and-additions

`textplot_wordcloud()` is now in **quanteda.textplots**.

**Comment by tbritton44** [comment]
Great, thanks!
