### ISSUE TITLE
Function "nsyllable" missing from latest 3.0 release?

### ISSUE THREAD

**Issue by schaubst** [quanteda/quanteda#2114]
I recently updated to version 3.0 of the package, and it seems that the "nsyllable" function is no longer included in the package.

I'm referring to this function here: https://quanteda.io/reference/nsyllable.html

I cannot find any info about its removal in the changelog.

Am I missing something here? A brief reply would be greatly appreciated, thank you!

**Comment by kbenoit** [comment]
It its own package now. https://github.com/quanteda/nsyllable

**Comment by schaubst** [comment]
Thank you kindly for the very quick response! I missed that info.
