### ISSUE TITLE
Accented characters trigger error in kwic?

### ISSUE THREAD

**Issue by jkrybicki** [quanteda/quanteda#2115]
## Describe the bug

When I run kwic on a collection of texts in Polish, and the pattern includes any of the following non-English characters, ąćęłńóśźżĄĆĘŁŃÓŚŹŻ, the pattern is not found and the function returns the message: 
Keyword-in-context with 0 matches.
It works fine when the search pattern does NOT contain any of those characters.

## Reproducible code
my.corpus <- readtext("corpus/*.txt", cache = FALSE, encoding="UTF-8")
my_corpus <- corpus(my.corpus)  ## this is attached as .rds
kwic(tokens(my_corpus), pattern = "biały")

Please paste minimal code that reproduces the bug. If possible, please upload the data file as `.rds` (zipped).
r
# paste here #
[my_data.zip](https://github.com/quanteda/quanteda/files/6477387/my_data.zip)

## Expected behavior

Find the patterns, I guess :-)

## System information

Please run `sessionInfo()` and paste the output.

# paste here #
R version 4.0.5 (2021-03-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=Polish_Poland.1250  LC_CTYPE=Polish_Poland.1250   
[3] LC_MONETARY=Polish_Poland.1250 LC_NUMERIC=C                  
[5] LC_TIME=Polish_Poland.1250    
system code page: 1252

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] readtext_0.80           forcats_0.5.1           stringr_1.4.0          
 [4] dplyr_1.0.5             purrr_0.3.4             readr_1.4.0            
 [7] tidyr_1.1.3             tibble_3.1.0            ggplot2_3.3.3          
[10] tidyverse_1.3.0         stylo_0.7.4             quanteda.textplots_0.94
[13] quanteda_3.0.0         

loaded via a namespace (and not attached):
 [1] httr_1.4.2          jsonlite_1.7.2      splines_4.0.5      
 [4] modelr_0.1.8        RcppParallel_5.1.4  assertthat_0.2.1   
 [7] pamr_1.56.1         cellranger_1.1.0    pillar_1.5.1       
[10] backports_1.2.1     lattice_0.20-41     glue_1.4.2         
[13] digest_0.6.27       rvest_1.0.0         colorspace_2.0-0   
[16] Matrix_1.3-2        pkgconfig_2.0.3     ISOcodes_2021.02.24
[19] broom_0.7.5         tsne_0.1-3          haven_2.3.1        
[22] scales_1.1.1        proxy_0.4-25        generics_0.1.0     
[25] farver_2.1.0        ellipsis_0.3.1      withr_2.4.1        
[28] cli_2.3.1           survival_3.2-10     magrittr_2.0.1     
[31] crayon_1.4.1        readxl_1.3.1        ps_1.6.0           
[34] stopwords_2.2       fs_1.5.0            fansi_0.4.2        
[37] nlme_3.1-152        xml2_1.3.2          class_7.3-18       
[40] tools_4.0.5         data.table_1.14.0   hms_1.0.0          
[43] lifecycle_1.0.0     tcltk2_1.2-11       munsell_0.5.0      
[46] reprex_1.0.0        cluster_2.1.1       compiler_4.0.5     
[49] e1071_1.7-6         rlang_0.4.10        grid_4.0.5         
[52] rstudioapi_0.13     tcltk_4.0.5         labeling_0.4.2     
[55] gtable_0.3.0        DBI_1.1.1           R6_2.5.0           
[58] lubridate_1.7.10    utf8_1.2.1          fastmatch_1.1-0    
[61] ape_5.4-1           stringi_1.4.6       parallel_4.0.5     
[64] Rcpp_1.0.6          vctrs_0.3.6         dbplyr_2.1.0       
[67] tidyselect_1.1.0 

## Additional info

Please add any other information about the issue.

**Comment by koheiw** [comment]
Thanks @jkrybicki. Seems that we are doing too much Unicode normalization.
```r
> stringi::stri_trans_nfc("spływało")
[1] "splywalo"
```
https://github.com/quanteda/quanteda/blob/51f073792d65dace08dd484fd1cb745bde7be7a9/R/pattern2fixed.R#L36

Sorry @gagolews for not using your package for your language. Which normalization should I use? 😄

**Comment by kbenoit** [comment]
Good to catch this!

**Comment by kbenoit** [comment]
Actually this appears to be very much dependent on the platform. Works fine on my system (macOS).

``` r
library("quanteda")
## Package version: 3.0.9000
## Unicode version: 13.0
## ICU version: 69.1
## Parallel computing: 12 of 12 threads used.
## See https://quanteda.io for tutorials and examples.

my_corpus <- readRDS("~/Downloads/my_data.rds")
Encoding(my_corpus)
## [1] "UTF-8" "UTF-8"
print(my_corpus)
## Corpus consisting of 2 documents.
## orzeszkowa_anastazya_1910.txt :
## "ANASTAZYA ANASTAZYA I. Czerwone słońce sierpniowe spływało p..."
## 
## orzeszkowa_antonina_1886.txt :
## "Eliza Orzeszkowa Panna Antonina — Gdybym miała dwanaście cór..."

kwic(tokens(my_corpus), pattern = "biały", window = 2)
## Keyword-in-context with 4 matches.                                                                 
##  [orzeszkowa_anastazya_1910.txt, 22684]     jednej ręce | biały |
##  [orzeszkowa_anastazya_1910.txt, 28907]         daleki, | biały |
##  [orzeszkowa_anastazya_1910.txt, 38532]        w marmur | biały |
##  [orzeszkowa_anastazya_1910.txt, 47731] spuszczonemi na | biały |
##                    
##  kubek gliniany    
##  śnieg zapatrzonemi
##  i niemy           
##  fartuch,


stringi::stri_trans_nfc("spływało")
## [1] "spływało"
packageVersion("stringi")
## [1] '1.6.1'
```

**Comment by koheiw** [comment]
True, above was on Windows. On Linux
```r
> stringi::stri_trans_nfd("spływało")
[1] "spływało"
```

**Comment by koheiw** [comment]
It is not only the Unicode normalization function...
```r
> stringi::stri_trim("spływało")
[1] "splywalo"
```

**Comment by koheiw** [comment]
Not even a stringi problem on Windows.
```r
> cat("spływało")
splywalo
```
I don't know if this is only in the latest R but the only solution for @jkrybicki at the moment is to use Mac or Linux...

**Comment by jkrybicki** [comment]
…and that’s exactly what I was worried about: the combination of Windows in non-English locales + R. We do seem to have found some workarounds in our R package, stylo: https://github.com/computationalstylistics/stylo

Thanks anyway,

Jan

 

Od: Kohei Watanabe ***@***.***> 
Wysłano: piątek, 14 maja 2021 12:28
Do: quanteda/quanteda ***@***.***>
DW: Jan Rybicki ***@***.***>; Mention ***@***.***>
Temat: Re: [quanteda/quanteda] Accented characters trigger error in kwic? (#2115)

 

Closed #2115 <https://github.com/quanteda/quanteda/issues/2115> .

**Comment by gagolews** [comment]
Yes! I replaced all Unicode chars in Rd files with their escaped  \uc0de ‘s . That should help, seems like an issue with R itself.

Marek Gagolewski
https://www.gagolewski.com

*Sent from my mobile device. Please excuse my brevity.*

**Comment by koheiw** [comment]
By the way, congratulate @gagolews on the new life in Australia. You deserve a lot of :sun_with_face: Glad to have you in the same timezone!

**Comment by gagolews** [comment]
Thanks :blush: 

But still — Hello from the other side :wink:

**Comment by koheiw** [comment]
@jkrybicki possible workaround is write Unicode characters in a file and load to R using `dictionary()` or something else.

**Comment by jkrybicki** [comment]
Thanks; what I did was simply to use Unicode codes (\u0105 etc.) in search patterns; works like a charm, of course. Before that, I tried using my old Ubuntu computer, but 1. installing quanteda there was a pain (there were always some Ubuntu libraries missing) and 2) because I work on large texts (novels), R stopped working every time I tried. This does not happen on my newer Windows machine with more memory.

Anyway, I would like to thank you guys for your quick reaction and help; that does not always happen in the case of R packages!

Best,

Jan

@jkrybicki <https://github.com/jkrybicki> 

 

Od: Kohei Watanabe ***@***.***> 
Wysłano: niedziela, 16 maja 2021 01:01
Do: quanteda/quanteda ***@***.***>
DW: Jan Rybicki ***@***.***>; Mention ***@***.***>
Temat: Re: [quanteda/quanteda] Accented characters trigger error in kwic? (#2115)

 

@jkrybicki <https://github.com/jkrybicki>  possible workaround is write Unicode characters in a file and load to R using dictionary() or something else.

**Comment by gagolews** [comment]
By the way, non-ASCII code points can be convergeted to `\uc0de`'s automagically by calling:

```r
cat(stringi::stri_trans_general("zażółć gęślą jaźń ©ß→µ😇🤦", "[^\\u0001-\\u007f] hex/c"))
## za\u017C\u00F3\u0142\u0107 g\u0119\u015Bl\u0105 ja\u017A\u0144 \u00A9\u00DF\u2192\u00B5\U0001F607\U0001F926
```

**Comment by jkrybicki** [comment]
Brilliant!

JR

 

Od: Marek Gagolewski ***@***.***> 
Wysłano: środa, 19 maja 2021 03:48
Do: quanteda/quanteda ***@***.***>
DW: Jan Rybicki ***@***.***>; Mention ***@***.***>
Temat: Re: [quanteda/quanteda] Accented characters trigger error in kwic? (#2115)

 

By the way, non-ASCII code points can be convergeted to \uc0de's automagically by calling:

cat(stringi::stri_trans_general("zażółć gęślą jaźń ©ß→µ😇🤦", "[^\\u0001-\\u007f] hex/c"))
 
## za\u017C\u00F3\u0142\u0107 g\u0119\u015Bl\u0105 ja\u017A\u0144 \u00A9\u00DF\u2192\u00B5\U0001F607\U0001F926

**Comment by kbenoit** [comment]
\U0001F44D

**Comment by jkrybicki** [comment]
Still, this doesn’t help: any (of my) attempts to convert this to a list of patterns to feed to kwic result in double backslashes, and the strings are rejected by kwic. You gotta love what non-English Windows 10 and R can do together! BTW, changing R locale doesn’t help too.

The good news is making a dictionary out of a UTF-8 text file and using it as pattern works perfectly, and that’s what I’ll be using on my students.

Best,

Jan

http://info.filg.uj.edu.pl/~jrybicki/

 

Od: Marek Gagolewski ***@***.***> 
Wysłano: środa, 19 maja 2021 03:48
Do: quanteda/quanteda ***@***.***>
DW: Jan Rybicki ***@***.***>; Mention ***@***.***>
Temat: Re: [quanteda/quanteda] Accented characters trigger error in kwic? (#2115)

 

By the way, non-ASCII code points can be convergeted to \uc0de's automagically by calling:

cat(stringi::stri_trans_general("zażółć gęślą jaźń ©ß→µ😇🤦", "[^\\u0001-\\u007f] hex/c"))
 
## za\u017C\u00F3\u0142\u0107 g\u0119\u015Bl\u0105 ja\u017A\u0144 \u00A9\u00DF\u2192\u00B5\U0001F607\U0001F926

**Comment by kbenoit** [comment]
👍 Wish I could test this, but I don't have the non-English Windows. Crazy that these encoding and locale issues are still present in 2021 though. Glad you found a workaround.

BTW on your web site, the top-level "Computational Stylistics" menu option link is broken.

**Comment by jkrybicki** [comment]
Thanks. Will attend to it.

Best,

Jan

 

Od: Kenneth Benoit ***@***.***> 
Wysłano: czwartek, 20 maja 2021 09:36
Do: quanteda/quanteda ***@***.***>
DW: Jan Rybicki ***@***.***>; Mention ***@***.***>
Temat: Re: [quanteda/quanteda] Accented characters trigger error in kwic? (#2115)

 

👍 Wish I could test this, but I don't have the non-English Windows. Crazy that these encoding and locale issues are still present in 2021 though. Glad you found a workaround.

BTW on your web site, the top-level "Computational Stylistics" menu option link is broken.

**Comment by jkrybicki** [comment]
Sorry for being a pest: I’ve just noticed something weird.

1.	I input words with non-English characters (like: odparł) that display correctly in the Windows R GUI into a list
2.	I use the list as pattern, kwic registers no hits. 
3.	When I run a series of simple gsubs, like: 

lista<-gsub("ł","\u0142",lista), 

the characters in lista display in the same correct way as if nothing has changed…

4.	…but when I then use this gsubbed list as pattern, kwic correctly registers all the hits. 

Interesting, huh?

If you’re bored with this, just don’t reply, it’s OK.

Best,

Jan

 

Od: Kenneth Benoit ***@***.***> 
Wysłano: czwartek, 20 maja 2021 09:36
Do: quanteda/quanteda ***@***.***>
DW: Jan Rybicki ***@***.***>; Mention ***@***.***>
Temat: Re: [quanteda/quanteda] Accented characters trigger error in kwic? (#2115)

 

👍 Wish I could test this, but I don't have the non-English Windows. Crazy that these encoding and locale issues are still present in 2021 though. Glad you found a workaround.

BTW on your web site, the top-level "Computational Stylistics" menu option link is broken.

**Comment by gagolews** [comment]
So, wait, does this problem occur when you call `gsub()`?
Can you reproduce it using `stringi::stri_replace_all_regex()`?

**Comment by jkrybicki** [comment]
No: the other way round! Calling gsub() fixes the problem without seeming to fix it: after gsub(), the Polish characters display onscreen just as they did before calling gsub() (as if nothing had changed); but when the gsubbed list is used as pattern, kwic correctly finds the list’s elements in my texts (which it does NOT on the list before calling gsub()).

And yes, the same thing happens when I use stri_replace_all_regex() instead of gsub().

JR 

 

Od: Marek Gagolewski ***@***.***> 
Wysłano: piątek, 21 maja 2021 01:24
Do: quanteda/quanteda ***@***.***>
DW: Jan Rybicki ***@***.***>; Mention ***@***.***>
Temat: Re: [quanteda/quanteda] Accented characters trigger error in kwic? (#2115)

 

So, wait, does this problem occur when you call gsub()?
Can you reproduce it using stringi::stri_replace_all_regex()?

**Comment by gagolews** [comment]
So can it that be a bug in R itself? Can you generate a minimal reproducible example using only calls to base R functions?
