### ISSUE TITLE
topfeature function return weird result

### ISSUE THREAD

**Issue by killno1991** [quanteda/quanteda#2117]
I am constructing a network based on corpus using a keyword (anti-elab movment etc). Hence, when I constructed the fcm of the corpus, I expected the keyword will come out as the top feature. However, the keyword was not within the top feature. I suspect that it is because the feature is calculated based on tf-idf? Can I change the way to calculate the top features?

**Comment by kbenoit** [comment]
Can you illustrate what you are trying to do, using a keyword and an analysis of some of the inaugural corpus texts, so that we can reproduce the issue?

**Comment by killno1991** [comment]
I created a corpus based on a keyword, which means all documents within the corpus contain that keyword. When I create the dfm, the keyword still maintained the highest frequency when I check it using textstat_frequency. When I create a fcm, the fcm contains the keyword. Then I would like to create a network using the fcm, and to make my network comprehensive, I used topfeature to filter the top 100 features. When I use this feature a year ago, the keyword occurred in the top 100 features. However, when I created another network today using the same dfm, I discover that the keyword disappeared from the top 100 features. I tried different settings, but the keyword still missing from the top 100 features. 
Because the keyword appeared in all documents, I suspected the keyword disappeared because it is calculated based on tf-idf, but I am not sure. 
Sorry for my incapability to provide more insight due to my lack of programming ability.
P.S. Prof. Benoit, your work introduces me to the world of text analysis. It is my gratitude to discuss with (annoy) you

**Comment by kbenoit** [comment]
Since dfm_tfidf() does not work on fcm objects, I can only think that you have created a dfm first to which you are applying `dfm_tfidf()` before creating the fcm. If so, then the short answer is that you are right: `dfm_tfidf()` will zero-weight any feature that occurs in all documents.

Here's a reconstruction:

``` r
library("quanteda")
## Package version: 3.0.9000
## Unicode version: 13.0
## ICU version: 69.1
## Parallel computing: 12 of 12 threads used.
## See https://quanteda.io for tutorials and examples.

toks <- tokens(data_corpus_inaugural) %>%
  tokens_select("war", window = 5) %>%
  tokens_subset(ntoken(.) > 0)
fcmat <- fcm(toks)
topfeatures(fcmat, n = 5)
##  war    ,    .  the   in 
## 8888 1691 1685 1181 1120

fcmat2 <- dfm(toks) %>%
  dfm_tfidf() %>%
  fcm()
topfeatures(fcmat2, n = 5)
##      late  colonies    render prisoners concluded 
##  459.2246  410.6526  401.4231  369.2471  347.3016
```

The solution? Don't weight by tf-idf.

**Comment by killno1991** [comment]
The problem is, I construct my dfm normally, and this is the reason why the fcm constructed a year ago perform normally. The change happened after the recent big upgrade, therefore I suspected something happened in the code.

**Comment by kbenoit** [comment]
Well, I was trying to guess what you might have done, but without your code, it's only a guess. If you can include that code, then we can identify the problem and determine its cause.

**Comment by killno1991** [comment]
``
library(quanteda)
library(quanteda.textmodels)
library(quanteda.textplots)
library(quanteda.textstats)
library(igraph)
library(skynet)

cps_case_dfm1 = dfm_trim(Anchor_baby_focus_dfm, min_termfreq = 1000, min_docfreq = 10)
case_fcm=fcm(cps_case_dfm1 , context = "document",count = "boolean", span_sentence = FALSE, tri = T)
top_filter <- names(topfeatures(case_fcm, 100))
case_fcm_1 <- fcm_select(case_fcm, pattern = top_filter)

graph_1 = as.igraph(case_fcm_1,mode = "upper", weighted = T)
graph_2= disparity_filter(graph_1, alpha = 0.1)
write_graph(graph_2, "AB_focus_boolean2.gml", format="gml")


This is my code. The dfm is about the online discussion of anchor babies, hence the term 'anchor babies (in Chinese) is the most frequent term. If I directly export the fcm into a graph, the term 'anchor babies' exists and being the largest node. However, once I apply the top_filter, the term 'anchor_babies' disappears. 

Not sure if this is the code you need.

**Comment by kbenoit** [comment]
We still can't reproduce your problem from this, as you have not included the data objects. But it sounds like anchor_babies is not included in your `top_filter`. Note that the centrality of a term in the co-occurrence network is not the same as being the top most frequent feature. Have you considered `textplot_network()` for your network plot instead of your usage above?
