### ISSUE TITLE
quanteda convert to STM object

### ISSUE THREAD

**Issue by mimshiran** [quanteda/quanteda#2119]
## Consider StackOverflow

If you have a question on how to use **quanteda**, please first search [our StackOverflow channel](https://stackoverflow.com/questions/tagged/quanteda). If it does not solve you problem, please post your question there. We monitor the channel and should respond to your question very quickly. 

## Report a bug

If you know how to use **quanteda** but not seeing what you expect, please check [existing issues](https://github.com/quanteda/quanteda/issues?utf8=%E2%9C%93&q=is%3Aissue). If it does not help, please [open an issue](https://github.com/quanteda/quanteda/issues/new?template=bug_report.md).

## Other questions

Please write your questions here.

When I convert a corpus processed using quanteda to stm object, the text field is missing from the stm object. Am I doing anything wrong? I need the 'docs' for findThoughts function of stm.
Thanks 

df <- quanteda::corpus(data, text_field = 'text')

dfm_corp <- df %>% 
  tokens(remove_numbers = TRUE, remove_punct = TRUE,  remove_url = TRUE) %>%
  tokens_remove(pattern = stopwords("zh_cn", source = "marimo"), min_nchar = 2) %>% 
  dfm() %>% 
  dfm_remove(pattern = c("*.tt", "*.uk", "*.com", "rt", "#*", "@*")) %>% 
  dfm_remove(pattern = custom)

stmob <- convert(dfm_corp, to = 'stm')

**Comment by kbenoit** [comment]
You should be able to supply the `df` -- or if that does not work, `as.character(df)` -- as the argument for `texts` in `findThroughts`.
