### ISSUE TITLE
Can this project’s KWIC support Corpus Query Language ?

### ISSUE THREAD

**Issue by svjack** [quanteda/quanteda#2120]
As the parameter 
`valuetype = c("glob", "regex", "fixed"),
                 separator = " ", `
in kwic say, the tokenized corpus seems only separate by char “separator”
and valuetype always not related with part of speech of token.
And as the concept of KWIC or Concordancer say, 
Corpus Query Language seems support this (but week at expression ability than regex expression)
take a look at:
https://www.sketchengine.eu/documentation/cql-basics/
and
https://github.com/liao961120/concordancer

The latter also have kwic interface (but parsed Corpus Query Language)
can this project add lexer that can parse Corpus Query Language in the future ?

**Comment by koheiw** [comment]
We have not plan to support CQL, because it difficult to support wildcard patterns that are used in the language. However, you can do the same operation using `tokens_select()` with its `window` argument.
