### ISSUE TITLE
Quanteda install failing via SSH on Fedora 34

### ISSUE THREAD

**Issue by vidus** [quanteda/quanteda#2133]
## Describe the bug

Each time I go to install quanteda, I'm getting a remote connection failure on my Fedora server. 

## Reproducible code

Please paste minimal code that reproduces the bug. If possible, please upload the data file as `.rds`.
```r
install.packages('quanteda')
```

## Expected behavior

I expect it will install. 

## System information

Please run `sessionInfo()` and paste the output.
```
R version 4.0.5 (2021-03-31)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Fedora 34 (Server Edition)

Matrix products: default
BLAS/LAPACK: /usr/lib64/libflexiblas.so.3.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.5 tools_4.0.5 
```

## Additional info

g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG -DARMA_DONT_PRINT_OPENMP_WARNING  -I../inst/include -I'/usr/lib64/R/library/Rcpp/include' -I'/usr/lib64/R/library/RcppParallel/include' -I'/usr/lib64/R/library/RcppArmadillo/include' -I/usr/local/include   -fpic  -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection  -c tokens_compound_mt.cpp -o tokens_compound_mt.o
Connection to XXXXXXXX closed by remote host.
Connection to XXXXXXXX closed.

**Comment by kbenoit** [comment]
Looks like a CRAN connection problem. Have you tried installing other packages or testing your CRAN repository setting?

Current R is 4.1.1 - upgrading might also solve this.

**Comment by vidus** [comment]
I've installed tidy verse and shiny just fine thus far. I will see about getting updated R. Thanks!

**Comment by vidus** [comment]
Ok, so this appears to be a distro philosophy issue in that Fedora doesn't have the newest version of CRAN. I'm working to get a server up for several research projects, so I'm going to just nuke this server and swap distros, but I wanted to let you know that the issue didn't get resolved by me as I've got to get this server going and don't have the time to get it working, but wanted there to be a record of issue.
