### ISSUE TITLE
Error in grouping dfm 

### ISSUE THREAD

**Issue by ruudfiers** [quanteda/quanteda#2134]
When grouping a dfm, I get an error (_Error in qatd_cpp_is_grouped_numeric(as.numeric(x), group) : Invalid groups_) with one docvar, while another docvar that is similar, does work. I can't figure out what the difference is and how to solve it.

**Comment by ruudfiers** [comment]
Thanks for your reply! It had to do with missing values. You can't group by a variable that has NA's.

**Comment by kbenoit** [comment]
Interesting, thanks. @koheiw I wonder if we should trap this condition.
