### ISSUE TITLE
Error: package or namespace load failed for ‘quanteda’

### ISSUE THREAD

**Issue by BluePotato00** [quanteda/quanteda#2137]
## Other questions
I am having troubles loading the quanteda library. The package installation is fine:
`Restarting R session...

> install.packages("quanteda")
Installing package into ‘/Users/davidweber/Library/R/arm64/4.1/library’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.1/quanteda_3.1.0.tgz'
Content type 'application/x-gzip' length 4306234 bytes (4.1 MB)
==================================================
downloaded 4.1 MB

The downloaded binary packages are in
	/var/folders/p8/0ltmd6wx6g5gx3tw0r51q9fh0000gn/T//RtmpXqDaS1/downloaded_packages`

But when I attempt to load the library, I am met with an error:
`> library(quanteda)
Package version: 3.1.0
Unicode version: 13.0
ICU version: 67.1
Error: package or namespace load failed for ‘quanteda’:
 .onAttach failed in attachNamespace() for 'quanteda', details:
  call: qatd_cpp_tbb_enabled()
  error: function 'Rcpp_precious_remove' not provided by package 'Rcpp'`

I am unable to call functions like `tokens()`:
`> tokens()
Error in tokens() : could not find function "tokens"`

I see there is another user who had a similar problem, but the topic was closed on StackOverflow before any answer was provided. [https://stackoverflow.com/questions/68565727/error-when-loading-quanteda-package-right-after-installing-it]

Below is my session info if that would prove helpful:
`> devtools::session_info()
─ Session info ────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 4.1.1 (2021-08-10)
 os       macOS Big Sur 11.5.2        
 system   aarch64, darwin20           
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/Phoenix             
 date     2021-09-17                  

─ Packages ────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package      * version date       lib source        
 cachem         1.0.6   2021-08-19 [1] CRAN (R 4.1.1)
 callr          3.7.0   2021-04-20 [2] CRAN (R 4.1.0)
 cli            2.5.0   2021-04-26 [2] CRAN (R 4.1.0)
 crayon         1.4.1   2021-02-08 [2] CRAN (R 4.1.0)
 desc           1.3.0   2021-03-05 [1] CRAN (R 4.1.0)
 devtools       2.4.2   2021-06-07 [1] CRAN (R 4.1.0)
 ellipsis       0.3.2   2021-04-29 [2] CRAN (R 4.1.0)
 fastmap        1.1.0   2021-01-25 [1] CRAN (R 4.1.0)
 fastmatch      1.1-3   2021-07-23 [1] CRAN (R 4.1.0)
 fs             1.5.0   2020-07-31 [2] CRAN (R 4.1.0)
 glue           1.4.2   2020-08-27 [2] CRAN (R 4.1.0)
 lattice        0.20-44 2021-05-02 [2] CRAN (R 4.1.1)
 lifecycle      1.0.0   2021-02-15 [2] CRAN (R 4.1.0)
 magrittr       2.0.1   2020-11-17 [2] CRAN (R 4.1.0)
 Matrix         1.3-4   2021-06-01 [1] CRAN (R 4.1.1)
 memoise        2.0.0   2021-01-26 [1] CRAN (R 4.1.0)
 pkgbuild       1.2.0   2020-12-15 [1] CRAN (R 4.1.0)
 pkgload        1.2.2   2021-09-11 [1] CRAN (R 4.1.1)
 prettyunits    1.1.1   2020-01-24 [2] CRAN (R 4.1.0)
 processx       3.5.2   2021-04-30 [2] CRAN (R 4.1.0)
 ps             1.6.0   2021-02-28 [2] CRAN (R 4.1.0)
 purrr          0.3.4   2020-04-17 [2] CRAN (R 4.1.0)
 quanteda       3.1.0   2021-08-17 [1] CRAN (R 4.1.1)
 R6             2.5.0   2020-10-28 [2] CRAN (R 4.1.0)
 Rcpp           1.0.6   2021-01-15 [2] CRAN (R 4.1.0)
 RcppParallel   5.1.4   2021-05-04 [1] CRAN (R 4.1.0)
 remotes        2.4.0   2021-06-02 [1] CRAN (R 4.1.0)
 rlang          0.4.11  2021-04-30 [2] CRAN (R 4.1.0)
 rprojroot      2.0.2   2020-11-15 [1] CRAN (R 4.1.0)
 sessioninfo    1.1.1   2018-11-05 [1] CRAN (R 4.1.0)
 stopwords      2.2     2021-02-10 [1] CRAN (R 4.1.0)
 stringi        1.6.2   2021-05-17 [2] CRAN (R 4.1.0)
 testthat       3.0.4   2021-07-01 [1] CRAN (R 4.1.0)
 usethis        2.0.1   2021-02-10 [1] CRAN (R 4.1.0)
 withr          2.4.2   2021-04-18 [2] CRAN (R 4.1.0)

[1] /Users/davidweber/Library/R/arm64/4.1/library
[2] /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library`

I am on an M1 MacBook Air. I get the same error on an M1 Mac mini. I have successfully downloaded, installed, and used ~15 other packages in the past with no issues. It's just quanteda giving me these issues.

Thank you kindly for any assistance you can provide.

**Comment by koheiw** [comment]
Please try again after reinstalling the Rcpp package.

**Comment by BluePotato00** [comment]
> Please try again after reinstalling the Rcpp package.

That did it! Thank you for your help and quick reply. Have a great weekend.
