### ISSUE TITLE
Corpus reshape other than sentence or paragraph

### ISSUE THREAD

**Issue by epeksoy** [quanteda/quanteda#2138]
## Other questions

Hi,

How can we reshape corpus to equal sized chunks by word or character count without spoiling sentence delimiters. Is there a function for this? Let's say I need a corpus of documents with 1000 words in each of them. Thanks.

**Comment by koheiw** [comment]
https://stackoverflow.com/ is a better place to post such a question. Don't try to do many thing on corpus; use `tokens_chunk()`.
