### ISSUE TITLE
Tokenizer for italian language

### ISSUE THREAD

**Issue by agnesevardanega** [quanteda/quanteda#2153]
As an Italian user of Quanteda, I would like a tokenizer following the Italian conventions for word boundaries, including apostrophes. 

At the moment, I add this line before creating corpora o token objects:

```r
x %>%
  mutate(text = str_replace_all(text, "[\'’]", "' ")) %>%
  corpus()  # or tokens()
```

With this correction texts are parsed correctly, since in Italian apostrophes are word boundaries.

Maybe it is possible to add an argument to the functions, like that for the hyphens.

All the best

**Comment by kbenoit** [comment]
It also might make sense to use an alternative tokeniser, then coerce this to a quanteda tokens object. In quanteda 2.0 we made this much easier: anything that is a named list of characters can be coerced into a quanteda tokens object using `as.tokens()`. So you could use the **tokenizers** package, or **spacyr**, or your own tokeniser that has the Italian rules.

**Comment by agnesevardanega** [comment]
The _tokenizers_ package is almost the same tokenizer, while _spacyr_ or even _hunspell_ are ok if one is not interested in using a corpus object to organize texts and segments, or in measures such as readability etc. 
Apostrophes are very common, in Italian and French: all articles have a truncated form, just to say. In my experience, at the moment, the best option is simply transforming the text within the readr dataframe. After all, it is just a line of code.
Thanks

**Comment by kbenoit** [comment]
Some other options:

``` r
library("quanteda")
## Package version: 3.2.0
## Unicode version: 13.0
## ICU version: 69.1
## Parallel computing: 12 of 12 threads used.
## See https://quanteda.io for tutorials and examples.

txt <- "In questa lezione parleremo dell’uso dell’apostrofo nella lingua italiana."

# works
stringr::str_replace_all(txt, "[\'’]", "' ") %>%
  corpus() %>%
  print(max_nchar = -1)
## Corpus consisting of 1 document.
## text1 :
## "In questa lezione parleremo dell' uso dell' apostrofo nella lingua italiana."

# another option that removes the apostrophe
tokens(txt) %>%
  tokens_split("['’]", valuetype = "regex")
## Tokens consisting of 1 document.
## text1 :
##  [1] "In"        "questa"    "lezione"   "parleremo" "dell"      "uso"      
##  [7] "dell"      "apostrofo" "nella"     "lingua"    "italiana"  "."

# tokens approach that keeps the apostrophe as per your example
tokens(txt) %>%
  tokens_split("['’]", valuetype = "regex", remove_separator = FALSE) %>%
  tokens_compound(phrase("* '"), concatenator = "")
## Tokens consisting of 1 document.
## text1 :
##  [1] "In"        "questa"    "lezione"   "parleremo" "dell'"     "uso"      
##  [7] "dell'"     "apostrofo" "nella"     "lingua"    "italiana"  "."
```

**Comment by agnesevardanega** [comment]
Yes, for tokens objects these are actually great solutions. The difference between keeping or removing apostrophes is relevant when applying a stopword list. Quanteda list is without apostrophes (a part from "l'", we may have longer words such as "dell'"), so the first one is better. This is also the reason why Hunspell is uneasy. 

Adding a space after the apostrophe, the apostrophe will be kept in the corpus (which will contain all of the graphic forms and the right number of tokens), then, being considered as punctuation, it will be removed in the tokens object.

Thank you

**Comment by koheiw** [comment]
FYI https://www.unicode.org/reports/tr29/#Word_Boundaries

> The use of the apostrophe is ambiguous. It is usually considered part of one word (“can’t” or “aujourd’hui”) but it may also be considered as part of two words (“l’objectif”). A further complication is the use of the same character as an apostrophe and as a quotation mark. Therefore leading or trailing apostrophes are best excluded from the default definition of a word. In some languages, such as French and Italian, tailoring to break words when the character after the apostrophe is a vowel may yield better results in more cases. This can be done by adding a rule WB5a.
Break between apostrophe and vowels (French, Italian).
>
> WB5a 	apostrophe 	÷ 	vowels
>
> and defining appropriate property values for apostrophe and vowels. Apostrophe includes U+0027 ( ' ) APOSTROPHE and U+2019 ( ’ ) RIGHT SINGLE QUOTATION MARK (curly apostrophe). Finally, in some transliteration schemes, apostrophe is used at the beginning of words, requiring special tailoring.

**Comment by agnesevardanega** [comment]
Great! In Italian, as far as I know, there is no case like "aujourd'hui" in French. Eventually they can be treated like multiword. 

https://www.treccani.it/enciclopedia/apostrofo_(La-grammatica-italiana)/

https://www.treccani.it/enciclopedia/elisione_%28La-grammatica-italiana%29/

All the best
