### ISSUE TITLE
 dfm function in quanteda

### ISSUE THREAD

**Issue by niutyut** [quanteda/quanteda#2158]
In using the Chinese corpus, the dfm function in quanteda re-partitioned some words that had been separated by spaces. But the re-sorting is wrong, I need to keep the space kind of splitting words. For example,“精巧  密切  钱浓” which is originally three words, the result is dtm into “精”“巧”“密”“切”“钱”“浓”six words, how to set dfm, so that it allows only according to the space to split words?  thanks

**Comment by koheiw** [comment]
quanteda' tokenizer can split Chinese words even without space, but your texts are already segmented. In that case, you should use an external tool. Like below:

``` r
require(quanteda)
#> Loading required package: quanteda
#> Package version: 3.2.0
#> Unicode version: 13.0
#> ICU version: 66.1
#> Parallel computing: 6 of 6 threads used.
#> See https://quanteda.io for tutorials and examples.
toks <- as.tokens(stringi::stri_split_fixed("精巧 密切 钱浓", pattern = " "))
dfm(toks)
#> Document-feature matrix of: 1 document, 3 features (0.00% sparse) and 0 docvars.
#>        features
#> docs    精巧 密切 钱浓
#>   text1    1    1    1
```

**Comment by niutyut** [comment]
Thank you very much for your reply
My dfm is associated with a dataframe because I want to read the docvars property in the dataframe. The code is as follows.
dtm <- dfm(corpus(DB$text, docvars = DB))
where DB is.
text                                 Year      author
"精巧 密切 钱浓"        2001     张轼
"山水  花卉 高涨"       2012     李白
In the subsequent operation, I need to use the two parameters year and author. How to solve it?

**Comment by niutyut** [comment]
Thank you very much for your reply
My dfm is associated with a dataframe because I want to read the docvars property in the dataframe. The code is as follows.
dtm <- dfm(corpus(DB$text, docvars = DB))
where DB is.
 text                        Year      author
"精巧 密切 钱浓"    2001      张轼
"山水 花卉 高涨"    2012      李白
In the subsequent operation, I need to use the two parameters year and author. How to solve it?

**Comment by niutyut** [comment]
Thank you very much for your reply
My dfm is associated with a dataframe because I want to read the docvars property in the dataframe. The code is as follows.
dtm <- dfm(corpus(DB$text, docvars = DB))
where DB is.
text --------------  Year----- author
"精巧 密切 钱浓"   2001      张轼
"山水 花卉 高涨"   2012      李白
In the subsequent operation, I need to use the two parameters year and author. How to solve it?

**Comment by niutyut** [comment]
Thank you very much for your reply
My dfm is associated with a dataframe because I want to read the docvars property in the dataframe. The code is as follows.
dtm <- dfm(corpus(DB$text, docvars = DB))
where DB is.
   text                   Year       author
"精巧 密切 钱浓" 2001 张轼
"山水 花卉 高涨" 2012 李白
In the subsequent operation, I need to use the two parameters year and author. How to solve it?

**Comment by koheiw** [comment]
You can add docvars anytime.
```r
docvars(toks) <- DB
# or 
dfmt <- dfm(toks)
docvars(dfmt) <- DB
```

**Comment by kbenoit** [comment]
The tokenization of the original text in question seems to be working fine now.

``` r
library("quanteda")
#> Package version: 3.2.5.9000
#> Unicode version: 14.0
#> ICU version: 71.1
#> Parallel computing: 10 of 10 threads used.
#> See https://quanteda.io for tutorials and examples.

tokens("精巧 密切 钱浓")
#> Tokens consisting of 1 document.
#> text1 :
#> [1] "精巧" "密切" "钱"   "浓"

sessionInfo()
#> R version 4.2.3 (2023-03-15)
#> Platform: aarch64-apple-darwin20 (64-bit)
#> Running under: macOS Ventura 13.2.1
#> 
#> Matrix products: default
#> BLAS:   /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRblas.0.dylib
#> LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib
#> 
#> locale:
#> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] quanteda_3.2.5.9000
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.10        rstudioapi_0.14    knitr_1.42         magrittr_2.0.3    
#>  [5] stopwords_2.3      R.cache_0.16.0     lattice_0.20-45    rlang_1.1.0       
#>  [9] fastmatch_1.1-3    fastmap_1.1.1      styler_1.9.1       tools_4.2.3       
#> [13] grid_4.2.3         xfun_0.37          R.oo_1.25.0        cli_3.6.1         
#> [17] withr_2.5.0        htmltools_0.5.5    RcppParallel_5.1.7 yaml_2.3.7        
#> [21] digest_0.6.31      lifecycle_1.0.3    Matrix_1.5-3       purrr_1.0.1       
#> [25] vctrs_0.6.1        R.utils_2.12.2     fs_1.6.1           glue_1.6.2        
#> [29] evaluate_0.20      rmarkdown_2.21     reprex_2.0.2       stringi_1.7.12    
#> [33] compiler_4.2.3     R.methodsS3_1.8.2
```

<sup>Created on 2023-03-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by kbenoit** [comment]
Or use the "fasterword" tokenizer:

``` r
library("quanteda")
#> Package version: 3.2.5.9000
#> Unicode version: 14.0
#> ICU version: 71.1
#> Parallel computing: 10 of 10 threads used.
#> See https://quanteda.io for tutorials and examples.

tokens("精巧 密切 钱浓", what = "fasterword")
#> Tokens consisting of 1 document.
#> text1 :
#> [1] "精巧" "密切" "钱浓"
```

<sup>Created on 2023-03-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
