### ISSUE TITLE
Quanteda CRAN Fixes

### ISSUE THREAD

**Issue by cschwem2er** [quanteda/quanteda#2163]
Hi,

just got a CRAN message:

``` 

Dear maintainers,

This concerns the CRAN packages

  LDAShiny LSX LexisNexisTools RNewsflow Twitmo akc conText corpustools
  doc2concrete docreview gofastr keyATM newsmap oolong politeness
  quanteda quanteda.textmodels quanteda.textplots quanteda.textstats
  rainette rollinglda seededlda sentometrics stm stmCorrViz stmgui
  stminsights sweater text2sdg textstem tosca



We have asked for an update fixing the check problems shown at
(https://cran.r-project.org/web/checks/check_results_quanteda.html)
with no update from the maintainer thus far.

Thus, package quanteda is now scheduled for archival on 2022-03-14, and
archiving this will necessitate also archiving its strong reverse
dependencies.

Please negotiate the necessary actions.

The CRAN Team
``` 

Are we supposed to be concerned? =D

**Comment by JBGruber** [comment]
I think the problem are these lines:

https://github.com/quanteda/quanteda/blob/4ea0b4322ea6cd3602f11c158f6b3625d2204f76/tests/testthat/test-as.dictionary.R#L85-L88

Either the new `testthat` (updated 20 Jan) or the CRAN workers don't like the Unicode characters here. An easy fix would be:

```
expect_error(
    as.dictionary(df, format = "koRpus"),
    "'arg' should be (one of )?[[:punct:]]tidytext[[:punct:]]"
)
```

But I'm just guessing. I couldn't reproduce the error and only [r-devel-linux-x86_64-debian-clang](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-clang/quanteda-00check.html) actually complains about some characters.

**Comment by kbenoit** [comment]
Hi - Yes I am slowly fixing these. Just fixed a similar issue in **nsyllable** today, will do the others soon. But feel free to issue a PR!

**Comment by kbenoit** [comment]
Fixed and resubmitted.
