### ISSUE TITLE
dfm_trim() generates different dfms which produces inconsistent seeded lda results

### ISSUE THREAD

**Issue by emanaped** [quanteda/quanteda#2164]
## Describe the bug

When the corpus is large and the min_docfreq is small, running dfm_trim() produces different dfms which yield different seeded LDA topic models (even though code stays the same including seed, data, and hyperparameters).

Inconsistent results; min_docfreq = .001, external dictionary
![image](https://user-images.githubusercontent.com/55507715/157570916-d71c8176-e449-4c60-b07a-2f1fbdea1aab.png)

Inconsistent results; min_docfreq = .001, hard coded dictionary
![image](https://user-images.githubusercontent.com/55507715/157573923-b2fa919d-9e9c-48e1-8726-c1bc3896d403.png)

## Reproducible code

Please paste minimal code that reproduces the bug. If possible, please upload the data file as `.rds`.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#### PACKAGES ####
library(quanteda)
library(quanteda.corpora)
library(quanteda.textmodels)
library(seededlda)
library(rlist)
library(Matrix)
```

# (1) Import Data

```{r load_data, include=FALSE}
corp <- download("data_corpus_guardian")

set.seed(87, sample.kind = "Rejection") # per https://rdrr.io/r/base/Random.html and https://stackoverflow.com/questions/56268011/sample-function-gives-different-result-in-console-and-in-knitted-document-when-s
```

# (2) Tokenize

```{r clean, include=FALSE}
toks = tokens(corp, remove_punct = TRUE, remove_symbols = TRUE, padding = FALSE) %>% 
    # remove English stopwords
    tokens_remove(stopwords("en"), padding = FALSE)
```

# (3) Create Document-Feature Matrix
```{r dfm_corp, include=FALSE}
# ==== create dfm ====
dfm_corp <- toks %>% dfm()
```

# (4) Create Sparse Document-Feature Matrix
```{r dfm_sparse}
# ==== create dfm ====
dfm_sparse <- dfm_trim(dfm_corp
  , docfreq_type = "prop" 
  , min_docfreq = .001
  , verbose = TRUE
  )
```

# (5) Topic Model
These results change between R Studio, HTML, and PDF.
```{r tmod, echo=FALSE}
# load dictionary containing seed words
dict_topic <- dictionary(list(
    dismissal = c("possibly","possible","perhaps")
  , race = c("race","ethnicity","minority","nonwhite")
  , interpersonal = c("beliefs","prejudice","discrimination","racist")
  , societal = c("society","structural","institutional","systemic")
  , actionable = c("political","power","change","policies","action","truth")
  )
)

tmod_slda <- textmodel_seededlda(dfm_sparse, dictionary = dict_topic
                                  , residual = TRUE # include for "garbage topic"
                                 )

# top terms
terms(tmod_slda, 20)

# add seeded topic to dfm_sparse
dfm_sparse$topic <- topics(tmod_slda)

# cross-table of the topic frequency
table(dfm_sparse$topic)
```

## Expected behavior

The same dfm should be created for each run because the frequency hyperparameters are deterministic, not random.

## System information

Please run `sessionInfo()` and paste the output.
```
R version 4.1.1 (2021-08-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] quanteda.corpora_0.9.2    Matrix_1.3-4              rlist_0.4.6.2             seededlda_0.6.0           quanteda.textmodels_0.9.4
[6] quanteda_3.1.0           

loaded via a namespace (and not attached):
 [1] shape_1.4.6        xfun_0.26          remotes_2.4.2      purrr_0.3.4        splines_4.1.1      lattice_0.20-44    testthat_3.1.2    
 [8] htmltools_0.5.2    usethis_2.1.5      LiblineaR_2.10-12  yaml_2.2.1         survival_3.2-11    rlang_0.4.11       pkgbuild_1.3.1    
[15] glue_1.6.2         withr_2.5.0        sessioninfo_1.2.2  lifecycle_1.0.1    foreach_1.5.1      devtools_2.4.3     codetools_0.2-18  
[22] memoise_2.0.1      evaluate_0.14      knitr_1.36         callr_3.7.0        fastmap_1.1.0      SparseM_1.81       ps_1.6.0          
[29] curl_4.3.2         Rcpp_1.0.7         cachem_1.0.6       desc_1.4.1         pkgload_1.2.4      RcppParallel_5.1.4 fs_1.5.0          
[36] brio_1.1.3         fastmatch_1.1-3    stopwords_2.2      digest_0.6.28      stringi_1.7.5      processx_3.5.2     grid_4.1.1        
[43] rprojroot_2.0.2    here_1.0.1         cli_3.2.0          tools_4.1.1        magrittr_2.0.1     glmnet_4.1-3       crayon_1.4.1      
[50] ellipsis_0.3.2     data.table_1.14.2  prettyunits_1.1.1  rstudioapi_0.13    rmarkdown_2.11     iterators_1.0.13   R6_2.5.1          
[57] compiler_4.1.1 
```

## Additional info

With the same hyperparameters, corpus, and seed (with sample.kind="Rejection" (per https://stackoverflow.com/questions/56268011/sample-function-gives-different-result-in-console-and-in-knitted-document-when-s and https://rdrr.io/r/base/Random.html), dfm_trim() produces different dfms.

I could not reproduce the bug using the data_corpus_sotu dataset, perhaps because the n was too small. With the larger data_corpus_guardian dataset and a min_docfreq = .001, I was able to reproduce the issue of inconsistent terms and counts per topic (see first screenshot in bug description).

A larger value for min_doqfreq (e.g., .0023) produced consistent results between R Studio console and the HTML output, as shown in the following screenshot.

Consistent results
![image](https://user-images.githubusercontent.com/55507715/157572465-486b69ef-c5f8-4c49-9ca4-055552a41343.png)

I became aware of this bug while using the package seededlda (textmodel_seededlda()) based on the hyperparameters outlined in the quanteda tutorial (https://tutorials.quanteda.io/machine-learning/topicmodel/). I am working on a private dataset, so I reproduced the bug using quanteda data and an abridged version of my seeded dictionary.

I noticed that even with the exact same code, I got different output from my seeded LDA if I knit to PDF, HTML, or (re)ran in R Studio. Both the top terms and counts of documents within topics would change. In my corpus of 870 documents, some topic counts would change by more than 100, particularly for the "race" and "other" topics (see below screenshots).

R Studio console output
![image](https://user-images.githubusercontent.com/55507715/157552168-46d16312-e25f-4559-ab87-a1aa3576e8f1.png)

HTML output
![image](https://user-images.githubusercontent.com/55507715/157552130-77574f95-dd0c-48a2-80ec-e62772d6ecf2.png)

So far, I have troubleshooted the following scenarios for generating textmodel_seededlda:
- with or without residual = TRUE
- including/excluding max_iter with different values
- outputting to PDF, HTML, or R Studio console
- hardcoding an abbreviated dictionary into the code vs. loading the full yaml dictionary

The textmodel results continued to change, despite setting the seed.

I realized when I do not recreate the sparse dfm, the topic model results are consistent, suggesting that the issue is within in the dfm_trim() function. I have tried:
- changing the term frequency type from "quantile" to "prop"
- setting only one restriction (e.g., min_docfreq = .0023)
- trying different values for min_docfreq

My current workaround for generating a consistent textmodel is by permanently saving the sparse dfm which is loaded for subsequent runs.

```{r dfm_sparse, eval=FALSE}
# ==== create dfm ====
dfm_sparse <- dfm_trim(dfm_corp
  , docfreq_type = "prop" 
  , min_docfreq = .001
#  , min_docfreq = .01
  , verbose = TRUE
  )
save(dfm_sparse,
     file = here::here("data/dfm_sparse.RData"))
```

**Comment by koheiw** [comment]
We had an issue of the [random ordering of DFM columns](https://github.com/quanteda/quanteda/pull/2150), but we fixed it in v3.2. Your quanteda is a bit old, but you are not using `tokens_compound()` or `tokens_ngrams()` that induced the randomness anyway.

The change in your results is due to the random number generation in `textmodel_seededlda()`, which should be discussed elsewhere. You are (rightly) using `set.seed()` but it should be in the same chunk as the LDA function ([see](https://stackoverflow.com/questions/47897435/how-to-use-set-seed-globally-in-r-markdown)). 

```
set.seed(87, sample.kind = "Rejection")
tmod_slda <- textmodel_seededlda(dfm_sparse, dictionary = dict_topic, residual = TRUE)
```

More generally, I recommend you to use a plain R file instead of Rmd to run computationally intensive code.

**Comment by kbenoit** [comment]
I can confirm through testing that following the `dfm_trim()` operation, there is no difference in the resulting `dfm_sparse` once that call is repeated. There is a call to `quantile()` in `dfm_trim(x, docfreq_type = "prop",  min_docfreq = .001)` but that does not involve any random (sampling) operation.

So as @koheiw explains above, you should update to **quanteda** >= 3.2.1 and use the `set.seed()` before the call to `textmodel_seededlda()`.

**Comment by emanaped** [comment]
Thank you for the quick response! I actually did have tokens_compound() in my working code but, out of simplification, removed it to report the bug. The updated package fixed the issue.
