### ISSUE TITLE
Error in char_wordstem.character(featnames(x), language = language) :    whitespace detected: you can only stem tokenized texts

### ISSUE THREAD

**Issue by geokilly** [quanteda/quanteda#2169]
I keep getting this error message when trying when trying to convert corpus to dfm. I have tried tokenizing migCopr first, but the error message persists. I have also tried to edit the original data to remove any whitespaces etc. 

Text_1 <- readtext("SHORT TEST.csv", text_field = "Text")
subtext_1 <-subset.data.frame(Text_1, Date >= "1996")
subtext_1$Date_ok <- as.numeric(as.factor(subtext_1$Date))
migCorp <- corpus(subtext_1, docid_field = "doc_id")
dfmMIG <- dfm(migCorp, remove = stopwords("english"), tolower = TRUE, stem = TRUE,
                  remove_punct = TRUE, remove_symbols = TRUE, remove_numbers = TRUE)

This is a short version of my dataset: 
[SHORT TEST.csv](https://github.com/quanteda/quanteda/files/8385355/SHORT.TEST.csv)

**Comment by kbenoit** [comment]
The deprecation warnings you are getting is because the usage has changed as we move forward in major versions. These are all documented in `NEWS.md`.

Try it the last way below and there are no warnings.

``` r
library("quanteda")
#> Package version: 3.2.1
#> Unicode version: 13.0
#> ICU version: 67.1
#> Parallel computing: 10 of 10 threads used.
#> See https://quanteda.io for tutorials and examples.

Text_1 <- readtext::readtext("~/Downloads/SHORT.TEST.csv", text_field = "Text")
subtext_1 <-subset.data.frame(Text_1, Date >= "1996")
subtext_1$Date_ok <- as.numeric(as.factor(subtext_1$Date))
migCorp <- corpus(subtext_1, docid_field = "doc_id")

# warnings
dfmMIG <- dfm(migCorp, remove = stopwords("english"), tolower = TRUE, stem = TRUE,
              remove_punct = TRUE, remove_symbols = TRUE, remove_numbers = TRUE)
#> Warning: 'dfm.corpus()' is deprecated. Use 'tokens()' first.
#> Warning: '...' should not be used for tokens() arguments; use 'tokens()' first.
#> Warning: 'remove' is deprecated; use dfm_remove() instead
#> Warning: 'stem' is deprecated; use dfm_wordstem() instead

# no warnings
dfmMIG <- tokens(migCorp, remove_punct = TRUE, remove_symbols = TRUE, 
                 remove_numbers = TRUE) %>%
    tokens_remove(stopwords("english")) %>%
    tokens_wordstem()
```

<sup>Created on 2022-03-31 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
