### ISSUE TITLE
Getting error message  could not find function "tokens"

### ISSUE THREAD

**Issue by Nehagupta90** [quanteda/quanteda#2170]
Hi, I have a problem in the following code

train.tokens <- tokens(train$DESCRIPTION, what = "word", 
                       remove_numbers = TRUE, remove_punct = TRUE,
                       remove_symbols = TRUE, remove_hyphens = TRUE)

Error in tokens(train$DESCRIPTION, what = "word", remove_numbers = TRUE,  : 
  could not find function "tokens"

Package version: 3.2.1
Unicode version: 10.0
ICU version: 61.1

**Comment by kbenoit** [comment]
Please include all of your output, for which we recommend using `reprex::reprex()`. It looks like you have not loaded **quanteda** yet.

**Comment by Nehagupta90** [comment]
Thank you for your response.

When I try to load the library from the packages tab (right side of
Rstudio), it gives the following error

library(quanteda)
Package version: 3.2.1
Unicode version: 10.0
ICU version: 61.1
Error: package or namespace load failed for ‘quanteda’:
 .onAttach failed in attachNamespace() for 'quanteda', details:
  call: qatd_cpp_tbb_enabled()
  error: function 'Rcpp_precious_remove' not provided by package 'Rcpp'
In addition: Warning message:
package ‘quanteda’ was built under R version 4.0.5


When I try to load the library using code library(quanteda)

It shows the following and goes to indefinite wait (Rstudio hangs)

library(quanteda)
Package version: 3.2.1
Unicode version: 10.0
ICU version: 61.1

**Comment by kbenoit** [comment]
It looks like your version of R is out of date. Try installing R 4.1.3, updating your packages, and then re-installing **quanteda**.

```r
update.packages(ask = FALSE)
install.packages("quanteda")
```

**Comment by Nehagupta90** [comment]
A few minutes ago, I run this code and the packages were updated.

update.packages(ask = FALSE)


Now I am trying to update the R package, but not sure if I have to
re-install the latest version of Rstudio?
