### ISSUE TITLE
kwic for a list of patterns including both unigrams and phrases

### ISSUE THREAD

**Issue by hhnmg** [quanteda/quanteda#2179]
Dear @kbenoit , @koheiw and other users,

I am using **kwic** to extract the context surrounding given keywords.
I am seeing that the use of **kwic** is separated into two options, for examples: 

1. `kw_immig <- kwic(toks, pattern =  ".....list of unigrams....")` if keywords are unigrams, and 
2. `kw_asylum <- kwic(toks, pattern = phrase("...list of n-grams...."))` if keywords are phrases (I am understanding that those are n-grams). 

How could I aggregate both options to use as I have a list of keywords that includes both uni and bi-grams. 

Thank you in advance!

hhn

**Comment by koheiw** [comment]
Please post questions on how to use the package to https://stackoverflow.com/
