### ISSUE TITLE
Could not find function "textstat_collocations" with Quanteda installed

### ISSUE THREAD

**Issue by yinw4-1738276** [quanteda/quanteda#2184]
I have already installed the "Quanteda" package but when I run 
textstat_collocations(corpus_tokens, min_count = 25)
It gives an error message saying "could not find function "textstat_collocations""
my quanteda package version is 3.2.3 if that helps(?)
And my Rstudio is up to date as well.
I couldn't figure out why this is happening, does anyone has any idea? Thank you very much!

**Comment by kbenoit** [comment]
https://github.com/quanteda/quanteda/blob/master/NEWS.md#changes-and-additions-3
