### ISSUE TITLE
Unexpected discrepancy for tokens_lookup() output when concatenator is a space versus underscore (potentially others?)

### ISSUE THREAD

**Issue by brhkim** [quanteda/quanteda#2187]
## Describe the bug
tokens_lookup appears to return extraneous dictionary matches when a token object is concatenated with spaces, rather than another character like an underscore. It appears that the number of extraneous matches is tied to the number of matches (seems to double?).

## Reproducible code

```r
library(quanteda)

tokens <- tokens("we as a team won as the best broadcast program for several rounds")

ngrams_underscore <- tokens_ngrams(tokens, n=c(1, 2), concatenator = "_")

dict_underscore <- dictionary(
  list(
    match = c("the_best")
  ))

tokens_lookup(ngrams_underscore, dictionary=dict_underscore)
# Tokens consisting of 1 document.
# text1 :
# [1] "match"

ngrams_space <- tokens_ngrams(tokens, n=c(1,2), concatenator = " ")

dict_space <- dictionary(
  list(
    match = c("the best")
  ))

tokens_lookup(ngrams_space, dictionary=dict_space)
# Tokens consisting of 1 document.
# text1 :
# [1] "match" "match"

dict_underscore2 <- dictionary(
  list(
    match = c("a_team", "the_best")
  ))

tokens_lookup(ngrams_underscore, dictionary=dict_underscore2)
# Tokens consisting of 1 document.
# text1 :
# [1] "match" "match"

dict_space2 <- dictionary(
  list(
    match = c("a team", "the best")
  ))

tokens_lookup(ngrams_space, dictionary=dict_space2)
# Tokens consisting of 1 document.
# text1 :
# [1] "match" "match" "match" "match"
```

## Expected behavior

I did not expect the choice of concatenator to change the way tokens were matched to the dictionary. My expectation for behavior here was that both outputs shown above would appear as the underscore concatenator output does (one single token match returned).

## System information

Please run `sessionInfo()` and paste the output.
```
R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22621)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] quanteda_3.2.3

loaded via a namespace (and not attached):
 [1] compiler_4.2.1     magrittr_2.0.3     Matrix_1.4-1       tools_4.2.1        fastmatch_1.1-3   
 [6] Rcpp_1.0.9         stringi_1.7.8      grid_4.2.1         stopwords_2.3      RcppParallel_5.1.5
[11] lattice_0.20-45   
```

## Additional info

Number of n-grams the tokens object is tokenized to doesn't seem to matter (still returns two matches for the space version), and valuetype="fixed" doesn't seem to change behavior, either. 

Note: I absolutely love this package and hugely appreciate your work on this! I encountered this during a major analysis and it caused some issues, so wanted to make sure to document this ASAP. Please let me know if there's anything more I can provide here and/or if I've just misunderstood entirely how tokens_lookup should work!

**Comment by kbenoit** [comment]
This is because of how `tokens_lookup()` matches multi-element dictionary values (such as "the best") with the sequence of unigrams `"the", "best". It also matches the bigram "the best". It's a feature, although it could probably be better documented. 

Note that you can redefine the multi-element dictionary value separator when you define the dictionary. So to avoid the extra match, make sure the dictionary separator is different from the ngram concatenator. 

``` r
library("quanteda")
#> Package version: 3.2.3
#> Unicode version: 14.0
#> ICU version: 70.1
#> Parallel computing: 10 of 10 threads used.
#> See https://quanteda.io for tutorials and examples.

# matches "b", "c" sequence
tokens("a b c") |>
    tokens_lookup(dictionary = dictionary(list(match = "b c")), exclusive = FALSE)
#> Tokens consisting of 1 document.
#> text1 :
#> [1] "a"     "MATCH"

# matches "b", "c" AND "b c" ngram
tokens("a b c") |>
    tokens_ngrams(n = c(1, 2), concatenator = " ") |>
    tokens_lookup(dictionary = dictionary(list(match = "b c")), exclusive = FALSE)
#> Tokens consisting of 1 document.
#> text1 :
#> [1] "a"     "MATCH" "a b"   "MATCH"

# but so does this, because of how the dictionary separator is defined
tokens("a b c") |>
    tokens_ngrams(n = c(1, 2), concatenator = "_") |>
    tokens_lookup(dictionary = dictionary(list(match = "b c"), separator = "_"), 
                  exclusive = FALSE)
#> Tokens consisting of 1 document.
#> text1 :
#> [1] "a"     "MATCH" "a_b"   "MATCH"
```

<sup>Created on 2022-10-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by brhkim** [comment]
Ahh okay, that makes sense. Thanks for the speedy clarification!
