### ISSUE TITLE
Unable to load the quanteda package

### ISSUE THREAD

**Issue by ghost** [quanteda/quanteda#2197]
Hi. I'm new here. Soon after I installed Ventura, I get the following errors and cannot use quanteda at all. I have already deinstall and reinstall the quanteda package and the R.app itself. The R version is 4.2.2. Big Sur ARM. Other packages I work fine. This happens to my two of my Mac, both are Ventura. Is there anything I can do? Thank you.

=========================================
library(quanteda)

 *** caught segfault ***
address 0x245, cause 'invalid permissions'

Traceback:
 1: RcppParallel::defaultNumThreads()
 2: get_threads()
 3: unname(min(get_threads(), na.rm = TRUE))
 4: get_options_default()
 5: quanteda_initialize()
 6: quanteda_options("print_corpus_max_ndoc")
 7: doTryCatch(return(expr), name, parentenv, handler)
 8: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 9: tryCatchList(expr, names[-nh], parentenv, handlers[-nh])
10: doTryCatch(return(expr), name, parentenv, handler)
11: tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]),     names[nh], parentenv, handlers[[nh]])
12: tryCatchList(expr, classes, parentenv, handlers)
13: tryCatch({    x <- as.integer(x)}, warning = fun, error = fun)
14: check_integer(max_ndoc, min = -1)
15: print.corpus(x)
16: (function (x, ...) UseMethod("print"))(x)

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection: 

Another Mac returns a slightly different but nearly same message
 *** caught segfault ***
address 0x1d1, cause 'memory not mapped'

**Comment by kbenoit** [comment]
I use macOS with both an M1 Max (laptop) and M2 chip (desktop) and it's all working swimmingly on my systems.

Suggest you update all packages and try again. And please show all of the session output, not just the segfault error.
