### ISSUE TITLE
Perform token serialization in C++

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda#2218]
It is tested on the `dev-serialize`  branch.

**Comment by kbenoit** [comment]
Does this issue require xpointers or can it be merged into v3?

**Comment by koheiw** [comment]
I don't think it will make it faster because of the overhead in copying objects between C++ and R. The C++ header is also very different in v4 .

**Comment by kbenoit** [comment]
It's already merged into `master` which is as of today, in v3, so we can close this issue.
