### ISSUE TITLE
How to convert Chinese tokens in  fcm textstat_network into English?

### ISSUE THREAD

**Issue by chentitus** [quanteda/quanteda#2219]
Hi, I am new to quanteda, and I am working to generate a textstat_network plot. The corpus for analysis is Chinese, and I need to generate a textstat_network plot with English tokens. Is there any way to translate those Chinese tokens into English? Thanks in advance for your suggestions.

**Comment by kbenoit** [comment]
You could try https://cran.r-project.org/web/packages/googleLanguageR/vignettes/translation.html.
