### ISSUE TITLE
tokens_tokenizer_word not showing up in options

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#2233]
I'm baffled... 

``` r
library("quanteda")
#> Package version: 3.2.5
#> Unicode version: 14.0
#> ICU version: 71.1
#> Parallel computing: 10 of 10 threads used.
#> See https://quanteda.io for tutorials and examples.

quanteda_options(initialize = TRUE)

"tokens_tokenizer_word" %in% names(quanteda_options())
#> [1] FALSE
```

<sup>Created on 2023-04-03 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by koheiw** [comment]
It should be `quanteda_options(reset = TRUE)`

**Comment by kbenoit** [comment]
initialize should work too ... anyway it was this issue:

https://github.com/quanteda/quanteda/issues/2230#issuecomment-1495310233
