### ISSUE TITLE
Bug: current master makes quanteda.textstats unable to build

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#2234]
I checked the master at [395c59a](https://github.com/quanteda/quanteda/commit/395c59a767a27ca8c1754dc8ca722971e85f087b) with revdep_check, and we passed 37 of 28 packages, but failed **quanteda.textstats**, which is [completely clean](https://cran.r-project.org/web/checks/check_results_quanteda.textstats.html) on CRAN.

This is the error I am seeing when we try to build **quanteda.textstats** using the current dev version of **quanteda**:

```
(Personal)/GitHub/quanteda/quanteda/revdep/library.noindex/quanteda.textstats/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/quanteda/include' -I/opt/R/arm64/include   -fPIC  -falign-functions=64 -Wall -g -O2  -c utility.cpp -o utility.o
utility.cpp:4:7: error: redefinition of 'GLOBAL_PATTERN_MAX_LOAD_FACTOR' with a different type: 'float' vs 'const float'
...
utility.cpp:5:7: error: redefinition of 'GLOBAL_NGRAMS_MAX_LOAD_FACTOR' with a different type: 'float' vs 'const float'
float GLOBAL_NGRAMS_MAX_LOAD_FACTOR = 0.25;
      ^
/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/quanteda/include/lib.h:21:13: note: previous definition is here
const float GLOBAL_NGRAMS_MAX_LOAD_FACTOR = 0.25;
            ^
2 errors generated.
make: *** [utility.o] Error 1
ERROR: compilation failed for package ‘quanteda.textstats’
```

@koheiw can you please fix ASAP so I can resubmit **quanteda** to CRAN?

**Comment by koheiw** [comment]
I know that the textstats does not build with v4 (because I changed lib.h), but it should be fine with v3.

**Comment by kbenoit** [comment]
Could you try building quanteda.textstats with the current (v3) GitHub master? I need to resubmit v3 pretty urgently. Kurt said he'd help with the R-side code, but asked me to resubmit.

**Comment by koheiw** [comment]
In lib.h.
```
# v4
const float GLOBAL_NGRAMS_MAX_LOAD_FACTOR = 0.25;

# master
extern float GLOBAL_NGRAMS_MAX_LOAD_FACTOR = 0.25;
```

**Comment by kbenoit** [comment]
bizzarre... It is working for me now using the current master of **quanteda** installed, and building the CRAN version of **quanteda.textstats**. Maybe I had the wrong branch installed of **quanteda** when I ran the tests.

**Comment by kbenoit** [comment]
I think it had something to do with this: https://github.com/quanteda/quanteda/issues/2230#issuecomment-1495310233

Glad I sorted that out. Migrated recently to a new machine and it set the default .libPath() differently!
