### ISSUE TITLE
downstream dependency problem with new docvars() generic

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#2239]
We have a problem now with the new docvars generic, which is blocking the CRAN update.

> Package check result: OK
> 
> Changes to worse in reverse depends:
> 
> Package: sentopics
> Check: S3 generic/method consistency
> New result: WARNING
>   docvars:
>     function(x, field, user, system)
>   docvars.sentopicmodel:
>     function(x, field)
>   See section ‘Generic functions and methods’ in the ‘Writing R
>   Extensions’ manual.

Solutions:
1) rewrite it as a real generic, with `docvars(x, field = NULL, ...)` as the generic, and then define the other arguments for specific objects. Although this still might break **sentopics**.
2) Unroll #2222 and make this a feature forthcoming in v4.

I prefer 2.

**Comment by koheiw** [comment]
I created the branch for v4. You keep merging branches to the master...

**Comment by kbenoit** [comment]
OK I'll undo it, and issue a new PR for merger to v4.
#2222 was a PR to merge that branch to master - each PR can specify its target. I just didn't think enough about downstream packages or test them.

**Comment by odelmarcelle** [comment]
Hi,
Feel free to modify `docvars()` as you need. I added a method in **sentopics** to ease access to an underlying `tokens` object, nothing critical there.
If it breaks, I'll quickly adjust.

**Comment by kbenoit** [comment]
Closing this because it seems to be ok now.
