### ISSUE TITLE
Deprecate nsentence()

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda#2241]
It should be done in this way
```r
ntoken(tokens(txt, what = "sentence"))
```

**Comment by kbenoit** [comment]
Agreed, `nsentence()` should only work on objects that already contain sentence segments.

One of the long-standing goals, however, e.g. #9, is to have a corpus contain pre-processed texts, including sentences, tokens, POS, entities, etc - like an "nlp" class object in spaCy. If that were the case, then `nsentence()` would work fine on those objects too. It works fine on an `spacyr_parsed` class object now, without doing any segmentation.

So we should deprecate this function but only in the cases where it performs segmentation on the fly. Exactly as we deprecated `dfm(corp)` (to push users not to skip the `tokens()` step).
