### ISSUE TITLE
Fix tests incompatible with forthcoming version of the Matrix package

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#2258]
I received the following communication today from Mikael Jagan:

> Matrix 1.5-5 will fix a number of bugs affecting subscripts of objects
> inheriting from the virtual class 'Matrix'.  Your package quanteda seems
> to rely on the following returning character(0) instead of NULL:
> 
>     rownames(<Matrix with rownames>[integer(0), , drop = FALSE])
>     colnames(<Matrix with colnames>[, integer(0), drop = FALSE])
> 
> Matrix previously gave character(0) in some cases but going forward will
> always give NULL, to be consistent with base R's handling of traditional
> matrices.  This fix causes some of quanteda's tests to fail.
> 
> Please correct and verify that your package passes its checks under the
> development version of Matrix, which you can install with Subversion,
> like so:
> 
> $ svn checkout svn://svn.r-forge.r-project.org/svnroot/matrix/pkg/Matrix
> $ R CMD build Matrix
> $ R CMD INSTALL Matrix_1.5-5.tar.gz
> 
> {
>     Note that installing in the usual way
> 
>     > install.packages("Matrix", repos = "http://r-forge.r-project.org/")
> 
>     seems to provide an outdated version of Matrix, due to a glitch
>     in R-Forge, which I hope is just temporary ...
> 
>     If you do not have Subversion, then I can try to host a tarball on
>     GitHub for you ...
> }

**Comment by koheiw** [comment]
We could make `dimnames.dfm()` and `dimnames.fcm()`, which return always `character()`. Otherwise, we should return NULL too.

**Comment by kbenoit** [comment]
That's a better fix. How about we do that for v3, and consider changing these to return `NULL` in v4.
