### ISSUE TITLE
Removing ... tokens options from ntoken(), ntype()

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#2269]
Since we had a discussion about this on #2263, I thought it could be useful to continue that discussion here, rather than it potentially holding up future PRs.

I agree, we should be limiting what is done "on the fly". This means we should disallow, with or without options:
- [ ] `ntype.character()`
- [ ] `ntype.corpus()`
- [ ] `ntoken.character()`
- [ ] `ntoken.corpus()`

But it actually makes _more_ sense to allow ... removals for `tokens_xptr` objects than for any other type of object, since the removals are efficient for already tokenised objects, and since there is no overhead of passing by value to/from C++.

The "on-the-fly" part we should focus on removing is skipping an explicit tokenisation step. But since we allow `tokens()` removal or splitting options on `tokens` objects, and designed all of the options to be from more to less operations (always removals or splitting things not split), then we should be encouraging users to "post-process" tokens objects using options they might have instead destructively applied on the first tokenisation. Especially for very large objects, this approach can save a lot of time, since it's the segmentation that takes more time than removals.

Without the ability to pass these options as an intermediate object to the ntoken/ntype functions for tokens/tokens_xtpr, the syntax is counter-intuitive as well as fairly horrible when it comes to tokens_xptr in particular, for something as simple as wanting to know what a set of post-tokenisation removals will trim. (I use this occasionally and always in teaching.)

``` r
library("quanteda")
#> Package version: 4.0.0
#> Unicode version: 14.0
#> ICU version: 71.1
#> Parallel computing: 10 of 10 threads used.
#> See https://quanteda.io for tutorials and examples.

toks <- tokens(head(data_corpus_inaugural, 5))
xtoks <- as.tokens_xptr(toks)

# total punctuation in corpus
ntoken(toks) - ntoken(toks, remove_punct = TRUE)
#> 1789-Washington 1793-Washington      1797-Adams  1801-Jefferson  1805-Jefferson 
#>             107              12             259             197             214

# but for xtoks: potential error
# works once
ntoken(xtoks) - ntoken(tokens(xtoks, remove_punct = TRUE))
#> 1789-Washington 1793-Washington      1797-Adams  1801-Jefferson  1805-Jefferson 
#>             107              12             259             197             214
# fails on second try
ntoken(xtoks) - ntoken(tokens(xtoks, remove_punct = TRUE))
#> 1789-Washington 1793-Washington      1797-Adams  1801-Jefferson  1805-Jefferson 
#>               0               0               0               0               0

# solution is a deep copy, which is the least efficient of all
toks <- tokens(head(data_corpus_inaugural, 5))
xtoks <- as.tokens_xptr(toks)
# works once
ntoken(xtoks) - ntoken(tokens(as.tokens_xptr(xtoks), remove_punct = TRUE))
#> 1789-Washington 1793-Washington      1797-Adams  1801-Jefferson  1805-Jefferson 
#>             107              12             259             197             214
# works twice
ntoken(xtoks) - ntoken(tokens(as.tokens_xptr(xtoks), remove_punct = TRUE))
#> 1789-Washington 1793-Washington      1797-Adams  1801-Jefferson  1805-Jefferson 
#>             107              12             259             197             214
```

<sup>Created on 2023-05-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by koheiw** [comment]
`ntype()` and `ntoken()` on character and corpus objects run tokenizer on the fly. Shall we deprecate them?
