### ISSUE TITLE
Erreur dans if (...length() && any(...names() == "Dimnames")) .Object@Dimnames <- fixupDN(.Object@Dimnames) :    valeur manquante là où TRUE / FALSE est requis

### ISSUE THREAD

**Issue by FranckyFroggy** [quanteda/quanteda#2283]
## Describe the bug

Please describe what the bug is.

## Reproducible code

Please paste minimal code that reproduces the bug. If possible, please upload the data file as `.rds`.
```r
# paste here #
library("quanteda")

corp_uk <- corpus(data_char_ukimmig2010)  # build a new corpus from the texts
summary(corp_uk)

## Expected behavior

would like summary function to produce tutorial output (i.e)

Corpus consisting of 9 documents, showing 9 documents:
## 
##          Text Types Tokens Sentences
##           BNP  1125   3280        88
##     Coalition   142    260         4
##  Conservative   251    499        15
##        Greens   322    677        21
##        Labour   298    680        29
##        LibDem   251    483        14
##            PC    77    114         5
##           SNP    88    134         4
##          UKIP   346    722        26
## System information

Please run `sessionInfo()` and paste the output.
```
# paste here #
RStudio
2023.03.1 Build 446

R.Version()
$platform
[1] "x86_64-pc-linux-gnu"

$arch
[1] "x86_64"

$os
[1] "linux-gnu"

$system
[1] "x86_64, linux-gnu"

$status
[1] ""

$major
[1] "4"

$minor
[1] "1.2"

$year
[1] "2021"

$month
[1] "11"

$day
[1] "01"

$`svn rev`
[1] "81115"

$language
[1] "R"

$version.string
[1] "R version 4.1.2 (2021-11-01)"

$nickname
[1] "Bird Hippie"

## Additional info

Please add any other information about the issue.

**Comment by koheiw** [comment]
I had a same problem from the Matrix package. I need to install the latest version of R to solve this.
