### ISSUE TITLE
Extend support for dfm() to accept matrix/dataframe-like objects

### ISSUE THREAD

**Issue by khughitt** [quanteda/quanteda#2288]
## Requested feature

It is common for to have data already formulated as a document-term matrix, and stored in something like a matrix, dataframe, sparse matrix, etc.

It would be great if `dfm()` were able to accept at least the most common of these (e.g. matrix/dataframe).

At present `dfm()` excepts input in the form of a `corpus`, `tokens` or `dfm` object, and will fail if you try to provide it an existing dataframe.

I'm sure there must be a straight-forward way to get such a dataframe into `dfm`, but after about 10-20 minutes of searching the docs and github, I could not find anything, so I thought I would bring it up here.

```r
df <- data.frame(word1 = c(1, 3, 2), word2 = c(3, 2, 0), word3 = c(9, 2, 0), row.names = c("doc1", "doc2", "doc3"))

> dfm(df)
Error: dfm() only works on character, corpus, dfm, tokens objects.
```

## Use case

Text-preprocessing & document-term frequency matrix already performed, e.g. with a separate tool or earlier analysis, and result saved in something like a dataframe.

**Comment by kbenoit** [comment]
```r
> as.dfm(df)
Document-feature matrix of: 3 documents, 3 features (22.22% sparse) and 0 docvars.
      features
docs   word1 word2 word3
  doc1     1     3     9
  doc2     3     2     2
  doc3     2     0     0
```
