### ISSUE TITLE
Warning in asMethod(object) :   sparse->dense coercion: allocating vector of size 13.0 GiB

### ISSUE THREAD

**Issue by santoshbs** [quanteda/quanteda#2293]
I am not sure how to interpret and address this warning which appears when using `dfm_weight()`.

```
Warning in asMethod(object) :
  sparse->dense coercion: allocating vector of size 13.0 GiB

```
Is this something to worry about? Would that affect the results?

Thanks!
sbs

**Comment by koheiw** [comment]
It only says that conversion is using a lot of space in RAM. What the value of `scheme`?

**Comment by santoshbs** [comment]
Not sure what scheme is and how to report it. Could you please help?

**Comment by kbenoit** [comment]
@koheiw means we need at a minimum, the call to `dfm_weight()` to understand what you did, and ideally, reproducible code. We also need to know the version numbers that are shown when starting quanteda. Can you produce this output using `reprex::reprex()`?

By "scheme" we mean the `scheme` argument from `dfm_weight()`:

```r
dfm_weight(
  x,
  scheme = c("count", "prop", "propmax", "logcount", "boolean", "augmented", "logave"),
  weights = NULL,
  base = 10,
  k = 0.5,
  smoothing = 0.5,
  force = FALSE
)
```

**Comment by santoshbs** [comment]
Thank you.

I am using both count and weights. Not sure which is causing the issue.

```
    if(!weighted){
      dfm_count = dfm_weight(dfm_custom, scheme = "count")
    } else {
      dfm_count= dfm_weight(dfm_custom, weights= list_weights)

```

**Comment by XjtuZhangKun-lab** [comment]
How did it work out in the end?
