### ISSUE TITLE
Spell checker

### ISSUE THREAD

**Issue by statzhero** [quanteda/quanteda#2297]
## Spell checking function

Are you planning to add a function that can find and replace typos and other spelling mistakes? 

## Use case

Useful, for example, when the corpus comes from scanned PDFs where OCR was not perfect.

## Additional context

There are of course R libraries such as [hunspell](https://github.com/hunspell/hunspell) but I found them to be lacking speed and context-awareness. I have not seen a port of [symspell](https://github.com/wolfgarbe/SymSpell) yet?

**Comment by kbenoit** [comment]
No, I'm afraid we have no such plans. But you can always use a different package to clean up the texts in your corpus object, which is a special character vector so easily passed as an input to any function that needs a character input.
