### ISSUE TITLE
Word count: is performance an issue (compared to counting sentences/characters) ?

### ISSUE THREAD

**Issue by xfim** [quanteda/quanteda#2298]
I want to get different measures of the length of the documents in my corpus, namely characters, words and sentences. While characters and sentences are very quick to compute, quanteda seems to struggle counting words. Is this normal?

So here are the details:

- The corpus has 2,264 documents. Each one has been gathered from PDF files of around 10-20 pages, using `readtext()`.
- For characters I use `nchar(Corpus)`, and it takes a couple of seconds.
- For sentences I use `ntoken(Corpus, what = "sentence")`, and it takes 14 seconds.
- For words, I use `ntoken(Corpus, what = "word")`. It has been running for more than 6 hours and still has not finished.

I have tried to check before what could be the time, measuring 10 and 100 documents of the corpus, and for 10 documents (`ntoken(Corpus[1:10], what = "word")`) it has taken 8 seconds, and 75 seconds for 100. I have extrapolated and was expecting 36 minutes, which still is a long time compared to counting characters or sentences. But more than 6 hours seems problematic at this point. If it counts, I am also setting `quanteda_options("threads" = 8)`, but only one core is being used.

So my questions are the following:

- Is counting words performance so different from counting sentences?
- Is it normal to increase the penalization of counting words in documents when the number of documents increases?
- Is this behaviour "normal" or expected?
- Is it possible to paralellize `ntoken()`?

Thank you very much for your support.

**Comment by koheiw** [comment]
What happens if you run `tokens(Corpus)`? Does it take time?

**Comment by xfim** [comment]
Yes, I would say so. So far, more than two minutes with this:

```
tic(); tokens(C); toc()
```

Thank you @koheiw for your support.

I will update with the final time.

**Comment by xfim** [comment]
After one hour, it is still going.

**Comment by koheiw** [comment]
It should be completed in a few minutes. Please share the version number of the quanteda and the corpus for us to investigate.

**Comment by kbenoit** [comment]
What about the output of 

```r
tokens(Corpus, what = "fasterword", verbose = TRUE)
```

**Comment by xfim** [comment]
22 seconds.

```
Creating a tokens object from a corpus input...
 ...starting tokenization
 ...tokenizing 1 of 1 blocks
 ...1,080,558 unique types
 ...removing separators
 ...complete, elapsed time: 22.5 seconds.
Finished constructing tokens from 2,294 documents.
Tokens consisting of 2,294 documents and 6 docvars.
1094_G059_2005_0001-05.pdf :
 [1] "Bundesrat"       "Drucksache"      "1/05"            "07.01.05"        "G"
 [6] "-"               "K"               "Gesetzentwurf"   "der"             "Bundesregierung"
[11] "Entwurf"         "eines"
[ ... and 7,429 more ]

1812_G031_2007_0001-07.pdf :
 [1] "Bundesrat"  "Drucksache" "1/07"       "05.01.07"   "AS"         "-"          "FS"
 [8] "-"          "Fz"         "-"          "K"          "-"
[ ... and 7,840 more ]

1473_F048_2009_0001-09.pdf :
 [1] "Bundesrat"       "Drucksache"      "1/09"            "02.01.09"        "A"
 [6] "-"               "U"               "Gesetzentwurf"   "der"             "Bundesregierung"
[11] "Entwurf"         "eines"
[ ... and 944 more ]

346_D003_2010_0001-10.pdf :
 [1] "Bundesrat"       "Drucksache"      "1/10"            "01.01.10"        "Fz"
 [6] "Gesetzentwurf"   "der"             "Bundesregierung" "Entwurf"         "eines"
[11] "Gesetzes"        "über"
[ ... and 40,739 more ]

1975_J030_2021_0001-21.pdf :
 [1] "Bun"        "d"          "esrat"      "Drucksache" "1/21"       "01.01.21"   "Vk"
 [8] "-"          "AIS"        "-"          "Fz"         "B"
[ ... and 1,881 more ]

2107_XN001_2003_0002-03.pdf :
 [1] "Bundesrat"       "Drucksache"      "2/03"            "03."             "01."
 [6] "03"              "U"               "–"               "Wi"              "Gesetzentwurf"
[11] "der"             "Bundesregierung"
[ ... and 27,452 more ]

[ reached max_ndoc ... 2,288 more documents ]
23.954 sec elapsed
```

Thank you both for helping with this.

**Comment by kbenoit** [comment]
OK, so it seems to be an issue with the v3 tokeniser. We've built the forthcoming v4 tokeniser into 3.3.1 already. What if you try:

```r
toks <- tokens(Corpus, what = "word4", verbose = TRUE)
```

**Comment by xfim** [comment]
A bit more, 3 minutes.

Incidentally, the first time that I have tried it, it has crashed due to memory usage. I have 32 GB, and the original process counting words is still running, as well as the second one (`tokens(Corpus)`). I've killed  this second one and then it has finished.


```
Creating a tokens object from a corpus input...
 ...starting tokenization
 ...tokenizing 1 of 1 blocks
 ...preserving hyphens
 ...preserving elisions
 ...preserving social media tags (#, @)
 ...700,088 unique types
 ...removing separators
 ...complete, elapsed time: 172 seconds.
Finished constructing tokens from 2,294 documents.
172.269 sec elapsed
```

**Comment by xfim** [comment]
Finally the first one has finished ("word"), after around 24 hours, compared to the 3 minutes of "word4". I've checked and it is exactly the same result. Perfect correlation.

Then, I will be closing the issue. But wouldn't it be better to make "word4" the default? Is there any drawback of using "word4" compared to "

Thank you very much @koheiw and @kbenoit for your help.

**Comment by kbenoit** [comment]
Wow, that's crazy. Agreed that we should switch to "word4" asap but it would still be interesting to diagnose the bottleneck. Must be something in your texts. @xfim is there a way you could share a link to the data object for our tests? (if it were on a cloud server)

**Comment by xfim** [comment]
Gladly.

**Comment by koheiw** [comment]
It seems that your texts are noisy with a lot of hyphens. They are slowing down tokenization.

```
> system.time(
+     tokens(Corpus[1:100], what = "word3", split_hyphens = FALSE)
+ )
   user  system elapsed 
  88.22    0.01   93.80 
> 
> system.time(
+     tokens(Corpus[1:100], what = "word3", split_hyphens = TRUE)
+ )
   user  system elapsed 
   2.10    0.13    1.61 

```

**Comment by xfim** [comment]
The texts come from PDF documents, as I mentioned earlier. I see two possibilities here. One is the hyphens, as you mention, @koheiw , that are probably due to the original PDF not contemplating the possibility to delete them and join the words  that are splitted between lines originally. 

The second one is the fact that some PDF are old, in the sense that I suspect that some contain images, not text. They have not been OCR'ed (if this is a concept), and therefore the images get transformed into something else, some unusual characters that slow down everything.

In the first case, is there any other option to create a corpus from PDF documents that can improve from the default `readtext()`?
