### ISSUE TITLE
Documentation issues that need solving

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#2305]
From the checks:

```
Version: 3.3.1 
Check: Rd \usage sections 
Result: NOTE 
    Documented arguments not in \usage in Rd file 'convert-wrappers.Rd':
     ‘...’
    
    Documented arguments not in \usage in Rd file 'corpus-class.Rd':
     ‘if’
    
    Documented arguments not in \usage in Rd file 'dfm-class.Rd':
     ‘drop_docid’
    
    Documented arguments not in \usage in Rd file 'dictionary-class.Rd':
     ‘object’
    
    Documented arguments not in \usage in Rd file 'matrix2fcm.Rd':
     ‘slots’
    
    Documented arguments not in \usage in Rd file 'meta_system.Rd':
     ‘source’
    
    Documented arguments not in \usage in Rd file 'search_index.Rd':
     ‘regex’
    
    Functions with \usage entries need to have the appropriate \alias
    entries, and all their arguments documented.
    The \usage entries must correspond to syntactically valid R code.
    See chapter ‘Writing R documentation files’ in the ‘Writing R
    Extensions’ manual. 
```

Flavors: [r-devel-linux-x86_64-debian-clang](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-clang/quanteda-00check.html), [r-devel-linux-x86_64-debian-gcc](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-gcc/quanteda-00check.html), [r-devel-linux-x86_64-fedora-clang](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-clang/quanteda-00check.html), [r-devel-linux-x86_64-fedora-gcc](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-gcc/quanteda-00check.html), [r-devel-windows-x86_64](https://www.r-project.org/nosvn/R.check/r-devel-windows-x86_64/quanteda-00check.html)

```
Check: HTML version of manual 
Result: NOTE 
    Found the following HTML validation problems:
    groups.html:30:9 (groups.Rd:7): Warning: <code> anchor "groups" already defined
    pattern.html:31:9 (pattern.Rd:7): Warning: <code> anchor "pattern" already defined
    valuetype.html:30:9 (valuetype.Rd:8): Warning: <code> anchor "valuetype" already defined 
```
Flavor: [r-devel-linux-x86_64-fedora-gcc](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-gcc/quanteda-00check.html)

```
* checking S3 generic/method consistency ... NOTE
Mismatches for apparent methods not registered:
docvars:
  function(x, field)
docvars.kwic:
  function(x)

Apparent methods for exported generics not registered:
  docvars.kwic
See section 'Registering S3 methods' in the 'Writing R Extensions'
manual.
```

**Comment by jaivardhan-bhola** [comment]
Can i work on this?

**Comment by kbenoit** [comment]
@jaivardhan-bhola Sure, if you like!

**Comment by jaivardhan-bhola** [comment]
Can I get some details

**Comment by kbenoit** [comment]
The details are all above. It would involve you forking the repo, creating a branch to solve these issues, fixing them, and issuing a PR. You'd need to give me access to your fork branch for review and edits.
