### ISSUE TITLE
Add pass argument to tokens functions to return documents intact

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda#2322]
Sometimes, tokens selection need to be conditional on other tokens or document variables, but we cannot do this efficiently using existing functions. In the example, "C" and "R" refer to computer languages in the first texts but they are trademark or copyright symbols in the second. How can we remove them from the second text while keeping the first text intact?

``` r
require(quanteda)
txt <- c("R and C are languages",
         "Windows (R), Quanteda (C)")
toks <- tokens(txt, remove_symbols = TRUE, remove_punct = TRUE)
toks
#> Tokens consisting of 2 documents.
#> text1 :
#> [1] "R"         "and"       "C"         "are"       "languages"
#> 
#> text2 :
#> [1] "Windows"  "R"        "Quanteda" "C"
# Languages are removed
tokens_select(toks, min_nchar = 2)
#> Tokens consisting of 2 documents.
#> text1 :
#> [1] "and"       "are"       "languages"
#> 
#> text2 :
#> [1] "Windows"  "Quanteda"
````
Currently, we can achieve this by splitting tokens into two, apply `tokens_select()` and combine them. This is very inefficient.
```r
# Currently method
c(toks[1], tokens_select(toks[2], min_nchar = 2))
#> Tokens consisting of 2 documents.
#> text1 :
#> [1] "R"         "and"       "C"         "are"       "languages"
#> 
#> text2 :
#> [1] "Windows"  "Quanteda"
```
So, how about adding an argument that simply pass documents without changes when `TRUE`?
```r
# Proposed method
tokens_select(toks, min_nchar = 2, pass = c(TRUE, FALSE))
#> Tokens consisting of 2 documents.
#> text1 :
#> [1] "R"         "and"       "C"         "are"       "languages"
#> 
#> text2 :
#> [1] "Windows"  "Quanteda"

# This allows conditioning based on patters or docvars
tokens_select(toks, min_nchar = 2, 
              pass = ntoken(tokens_select(toks, "language*")) > 0)
tokens_select(toks, min_nchar = 2, 
              pass = toks$year > 1960)
```
I can add this to `tokens_select()`, `tokens_compound()`, `tokens_tolower/upper()`, `tokens_split()` and `tokens_replace()`.

**Comment by kbenoit** [comment]
I like this idea and have found the same need on occasion. This is essentially a document mask, where you are proposing we use  `pass = TRUE` to mask the operation matched by `pattern` and leaves the document unaffected by the operation.

There's actually a great package for this already: **purrr**. What if we defined `map_if()` and `map_at()` in **quanteda.tidy** and finally release that package instead? It would allow a more general application of any function to a document mask based on a logical, a function conditional, or an index position.

``` r
library("quanteda")
#> Package version: 4.0.0
#> Unicode version: 14.0
#> ICU version: 71.1
#> Parallel computing: 10 of 10 threads used.
#> See https://quanteda.io for tutorials and examples.

toks <- tokens(c("a b c", "a b c d e"))

# logical mask
purrr::map_if(as.list(toks), c(TRUE, FALSE), toupper)
#> $text1
#> [1] "A" "B" "C"
#> 
#> $text2
#> [1] "a" "b" "c" "d" "e"

# function as a conditional
purrr::map_if(as.list(toks), function(x) length(x) <= 3, toupper)
#> $text1
#> [1] "A" "B" "C"
#> 
#> $text2
#> [1] "a" "b" "c" "d" "e"

# applied to specific index positions
purrr::map_at(as.list(toks), c(1), toupper)
#> $text1
#> [1] "A" "B" "C"
#> 
#> $text2
#> [1] "a" "b" "c" "d" "e"
```

<sup>Created on 2023-12-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by koheiw** [comment]
I will add the function then. Since it is very easy to implement, we could release in v4.0.

**Comment by kbenoit** [comment]
Do you mean in **quanteda.tidy**? I was proposing we define methods for the **purr** functions in that package, and not add document-masking functions to the **quanteda** functions that currently aim at modifying features or tokens.

**Comment by koheiw** [comment]
It must be in quanted's C++ function for performance reasons. I can add this without any overhead.

**Comment by kbenoit** [comment]
Sounds good to me. So as the `map_*()` functions or as a new argument? I'd prefer the map functions to keep things external, but if that is not efficient, what about using an argument called `map` that takes a logical or an index, and operates in the way that the `purrr::map()` functions operate?

**Comment by koheiw** [comment]
OK, let's add a new argument to `tokens_select()` and `tokens_compound()` to start. I was thinking to name it `pass` or `bypass` with default `NULL`. `map` is not bad, but it implies mapping x to y...
