### ISSUE TITLE
ndiMatrix / replValueSp - definition not updated

### ISSUE THREAD

**Issue by seb-29** [quanteda/quanteda#2325]
When loading quanteda (version 3.3.1) in R, I receive the following **warning message**:

`In .recacheSubclasses(def@className, def, env) : `<br>`
  undefined subclass "ndiMatrix" of class "replValueSp"; definition not updated`

What exactly does it mean? And where does it come from? Could this have something to do with the [Matrix package](https://cran.r-project.org/web/packages/Matrix/index.html)? R 4.3.2 comes with version 1.6.1.1, but the latest one is 1.6-4. If that was the issue, could you please advise me on how to update this package? Being pre-installed, it is located in the system library - which is not writable. Thanks a lot in advance!

**Comment by kbenoit** [comment]
This ought to be solved by updating to the latest Matrix package, please try that. You can install local libraries to a user path that will take priority over the system path by setting this using `.libPaths()`.
