### ISSUE TITLE
Warning: sparse->dense coercion: allocating vector of size 5.5 GiBWarning: Feature names cannot have underscores ('_'), replacing with dashes ('-')

### ISSUE THREAD

**Issue by Voltarikk** [quanteda/quanteda#2332]
Thanks for reporting this package. However when I run the code belowing,there's some trouble,could you please help me to solve it.Very thanks!
`library(Seurat)
library(Matrix)
sdata <- readRDS(file="D:/code/single_cell/github_code/harmony2019/data/figure3/exprs_30k.rds")
data_matrix <- as.matrix(sdata)
pan <- CreateSeuratObject(counts=data_matrix,project = 'myproject')`

**Warning: sparse->dense coercion: allocating vector of size 5.5 GiBWarning: Feature names cannot have underscores ('_'), replacing with dashes ('-')**

**Comment by koheiw** [comment]
See #2333
