### ISSUE TITLE
Dictionaries in Portuguese

### ISSUE THREAD

**Issue by apagano07** [quanteda/quanteda#2335]
Hi. I'm developing a text and sentiment analysis project in R for a call center in Brazil. I would like to know if Quanteda has built-in dictionaries in Portuguese. As far as I knwor there is a bunch of dictionaries but I suspect they are all in English, I am right? Thank you for your comments.

**Comment by kbenoit** [comment]
No, none currently in Portuguese. More dictionaries can be found in https://github.com/kbenoit/quanteda.dictionaries.
