### ISSUE TITLE
Make cpp_kwic()

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda#2339]
I should make C++ function to produce concordance views for KWIC. Currently, these commands are failing in Rmd probably because repeated deep-copying of the very long document (whole book).

https://github.com/quanteda/quanteda/blob/02c79e556c9d6dbf819d8fbd5bcbfbf482958a77/vignettes/pkgdown/replication/digital-humanities.Rmd#L122-L123

**Comment by kbenoit** [comment]
Interesting... is it the second one with the glob? or the fact that it's being run twice?
