### ISSUE TITLE
Keep original unigrams in tokens_compound()

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda#2399]
It is possible to keep unigrams in `tokens_ngrams()` by setting `n = 1` but it is not in `tokens_compound()`.  Keeping unigrams makes it easy to apply pattern matching in the downstream. How about adding an option like `keep_unigram`?

**Comment by kbenoit** [comment]
OK, good idea. `keep_unigrams = FALSE` (plural), or
```
action = c("replace", "add")
```
but the `action` would only make sense if there were a possible third option, and I cannot think of any.
