### ISSUE TITLE
Relax regex patterns for URL

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda#2430]
Currently, only URL with [http or https schemas are preserved](https://github.com/quanteda/quanteda/blob/master/R/tokenizers.R#L72), but there are [many more](https://en.wikipedia.org/wiki/List_of_URI_schemes). 

Current:
```
address <- "(https?:\\/\\/(www\\.)?|@)[-a-zA-Z0-9@:%._\\+~#=]{1,256}\\.[a-z]{2,4}\\b([-a-zA-Z0-9@:%_\\+.~#?&//=]*)"
```
New:
```
address <- "([-a-zA-Z0-9+.]{2,20}:\\/\\/(www\\.)?|@)[-a-zA-Z0-9@:%._\\+~#=]{1,256}\\.[a-z]{2,4}\\b([-a-zA-Z0-9@:%_\\+.~#?&//=]*)"
```

Also see [RFC 3986](https://www.rfc-editor.org/rfc/rfc3986#section-3.1).

**Comment by kbenoit** [comment]
That makes sense to me, as a default. That's a one-line change to tokenizers.R, right?
