### ISSUE TITLE
Wishlist: Better dplyr function support

### ISSUE THREAD

**Issue by methodds** [quanteda/quanteda#529]
Hi,

its so awesome how much user friendlier quanteda became in the last year and I could imagine this to improve even more by adding better dplyr support to quanteda. Of course, corpora are not data frames, but often have docvars and imagine a world where you could do something like this:

```
library(quanteda)
corpus <- data_corpus_inaugural

dfm_grouped <- corpus %>% 
 mutate(war = ifelse(Year<1945, "pre-war", "post-war")) %>%
 group_by(war) %>% dfm(remove=stopwords('english'))
```
This could work if a corpus (or other quanteda objects) would recognize a dplyr call and pass ``docvars()`` accordingly etc. What do you think about this?

**Comment by kbenoit** [comment]
Following on the discussion at #1171, here's a possibility for making the popular **dplyr** operations on corpus object docvars available from **quanteda**: We create a companion package called **quanteda.dplyr** that imports **dplyr**, exports its generics, and provides methods for our corpus objects.

These would mainly (or only) perform manipulation on document variables, or if grouping, group document variables using a limited subset of functions while concatenating texts in the group.

Currently we have `corpus_sample()` and `corpus_subset()`, for instance. An alternative would be `sample` and `filter` from **dplyr**, for sampling and subsetting documents. Other extensions would do the same directly on dovcars, but handling the documents correctly. **dplyr** candidates include:

* `filter`
* `group_by`
* `*_join`, `join`
* `mutate`
* `recode`
* `rename`
* `select`
* `transmute`

@hadley if you have time to take a brief look at #1171 your input on whether this is the best way to extend `dplyr::filter()` would be most appreciated!

**Comment by kbenoit** [comment]
This issue was moved to quanteda/quanteda.tidy#1
