### ISSUE TITLE
corpus_segment by fixed token lengths

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#679]
We should add an option to segment documents by fixed word length segments.

**Comment by lmullen** [comment]
I'm not sure if this is suitable for your purposes, but there will be a function to do this in the next release of tokenizers. It's not quite finished, but it's functional. 

https://github.com/ropensci/tokenizers/blob/master/R/chunk-text.R#L17

**Comment by koheiw** [comment]
I believe this should be `tokens_segment()` instead of `corpus_segment()`, because we never know the accurate number of tokens until tokening texts. For `corpus_segment()`, it should be the number of characters (this can be done with regex actually, `.{1,100}` for 100 characters).

**Comment by kbenoit** [comment]
But `tokens_anything()` would need to input tokens and output tokens. I don't think `tokens_segment()` would do that.

**Comment by koheiw** [comment]
It will, taking tokens and return reshaped tokens.

**Comment by kbenoit** [comment]
Yes that could work. It causes us to need to think carefully about what we allow a "token" to be, since currently we have a `what = "sentence"` option that allows a "token" to be a sentence. How would `tokens_segment()` work with sentence "tokens"?

**Comment by koheiw** [comment]
tokens_segment will return groups of sentences when a fixed length is given, but I am not sure who will use it in this way...

**Comment by koheiw** [comment]
I think `coups_reshape()` can be implemented as `corpus_segment()` + `corpus_group()` more consistently with other functions, because reshaping from sentences to documents is grouping corpus by original document IDs.

**Comment by kbenoit** [comment]
Agreed - I was thinking that `corpus_segment` would become an renamed internal function, with the exported `corpus_segment` a deprecated function. `corpus_reshape` would work as it does not, but reply on the internal `corpus_segment` that would also use `corpus_group`. 

Is this what you meant?

**Comment by koheiw** [comment]
My idea is to keep `corpus_segment()` (largely) unchanged and create `corpus_group()`. We will remove `corpus_reshape()`, because there is no reshape functions for tokens and dfm. We can export `tokens_group()` to complete the set.

**Comment by kbenoit** [comment]
But group only aggregates. Reshape allows going up or down.

**Comment by koheiw** [comment]
From documents to sentences use `corpus_segment()`
From sentences to documents use `corpus_group()`

**Comment by kbenoit** [comment]
That might make a lot of sense. Let me think about it. We would have to "fix" the idea of a "document" at the level of the original corpus text, if we are to use `corpus_group(x, by = "document")`, but that means that `corpus_segment(x, by = "sentence") %>% docnames()` is not returning a list of "document" names, but rather the document-as-sentence names. Is that consistent?

**Comment by koheiw** [comment]
I always feel strange to say "documents are sentences in this analysis...". I should say "units are sentences..." or "texts are sentences", so "unitnames" or "textnames" or just "names"?

**Comment by kbenoit** [comment]
Solved in #1520 via `tokens_chunk()`.

**Comment by kbenoit** [comment]
Not sure we need this any more, given `tokens_chunk()`.
