### ISSUE TITLE
Reduce peak memory use in operations on token objects

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda#681]
Currently,the following process takes around 5GB of memory at the peak when a 500MB of text file is given. The memory use peaks when std::vectors are converted to Rcpp list by `Rcpp::wrap()`. Although the best solution is not converting large objects, returning only a pointer to R, there are places to fix in the C++ code.

**Comment by kbenoit** [comment]
@kohei is this solved now? Or just partially?

**Comment by koheiw** [comment]
Only partially. I cannot solve this easily.

**Comment by koheiw** [comment]
I developed a prototype of a new tokens object in `dev-xpointer`. It reduces user time to process large tokens object by 30%, and allows the operation system to reclaim the memory. However, it requires extensive work in upgrading the tokens object or adding a new tokens object. This is why it is better to address this issue after the 1.0 release.

**Comment by kbenoit** [comment]
Sounds excellent. But I agree, let's finish this release with a focus on being consistent, stable (API), and bug-free, then we pay attention to the tokens and corpus structures. I want to make it possible to select on POS too.

**Comment by koheiw** [comment]
I can work on POS-based selection. I was thinking of working on it in this summer.

**Comment by kbenoit** [comment]
Might make sense to overhaul tokens as per `dev-xpointer` first? 

There are some interesting things I think we could do with really making the dictionary functions robust and more flexible in the meantime.

**Comment by koheiw** [comment]
I updated the `dev-xpointer` branch to make xtokens object work. I cannot work on this but I started thinking about how to introduce the new tokens object.

xtokens is significantly faster than tokens (benchmark will follow) because there is no transaction cost between C and R, which is large when there are a lot of short documents (sentences or tweets). We should switch to this xtokens to make the package really fast and memory efficient, but there are issues: 

1. backward compatibility
2. inability to save to disk
3. (must be more)

One way of introduce this object is to have dual system (tokens and xtokens) until all the problems will be solved. The other way is use xtokens only *internally*, although it benefits very few functions such as `dfm()`. Other possibility is to use xtokens only in `%>%`, but I am not sure if it is possible.

**Comment by koheiw** [comment]
On the second issue, I think we only need something like `save.xtokens()` and `saveRDS.xtokens()` (they don't have generic nonetheless). I am not sure if people want to save larger tokens objects when `save.image()` is called (I do not).

**Comment by koheiw** [comment]
Here is the benchmark. The difference becomes larger when there are a lot of short texts:

```
> microbenchmark::microbenchmark(
+     token = tokens_select(toks, stopwords(), valuetype = 'fixed', padding = TRUE),
+     xtokens = tokens_select(xtoks, stopwords(), valuetype = 'fixed', padding = TRUE),
+     times = 10, unit = 'relative'
+ )
Unit: relative
    expr      min       lq     mean   median       uq      max neval
   token 1.134175 1.148235 1.206825 1.170705 1.301632 1.291053    10
 xtokens 1.000000 1.000000 1.000000 1.000000 1.000000 1.000000    10
> 
> toks_sent <- tokens_segment(toks, c(".", "?", "!"), valuetype = "fixed", pattern_position = "after")
> xtoks_sent <- as.xtokens(toks_sent)
> 
> microbenchmark::microbenchmark(
+     token = tokens_select(toks_sent, stopwords(), valuetype = 'fixed', padding = TRUE),
+     xtokens = tokens_select(xtoks_sent, stopwords(), valuetype = 'fixed', padding = TRUE),
+     times = 10, unit = 'relative'
+ )
Unit: relative
    expr      min       lq     mean   median       uq      max neval
   token 1.599025 1.963204 1.911048 1.914266 1.844607 2.202584    10
 xtokens 1.000000 1.000000 1.000000 1.000000 1.000000 1.000000    10
```

**Comment by koheiw** [comment]
Relevant discussion here:
https://privefl.github.io/bigstatsr/articles/bigstatsr-and-bigmemory.html

**Comment by kbenoit** [comment]
Very interesting. I will study this and let's discuss how we might implement some version of it, but in the context of a tokens/corpus redesign.

**Comment by koheiw** [comment]
`setHook()` might be useful to automatically save XPtr objects: 
https://stat.ethz.ch/R-manual/R-devel/library/base/html/userhooks.html

**Comment by koheiw** [comment]
I noticed that `saveRDS()` also has `refhook` for handling of reference objects. We could use that to bring xtokens back to R  by `as.tokens.xtokens()`:
http://stat.ethz.ch/R-manual/R-devel/library/base/html/readRDS.html

**Comment by koheiw** [comment]
User will save `xtokens` object using `saveRDS()` but `vector<<vector<unsigned int>>>` should be save as a single vector in a way [suggested on SO](https://stackoverflow.com/questions/8193590/how-to-write-a-2d-vector-into-a-binary-file) to avoid complex serialization in C++. `xtokens` should have a numeric vector recording lengths of documents, a hash key of itself for verification and file path to the binary file.

**Comment by koheiw** [comment]
We can make a special package for xtokens with all the `tokens_*.xpointer()` functions. It is like data.table for data.frame, fmatch for match.

**Comment by kbenoit** [comment]
That's a great idea. Could it inherit from tokens and then be used as a replacement for standard quanteda tokens objects, or would we need to rewrite also the `tokens_*()` functions that call C++?

**Comment by koheiw** [comment]
The easiest approach is calling new pointer-based tokens functions from the conventional tokens functions and return a copy of the object as a list `as.tokens.xtokens()`. Advanced users can use the pointer-based function by loading a package, setting an option, or calling new wrapper functions. I don't know which is the best. 

In any case, I need to change input and output of all the C++ functions to refashion them as pointer based.

**Comment by koheiw** [comment]
The best design might be let `tokens_*()` to return the same type of object, list or xpointer, as the input. Then, we only need to add `as.xtokens()` and `tokens(..., xtokens = TRUE)`.

**Comment by koheiw** [comment]
This is what I meant. 4 times faster by keeping the tokens object in C++. Need to test reliability, obviously.
``` r
require(quanteda)
#> Loading required package: quanteda
#> Package version: 3.2.5
#> Unicode version: 14.0
#> ICU version: 70.1
#> Parallel computing: 4 of 4 threads used.
#> See https://quanteda.io for tutorials and examples.
data(data_corpus_sotu, package = "quanteda.corpora")
corp <- as.corpus(data_corpus_sotu)
toks <- tokens(corp)

type <- types(toks)
ids <- object2id(data_dictionary_LSD2015, type)
startpos <- rep(1, length.out = ndoc(toks))
endpos <- rep(-1, length.out = ndoc(toks))

xtoks <- quanteda:::qatd_cpp_as_xptr(toks, type)
class(xtoks)
#> [1] "externalptr"

tokens_select_old <- function(x) {
    quanteda:::qatd_cpp_tokens_select(x, type, ids, 1, TRUE, 0, 0, startpos, endpos)
}

tokens_select_new <- function(x) {
    is_xptr <- identical(class(x), "externalptr")
    if (!is_xptr)
        x <- quanteda:::qatd_cpp_as_xptr(x, type)
    result <- quanteda:::qatd_cpp_tokens_select_xptr(x, ids, 1, TRUE, 0, 0, startpos, endpos)
    if (!is_xptr)
        result <- quanteda:::qatd_cpp_as_list(result)
    return(result)
}

toks1 <- tokens_select_old(toks)
toks2 <- tokens_select_new(toks)
toks3 <- tokens_select_new(xtoks)
class(toks1)
#> [1] "tokens"
class(toks2)
#> [1] "tokens"
class(toks3)
#> [1] "externalptr"
identical(unclass(toks1), unclass(toks2))
#> [1] TRUE
identical(unclass(toks1), 
          unclass(quanteda:::qatd_cpp_as_list(toks3)))
#> [1] TRUE
identical(unclass(toks2), 
          unclass(quanteda:::qatd_cpp_as_list(toks3)))
#> [1] TRUE

microbenchmark::microbenchmark(
    tokens_select_old(toks),
    tokens_select_new(toks), 
    tokens_select_new(xtoks),
    times = 10
)
#> Unit: milliseconds
#>                      expr       min        lq      mean    median        uq
#>   tokens_select_old(toks) 1086.4954 1094.6484 1225.9652 1268.8489 1289.5383
#>   tokens_select_new(toks) 1168.5755 1228.9766 1250.5560 1249.1861 1272.3120
#>  tokens_select_new(xtoks)  272.4428  281.4071  313.1075  294.1336  351.3806
#>        max neval
#>  1324.5854    10
#>  1335.1111    10
#>   402.6181    10
```

<sup>Created on 2023-01-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by koheiw** [comment]
```
> microbenchmark::microbenchmark(
+     toks %>% tokens_select_old() %>% tokens_select_old() %>% tokens_select_old(),
+     toks %>% tokens_select_new() %>% tokens_select_new() %>% tokens_select_new(),
+     xtoks %>% tokens_select_new() %>% tokens_select_new() %>% tokens_select_new(),
+     times = 10
+ )
Unit: milliseconds
                                                                          expr       min       lq
  toks %>% tokens_select_old() %>% tokens_select_old() %>% tokens_select_old() 1538.5325 1587.746
  toks %>% tokens_select_new() %>% tokens_select_new() %>% tokens_select_new() 1683.5615 1821.680
 xtoks %>% tokens_select_new() %>% tokens_select_new() %>% tokens_select_new()  717.9069  826.937
      mean    median        uq      max neval
 1757.2687 1826.4637 1867.0365 1996.662    10
 1938.0663 1879.1799 2111.5557 2329.289    10
  905.3387  906.5886  958.4543 1069.873    10
```

**Comment by koheiw** [comment]
If users apply `as.externalptr()`, `tokens_select.externalptr()` is used until `as.tokens()` is applied. Very easy.
``` r
require(quanteda)
#> Loading required package: quanteda
#> Package version: 3.2.5
#> Unicode version: 14.0
#> ICU version: 70.1
#> Parallel computing: 4 of 4 threads used.
#> See https://quanteda.io for tutorials and examples.
data(data_corpus_sotu, package = "quanteda.corpora")
corp <- as.corpus(data_corpus_sotu)
toks <- tokens(corp)
xtoks <- as.externalptr(toks)
class(toks)
#> [1] "tokens"

toks2 <- tokens_select(toks, data_dictionary_LSD2015)
xtoks2 <- tokens_select(xtoks, data_dictionary_LSD2015)

identical(toks2, as.tokens(xtoks2))
#> [1] TRUE

microbenchmark::microbenchmark(
    tokens_select(toks, data_dictionary_LSD2015),
    tokens_select(xtoks, data_dictionary_LSD2015),
    times = 10
)
#> Unit: milliseconds
#>                                           expr       min        lq     mean
#>   tokens_select(toks, data_dictionary_LSD2015) 1782.9029 1877.0973 1999.269
#>  tokens_select(xtoks, data_dictionary_LSD2015)  979.7736  984.2815 1060.094
#>    median       uq      max neval
#>  1982.571 2162.004 2234.965    10
#>  1031.836 1108.115 1244.080    10
```

**Comment by koheiw** [comment]
`tokens_select()` became really compact :smile: 
https://github.com/quanteda/quanteda/blob/1cdaf5f21a133872b3084aa3942c5ef48addfde0/R/tokens_select.R#L228-L230

**Comment by kbenoit** [comment]
So the operations work by:
1. `x <- tokens()` as normal
2. coerce using `as.externalptr(x)`
3. do the `tokens_select()` etc operations that work efficiently in C++ land
4. coerce back to regular tokens using `as.tokens()`?

Is 4. required for input operations such as `dfm()`?

**Comment by koheiw** [comment]
You should play with xtokens on the branch.

1. `tokens()` call will `tokens_select.externalptr()` internally, but users will not notice the change. We should add an `pointer = TRUE` so that advanced users get externalptr from the function.
2. Yes but we need to think about the function name (and the object class name).
3. You can see how small the change in the C++ functions.
4. Apply `as.tokens(x)` internally in functions that do not support externalptr:
```r
dfm.externalptr <- function(x, ...) { 
    dfm(as.tokens(x), ...)
}
```
