### ISSUE TITLE
kwic output does not match documentation

### ISSUE THREAD

**Issue by mpadge** [quanteda/quanteda#888]
@kbenoit The docs for `kwic` state that it has a field named [`position`](https://github.com/kbenoit/quanteda/blob/master/R/kwic.R#L17), yet:
```
> names(kwic(data_corpus_inaugural, "secure*", window = 3, valuetype = "glob")) 
[1] "docname" "from"    "to"      "pre"     "keyword" "post"   
```
There is no `position`, and what is actually given appears to be the structure of `print.kwic`. And further:
```
> k <- names(kwic(data_corpus_inaugural, "secure*", window = 3, valuetype = "glob")) 
> all(k$from == k$to)
TRUE
```
yet [these lines](https://github.com/kbenoit/quanteda/blob/master/R/kwic.R#L140-L144) suggest the output in those cases should have `from` only and not the redundant `to`. Either way, the field is not called `"position"` as suggested by the docs.

**Comment by kbenoit** [comment]
You're right about the documentation, I will fix this now!

We have `from` and `to` because of multi-word matches, e.g.
```r
> mykwic <- kwic(data_corpus_inaugural, phrase("nuclear *"), window = 3, valuetype = "glob")
> head(as.data.frame(mykwic))
      docname from   to                 pre          keyword              post
1  1973-Nixon  428  429   the limitation of     nuclear arms          , and to
2 1977-Carter 1103 1104  elimination of all  nuclear weapons   from this Earth
3 1985-Reagan 2208 2209 further increase of  nuclear weapons         . We seek
4 1985-Reagan 2229 2230          one day of  nuclear weapons     from the face
5 1985-Reagan 2264 2265          the use of  nuclear weapons       , the other
6 1985-Reagan 2334 2335  that would destroy nuclear missiles before they reach
> packageVersion("quanteda")
[1] ‘0.9.9.85’
```

In the development version, we signal sequences using the `phrase()` wrapper.

**Comment by mpadge** [comment]
Multi-word matches are exactly what I was looking for and have currently hand-coded a (non-`quanteda`) hack job for `flipper`. `phrase` is great, but still not quite what I want to do, which is effectively get positions of all patterns in a phrase even when they're not immediately adjacent:
```
for (p in phrase)
  kwic (data_corpus_inaugral, p)$from
```
but that obviously can't really fall within the scope of `kwic` because it's asking for "key word**s**". `kwic` nevertheless seems so supremely optimised that even an explicit loop like that is actually effective.

**Comment by kbenoit** [comment]
Interesting use case, since @koheiw also wants the ability to extract targeted phrase sequences (aka "collocations") - see our discussion in #521.

I'll take a stab at what I think you want here, using two workarounds.

**Use `*` as a glob wildcard** to get any match.  However this is not variable length, within say a context window. 
```r
> kwic(data_corpus_inaugural, phrase(c("america * again")), window = 3)
                                                                           
 [2017-Trump, 1613:1615] we will make | America strong again  | . We will  
 [2017-Trump, 1620:1622] We will make | America wealthy again | . We will  
 [2017-Trump, 1627:1629] We will make |  America proud again  | . We will  
 [2017-Trump, 1634:1636] We will make |  America safe again   | . And,     
 [2017-Trump, 1647:1649] we will make |  America great again  | . Thank you
```

**Run `kwic()` on the results of a (slightly converted) kwic object.** e.g.
```r
> mykwic2 <- kwic(data_corpus_inaugural, phrase(c("america")), window = 5)
> kwic(as.tokens(mykwic2), phrase("* again *"))
                                                                            
 [2017-Trump.7, 9:11] down. America will start | winning again , |          
 [2017-Trump.13, 7:9]   , we will make America | strong again .  | We will  
 [2017-Trump.14, 7:9]   . We will make America | wealthy again . | We will  
 [2017-Trump.15, 7:9]   . We will make America |  proud again .  | We will  
 [2017-Trump.16, 7:9]   . We will make America |  safe again .   | And,     
 [2017-Trump.17, 7:9]   , we will make America |  great again .  | Thank you
```

But if you let me know what you want as input and output, I can probably do better (or we can add this to the package.

**Comment by mpadge** [comment]
i like that approach, but it runs into the problem i'm facing which is that extension to two-pattern phrases is okay, but extension to n-pattern phrases quickly becomes a multi-dimensional nightmare. I'll work through some of the collocation code and see if any of that might do the job.

**Comment by kbenoit** [comment]
The other option is `fcm` within a window, using `ordered = TRUE` possibly. But how about an example of your problem and what you are expecting as output?

**Comment by mpadge** [comment]
sure, i'll ping you from a flipper issue so as not to clutter up quanteda. Thanks in advance!

**Comment by kbenoit** [comment]
@mpadge We are reviewing issues and are wondering what you think we should do with this one. Are we still in need of changing something related to this issue?

**Comment by mpadge** [comment]
Nah, I think [this documentation fix](https://github.com/quanteda/quanteda/commit/d314baa4acace7e442660b63e754da1c2da1c0be#diff-3b105c74c3cae49b233f378efc5d4734) clarifies the original issue. I've got some pretty efficient `n`-pattern combinatoric code up and running with this present form of `kwic`, so all good. Thanks for all the feedback and response!
