### ISSUE TITLE
feature request: kwic minimal phrase length

### ISSUE THREAD

**Issue by mpadge** [quanteda/quanteda#912]
@kbenoit A few points prior to describing my feature request:

1. The `pkgdown` documentation is somewhat behind (`kwic`, for example, still notes the [`join` option](http://quanteda.io/reference/kwic.html) which is no longer possible; and note that most of the [`quickstart` vignette](http://quanteda.io/articles/quickstart.html) is the **full** output of a `textstat_simil()` matrix - whoops!.
2. I'm curious as to why `join` was disabled in `kwic` because it would make my feature request much simpler. Anyway ...

What i've now implemented in [`flipper`](https://github.com/ropenscilabs/flipper/blob/master/R/phrase_to_pkg.R) (in the last, somewhat inappropriately named, fn, `phrase_to_pkg`) is a function that converts a phrase to stemmed tokens and finds their positions in all corpus docs (via `kwic`). What I then do is simply convert those positions into the length of the shortest phrase that contains all of those terms. (In practice, the maximal number of co-occurring terms is first extracted, which might be < all.) The idea is that descriptions in which terms occur closer together are likely to be more relevant.

It seems that the arguably conventional approach to this kind of [proximity search analysis](https://en.wikipedia.org/wiki/Proximity_search_(text)), as reflected in both `kwic()` and `collocations()`, is to pre-specify the maximal `width` or `size` of a desired proximity/collocation search. What I thought would be better is to simply measure the minimal phrase length that contains as many terms as possible.

## Technical Issues

If `kwic` still offered `join = FALSE`, this ability could be directly implemented. `kwic` operating on a vector `pattern` would then simply return an additional column quantifying the length of the minimal phrase containing the terms. You'd see in each case how many terms that was, so interpretation would be straightforward. However, `kwic` no longer offers this possibility, and instead documents in which `pattern` terms are directly adjacent give different `to` and `from` values, along with a compound keyword. This requires an ungainly loop in the `flipper` code (currently [here](https://github.com/ropenscilabs/flipper/blob/master/R/phrase_to_pkg.R#L149-L151)).

It would certainly help my current needs if `join = FALSE` could be (re-)implemented, then that current loop which is run once for each package could simply be run on the entire corpus, and the rest of the code ported off to `C++`-land where it would run in no time. In short: What I'd like to do is run `kwic` once on the phrase and send the result to `C++` to extract the lengths of minimal phrases, but I can't currently do that effectively because `kwic` mashes together adjacent terms into compound `keyword` entries.

Once that issue is resolved, I'd be happy to do a PR for the `C++` code to extract minimal phrase lengths. I think it's a cool metric that would be quite useful. Just think text searching:
```
> kwic(corpus,"i'm not really sure but please match some of this stuff")
```
Consideration of the best match has to involve some measure of minimal length of phrase that contains as many of the `pattern` terms as possible.

**Comment by kbenoit** [comment]
@mpadge This is a really interesting issue, and we're delighted at your attention to this matter and for the offer to contribute!

I'm not sure why `join` is still in the function signature, since as you point out it has no effect. I think originally, the `join = TRUE` returned this:

```r
#  [1857-Buchanan, 2911, 2913] advantage of the | fortune | of | war | against a sister republic, 
```
and we decided this wreaked havoc with our methods for `kwic` objects that expected just a single keyword value, e.g.
```r
#   [1857-Buchanan, 2911]                     to take advantage of the | fortune | of war against a sister                
#   [1857-Buchanan, 2913]                  advantage of the fortune of |   war   | against a sister republic,  
```

We have been discussing what I think is a similar issue in https://github.com/kbenoit/quanteda/issues/521 (which I think is misnamed). The idea there is to provide something similar to this functionality:

```r
devtools::install_github("kasperwelbers/corpustools")
library(corpustools)

tc <- create_tcorpus(sotu_texts, doc_column = 'id')
hits <- tc$search_features('"freedom americ*"~5')  
kwic <- tc$kwic(hits, ntokens = 3)
head(kwic$kwic, 3)
# [1] "...making progress toward <freedom> will find <America> is their friend..."    
# [2] "...friends, and <freedom> in Iraq will make <America> safer for generations..."
# [3] "...men who despise <freedom>, despise <America>, and aim..." 
```

As for your example (`"i'm not really sure..."`) we already can extract phrases e.g.
```r
kwic(data_corpus_inaugural, phrase("poverty from the effects of war , but soon to emerge"))
                                                                                                                      
# [1869-Grant, 554:564] with the ten States in | poverty from the effects of war , but soon to emerge | , I trust, into
```
but I think this is different from what you are requesting. Please clarify!

**Comment by kbenoit** [comment]
BTW @mpadge I have fixed the vignette in a branch that will be merged shortly, thanks for pointing this out!

**Comment by mpadge** [comment]
thanks for the response! Consider your last example, but presume that I can't remember exactly what was said but simply know that somebody said something about poverty as an effect of war. I therefore try:
```
kwic(data_corpus_inaugural, phrase("poverty as an effect of war")) 
```
And of course get nothing. What my `flipper` stuff does can be pasted here in highly non-efficient code:
```
get_min_phrase_len <- function (mycorpus, phrase)
{
    phrase <- phrase %>% quanteda::tokens() %>% quanteda::tokens_wordstem() %>% as.character()
    doc_names <- quanteda::docnames (mycorpus)
    min_phrase_len <- num_present <- rep (NA, length (doc_names))
    txts <- mycorpus$documents$texts
    for (i in seq (doc_names))
    {
        txti <- txts [[i]] %>% tokens() %>% tokens_wordstem
        pos <- sapply (phrase, function (j)
                       quanteda::kwic (txti, j, valuetype = "regex")$from)
        npos <- which (lapply (pos, length) == 0)
        pos [npos] <- NULL

        num_present [i] <- length (pos)

        combs <- combn (length (pos), 2)
        dmin <- rep (NA, ncol (combs))
        for (j in seq (ncol (combs)))
        {
            pj1 <- pos [[combs [1, j] ]]
            pj2 <- pos [[combs [2, j] ]]
            dj1 <- matrix (pj1, nrow = length (pj1), ncol = length (pj2))
            dj2 <- t (matrix (pj2, nrow = length (pj2), ncol = length (pj1)))
            dmin [j] <- min (abs (dj1 - dj2))
        }
        min_phrase_len [i] <- max (dmin) + 1
    }
    # just return matches with maximal numbers of tokens - real use case would return all
    indx <- which (num_present == max (num_present))
    ord <- order (min_phrase_len [indx])
    data.frame (name = doc_names [indx [ord]],
                ntokens = num_present [indx [ord]],
                phrase_len = min_phrase_len [indx [ord]])
}
```
with the following results:
```
> get_min_phrase_len (data_corpus_inaugural, "poverty as an effect of war")
            name ntokens phrase_len
1     1869-Grant       6         36
2    1929-Hoover       6         42
3 1937-Roosevelt       6        209
4    1949-Truman       6        389
```
and without even knowing exactly what was said, you can find out that it was Grant in 1869 (with additional info that Hoover in 1929 seems to have uttered something similar).

----

I also acknowledge that this seems somewhat astray from the remit of `kwic`, so is or could be perhaps deserving of a separate function for general text searching rather than just keywords. That could then simply be based on `kwic` without changing the functionality of that. That would enable the code of `kwic` to be modified to avoid the problem above of having to `sapply(..., kwic)` for each document, and then the whole thing could be `C++`ed easily. I suppose I could have a go at that as a PR?

**Comment by kbenoit** [comment]
This is very clever and could make a nice behavioural upgrade to `kwic`. It suggests you could modify `kwic` to allow a window of proximity for two words, say `phrase("poverty war", window = 6)`, or implement some other scheme for approximate matching of phrases. I'm a little fuzzy on the details of what you need in the return object though.

We have a crude ability to do things like this now, but if you pair two wildcards, the current inefficient implementation of combinatorics slows the function to a halt. Even this is slow:
```r
kwic(data_corpus_inaugural, phrase("poverty from * ?ffect* of war"))
                                                                                                      
# [1869-Grant, 554:559] with the ten States in | poverty from the effects of war | , but soon to emerge
```

**Comment by mpadge** [comment]
Actually, the way i see it the whole need to specify fixed-width windows ought not be necessary at all (in spite of apparent universality according to the [wikipedia article](https://en.wikipedia.org/wiki/Proximity_search_(text))): Just let the search itself find the match with the minimal window size. That is nevertheless why I suspect such functionality might lie beyond the scope of `kwic()`, because it would disrupt current and indubitably useful functionality. `kwic()` should retain window-size specifications, and thus I suspect minimal-phrase-length-search or whatever it is (to be) called should be implemented in a different function.

Note in particular that my function above tokenizes both the phrase and the corpus docs to allow direct matching of stems which I think is a very useful approach, but one that is also not compatible with the purpose of `kwic()`. Given all of quanteda's other `text*` functions, why not just `textsearch`? There is currently no other R function of that name. The combinatorics are trivial in a `C++` sense and very easy to program with a slightly modified `kwic`. Documentation of both could easily cross-ref to emphasise `textsearch` as an exploratory tool for multi-word phrases, and `kwic` for a more precise tool for specific words or phrases.

**Comment by koheiw** [comment]
Hi @mpadge is this close to what you need? I agree that it is more efficient to drop short sequential matches in C++.
```r
kw <- kwic(data_corpus_inaugural, unlist(tokens("poverty from the effects of war but soon to emerge")), join = TRUE)
kw[(kw$to - kw$from) > 3,]
# [1841-Harrison, 5685:5689] statesmen that at the commencement |        of the War of the        | Revolution the most stupid men
# [1869-Grant, 554:559]             with the ten States in | poverty from the effects of war | , but soon to emerge
```

**Comment by mpadge** [comment]
Thanks @koheiw, but not exactly. What i want - need - is an ability to do
```
phrase <- some_fn("poverty as an effect of war")
kw <- kwic(data_corpus_inaugural, phrase)
```
where `some_fn` is just whatever transformation is necessary. That phrase does not actually occur in any inaugural document, but what I want is the ability to match the document which contains as much of it as possible in as few words as possible.

Nevertheless, your help from #916 gets me to where I need as a starting point, which is a flat table with a single entry for each token of `phrase` (current `join = FALSE` behaviour). That'll enable me to write an efficient `C++` function just to do the combinatorics of all positions, and it'll all work. I'm happy to do that somewhere else, and just ping you when it's done so you can ponder whether it might be worth incorporating within `quanteda`. Feel free to close this issue if you want - thanks to both of you for the interest!

**Comment by kbenoit** [comment]
I think where we are still not 100% clear is

> "match the document which contains as much of it as possible in as few words as possible"

what that means exactly and also

- what sort of return object do you want - would a `kwic` return work, where the match was the (multi-word) keyword? If that is the case, then we could use kwic for this and modify its matching behaviour, and just set window = 0.

**Comment by koheiw** [comment]
It sounds like keyword density, which can be done in this (really inefficient) way:

```r

tok <- tokens(data_corpus_inaugural)
ng <- tokens_ngrams(tok, 5, concatenator = ' ') # moving window of 5
txt <- unlist(ng)
mx <- dfm(txt)
mx2 <- dfm_select(mx, unlist(tokens("poverty from the effects of war, but soon to emerge")))
density <- ntoken(mx2) / ntoken(mx)

seq <- txt[names(sort(density, decreasing = TRUE))[1:10]]

kwic(tok, phrase(seq), join = TRUE)

# [1789-Washington, 429:433]     to the liberties and happiness |                  of the people of the                  | United States a Government instituted
# [1837-VanBuren, 2907:2911]          confided in by a majority |                  of the people of the                  | United States, including those       
# [1841-Harrison, 5685:5689] statesmen that at the commencement |                   of the War of the                    | Revolution the most stupid men       
# [1841-Harrison, 5751:5755]      Columbia are not the subjects |                  of the people of the                  | States, but free American            
# [1845-Polk, 2640:2644]  sound moral and honorable feeling |                  of the people of the                  | indebted States can not be           
# [1869-Grant, 554:565]             with the ten States in | poverty from the effects of war , but soon to emerge , | I trust, into greater  

```

**Comment by mpadge** [comment]
kind of. Output actually could be mostly `kwic` compatible:
```
> kwic(data_corpus_inaugural, fuzzy_phrase("poverty as an effect of war"))
# [1869-Grant, 519-554] | Treasury for every dollar collected , and the greatest practicable retrenchment in expenditure in every department of Government . When we compare the paying capacity of the country now , with the ten States in poverty from the effects of war. |
```
To reiterate: This phrase has no match in the text; what the above function does is match each token in the phrase, and find the shortest phrase in each corpus document that contains all of the tokens. Hence some function `fuzzy_phrase` which just tells `kwic` to first do a standard kwic on the token of each term before passing to the combinatorial `C++` magic which extracts the length of the shortest phrase which contains the maximal number of terms. (Note this is a regex match, so "as" matches with "treASury".)

Incompatibility arises because there's a necessary extra bit of information, which is the number of tokens matched, so this output should be:
```
> kwic(data_corpus_inaugural, fuzzy_phrase("poverty as an effect of war"))
# [1869-Grant, 519-554, 6] | Treasury for every dollar collected , and the greatest practicable retrenchment in expenditure in every department of Government . When we compare the paying capacity of the country now , with the ten States in poverty from the effects of war. |
```
where 6 is the number of tokens (all of them in this case). That's vital because documents will often only match less than the full number of phrase tokens, and there will inevitably be a statistical association between numbers of tokens found and phrase length. Another issue will arise, as mentioned above, in that phrase lengths might be extremely long, and printing all to screen in the default `print` method might become impracticable. So it's mostly, but not entirely, compatible with current `kwic` behaviour. Being a big fan of type consistency, I do not think that modifying output structure for one special use case is a good idea, and so am still happy to let this issue be closed, unless you can think of a clever way to encapsulate the necessary information in a type-consistent manner. However ..

This must offer something here because even my very inefficient code is still much faster than @kbenoit's above example using two wildcards ... maybe the issue can be potentially morphed into a separate issue of improving the efficiency of `regex2id`.

**Comment by koheiw** [comment]
I am aware that regex2is is not fast with wildcards. This is what we have to spend to improve. 

I think thay fuzzy_phrase() genetares a list of all the subsequences, kwic will do the job quickly. For example, list(c('a', 'b', 'c'), c('a', 'b'), c('b', 'c')) for 'a b c'.
