### ISSUE TITLE
Add vignette for sentiment analysis

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#993]
Can use a combination of dictionary analysis with `data_dictionary_LSD2015`, and `textmodel_wordscores()`.

**Comment by stefan-mueller** [comment]
I can have a go next week if you specify:
- which data to use for the sentiment analysis (maybe [data_corpus_movies](https://github.com/kbenoit/quantedaData/blob/master/data/data_corpus_movies.rda) from **quantedaData**)?
- how to proceed after calling `dfm_lookup`(which stats, models etc shall we present)?
- how `textmodel_wordscores()` relates to sentiment analysis?

**Comment by kbenoit** [comment]
How about matching http://tidytextmining.com/sentiment.html but using the `data_corpus_inaugural` since 1960 instead of _Pride and Prejudice_?

You could focus on the dictionary methods, but if you want, could also try identifying keywords using a partitioned dfm and then plots from `textstat_keyness()`. If you want to use `textmodel_wordscores()` or better, `textmodel_affinity()` to score and identify positive and negative words, you could do the same with the results.

**Comment by stefan-mueller** [comment]
Not sure how to proceed. I could reproduce chapter 2.2 easily, but I've never used **quanteda** to identify the words that were the most common ones in positive and negative texts (chapter 2.4). 
Could you tell me how to proceed ? Shall I use the most positive and most negative inaugural speeches as reference texts for `textmodel_wordscores()` and `textmodel_affinitiy()` or do something different? And which texts should then be used for `textstat_keyness()`?

```r
# applying chapter 2.2 to data_corpus_inaugural
library(quanteda)
library(ggplot2)

corpus_inaugural_post_1945 <- corpus_subset(data_corpus_inaugural, Year > 1945)

dfm_inaugural_lookup <- dfm(corpus_inaugural_post_1945) %>% 
  dfm_lookup(data_dictionary_LSD2015)

data_dict_inaugural <- convert(dfm_inaugural_lookup, to = "data.frame")

data_dict_inaugural$YearPresident <-  docnames(corpus_inaugural_post_1945) 
data_dict_inaugural$pos_sentiment <-  data_dict_inaugural$positive - data_dict_inaugural$negative

ggplot(data_dict_inaugural, aes(x = YearPresident, y = pos_sentiment)) +
  geom_bar(stat = "identity") +
  coord_flip()
```

**Comment by stefan-mueller** [comment]
The [vignette](https://github.com/kbenoit/quanteda.dictionaries/blob/master/vignettes/quanteda.dictionaries_vignette.Rmd) in the **quanteda.dictionaries** package contains sections on sentiment analysis. I guess we can close this issue.
