### ISSUE TITLE
Add readtext vignette to quanteda

### ISSUE THREAD

**Issue by stefan-mueller** [quanteda/quanteda#996]
Now that we are extending and updating the vignettes on www.quanteda.io I thought about moving the **readtext** [vignette](https://github.com/kbenoit/quantedaData/blob/master/data/data_corpus_movies.rda) to the [pkgdown_only](https://github.com/kbenoit/quanteda/tree/master/vignettes/pkgdown_only) folder in **quanteda**. The file is currently hidden in the readtext repo, but many newcomers to text analysis probably struggle to read in their text. I think we could and should add it to the quanteda website (the inter-operability with quanteda is even part of the document).

**Comment by kbenoit** [comment]
This will be solved now by the new pkgdown ecosystem where each package has its own site. So closing here.
